using System.Collections.Generic;
using System.Threading.Tasks;
using SWLOR.Game.Server.EngineTests.Framework;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.EngineTests.Definitions.AbilityBehaviors
{
    /// <summary>
    /// Declarative engine-test coverage for FeatType.ApexCollapse through FeatType.LockstepCrush,
    /// alphabetically the first half of the NPC innate-ability tree
    /// (SWLOR.Game.Server/Feature/AbilityDefinition/NPC). See <see cref="NPCAbilityBehaviorsPart2"/>
    /// for the rest (FeatType.MaulingBite onward).
    ///
    /// These abilities are driven by the NPC AI through the same UsePerkFeat.TryUseAbility seam
    /// the executor calls, so every case here uses a spawned nw_rat001 activator directly - none
    /// of this tree gates on CustomValidation, a specific equipped weapon, or a PC-only item
    /// requirement. Almost every file is a thin call into one of three shared factories in this
    /// folder, all of which apply their status effect and damage unconditionally on a landed hit
    /// (no gating on caster/target state):
    ///   - InnateAbility.BuildSingleTarget / NPCSignatureAbility.BuildSingleTarget: hostile
    ///     single-target hit, RequirementStamina cost, unconditional status + damage.
    ///   - InnateAbility.BuildArea / NPCSignatureAbility.BuildArea: hostile cone/line/sphere AoE,
    ///     same cost/status/damage shape (NPCSignatureAbility pins RecastGroup to Capstone and is
    ///     used for the "capstone identity" abilities auto-generated by
    ///     UpdateCapstoneEnemyIdentity.ps1; InnateAbility is used for the regular tree).
    ///   - InnateAbility.BuildSelfBuff: self status effect only, no target/damage.
    /// A handful of files skip the factory and call the AbilityBuilder directly (still hostile,
    /// still an unconditional status/damage impact) - each is called out in its comment below.
    /// No RequirementFP appears anywhere in this tree, so ExpectsFPCost is never set; every
    /// ability here declares RequirementStamina > 0 and a recast delay > 0.
    /// </summary>
    public class NPCAbilityBehaviorsPart1 : IAbilityBehaviorSource
    {
        [EngineTest("NPC ability behaviors (part 1)", Category = "AbilityBehavior", TimeoutSeconds = 1800f)]
        public static async Task Run(EngineTestContext ctx)
        {
            await AbilityBehaviorExecutor.RunAsync(ctx, new NPCAbilityBehaviorsPart1().BuildCases());
        }

        public List<AbilityBehaviorCase> BuildCases()
        {
            return new List<AbilityBehaviorCase>
            {
                // ApexCollapseAbilityDefinition - NPCSignatureAbility.BuildArea, line AoE.
                new()
                {
                    Feat = FeatType.ApexCollapse,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(HemorrhageStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // ArcPulseAbilityDefinition - InnateAbility.BuildArea, self-centered sphere.
                new()
                {
                    Feat = FeatType.ArcPulse,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(ShockStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // BarbedVolleyAbilityDefinition - InnateAbility.BuildArea, target-anchored cone.
                new()
                {
                    Feat = FeatType.BarbedVolley,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(BleedStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // BloodFrenzyFlurryAbilityDefinition - InnateAbility.BuildArea, target-anchored cone.
                new()
                {
                    Feat = FeatType.BloodFrenzyFlurry,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(BleedStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // BonecrusherBiteAbilityDefinition - InnateAbility.BuildSingleTarget.
                new()
                {
                    Feat = FeatType.BonecrusherBite,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(SunderStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // BraceBreakerAbilityDefinition - NPCSignatureAbility.BuildSingleTarget.
                new()
                {
                    Feat = FeatType.BraceBreaker,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(DazedStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // BrutalBashAbilityDefinition - InnateAbility.BuildSingleTarget.
                new()
                {
                    Feat = FeatType.BrutalBash,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(KnockdownStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // CapacitorSurgeAbilityDefinition - InnateAbility.BuildArea, self-centered sphere.
                new()
                {
                    Feat = FeatType.CapacitorSurge,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(ShockStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // ChitinGuardAbilityDefinition - InnateAbility.BuildSelfBuff: unconditional status
                // on the activator, no target/damage.
                new()
                {
                    Feat = FeatType.ChitinGuard,
                    Target = AbilityTargetKind.Self,
                    ExpectedActivatorStatusEffects = new[] { typeof(IronCarapaceStatusEffect) },
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // ConcussiveChallengeAbilityDefinition - InnateAbility.BuildArea, self-centered sphere.
                new()
                {
                    Feat = FeatType.ConcussiveChallenge,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(DazedStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // CripplingTalonsAbilityDefinition - hand-written single-target impact; status
                // comes from an unconditional statusEffectFactory (new VulnerableStatusEffect(8)).
                new()
                {
                    Feat = FeatType.CripplingTalons,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(VulnerableStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                    Notes = "Status comes from an unconditional statusEffectFactory (VulnerableStatusEffect(8)) rather than a plain typeof argument.",
                },

                // CrossfireDrillAbilityDefinition - NPCSignatureAbility.BuildArea, target-anchored cone.
                new()
                {
                    Feat = FeatType.CrossfireDrill,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(SuppressionStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // CryoBileAbilityDefinition - InnateAbility.BuildArea, target-anchored cone.
                new()
                {
                    Feat = FeatType.CryoBile,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(FreezingStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // DarkShockAbilityDefinition - InnateAbility.BuildArea, target-anchored sphere.
                new()
                {
                    Feat = FeatType.DarkShock,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(ForceSuppressionStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // DisorientingScreechAbilityDefinition - hand-written self-centered sphere (no
                // RequiresTarget), unconditional damage + status on hostiles caught in range.
                new()
                {
                    Feat = FeatType.DisorientingScreech,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(DisorientedStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // DreadWaveAbilityDefinition - InnateAbility.BuildArea, self-centered sphere.
                new()
                {
                    Feat = FeatType.DreadWave,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(TerrifiedStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // EssenceScarAbilityDefinition - NPCSignatureAbility.BuildSingleTarget.
                new()
                {
                    Feat = FeatType.EssenceScar,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(ForceDisruptionStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // FinalEclipseAbilityDefinition - NPCSignatureAbility.BuildArea, line AoE.
                new()
                {
                    Feat = FeatType.FinalEclipse,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(ForceDisruptionStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // FinalLineAbilityDefinition - NPCSignatureAbility.BuildArea, line AoE.
                new()
                {
                    Feat = FeatType.FinalLine,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(ExposedStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // FinalMandateAbilityDefinition - NPCSignatureAbility.BuildArea, line AoE.
                new()
                {
                    Feat = FeatType.FinalMandate,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(SuppressionStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // FinalSuppressionAbilityDefinition - NPCSignatureAbility.BuildArea, line AoE.
                new()
                {
                    Feat = FeatType.FinalSuppression,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(StunnedStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // FinishingDriveAbilityDefinition - NPCSignatureAbility.BuildArea, line AoE.
                new()
                {
                    Feat = FeatType.FinishingDrive,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(HemorrhageStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // ForceRendAbilityDefinition - InnateAbility.BuildSingleTarget.
                new()
                {
                    Feat = FeatType.ForceRend,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(ForceErosionStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // ForceSunderAbilityDefinition - InnateAbility.BuildSingleTarget; afterSuccessfulHit
                // only attaches a cosmetic drain beam effect, not a tracked status effect.
                new()
                {
                    Feat = FeatType.ForceSunder,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(ForceErosionStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                    Notes = "afterSuccessfulHit attaches a cosmetic EffectBeam only; not a status effect, not asserted.",
                },

                // FrostSpitAbilityDefinition - InnateAbility.BuildSingleTarget.
                new()
                {
                    Feat = FeatType.FrostSpit,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(FreezingStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // GlacialSlimeAbilityDefinition - InnateAbility.BuildSingleTarget.
                new()
                {
                    Feat = FeatType.GlacialSlime,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(FreezingStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // GoringChargeAbilityDefinition - InnateAbility.BuildArea, target-anchored line.
                new()
                {
                    Feat = FeatType.GoringCharge,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(BleedStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // GrenadeBurstAbilityDefinition - InnateAbility.BuildArea, target-anchored sphere.
                new()
                {
                    Feat = FeatType.GrenadeBurst,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(BurnStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // HoarfrostGlobAbilityDefinition - InnateAbility.BuildSingleTarget.
                new()
                {
                    Feat = FeatType.HoarfrostGlob,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(FreezingStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // HoldfastSlamAbilityDefinition - NPCSignatureAbility.BuildSingleTarget.
                new()
                {
                    Feat = FeatType.HoldfastSlam,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(SunderStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // InfernoBlastAbilityDefinition - hand-written target-anchored cone (RequiresTarget),
                // unconditional damage + status.
                new()
                {
                    Feat = FeatType.InfernoBlast,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(BurnStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // InnerCircleBindAbilityDefinition - NPCSignatureAbility.BuildSingleTarget.
                new()
                {
                    Feat = FeatType.InnerCircleBind,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(WeaponJam1StatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // InnerCirclePounceAbilityDefinition - NPCSignatureAbility.BuildSingleTarget.
                new()
                {
                    Feat = FeatType.InnerCirclePounce,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(ExposedStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // InnerCircleSurgeAbilityDefinition - NPCSignatureAbility.BuildSingleTarget.
                new()
                {
                    Feat = FeatType.InnerCircleSurge,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(ExposedStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // InnerCircleVolleyAbilityDefinition - NPCSignatureAbility.BuildSingleTarget.
                new()
                {
                    Feat = FeatType.InnerCircleVolley,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(DisorientedStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // InnerRingFlurryAbilityDefinition - NPCSignatureAbility.BuildSingleTarget.
                new()
                {
                    Feat = FeatType.InnerRingFlurry,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(ExposedStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // InnerVoidAbilityDefinition - NPCSignatureAbility.BuildSingleTarget.
                new()
                {
                    Feat = FeatType.InnerVoid,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(WeakenedStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // IonBurstAbilityDefinition - InnateAbility.BuildArea, target-anchored cone.
                new()
                {
                    Feat = FeatType.IonBurst,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(DisorientedStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // IronCarapaceAbilityDefinition - hand-written self-buff: unconditional
                // StatusEffect.ApplyStatusEffect(activator, activator, ...) on the activator.
                new()
                {
                    Feat = FeatType.IronCarapace,
                    Target = AbilityTargetKind.Self,
                    ExpectedActivatorStatusEffects = new[] { typeof(IronCarapaceStatusEffect) },
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // LastBastionAbilityDefinition - NPCSignatureAbility.BuildArea, line AoE.
                new()
                {
                    Feat = FeatType.LastBastion,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(KnockdownStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },

                // LockstepCrushAbilityDefinition - NPCSignatureAbility.BuildArea, target-anchored cone.
                new()
                {
                    Feat = FeatType.LockstepCrush,
                    Target = AbilityTargetKind.HostileCreature,
                    ExpectedTargetStatusEffects = new[] { typeof(KnockdownStatusEffect) },
                    ExpectsTargetDamage = true,
                    ExpectsSTMCost = true,
                    ExpectsRecast = true,
                },
            };
        }
    }
}
