FROM postgres:17.11-alpine@sha256:b0f9560a2de083e2cc7382e75f808c7381a32852a7ec49117deedb300e552b24

RUN apk add --no-cache jq
COPY --chmod=0755 postgres-entrypoint.sh /usr/local/bin/swlor-postgres-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/swlor-postgres-entrypoint.sh"]
CMD ["postgres"]
