namespace SWLOR.Shared.Domain.Character.Enums
{
    public enum StatType
    {
        Invalid = 0,
        MaxHP = 1,
        MaxFP = 2,
        HPRegen = 3,
        FPRegen = 4,
        RecastReduction = 5,
        Defense = 6,
        Evasion = 7,
        Accuracy = 8,
        Attack = 9,
        ForceAttack = 10,
        Might = 11,
        Perception = 12,
        Vitality = 13,
        Agility = 14,
        Willpower = 15,
        Social = 16,
        ShieldDeflection = 17,
        AttackDeflection = 18,
        // 19 is free
        CriticalRate = 20,
        Enmity = 21,
        Haste = 22,
        Slow = 23,
        DamageReduction = 24,
        ForceDefense = 25,
        QueuedDMGBonus = 26,
        Paralysis = 27,
        AccuracyModifier = 28,
        RecastReductionModifier = 29,
        DefenseBypassModifier = 30,
        HealingModifier = 31,
        FPRestoreOnHit = 32,
        DefenseModifier = 33,
        ForceDefenseModifier = 34,
        ExtraAttackModifier = 35,
        AttackModifier = 36,
        ForceAttackModifier = 37,
        EvasionModifier = 38,
        XPModifier = 39,
        PoisonResist = 40,
        Level = 41,
        MaxSTM = 42,
        STMRegen = 43,
        ControlSmithery = 44,
        ControlFabrication = 45,
        ControlEngineering = 46,
        ControlAgriculture = 47,
        CraftsmanshipSmithery = 48,
        CraftsmanshipFabrication = 49,
        CraftsmanshipEngineering = 50,
        CraftsmanshipAgriculture = 51,
    }
}
