using System;
using System.Collections.Generic;
using System.Linq;
using SWLOR.Game.Server.Service.CraftService;
using SWLOR.Game.Server.Service.PropertyService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Service.SpaceService
{
    public static class StarfighterVariantCatalog
    {
        private record BaseVariant(string Name, AppearanceType AppearanceId, PropertyLayoutType Layout, bool IsLocked = false);

        public record StarfighterVariantDefinition(
            int Sequence,
            int Tier,
            string Name,
            string DisplayName,
            string DeedTag,
            string DeedResref,
            AppearanceType AppearanceId,
            bool IsLocked,
            PropertyLayoutType Layout,
            RecipeType RecipeType,
            int PerkLevel,
            int HighPowerNodes,
            int LowPowerNodes,
            int MaxHull,
            int MaxCapacitor,
            int MaxShield,
            int ShieldRechargeRate,
            int RecipeLevel,
            int EnhancementSlots,
            string RefinedComponentResref,
            int RefinedComponentQuantity,
            string MaterialComponentResref,
            int MaterialComponentQuantity,
            string FiberComponentResref,
            int FiberComponentQuantity,
            string ElectronicsComponentResref,
            int ElectronicsComponentQuantity);

        private static readonly IReadOnlyList<BaseVariant> _baseVariants = new List<BaseVariant>
        {
new("Neutral Striker", AppearanceType.SWLORShipNeutralStriker, PropertyLayoutType.Striker, false),
            new("Armored Transport", AppearanceType.SWLORShipArmoredTransport, PropertyLayoutType.Consular, false),
            new("Bretonia", AppearanceType.SWLORShipBretoniaFreighter, PropertyLayoutType.Saber, false),
            new("Civilian Elite Fighter", AppearanceType.SWLORShipCivilianEliteFighter, PropertyLayoutType.Fighter, true),
            new("Civilian Fighter", AppearanceType.SWLORShipCivilianFighter, PropertyLayoutType.Fighter, false),
            new("Corsair Mk2", AppearanceType.SWLORShipCorsairEliteFighter, PropertyLayoutType.Mule, true),
            new("Corsair", AppearanceType.SWLORShipCorsairFighter, PropertyLayoutType.Mule, false),
            new("Cutlass", AppearanceType.SWLORShipCutlass, PropertyLayoutType.Fighter, false),
            new("S-100 Stinger Starfighter", AppearanceType.SWLORShipFuryFighter, PropertyLayoutType.Fighter, false),
            new("Hutt Bomber", AppearanceType.SWLORShipHuttBomber, PropertyLayoutType.Fighter, true),
            new("Hutt Fighter", AppearanceType.SWLORShipHuttFighter, PropertyLayoutType.Fighter, true),
            new("Hutt Gunship", AppearanceType.SWLORShipHuttGunship, PropertyLayoutType.Merchant, true),
            new("Invader", AppearanceType.SWLORShipInvaderHeavyFighter, PropertyLayoutType.Fighter, false),
            new("Hunter", AppearanceType.SWLORShipHunterFighter, PropertyLayoutType.Fighter, false),
            new("Jedi Transport", AppearanceType.SWLORShipJediTransport, PropertyLayoutType.Falchion, false),
            new("Kusari Mk2", AppearanceType.SWLORShipKusariEliteFighter, PropertyLayoutType.Fighter, true),
            new("Kusari", AppearanceType.SWLORShipKusariFighter, PropertyLayoutType.Fighter, false),
            new("Kusari Freighter", AppearanceType.SWLORShipKusariFreighter, PropertyLayoutType.Panther, false),
            new("Liberty Mk2", AppearanceType.SWLORShipLibertyEliteFighter, PropertyLayoutType.Hound, true),
            new("Liberty", AppearanceType.SWLORShipLibertyFighter, PropertyLayoutType.Hound, false),
            new("Bretonia Freighter", AppearanceType.SWLORShipBretoniaFreighter, PropertyLayoutType.Consular, false),
            new("Mandalorian Brute Patrol Ship", AppearanceType.SWLORShipMandalorianBrutePatrolShip, PropertyLayoutType.Throne, true),
            new("Davaab-type Starfighter", AppearanceType.SWLORShipMandalorianDavaabFighter, PropertyLayoutType.Fighter, true),
            new("Teroch-type Gunship", AppearanceType.SWLORShipMandalorianTeroch, PropertyLayoutType.Fighter, true),
            new("Neutral Barracuda", AppearanceType.SWLORShipNeutralBarracuda, PropertyLayoutType.Fighter, false),
            new("Civilian BW Fighter", AppearanceType.SWLORShipNeutralBWFighter, PropertyLayoutType.Fighter, false),
            new("Civilian Condor", AppearanceType.SWLORShipNeutralCondor, PropertyLayoutType.Condor, false),
            new("Civilian Freighter", AppearanceType.SWLORShipNeutralDropship, PropertyLayoutType.LightFreighter1, false),
            new("ST-07 Assault ship", AppearanceType.SWLORShipNeutralGunship, PropertyLayoutType.Hound, true),
            new("Neutral Quartermaster transport", AppearanceType.SWLORShipNeutralQuartermastertransport, PropertyLayoutType.Throne, false),
            new("Starflier", AppearanceType.SWLORShipNeutralStarflier, PropertyLayoutType.Fighter, false),
            new("YV-929 Hauler", AppearanceType.SWLORShipNeutralYV929Hauler, PropertyLayoutType.Throne, false),
            new("Onderon Ruping Bomber", AppearanceType.SWLORShipOnderonRupingBomber, PropertyLayoutType.Mule, false),
            new("Onderon Type81a Fighter", AppearanceType.SWLORShipOnderonType81aFighter, PropertyLayoutType.Fighter, false),
            new("Order Fighter", AppearanceType.SWLORShipOrderFighter, PropertyLayoutType.Fighter, false),
            new("Phoebos", AppearanceType.SWLORShipPhoebosBomber, PropertyLayoutType.Fighter, false),
            new("Pirate Fighter", AppearanceType.SWLORShipPirateFighter, PropertyLayoutType.Striker, false),
            new("Pirate Freighter", AppearanceType.SWLORShipPirateFreighter, PropertyLayoutType.Hound, false),
            new("Assault Transport", AppearanceType.SWLORShipRepublicAssaultTransport, PropertyLayoutType.Merchant, false),
            new("Military Bomber MK 1", AppearanceType.SWLORShipRepublicBomberA, PropertyLayoutType.Condor, false),
            new("Military Bomber MK 2", AppearanceType.SWLORShipRepublicBomberB, PropertyLayoutType.Condor, true),
            new("Military Bomber MK 3", AppearanceType.SWLORShipRepublicBomberC, PropertyLayoutType.Condor, true),
            new("S-250 Chela Starfighter", AppearanceType.SWLORShipRepublicChelaBomber, PropertyLayoutType.Fighter, true),
            new("Military Gunship Large", AppearanceType.SWLORShipRepublicGunship, PropertyLayoutType.Striker, false),
            new("Military Gunship MK 1", AppearanceType.SWLORShipRepublicGunshipA, PropertyLayoutType.Hound, false),
            new("Military Gunship MK 2", AppearanceType.SWLORShipRepublicGunshipB, PropertyLayoutType.Hound, true),
            new("Military Gunship MK 3", AppearanceType.SWLORShipRepublicGunshipC, PropertyLayoutType.Hound, true),
            new("Infiltrator MK 1", AppearanceType.SWLORShipRepublicInfiltratorA, PropertyLayoutType.Fighter, false),
            new("Infiltrator MK 2", AppearanceType.SWLORShipRepublicInfiltratorB, PropertyLayoutType.Fighter, true),
            new("Infiltrator MK 3", AppearanceType.SWLORShipRepublicInfiltratorC, PropertyLayoutType.Fighter, true),
            new("Twin Infiltrator", AppearanceType.SWLORShipRepublicInfiltratorD, PropertyLayoutType.LightEscort1, false),
            new("Advanced Scout MK 1", AppearanceType.SWLORShipRepublicScoutA, PropertyLayoutType.Fighter, false),
            new("Advanced Scout MK 2", AppearanceType.SWLORShipRepublicScoutB, PropertyLayoutType.Fighter, true),
            new("Star Saber XC-01", AppearanceType.SWLORShipRepublicScoutC, PropertyLayoutType.Fighter, true),
            new("Advanced Striker MK 1", AppearanceType.SWLORShipRepublicStrikerA, PropertyLayoutType.Striker, false),
            new("Advanced Striker MK 2", AppearanceType.SWLORShipRepublicStrikerB, PropertyLayoutType.Striker, true),
            new("Advanced Striker MK 3", AppearanceType.SWLORShipRepublicStrikerC, PropertyLayoutType.Striker, true),
            new("Rheinland Mk 2", AppearanceType.SWLORShipRheinlandEliteFighter, PropertyLayoutType.Merchant, true),
            new("Rheinland", AppearanceType.SWLORShipRheinlandFighter, PropertyLayoutType.Merchant, false),
            new("Rheinland Freighter", AppearanceType.SWLORShipRheinlandFreighter, PropertyLayoutType.LightFreighter1, false),
            new("Advanced Bomber", AppearanceType.SWLORShipSithBomberA, PropertyLayoutType.Striker, false),
            new("Twin Bomber", AppearanceType.SWLORShipTwinBomber, PropertyLayoutType.Fighter, true),
            new("Advanced Bomber MK 2", AppearanceType.SWLORShipSithBomberB, PropertyLayoutType.Condor, true),
            new("Advanced Bomber MK 3", AppearanceType.SWLORShipSithBomberC, PropertyLayoutType.Condor, true),
            new("Advanced Gunboat", AppearanceType.SWLORShipSithGunboat, PropertyLayoutType.Mule, false),
            new("Advanced Gunship MK 1", AppearanceType.SWLORShipSithGunshipA, PropertyLayoutType.Condor, false),
            new("Advanced Gunship MK 2", AppearanceType.SWLORShipSithGunshipB, PropertyLayoutType.Condor, true),
            new("Advanced Gunship MK 3", AppearanceType.SWLORShipSithGunshipC, PropertyLayoutType.Condor, true),
            new("Infiltrator MK 1", AppearanceType.SWLORShipSithInfiltratorA, PropertyLayoutType.Striker, false),
            new("Infiltrator MK 2", AppearanceType.SWLORShipSithInfiltratorB, PropertyLayoutType.Striker, true),
            new("Infiltrator MK 3", AppearanceType.SWLORShipSithInfiltratorC, PropertyLayoutType.Striker, true),
            new("Advanced Scout MK 1", AppearanceType.SWLORShipSithScoutA, PropertyLayoutType.LightEscort1, false),
            new("Advanced Scout MK 2", AppearanceType.SWLORShipSithScoutB, PropertyLayoutType.LightEscort1, true),
            new("Advanced Scout MK 3", AppearanceType.SWLORShipSithScoutC, PropertyLayoutType.LightEscort1, true),
            new("Advanced Striker Mk 1", AppearanceType.SWLORShipSithStrikerA, PropertyLayoutType.LightEscort1, false),
            new("Advanced Striker Mk 2", AppearanceType.SWLORShipSithStrikerB, PropertyLayoutType.LightEscort1, true),
            new("Advanced Striker Mk 3", AppearanceType.SWLORShipSithStrikerC, PropertyLayoutType.LightEscort1, true),
            new("KT-400 Light Freighter", AppearanceType.SWLORShipKT400LightFreighter, PropertyLayoutType.Saber, true),
            new("Trandoshan Transport", AppearanceType.SWLORShipTrandoshanTransport, PropertyLayoutType.Consular, true),
            new("XS Freighter", AppearanceType.SWLORShipXSFreighter, PropertyLayoutType.LightFreighter1, false),
            new("Y8 Miner Ship", AppearanceType.SWLORShipY8MinerShip, PropertyLayoutType.LightFreighter1, false),
            new("Zoomer Fighter", AppearanceType.SWLORShipZoomerFighter, PropertyLayoutType.Fighter, false),
            new("Legion Fighter", AppearanceType.SWLORShipLegionFighter, PropertyLayoutType.Fighter, true),
        };

        private static readonly IReadOnlyList<StarfighterVariantDefinition> _variants = Build();
        private static readonly Dictionary<RecipeType, StarfighterVariantDefinition> _byRecipeType = _variants.ToDictionary(x => x.RecipeType, x => x);

        public static IReadOnlyList<StarfighterVariantDefinition> GetTier(int tier)
        {
            return _variants.Where(x => x.Tier == tier).ToList();
        }

        public static bool TryGetByRecipeType(RecipeType recipeType, out StarfighterVariantDefinition definition)
        {
            return _byRecipeType.TryGetValue(recipeType, out definition);
        }

        private static List<StarfighterVariantDefinition> Build()
        {
            var results = new List<StarfighterVariantDefinition>();

            var totalCounts = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
            foreach (var variant in _baseVariants)
            {
                if (!totalCounts.ContainsKey(variant.Name))
                    totalCounts[variant.Name] = 0;
                totalCounts[variant.Name]++;
            }

            var seenByName = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
            for (var i = 0; i < _baseVariants.Count; i++)
            {
                var sequence = i + 1;
                var baseVariant = _baseVariants[i];
                var profileA = sequence % 2 == 1;

                if (!seenByName.ContainsKey(baseVariant.Name))
                    seenByName[baseVariant.Name] = 0;
                seenByName[baseVariant.Name]++;
                var occurrence = seenByName[baseVariant.Name];
                var needsVariantSuffix = totalCounts[baseVariant.Name] > 1;
                var variantSuffix = needsVariantSuffix ? $" - Variant {occurrence}" : string.Empty;

                results.Add(CreateTierDefinition(sequence, 1, baseVariant, profileA, variantSuffix, occurrence, needsVariantSuffix));
                results.Add(CreateTierDefinition(sequence, 2, baseVariant, profileA, variantSuffix, occurrence, needsVariantSuffix));
                results.Add(CreateTierDefinition(sequence, 3, baseVariant, profileA, variantSuffix, occurrence, needsVariantSuffix));
                results.Add(CreateTierDefinition(sequence, 4, baseVariant, profileA, variantSuffix, occurrence, needsVariantSuffix));
                results.Add(CreateTierDefinition(sequence, 5, baseVariant, profileA, variantSuffix, occurrence, needsVariantSuffix));
            }

            return results;
        }

        private static StarfighterVariantDefinition CreateTierDefinition(
            int sequence,
            int tier,
            BaseVariant baseVariant,
            bool profileA,
            string variantSuffix,
            int occurrence,
            bool needsVariantSuffix)
        {
            var displayName = $"{baseVariant.Name}{variantSuffix} (Tier {tier})";
            var deedTag = $"sdeed_sv{sequence:000}_t{tier}";
            var deedResref = deedTag;

            var recipeType = RecipeTypeFor(sequence, tier);

            if (tier == 1)
            {
                return profileA
                    ? new StarfighterVariantDefinition(
                        sequence, tier, baseVariant.Name, displayName, deedTag, deedResref, baseVariant.AppearanceId, baseVariant.IsLocked, baseVariant.Layout, recipeType,
                        1, 2, 3, 50, 40, 50, 4, 5, 1,
                        "ref_tilarium", 2, "aluminum", 1, "fiberp_ruined", 1, "elec_ruined", 1)
                    : new StarfighterVariantDefinition(
                        sequence, tier, baseVariant.Name, displayName, deedTag, deedResref, baseVariant.AppearanceId, baseVariant.IsLocked, baseVariant.Layout, recipeType,
                        1, 3, 2, 40, 60, 40, 4, 10, 1,
                        "ref_tilarium", 5, "aluminum", 3, "fiberp_ruined", 3, "elec_ruined", 3);
            }

            if (tier == 2)
            {
                return profileA
                    ? new StarfighterVariantDefinition(
                        sequence, tier, baseVariant.Name, displayName, deedTag, deedResref, baseVariant.AppearanceId, baseVariant.IsLocked, baseVariant.Layout, recipeType,
                        2, 4, 5, 100, 80, 100, 6, 15, 1,
                        "ref_currian", 2, "steel", 1, "fiberp_flawed", 1, "elec_flawed", 1)
                    : new StarfighterVariantDefinition(
                        sequence, tier, baseVariant.Name, displayName, deedTag, deedResref, baseVariant.AppearanceId, baseVariant.IsLocked, baseVariant.Layout, recipeType,
                        2, 5, 4, 80, 120, 80, 6, 20, 1,
                        "ref_currian", 5, "steel", 3, "fiberp_flawed", 3, "elec_flawed", 3);
            }

            if (tier == 3)
            {
                return profileA
                    ? new StarfighterVariantDefinition(
                        sequence, tier, baseVariant.Name, displayName, deedTag, deedResref, baseVariant.AppearanceId, baseVariant.IsLocked, baseVariant.Layout, recipeType,
                        3, 5, 6, 150, 120, 150, 8, 25, 2,
                        "ref_idailia", 2, "obsidian", 1, "fiberp_good", 1, "elec_good", 1)
                    : new StarfighterVariantDefinition(
                        sequence, tier, baseVariant.Name, displayName, deedTag, deedResref, baseVariant.AppearanceId, baseVariant.IsLocked, baseVariant.Layout, recipeType,
                        3, 6, 5, 120, 180, 120, 8, 30, 2,
                        "ref_idailia", 5, "obsidian", 3, "fiberp_good", 3, "elec_good", 3);
            }

            if (tier == 4)
            {
                return profileA
                    ? new StarfighterVariantDefinition(
                        sequence, tier, baseVariant.Name, displayName, deedTag, deedResref, baseVariant.AppearanceId, baseVariant.IsLocked, baseVariant.Layout, recipeType,
                        4, 5, 6, 200, 160, 200, 10, 35, 2,
                        "ref_barinium", 2, "crystal", 1, "fiberp_imperfect", 1, "elec_imperfect", 1)
                    : new StarfighterVariantDefinition(
                        sequence, tier, baseVariant.Name, displayName, deedTag, deedResref, baseVariant.AppearanceId, baseVariant.IsLocked, baseVariant.Layout, recipeType,
                        4, 6, 5, 160, 240, 160, 10, 40, 2,
                        "ref_barinium", 5, "crystal", 3, "fiberp_imperfect", 3, "elec_imperfect", 3);
            }

            // Tier 5 intentionally uses only Throne/Consular profile templates.
            return profileA
                ? new StarfighterVariantDefinition(
                    sequence, tier, baseVariant.Name, displayName, deedTag, deedResref, baseVariant.AppearanceId, baseVariant.IsLocked, baseVariant.Layout, recipeType,
                    5, 6, 7, 250, 200, 250, 12, 45, 2,
                    "ref_gostian", 2, "diamond", 1, "fiberp_high", 1, "elec_high", 1)
                : new StarfighterVariantDefinition(
                    sequence, tier, baseVariant.Name, displayName, deedTag, deedResref, baseVariant.AppearanceId, baseVariant.IsLocked, baseVariant.Layout, recipeType,
                    5, 7, 6, 200, 300, 200, 12, 50, 2,
                    "ref_gostian", 5, "diamond", 3, "fiberp_high", 3, "elec_high", 3);
        }

private static RecipeType RecipeTypeFor(int sequence, int tier) => (tier, sequence) switch
        {
            (1, 1) => RecipeType.StarfighterNeutralStrikerTier1,
            (1, 2) => RecipeType.StarfighterArmoredTransportTier1,
            (1, 3) => RecipeType.StarfighterBretoniaTier1,
            (1, 4) => RecipeType.StarfighterCivilianEliteFighterTier1,
            (1, 5) => RecipeType.StarfighterCivilianFighterTier1,
            (1, 6) => RecipeType.StarfighterCorsairMk2Tier1,
            (1, 7) => RecipeType.StarfighterCorsairTier1,
            (1, 8) => RecipeType.StarfighterCutlassTier1,
            (1, 9) => RecipeType.StarfighterS100StingerStarfighterTier1,
            (1, 10) => RecipeType.StarfighterHuttBomberTier1,
            (1, 11) => RecipeType.StarfighterHuttFighterTier1,
            (1, 12) => RecipeType.StarfighterHuttGunshipTier1,
            (1, 13) => RecipeType.StarfighterInvaderTier1,
            (1, 14) => RecipeType.StarfighterHunterTier1,
            (1, 15) => RecipeType.StarfighterJediTransportTier1,
            (1, 16) => RecipeType.StarfighterKusariMk2Tier1,
            (1, 17) => RecipeType.StarfighterKusariTier1,
            (1, 18) => RecipeType.StarfighterKusariFreighterTier1,
            (1, 19) => RecipeType.StarfighterLibertyMk2Tier1,
            (1, 20) => RecipeType.StarfighterLibertyTier1,
            (1, 21) => RecipeType.StarfighterBretoniaFreighterTier1,
            (1, 22) => RecipeType.StarfighterMandalorianBrutePatrolShipTier1,
            (1, 23) => RecipeType.StarfighterDavaabTypeStarfighterTier1,
            (1, 24) => RecipeType.StarfighterTerochTypeGunshipTier1,
            (1, 25) => RecipeType.StarfighterNeutralBarracudaTier1,
            (1, 26) => RecipeType.StarfighterCivilianBWFighterTier1,
            (1, 27) => RecipeType.StarfighterCivilianCondorTier1,
            (1, 28) => RecipeType.StarfighterCivilianFreighterTier1,
            (1, 29) => RecipeType.StarfighterST07AssaultShipTier1,
            (1, 30) => RecipeType.StarfighterNeutralQuartermasterTransportTier1,
            (1, 31) => RecipeType.StarfighterStarflierTier1,
            (1, 32) => RecipeType.StarfighterYV929HaulerTier1,
            (1, 33) => RecipeType.StarfighterOnderonRupingBomberTier1,
            (1, 34) => RecipeType.StarfighterOnderonType81aFighterTier1,
            (1, 35) => RecipeType.StarfighterOrderFighterTier1,
            (1, 36) => RecipeType.StarfighterPhoebosTier1,
            (1, 37) => RecipeType.StarfighterPirateFighterTier1,
            (1, 38) => RecipeType.StarfighterPirateFreighterTier1,
            (1, 39) => RecipeType.StarfighterAssaultTransportTier1,
            (1, 40) => RecipeType.StarfighterMilitaryBomberMK1Tier1,
            (1, 41) => RecipeType.StarfighterMilitaryBomberMK2Tier1,
            (1, 42) => RecipeType.StarfighterMilitaryBomberMK3Tier1,
            (1, 43) => RecipeType.StarfighterS250ChelaStarfighterTier1,
            (1, 44) => RecipeType.StarfighterMilitaryGunshipLargeTier1,
            (1, 45) => RecipeType.StarfighterMilitaryGunshipMK1Tier1,
            (1, 46) => RecipeType.StarfighterMilitaryGunshipMK2Tier1,
            (1, 47) => RecipeType.StarfighterMilitaryGunshipMK3Tier1,
            (1, 48) => RecipeType.StarfighterInfiltratorMK1V1Tier1,
            (1, 49) => RecipeType.StarfighterInfiltratorMK2V1Tier1,
            (1, 50) => RecipeType.StarfighterInfiltratorMK3V1Tier1,
            (1, 51) => RecipeType.StarfighterTwinInfiltratorTier1,
            (1, 52) => RecipeType.StarfighterAdvancedScoutMK1V1Tier1,
            (1, 53) => RecipeType.StarfighterAdvancedScoutMK2V1Tier1,
            (1, 54) => RecipeType.StarfighterStarSaberXC01Tier1,
            (1, 55) => RecipeType.StarfighterAdvancedStrikerMK1Tier1,
            (1, 56) => RecipeType.StarfighterAdvancedStrikerMK2Tier1,
            (1, 57) => RecipeType.StarfighterAdvancedStrikerMK3Tier1,
            (1, 58) => RecipeType.StarfighterRheinlandMk2Tier1,
            (1, 59) => RecipeType.StarfighterRheinlandTier1,
            (1, 60) => RecipeType.StarfighterRheinlandFreighterTier1,
            (1, 61) => RecipeType.StarfighterAdvancedBomberTier1,
            (1, 62) => RecipeType.StarfighterTwinBomberTier1,
            (1, 63) => RecipeType.StarfighterAdvancedBomberMK2Tier1,
            (1, 64) => RecipeType.StarfighterAdvancedBomberMK3Tier1,
            (1, 65) => RecipeType.StarfighterAdvancedGunboatTier1,
            (1, 66) => RecipeType.StarfighterAdvancedGunshipMK1Tier1,
            (1, 67) => RecipeType.StarfighterAdvancedGunshipMK2Tier1,
            (1, 68) => RecipeType.StarfighterAdvancedGunshipMK3Tier1,
            (1, 69) => RecipeType.StarfighterInfiltratorMK1V2Tier1,
            (1, 70) => RecipeType.StarfighterInfiltratorMK2V2Tier1,
            (1, 71) => RecipeType.StarfighterInfiltratorMK3V2Tier1,
            (1, 72) => RecipeType.StarfighterAdvancedScoutMK1V2Tier1,
            (1, 73) => RecipeType.StarfighterAdvancedScoutMK2V2Tier1,
            (1, 74) => RecipeType.StarfighterAdvancedScoutMK3Tier1,
            (1, 75) => RecipeType.StarfighterAdvancedStrikerMk1Tier1,
            (1, 76) => RecipeType.StarfighterAdvancedStrikerMk2Tier1,
            (1, 77) => RecipeType.StarfighterAdvancedStrikerMk3Tier1,
            (1, 78) => RecipeType.StarfighterKT400LightFreighterTier1,
            (1, 79) => RecipeType.StarfighterTrandoshanTransportTier1,
            (1, 80) => RecipeType.StarfighterXSFreighterTier1,
            (1, 81) => RecipeType.StarfighterY8MinerShipTier1,
            (1, 82) => RecipeType.StarfighterZoomerFighterTier1,
            (1, 83) => RecipeType.StarfighterLegionFighterTier1,
            (2, 1) => RecipeType.StarfighterNeutralStrikerTier2,
            (2, 2) => RecipeType.StarfighterArmoredTransportTier2,
            (2, 3) => RecipeType.StarfighterBretoniaTier2,
            (2, 4) => RecipeType.StarfighterCivilianEliteFighterTier2,
            (2, 5) => RecipeType.StarfighterCivilianFighterTier2,
            (2, 6) => RecipeType.StarfighterCorsairMk2Tier2,
            (2, 7) => RecipeType.StarfighterCorsairTier2,
            (2, 8) => RecipeType.StarfighterCutlassTier2,
            (2, 9) => RecipeType.StarfighterS100StingerStarfighterTier2,
            (2, 10) => RecipeType.StarfighterHuttBomberTier2,
            (2, 11) => RecipeType.StarfighterHuttFighterTier2,
            (2, 12) => RecipeType.StarfighterHuttGunshipTier2,
            (2, 13) => RecipeType.StarfighterInvaderTier2,
            (2, 14) => RecipeType.StarfighterHunterTier2,
            (2, 15) => RecipeType.StarfighterJediTransportTier2,
            (2, 16) => RecipeType.StarfighterKusariMk2Tier2,
            (2, 17) => RecipeType.StarfighterKusariTier2,
            (2, 18) => RecipeType.StarfighterKusariFreighterTier2,
            (2, 19) => RecipeType.StarfighterLibertyMk2Tier2,
            (2, 20) => RecipeType.StarfighterLibertyTier2,
            (2, 21) => RecipeType.StarfighterBretoniaFreighterTier2,
            (2, 22) => RecipeType.StarfighterMandalorianBrutePatrolShipTier2,
            (2, 23) => RecipeType.StarfighterDavaabTypeStarfighterTier2,
            (2, 24) => RecipeType.StarfighterTerochTypeGunshipTier2,
            (2, 25) => RecipeType.StarfighterNeutralBarracudaTier2,
            (2, 26) => RecipeType.StarfighterCivilianBWFighterTier2,
            (2, 27) => RecipeType.StarfighterCivilianCondorTier2,
            (2, 28) => RecipeType.StarfighterCivilianFreighterTier2,
            (2, 29) => RecipeType.StarfighterST07AssaultShipTier2,
            (2, 30) => RecipeType.StarfighterNeutralQuartermasterTransportTier2,
            (2, 31) => RecipeType.StarfighterStarflierTier2,
            (2, 32) => RecipeType.StarfighterYV929HaulerTier2,
            (2, 33) => RecipeType.StarfighterOnderonRupingBomberTier2,
            (2, 34) => RecipeType.StarfighterOnderonType81aFighterTier2,
            (2, 35) => RecipeType.StarfighterOrderFighterTier2,
            (2, 36) => RecipeType.StarfighterPhoebosTier2,
            (2, 37) => RecipeType.StarfighterPirateFighterTier2,
            (2, 38) => RecipeType.StarfighterPirateFreighterTier2,
            (2, 39) => RecipeType.StarfighterAssaultTransportTier2,
            (2, 40) => RecipeType.StarfighterMilitaryBomberMK1Tier2,
            (2, 41) => RecipeType.StarfighterMilitaryBomberMK2Tier2,
            (2, 42) => RecipeType.StarfighterMilitaryBomberMK3Tier2,
            (2, 43) => RecipeType.StarfighterS250ChelaStarfighterTier2,
            (2, 44) => RecipeType.StarfighterMilitaryGunshipLargeTier2,
            (2, 45) => RecipeType.StarfighterMilitaryGunshipMK1Tier2,
            (2, 46) => RecipeType.StarfighterMilitaryGunshipMK2Tier2,
            (2, 47) => RecipeType.StarfighterMilitaryGunshipMK3Tier2,
            (2, 48) => RecipeType.StarfighterInfiltratorMK1V1Tier2,
            (2, 49) => RecipeType.StarfighterInfiltratorMK2V1Tier2,
            (2, 50) => RecipeType.StarfighterInfiltratorMK3V1Tier2,
            (2, 51) => RecipeType.StarfighterTwinInfiltratorTier2,
            (2, 52) => RecipeType.StarfighterAdvancedScoutMK1V1Tier2,
            (2, 53) => RecipeType.StarfighterAdvancedScoutMK2V1Tier2,
            (2, 54) => RecipeType.StarfighterStarSaberXC01Tier2,
            (2, 55) => RecipeType.StarfighterAdvancedStrikerMK1Tier2,
            (2, 56) => RecipeType.StarfighterAdvancedStrikerMK2Tier2,
            (2, 57) => RecipeType.StarfighterAdvancedStrikerMK3Tier2,
            (2, 58) => RecipeType.StarfighterRheinlandMk2Tier2,
            (2, 59) => RecipeType.StarfighterRheinlandTier2,
            (2, 60) => RecipeType.StarfighterRheinlandFreighterTier2,
            (2, 61) => RecipeType.StarfighterAdvancedBomberTier2,
            (2, 62) => RecipeType.StarfighterTwinBomberTier2,
            (2, 63) => RecipeType.StarfighterAdvancedBomberMK2Tier2,
            (2, 64) => RecipeType.StarfighterAdvancedBomberMK3Tier2,
            (2, 65) => RecipeType.StarfighterAdvancedGunboatTier2,
            (2, 66) => RecipeType.StarfighterAdvancedGunshipMK1Tier2,
            (2, 67) => RecipeType.StarfighterAdvancedGunshipMK2Tier2,
            (2, 68) => RecipeType.StarfighterAdvancedGunshipMK3Tier2,
            (2, 69) => RecipeType.StarfighterInfiltratorMK1V2Tier2,
            (2, 70) => RecipeType.StarfighterInfiltratorMK2V2Tier2,
            (2, 71) => RecipeType.StarfighterInfiltratorMK3V2Tier2,
            (2, 72) => RecipeType.StarfighterAdvancedScoutMK1V2Tier2,
            (2, 73) => RecipeType.StarfighterAdvancedScoutMK2V2Tier2,
            (2, 74) => RecipeType.StarfighterAdvancedScoutMK3Tier2,
            (2, 75) => RecipeType.StarfighterAdvancedStrikerMk1Tier2,
            (2, 76) => RecipeType.StarfighterAdvancedStrikerMk2Tier2,
            (2, 77) => RecipeType.StarfighterAdvancedStrikerMk3Tier2,
            (2, 78) => RecipeType.StarfighterKT400LightFreighterTier2,
            (2, 79) => RecipeType.StarfighterTrandoshanTransportTier2,
            (2, 80) => RecipeType.StarfighterXSFreighterTier2,
            (2, 81) => RecipeType.StarfighterY8MinerShipTier2,
            (2, 82) => RecipeType.StarfighterZoomerFighterTier2,
            (2, 83) => RecipeType.StarfighterLegionFighterTier2,
            (3, 1) => RecipeType.StarfighterNeutralStrikerTier3,
            (3, 2) => RecipeType.StarfighterArmoredTransportTier3,
            (3, 3) => RecipeType.StarfighterBretoniaTier3,
            (3, 4) => RecipeType.StarfighterCivilianEliteFighterTier3,
            (3, 5) => RecipeType.StarfighterCivilianFighterTier3,
            (3, 6) => RecipeType.StarfighterCorsairMk2Tier3,
            (3, 7) => RecipeType.StarfighterCorsairTier3,
            (3, 8) => RecipeType.StarfighterCutlassTier3,
            (3, 9) => RecipeType.StarfighterS100StingerStarfighterTier3,
            (3, 10) => RecipeType.StarfighterHuttBomberTier3,
            (3, 11) => RecipeType.StarfighterHuttFighterTier3,
            (3, 12) => RecipeType.StarfighterHuttGunshipTier3,
            (3, 13) => RecipeType.StarfighterInvaderTier3,
            (3, 14) => RecipeType.StarfighterHunterTier3,
            (3, 15) => RecipeType.StarfighterJediTransportTier3,
            (3, 16) => RecipeType.StarfighterKusariMk2Tier3,
            (3, 17) => RecipeType.StarfighterKusariTier3,
            (3, 18) => RecipeType.StarfighterKusariFreighterTier3,
            (3, 19) => RecipeType.StarfighterLibertyMk2Tier3,
            (3, 20) => RecipeType.StarfighterLibertyTier3,
            (3, 21) => RecipeType.StarfighterBretoniaFreighterTier3,
            (3, 22) => RecipeType.StarfighterMandalorianBrutePatrolShipTier3,
            (3, 23) => RecipeType.StarfighterDavaabTypeStarfighterTier3,
            (3, 24) => RecipeType.StarfighterTerochTypeGunshipTier3,
            (3, 25) => RecipeType.StarfighterNeutralBarracudaTier3,
            (3, 26) => RecipeType.StarfighterCivilianBWFighterTier3,
            (3, 27) => RecipeType.StarfighterCivilianCondorTier3,
            (3, 28) => RecipeType.StarfighterCivilianFreighterTier3,
            (3, 29) => RecipeType.StarfighterST07AssaultShipTier3,
            (3, 30) => RecipeType.StarfighterNeutralQuartermasterTransportTier3,
            (3, 31) => RecipeType.StarfighterStarflierTier3,
            (3, 32) => RecipeType.StarfighterYV929HaulerTier3,
            (3, 33) => RecipeType.StarfighterOnderonRupingBomberTier3,
            (3, 34) => RecipeType.StarfighterOnderonType81aFighterTier3,
            (3, 35) => RecipeType.StarfighterOrderFighterTier3,
            (3, 36) => RecipeType.StarfighterPhoebosTier3,
            (3, 37) => RecipeType.StarfighterPirateFighterTier3,
            (3, 38) => RecipeType.StarfighterPirateFreighterTier3,
            (3, 39) => RecipeType.StarfighterAssaultTransportTier3,
            (3, 40) => RecipeType.StarfighterMilitaryBomberMK1Tier3,
            (3, 41) => RecipeType.StarfighterMilitaryBomberMK2Tier3,
            (3, 42) => RecipeType.StarfighterMilitaryBomberMK3Tier3,
            (3, 43) => RecipeType.StarfighterS250ChelaStarfighterTier3,
            (3, 44) => RecipeType.StarfighterMilitaryGunshipLargeTier3,
            (3, 45) => RecipeType.StarfighterMilitaryGunshipMK1Tier3,
            (3, 46) => RecipeType.StarfighterMilitaryGunshipMK2Tier3,
            (3, 47) => RecipeType.StarfighterMilitaryGunshipMK3Tier3,
            (3, 48) => RecipeType.StarfighterInfiltratorMK1V1Tier3,
            (3, 49) => RecipeType.StarfighterInfiltratorMK2V1Tier3,
            (3, 50) => RecipeType.StarfighterInfiltratorMK3V1Tier3,
            (3, 51) => RecipeType.StarfighterTwinInfiltratorTier3,
            (3, 52) => RecipeType.StarfighterAdvancedScoutMK1V1Tier3,
            (3, 53) => RecipeType.StarfighterAdvancedScoutMK2V1Tier3,
            (3, 54) => RecipeType.StarfighterStarSaberXC01Tier3,
            (3, 55) => RecipeType.StarfighterAdvancedStrikerMK1Tier3,
            (3, 56) => RecipeType.StarfighterAdvancedStrikerMK2Tier3,
            (3, 57) => RecipeType.StarfighterAdvancedStrikerMK3Tier3,
            (3, 58) => RecipeType.StarfighterRheinlandMk2Tier3,
            (3, 59) => RecipeType.StarfighterRheinlandTier3,
            (3, 60) => RecipeType.StarfighterRheinlandFreighterTier3,
            (3, 61) => RecipeType.StarfighterAdvancedBomberTier3,
            (3, 62) => RecipeType.StarfighterTwinBomberTier3,
            (3, 63) => RecipeType.StarfighterAdvancedBomberMK2Tier3,
            (3, 64) => RecipeType.StarfighterAdvancedBomberMK3Tier3,
            (3, 65) => RecipeType.StarfighterAdvancedGunboatTier3,
            (3, 66) => RecipeType.StarfighterAdvancedGunshipMK1Tier3,
            (3, 67) => RecipeType.StarfighterAdvancedGunshipMK2Tier3,
            (3, 68) => RecipeType.StarfighterAdvancedGunshipMK3Tier3,
            (3, 69) => RecipeType.StarfighterInfiltratorMK1V2Tier3,
            (3, 70) => RecipeType.StarfighterInfiltratorMK2V2Tier3,
            (3, 71) => RecipeType.StarfighterInfiltratorMK3V2Tier3,
            (3, 72) => RecipeType.StarfighterAdvancedScoutMK1V2Tier3,
            (3, 73) => RecipeType.StarfighterAdvancedScoutMK2V2Tier3,
            (3, 74) => RecipeType.StarfighterAdvancedScoutMK3Tier3,
            (3, 75) => RecipeType.StarfighterAdvancedStrikerMk1Tier3,
            (3, 76) => RecipeType.StarfighterAdvancedStrikerMk2Tier3,
            (3, 77) => RecipeType.StarfighterAdvancedStrikerMk3Tier3,
            (3, 78) => RecipeType.StarfighterKT400LightFreighterTier3,
            (3, 79) => RecipeType.StarfighterTrandoshanTransportTier3,
            (3, 80) => RecipeType.StarfighterXSFreighterTier3,
            (3, 81) => RecipeType.StarfighterY8MinerShipTier3,
            (3, 82) => RecipeType.StarfighterZoomerFighterTier3,
            (3, 83) => RecipeType.StarfighterLegionFighterTier3,
            (4, 1) => RecipeType.StarfighterNeutralStrikerTier4,
            (4, 2) => RecipeType.StarfighterArmoredTransportTier4,
            (4, 3) => RecipeType.StarfighterBretoniaTier4,
            (4, 4) => RecipeType.StarfighterCivilianEliteFighterTier4,
            (4, 5) => RecipeType.StarfighterCivilianFighterTier4,
            (4, 6) => RecipeType.StarfighterCorsairMk2Tier4,
            (4, 7) => RecipeType.StarfighterCorsairTier4,
            (4, 8) => RecipeType.StarfighterCutlassTier4,
            (4, 9) => RecipeType.StarfighterS100StingerStarfighterTier4,
            (4, 10) => RecipeType.StarfighterHuttBomberTier4,
            (4, 11) => RecipeType.StarfighterHuttFighterTier4,
            (4, 12) => RecipeType.StarfighterHuttGunshipTier4,
            (4, 13) => RecipeType.StarfighterInvaderTier4,
            (4, 14) => RecipeType.StarfighterHunterTier4,
            (4, 15) => RecipeType.StarfighterJediTransportTier4,
            (4, 16) => RecipeType.StarfighterKusariMk2Tier4,
            (4, 17) => RecipeType.StarfighterKusariTier4,
            (4, 18) => RecipeType.StarfighterKusariFreighterTier4,
            (4, 19) => RecipeType.StarfighterLibertyMk2Tier4,
            (4, 20) => RecipeType.StarfighterLibertyTier4,
            (4, 21) => RecipeType.StarfighterBretoniaFreighterTier4,
            (4, 22) => RecipeType.StarfighterMandalorianBrutePatrolShipTier4,
            (4, 23) => RecipeType.StarfighterDavaabTypeStarfighterTier4,
            (4, 24) => RecipeType.StarfighterTerochTypeGunshipTier4,
            (4, 25) => RecipeType.StarfighterNeutralBarracudaTier4,
            (4, 26) => RecipeType.StarfighterCivilianBWFighterTier4,
            (4, 27) => RecipeType.StarfighterCivilianCondorTier4,
            (4, 28) => RecipeType.StarfighterCivilianFreighterTier4,
            (4, 29) => RecipeType.StarfighterST07AssaultShipTier4,
            (4, 30) => RecipeType.StarfighterNeutralQuartermasterTransportTier4,
            (4, 31) => RecipeType.StarfighterStarflierTier4,
            (4, 32) => RecipeType.StarfighterYV929HaulerTier4,
            (4, 33) => RecipeType.StarfighterOnderonRupingBomberTier4,
            (4, 34) => RecipeType.StarfighterOnderonType81aFighterTier4,
            (4, 35) => RecipeType.StarfighterOrderFighterTier4,
            (4, 36) => RecipeType.StarfighterPhoebosTier4,
            (4, 37) => RecipeType.StarfighterPirateFighterTier4,
            (4, 38) => RecipeType.StarfighterPirateFreighterTier4,
            (4, 39) => RecipeType.StarfighterAssaultTransportTier4,
            (4, 40) => RecipeType.StarfighterMilitaryBomberMK1Tier4,
            (4, 41) => RecipeType.StarfighterMilitaryBomberMK2Tier4,
            (4, 42) => RecipeType.StarfighterMilitaryBomberMK3Tier4,
            (4, 43) => RecipeType.StarfighterS250ChelaStarfighterTier4,
            (4, 44) => RecipeType.StarfighterMilitaryGunshipLargeTier4,
            (4, 45) => RecipeType.StarfighterMilitaryGunshipMK1Tier4,
            (4, 46) => RecipeType.StarfighterMilitaryGunshipMK2Tier4,
            (4, 47) => RecipeType.StarfighterMilitaryGunshipMK3Tier4,
            (4, 48) => RecipeType.StarfighterInfiltratorMK1V1Tier4,
            (4, 49) => RecipeType.StarfighterInfiltratorMK2V1Tier4,
            (4, 50) => RecipeType.StarfighterInfiltratorMK3V1Tier4,
            (4, 51) => RecipeType.StarfighterTwinInfiltratorTier4,
            (4, 52) => RecipeType.StarfighterAdvancedScoutMK1V1Tier4,
            (4, 53) => RecipeType.StarfighterAdvancedScoutMK2V1Tier4,
            (4, 54) => RecipeType.StarfighterStarSaberXC01Tier4,
            (4, 55) => RecipeType.StarfighterAdvancedStrikerMK1Tier4,
            (4, 56) => RecipeType.StarfighterAdvancedStrikerMK2Tier4,
            (4, 57) => RecipeType.StarfighterAdvancedStrikerMK3Tier4,
            (4, 58) => RecipeType.StarfighterRheinlandMk2Tier4,
            (4, 59) => RecipeType.StarfighterRheinlandTier4,
            (4, 60) => RecipeType.StarfighterRheinlandFreighterTier4,
            (4, 61) => RecipeType.StarfighterAdvancedBomberTier4,
            (4, 62) => RecipeType.StarfighterTwinBomberTier4,
            (4, 63) => RecipeType.StarfighterAdvancedBomberMK2Tier4,
            (4, 64) => RecipeType.StarfighterAdvancedBomberMK3Tier4,
            (4, 65) => RecipeType.StarfighterAdvancedGunboatTier4,
            (4, 66) => RecipeType.StarfighterAdvancedGunshipMK1Tier4,
            (4, 67) => RecipeType.StarfighterAdvancedGunshipMK2Tier4,
            (4, 68) => RecipeType.StarfighterAdvancedGunshipMK3Tier4,
            (4, 69) => RecipeType.StarfighterInfiltratorMK1V2Tier4,
            (4, 70) => RecipeType.StarfighterInfiltratorMK2V2Tier4,
            (4, 71) => RecipeType.StarfighterInfiltratorMK3V2Tier4,
            (4, 72) => RecipeType.StarfighterAdvancedScoutMK1V2Tier4,
            (4, 73) => RecipeType.StarfighterAdvancedScoutMK2V2Tier4,
            (4, 74) => RecipeType.StarfighterAdvancedScoutMK3Tier4,
            (4, 75) => RecipeType.StarfighterAdvancedStrikerMk1Tier4,
            (4, 76) => RecipeType.StarfighterAdvancedStrikerMk2Tier4,
            (4, 77) => RecipeType.StarfighterAdvancedStrikerMk3Tier4,
            (4, 78) => RecipeType.StarfighterKT400LightFreighterTier4,
            (4, 79) => RecipeType.StarfighterTrandoshanTransportTier4,
            (4, 80) => RecipeType.StarfighterXSFreighterTier4,
            (4, 81) => RecipeType.StarfighterY8MinerShipTier4,
            (4, 82) => RecipeType.StarfighterZoomerFighterTier4,
            (4, 83) => RecipeType.StarfighterLegionFighterTier4,
            (5, 1) => RecipeType.StarfighterNeutralStrikerTier5,
            (5, 2) => RecipeType.StarfighterArmoredTransportTier5,
            (5, 3) => RecipeType.StarfighterBretoniaTier5,
            (5, 4) => RecipeType.StarfighterCivilianEliteFighterTier5,
            (5, 5) => RecipeType.StarfighterCivilianFighterTier5,
            (5, 6) => RecipeType.StarfighterCorsairMk2Tier5,
            (5, 7) => RecipeType.StarfighterCorsairTier5,
            (5, 8) => RecipeType.StarfighterCutlassTier5,
            (5, 9) => RecipeType.StarfighterS100StingerStarfighterTier5,
            (5, 10) => RecipeType.StarfighterHuttBomberTier5,
            (5, 11) => RecipeType.StarfighterHuttFighterTier5,
            (5, 12) => RecipeType.StarfighterHuttGunshipTier5,
            (5, 13) => RecipeType.StarfighterInvaderTier5,
            (5, 14) => RecipeType.StarfighterHunterTier5,
            (5, 15) => RecipeType.StarfighterJediTransportTier5,
            (5, 16) => RecipeType.StarfighterKusariMk2Tier5,
            (5, 17) => RecipeType.StarfighterKusariTier5,
            (5, 18) => RecipeType.StarfighterKusariFreighterTier5,
            (5, 19) => RecipeType.StarfighterLibertyMk2Tier5,
            (5, 20) => RecipeType.StarfighterLibertyTier5,
            (5, 21) => RecipeType.StarfighterBretoniaFreighterTier5,
            (5, 22) => RecipeType.StarfighterMandalorianBrutePatrolShipTier5,
            (5, 23) => RecipeType.StarfighterDavaabTypeStarfighterTier5,
            (5, 24) => RecipeType.StarfighterTerochTypeGunshipTier5,
            (5, 25) => RecipeType.StarfighterNeutralBarracudaTier5,
            (5, 26) => RecipeType.StarfighterCivilianBWFighterTier5,
            (5, 27) => RecipeType.StarfighterCivilianCondorTier5,
            (5, 28) => RecipeType.StarfighterCivilianFreighterTier5,
            (5, 29) => RecipeType.StarfighterST07AssaultShipTier5,
            (5, 30) => RecipeType.StarfighterNeutralQuartermasterTransportTier5,
            (5, 31) => RecipeType.StarfighterStarflierTier5,
            (5, 32) => RecipeType.StarfighterYV929HaulerTier5,
            (5, 33) => RecipeType.StarfighterOnderonRupingBomberTier5,
            (5, 34) => RecipeType.StarfighterOnderonType81aFighterTier5,
            (5, 35) => RecipeType.StarfighterOrderFighterTier5,
            (5, 36) => RecipeType.StarfighterPhoebosTier5,
            (5, 37) => RecipeType.StarfighterPirateFighterTier5,
            (5, 38) => RecipeType.StarfighterPirateFreighterTier5,
            (5, 39) => RecipeType.StarfighterAssaultTransportTier5,
            (5, 40) => RecipeType.StarfighterMilitaryBomberMK1Tier5,
            (5, 41) => RecipeType.StarfighterMilitaryBomberMK2Tier5,
            (5, 42) => RecipeType.StarfighterMilitaryBomberMK3Tier5,
            (5, 43) => RecipeType.StarfighterS250ChelaStarfighterTier5,
            (5, 44) => RecipeType.StarfighterMilitaryGunshipLargeTier5,
            (5, 45) => RecipeType.StarfighterMilitaryGunshipMK1Tier5,
            (5, 46) => RecipeType.StarfighterMilitaryGunshipMK2Tier5,
            (5, 47) => RecipeType.StarfighterMilitaryGunshipMK3Tier5,
            (5, 48) => RecipeType.StarfighterInfiltratorMK1V1Tier5,
            (5, 49) => RecipeType.StarfighterInfiltratorMK2V1Tier5,
            (5, 50) => RecipeType.StarfighterInfiltratorMK3V1Tier5,
            (5, 51) => RecipeType.StarfighterTwinInfiltratorTier5,
            (5, 52) => RecipeType.StarfighterAdvancedScoutMK1V1Tier5,
            (5, 53) => RecipeType.StarfighterAdvancedScoutMK2V1Tier5,
            (5, 54) => RecipeType.StarfighterStarSaberXC01Tier5,
            (5, 55) => RecipeType.StarfighterAdvancedStrikerMK1Tier5,
            (5, 56) => RecipeType.StarfighterAdvancedStrikerMK2Tier5,
            (5, 57) => RecipeType.StarfighterAdvancedStrikerMK3Tier5,
            (5, 58) => RecipeType.StarfighterRheinlandMk2Tier5,
            (5, 59) => RecipeType.StarfighterRheinlandTier5,
            (5, 60) => RecipeType.StarfighterRheinlandFreighterTier5,
            (5, 61) => RecipeType.StarfighterAdvancedBomberTier5,
            (5, 62) => RecipeType.StarfighterTwinBomberTier5,
            (5, 63) => RecipeType.StarfighterAdvancedBomberMK2Tier5,
            (5, 64) => RecipeType.StarfighterAdvancedBomberMK3Tier5,
            (5, 65) => RecipeType.StarfighterAdvancedGunboatTier5,
            (5, 66) => RecipeType.StarfighterAdvancedGunshipMK1Tier5,
            (5, 67) => RecipeType.StarfighterAdvancedGunshipMK2Tier5,
            (5, 68) => RecipeType.StarfighterAdvancedGunshipMK3Tier5,
            (5, 69) => RecipeType.StarfighterInfiltratorMK1V2Tier5,
            (5, 70) => RecipeType.StarfighterInfiltratorMK2V2Tier5,
            (5, 71) => RecipeType.StarfighterInfiltratorMK3V2Tier5,
            (5, 72) => RecipeType.StarfighterAdvancedScoutMK1V2Tier5,
            (5, 73) => RecipeType.StarfighterAdvancedScoutMK2V2Tier5,
            (5, 74) => RecipeType.StarfighterAdvancedScoutMK3Tier5,
            (5, 75) => RecipeType.StarfighterAdvancedStrikerMk1Tier5,
            (5, 76) => RecipeType.StarfighterAdvancedStrikerMk2Tier5,
            (5, 77) => RecipeType.StarfighterAdvancedStrikerMk3Tier5,
            (5, 78) => RecipeType.StarfighterKT400LightFreighterTier5,
            (5, 79) => RecipeType.StarfighterTrandoshanTransportTier5,
            (5, 80) => RecipeType.StarfighterXSFreighterTier5,
            (5, 81) => RecipeType.StarfighterY8MinerShipTier5,
            (5, 82) => RecipeType.StarfighterZoomerFighterTier5,
            (5, 83) => RecipeType.StarfighterLegionFighterTier5,
            _ => RecipeType.Invalid,
        };

    }
}
