# build the dotnet
FROM mcr.microsoft.com/dotnet/core/sdk:3.1.102 AS DotnetLibraryBuild
ADD . /Build
WORKDIR /Build/SWLOR.Game.Server
RUN dotnet publish -c Release
# final image
FROM nwnxee/unified:latest
LABEL maintainer = "urothis@gmail.com"
# copy dotnet library to nwnxee image
COPY --from=DotnetLibraryBuild /Build/SWLOR.Game.Server/bin/Release/netcoreapp3.1/publish /nwn/data/data/
# dotNET
ENV NWNX_DOTNET_SKIP=n
ENV NWNX_DOTNET_ASSEMBLY=/nwn/data/data/SWLOR.Game.Server
# ENV NWNX_DOTNET_NETHOST_PATH=/usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/3.1.2/runtimes/linux-x64/native/libnethost.so
ENV NWNX_DOTNET_ENTRYPOINT=NWN.Internal
# often values
ENV NWN_MODULE=testmod
ENV NWN_PUBLICSERVER=0
ENV NWNX_CORE_LOG_LEVEL=6
# private values | pulled from gitlab
ARG NWNX_WEBHOOK_PRIVATE_CHANNEL
ARG NWNX_WEBHOOK_PUBLIC_CHANNEL
ARG NWN_DMPASSWORD
# set the env to the variable from gitlab
ENV NWNX_WEBHOOK_PRIVATE_CHANNEL=${NWNX_WEBHOOK_PRIVATE_CHANNEL} NWNX_WEBHOOK_PUBLIC_CHANNEL=${NWNX_WEBHOOK_PUBLIC_CHANNEL} NWN_DMPASSWORD=${NWN_DMPASSWORD}
# NWNX Plugins
ENV NWNX_ADMINISTRATION_SKIP=n NWNX_AREA_SKIP=n NWNX_CHAT_SKIP=n NWNX_CREATURE_SKIP=n NWNX_DAMAGE_SKIP=n NWNX_DATA_SKIP=n
ENV NWNX_EVENTS_SKIP=n NWNX_FEEDBACK_SKIP=n NWNX_ITEM_SKIP=n NWNX_ITEMPROPERTY_SKIP=n NWNX_OBJECT_SKIP=n NWNX_PLAYER_SKIP=n
ENV NWNX_UTIL_SKIP=n NWNX_VISIBILITY_SKIP=n NWNX_WEAPON_SKIP=n NWNX_RENAME_SKIP=n NWNX_REVEAL_SKIP=n NWNX_TWEAKS_SKIP=n
ENV NWNX_PROFILER_SKIP=n NWNX_PROFILER_ENABLE_SCRIPTS=false
# tweaks
ENV NWNX_TWEAKS_DISABLE_PAUSE=true NWNX_TWEAKS_DISABLE_QUICKSAVE=true NWNX_TWEAKS_PRESERVE_ACTIONS_ON_DM_POSSESS=true NWNX_TWEAKS_HIDE_CLASSES_ON_CHAR_LIST=true NWNX_TWEAKS_COMPARE_VARIABLES_WHEN_MERGING=true
# vanilla nwserver flags
ENV NWN_SERVERNAME="SWLOR Testing" NWN_MODULE="Star Wars LOR" NWN_PUBLICSERVER=1 NWN_MAXCLIENTS=96 NWN_MINLEVEL=1 NWN_MAXLEVEL=40
ENV NWN_ONEPARTY=0 NWN_PAUSEANDPLAY=0 NWN_PORT=5121 NWN_PVP=2 NWN_RELOADWHENEMPTY=0 NWN_SERVERVAULT=1
# stuff from zunaths launch exe
ENV SQL_SERVER_IP_ADDRESS=192.168.0.102 SQL_SERVER_USERNAME=zunath SQL_SERVER_PASSWORD=testpass SQL_SERVER_DATABASE=swlor
ENV DISCORD_WEBHOOK_URL="" DEBUGGING_ENABLED=true DEBUGGING_COMPONENT_ENABLED_SPACE=false DEBUGGING_COMPONENT_ENABLED_WEATHER=false DEBUGGING_COMPONENT_ENABLED_BASE=false DEBUGGING_COMPONENT_ENABLED_LASTATTACK=false