using System.Collections.Generic;
using SWLOR.Game.Server.Core.NWScript.Enum;
using SWLOR.Game.Server.Service.BeastMasteryService;

namespace SWLOR.Game.Server.Feature.BeastDefinition
{
    public class AradileBeastDefinition: IBeastListDefinition
    {
        private readonly BeastBuilder _builder = new();

        public Dictionary<BeastType, BeastDetail> Build()
        {
            _builder.Create(BeastType.Aradile)
                .Appearance(AppearanceType.LizardGiantBrown)
                .CombatStats(AbilityType.Vitality, AbilityType.Might)
                .Role(BeastRoleType.Bruiser)

                
                // Level 1
                .AddLevel()
                .HP(50)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 7)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 7)

                // Level 2
                .AddLevel()
                .HP(42)
                .FP(6)
                .STM(7)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 7)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 7)

                // Level 3
                .AddLevel()
                .HP(60)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 7)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 7)

                // Level 4
                .AddLevel()
                .HP(78)
                .FP(7)
                .STM(8)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 7)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 7)

                // Level 5
                .AddLevel()
                .HP(96)
                .FP(7)
                .STM(9)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 8)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 8)

                // Level 6
                .AddLevel()
                .HP(114)
                .FP(8)
                .STM(10)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 8)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 8)

                // Level 7
                .AddLevel()
                .HP(132)
                .FP(8)
                .STM(10)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 8)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 8)

                // Level 8
                .AddLevel()
                .HP(150)
                .FP(8)
                .STM(11)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 8)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 8)

                // Level 9
                .AddLevel()
                .HP(168)
                .FP(8)
                .STM(12)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 8)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 8)

                // Level 10
                .AddLevel()
                .HP(186)
                .FP(9)
                .STM(12)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 8)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 8)

                // Level 11
                .AddLevel()
                .HP(204)
                .FP(9)
                .STM(13)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 8)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 8)

                // Level 12
                .AddLevel()
                .HP(222)
                .FP(9)
                .STM(14)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 8)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 8)

                // Level 13
                .AddLevel()
                .HP(240)
                .FP(10)
                .STM(14)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 8)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 8)

                // Level 14
                .AddLevel()
                .HP(258)
                .FP(10)
                .STM(15)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 8)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 8)

                // Level 15
                .AddLevel()
                .HP(276)
                .FP(10)
                .STM(16)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 9)

                // Level 16
                .AddLevel()
                .HP(294)
                .FP(11)
                .STM(17)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 9)

                // Level 17
                .AddLevel()
                .HP(312)
                .FP(11)
                .STM(17)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 9)

                // Level 18
                .AddLevel()
                .HP(330)
                .FP(11)
                .STM(18)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 19
                .AddLevel()
                .HP(348)
                .FP(11)
                .STM(19)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 20
                .AddLevel()
                .HP(366)
                .FP(12)
                .STM(19)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 21
                .AddLevel()
                .HP(384)
                .FP(12)
                .STM(20)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 22
                .AddLevel()
                .HP(402)
                .FP(12)
                .STM(21)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 23
                .AddLevel()
                .HP(420)
                .FP(13)
                .STM(21)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 24
                .AddLevel()
                .HP(438)
                .FP(13)
                .STM(22)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 25
                .AddLevel()
                .HP(456)
                .FP(13)
                .STM(23)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 26
                .AddLevel()
                .HP(474)
                .FP(14)
                .STM(24)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 27
                .AddLevel()
                .HP(492)
                .FP(14)
                .STM(24)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 28
                .AddLevel()
                .HP(510)
                .FP(14)
                .STM(25)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 29
                .AddLevel()
                .HP(528)
                .FP(14)
                .STM(26)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 27)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 30
                .AddLevel()
                .HP(546)
                .FP(15)
                .STM(26)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 27)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 31
                .AddLevel()
                .HP(564)
                .FP(15)
                .STM(27)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 27)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 32
                .AddLevel()
                .HP(582)
                .FP(15)
                .STM(28)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 27)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 10)

                // Level 33
                .AddLevel()
                .HP(600)
                .FP(16)
                .STM(28)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 28)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 10)

                // Level 34
                .AddLevel()
                .HP(618)
                .FP(16)
                .STM(29)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 28)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 10)

                // Level 35
                .AddLevel()
                .HP(636)
                .FP(16)
                .STM(30)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 28)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 11)

                // Level 36
                .AddLevel()
                .HP(654)
                .FP(17)
                .STM(31)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 29)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 11)

                // Level 37
                .AddLevel()
                .HP(672)
                .FP(17)
                .STM(31)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 29)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 11)

                // Level 38
                .AddLevel()
                .HP(690)
                .FP(17)
                .STM(32)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 29)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 11)

                // Level 39
                .AddLevel()
                .HP(708)
                .FP(17)
                .STM(33)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 29)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 11)

                // Level 40
                .AddLevel()
                .HP(726)
                .FP(18)
                .STM(33)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 30)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 11)

                // Level 41
                .AddLevel()
                .HP(744)
                .FP(18)
                .STM(34)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 30)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 11)

                // Level 42
                .AddLevel()
                .HP(762)
                .FP(18)
                .STM(35)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 30)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 11)

                // Level 43
                .AddLevel()
                .HP(780)
                .FP(19)
                .STM(35)
                .Stat(AbilityType.Might, 29)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 30)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 11)

                // Level 44
                .AddLevel()
                .HP(798)
                .FP(19)
                .STM(36)
                .Stat(AbilityType.Might, 29)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 31)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 11)

                // Level 45
                .AddLevel()
                .HP(816)
                .FP(19)
                .STM(37)
                .Stat(AbilityType.Might, 29)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 31)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 12)

                // Level 46
                .AddLevel()
                .HP(834)
                .FP(20)
                .STM(38)
                .Stat(AbilityType.Might, 29)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 31)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 12)

                // Level 47
                .AddLevel()
                .HP(852)
                .FP(20)
                .STM(38)
                .Stat(AbilityType.Might, 30)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 31)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 12)

                // Level 48
                .AddLevel()
                .HP(870)
                .FP(20)
                .STM(39)
                .Stat(AbilityType.Might, 30)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 32)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 12)

                // Level 49
                .AddLevel()
                .HP(888)
                .FP(20)
                .STM(40)
                .Stat(AbilityType.Might, 30)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 32)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 12)

                // Level 50
                .AddLevel()
                .HP(950)
                .FP(21)
                .STM(40)
                .Stat(AbilityType.Might, 30)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 32)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 12)


                ;

            return _builder.Build();
        }
    }
}
