using System.Collections.Generic;
using SWLOR.Game.Server.Core.NWScript.Enum;
using SWLOR.Game.Server.Service.BeastMasteryService;

namespace SWLOR.Game.Server.Feature.BeastDefinition
{
    public class CrystalSpiderBeastDefinition: IBeastListDefinition
    {
        private readonly BeastBuilder _builder = new();

        public Dictionary<BeastType, BeastDetail> Build()
        {
            _builder.Create(BeastType.CrystalSpider)
                .Appearance(AppearanceType.SpiderCrystalB)
                .CombatStats(AbilityType.Agility, AbilityType.Willpower)
                .Role(BeastRoleType.Force)

                
                // Level 1
                .AddLevel()
                .HP(20)
                .FP(2)
                .STM(2)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 6)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 2
                .AddLevel()
                .HP(38)
                .FP(3)
                .STM(2)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 6)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 3
                .AddLevel()
                .HP(56)
                .FP(3)
                .STM(2)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 6)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 4
                .AddLevel()
                .HP(74)
                .FP(4)
                .STM(2)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 6)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 5
                .AddLevel()
                .HP(92)
                .FP(5)
                .STM(2)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 6)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 8)

                // Level 6
                .AddLevel()
                .HP(110)
                .FP(6)
                .STM(3)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 6)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 8)

                // Level 7
                .AddLevel()
                .HP(128)
                .FP(6)
                .STM(3)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 7)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 8)

                // Level 8
                .AddLevel()
                .HP(146)
                .FP(7)
                .STM(3)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 7)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 8)

                // Level 9
                .AddLevel()
                .HP(164)
                .FP(8)
                .STM(3)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 7)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 8)

                // Level 10
                .AddLevel()
                .HP(182)
                .FP(8)
                .STM(3)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 7)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 8)

                // Level 11
                .AddLevel()
                .HP(200)
                .FP(9)
                .STM(3)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 7)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 8)

                // Level 12
                .AddLevel()
                .HP(218)
                .FP(10)
                .STM(3)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 7)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 13
                .AddLevel()
                .HP(236)
                .FP(10)
                .STM(3)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 7)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 14
                .AddLevel()
                .HP(254)
                .FP(11)
                .STM(3)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 7)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 15
                .AddLevel()
                .HP(272)
                .FP(12)
                .STM(3)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 7)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 9)

                // Level 16
                .AddLevel()
                .HP(290)
                .FP(13)
                .STM(4)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 7)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 9)

                // Level 17
                .AddLevel()
                .HP(308)
                .FP(13)
                .STM(4)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 7)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 9)

                // Level 18
                .AddLevel()
                .HP(326)
                .FP(14)
                .STM(4)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 7)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 9)

                // Level 19
                .AddLevel()
                .HP(344)
                .FP(15)
                .STM(4)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 8)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 9)

                // Level 20
                .AddLevel()
                .HP(362)
                .FP(15)
                .STM(4)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 8)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 9)

                // Level 21
                .AddLevel()
                .HP(380)
                .FP(16)
                .STM(4)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 8)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 9)

                // Level 22
                .AddLevel()
                .HP(398)
                .FP(17)
                .STM(4)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 8)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 9)

                // Level 23
                .AddLevel()
                .HP(416)
                .FP(17)
                .STM(4)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 8)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 9)

                // Level 24
                .AddLevel()
                .HP(434)
                .FP(18)
                .STM(4)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 8)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 9)

                // Level 25
                .AddLevel()
                .HP(452)
                .FP(19)
                .STM(4)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 8)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 10)

                // Level 26
                .AddLevel()
                .HP(470)
                .FP(20)
                .STM(5)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 8)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 10)

                // Level 27
                .AddLevel()
                .HP(488)
                .FP(20)
                .STM(5)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 8)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 10)

                // Level 28
                .AddLevel()
                .HP(506)
                .FP(21)
                .STM(5)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 8)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 10)

                // Level 29
                .AddLevel()
                .HP(524)
                .FP(22)
                .STM(5)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 8)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 10)

                // Level 30
                .AddLevel()
                .HP(542)
                .FP(22)
                .STM(5)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 8)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 10)

                // Level 31
                .AddLevel()
                .HP(560)
                .FP(23)
                .STM(5)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 10)

                // Level 32
                .AddLevel()
                .HP(578)
                .FP(24)
                .STM(5)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 10)

                // Level 33
                .AddLevel()
                .HP(596)
                .FP(24)
                .STM(5)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 10)

                // Level 34
                .AddLevel()
                .HP(614)
                .FP(25)
                .STM(5)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 10)

                // Level 35
                .AddLevel()
                .HP(632)
                .FP(26)
                .STM(5)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 11)

                // Level 36
                .AddLevel()
                .HP(650)
                .FP(27)
                .STM(6)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 11)

                // Level 37
                .AddLevel()
                .HP(668)
                .FP(27)
                .STM(6)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 11)

                // Level 38
                .AddLevel()
                .HP(686)
                .FP(28)
                .STM(6)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 11)

                // Level 39
                .AddLevel()
                .HP(704)
                .FP(29)
                .STM(6)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 11)

                // Level 40
                .AddLevel()
                .HP(722)
                .FP(29)
                .STM(6)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 11)

                // Level 41
                .AddLevel()
                .HP(740)
                .FP(30)
                .STM(6)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 22)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 11)

                // Level 42
                .AddLevel()
                .HP(758)
                .FP(31)
                .STM(6)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 22)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 11)

                // Level 43
                .AddLevel()
                .HP(776)
                .FP(31)
                .STM(6)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 22)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 11)

                // Level 44
                .AddLevel()
                .HP(794)
                .FP(32)
                .STM(6)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 22)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 11)

                // Level 45
                .AddLevel()
                .HP(812)
                .FP(33)
                .STM(6)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 22)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 12)

                // Level 46
                .AddLevel()
                .HP(830)
                .FP(34)
                .STM(7)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 22)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 12)

                // Level 47
                .AddLevel()
                .HP(848)
                .FP(34)
                .STM(7)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 23)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 12)

                // Level 48
                .AddLevel()
                .HP(866)
                .FP(35)
                .STM(7)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 23)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 12)

                // Level 49
                .AddLevel()
                .HP(884)
                .FP(36)
                .STM(7)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 23)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 12)

                // Level 50
                .AddLevel()
                .HP(940)
                .FP(36)
                .STM(7)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 23)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 12)


                ;

            return _builder.Build();
        }
    }
}
