using System.Collections.Generic;
using SWLOR.Game.Server.Core.NWScript.Enum;
using SWLOR.Game.Server.Service.BeastMasteryService;

namespace SWLOR.Game.Server.Feature.BeastDefinition
{
    public class JungleBugBeastDefinition: IBeastListDefinition
    {
        private readonly BeastBuilder _builder = new();

        public Dictionary<BeastType, BeastDetail> Build()
        {
            _builder.Create(BeastType.JungleBug)
                .CombatStats(AbilityType.Might, AbilityType.Agility)
                .Role(BeastRoleType.Evasion)

                
                // Level 1
                .AddLevel()
                .HP(30)
                .FP(3)
                .STM(3)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 7)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 5)

                // Level 2
                .AddLevel()
                .HP(37)
                .FP(3)
                .STM(3)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 7)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 5)

                // Level 3
                .AddLevel()
                .HP(54)
                .FP(3)
                .STM(4)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 7)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 5)

                // Level 4
                .AddLevel()
                .HP(71)
                .FP(3)
                .STM(4)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 7)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 5)

                // Level 5
                .AddLevel()
                .HP(88)
                .FP(3)
                .STM(4)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 5)

                // Level 6
                .AddLevel()
                .HP(105)
                .FP(4)
                .STM(5)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 5)

                // Level 7
                .AddLevel()
                .HP(122)
                .FP(4)
                .STM(5)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 5)

                // Level 8
                .AddLevel()
                .HP(139)
                .FP(4)
                .STM(5)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 5)

                // Level 9
                .AddLevel()
                .HP(156)
                .FP(4)
                .STM(5)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 6)

                // Level 10
                .AddLevel()
                .HP(173)
                .FP(4)
                .STM(6)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 6)

                // Level 11
                .AddLevel()
                .HP(190)
                .FP(4)
                .STM(6)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 6)

                // Level 12
                .AddLevel()
                .HP(207)
                .FP(4)
                .STM(6)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 6)

                // Level 13
                .AddLevel()
                .HP(224)
                .FP(4)
                .STM(7)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 6)

                // Level 14
                .AddLevel()
                .HP(241)
                .FP(4)
                .STM(7)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 6)

                // Level 15
                .AddLevel()
                .HP(258)
                .FP(4)
                .STM(7)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 6)

                // Level 16
                .AddLevel()
                .HP(275)
                .FP(5)
                .STM(8)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 6)

                // Level 17
                .AddLevel()
                .HP(292)
                .FP(5)
                .STM(8)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 6)

                // Level 18
                .AddLevel()
                .HP(309)
                .FP(5)
                .STM(8)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 6)

                // Level 19
                .AddLevel()
                .HP(326)
                .FP(5)
                .STM(8)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 6)

                // Level 20
                .AddLevel()
                .HP(343)
                .FP(5)
                .STM(9)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 6)

                // Level 21
                .AddLevel()
                .HP(360)
                .FP(5)
                .STM(9)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 6)

                // Level 22
                .AddLevel()
                .HP(377)
                .FP(5)
                .STM(9)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 6)

                // Level 23
                .AddLevel()
                .HP(394)
                .FP(5)
                .STM(10)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 6)

                // Level 24
                .AddLevel()
                .HP(411)
                .FP(5)
                .STM(10)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 6)

                // Level 25
                .AddLevel()
                .HP(428)
                .FP(5)
                .STM(10)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 7)

                // Level 26
                .AddLevel()
                .HP(445)
                .FP(6)
                .STM(11)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 7)

                // Level 27
                .AddLevel()
                .HP(462)
                .FP(6)
                .STM(11)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 29)
                .Stat(AbilityType.Social, 7)

                // Level 28
                .AddLevel()
                .HP(479)
                .FP(6)
                .STM(11)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 29)
                .Stat(AbilityType.Social, 7)

                // Level 29
                .AddLevel()
                .HP(496)
                .FP(6)
                .STM(11)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 29)
                .Stat(AbilityType.Social, 7)

                // Level 30
                .AddLevel()
                .HP(513)
                .FP(6)
                .STM(12)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 30)
                .Stat(AbilityType.Social, 7)

                // Level 31
                .AddLevel()
                .HP(530)
                .FP(6)
                .STM(12)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 30)
                .Stat(AbilityType.Social, 7)

                // Level 32
                .AddLevel()
                .HP(547)
                .FP(6)
                .STM(12)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 30)
                .Stat(AbilityType.Social, 7)

                // Level 33
                .AddLevel()
                .HP(564)
                .FP(6)
                .STM(13)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 30)
                .Stat(AbilityType.Social, 7)

                // Level 34
                .AddLevel()
                .HP(581)
                .FP(6)
                .STM(13)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 31)
                .Stat(AbilityType.Social, 7)

                // Level 35
                .AddLevel()
                .HP(598)
                .FP(6)
                .STM(13)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 31)
                .Stat(AbilityType.Social, 7)

                // Level 36
                .AddLevel()
                .HP(615)
                .FP(7)
                .STM(14)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 31)
                .Stat(AbilityType.Social, 7)

                // Level 37
                .AddLevel()
                .HP(632)
                .FP(7)
                .STM(14)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 32)
                .Stat(AbilityType.Social, 7)

                // Level 38
                .AddLevel()
                .HP(649)
                .FP(7)
                .STM(14)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 32)
                .Stat(AbilityType.Social, 7)

                // Level 39
                .AddLevel()
                .HP(666)
                .FP(7)
                .STM(14)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 32)
                .Stat(AbilityType.Social, 7)

                // Level 40
                .AddLevel()
                .HP(683)
                .FP(7)
                .STM(15)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 32)
                .Stat(AbilityType.Social, 7)

                // Level 41
                .AddLevel()
                .HP(700)
                .FP(7)
                .STM(15)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 33)
                .Stat(AbilityType.Social, 8)

                // Level 42
                .AddLevel()
                .HP(717)
                .FP(7)
                .STM(15)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 33)
                .Stat(AbilityType.Social, 8)

                // Level 43
                .AddLevel()
                .HP(734)
                .FP(7)
                .STM(16)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 33)
                .Stat(AbilityType.Social, 8)

                // Level 44
                .AddLevel()
                .HP(751)
                .FP(7)
                .STM(16)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 34)
                .Stat(AbilityType.Social, 8)

                // Level 45
                .AddLevel()
                .HP(768)
                .FP(7)
                .STM(16)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 34)
                .Stat(AbilityType.Social, 8)

                // Level 46
                .AddLevel()
                .HP(785)
                .FP(8)
                .STM(17)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 34)
                .Stat(AbilityType.Social, 8)

                // Level 47
                .AddLevel()
                .HP(802)
                .FP(8)
                .STM(17)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 34)
                .Stat(AbilityType.Social, 8)

                // Level 48
                .AddLevel()
                .HP(819)
                .FP(8)
                .STM(17)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 35)
                .Stat(AbilityType.Social, 8)

                // Level 49
                .AddLevel()
                .HP(836)
                .FP(8)
                .STM(17)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 35)
                .Stat(AbilityType.Social, 8)

                // Level 50
                .AddLevel()
                .HP(870)
                .FP(8)
                .STM(18)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 35)
                .Stat(AbilityType.Social, 8)


                ;

            return _builder.Build();
        }
    }
}
