using System.Collections.Generic;
using SWLOR.Game.Server.Core.NWScript.Enum;
using SWLOR.Game.Server.Service.BeastMasteryService;

namespace SWLOR.Game.Server.Feature.BeastDefinition
{
    public class KlorslugBeastDefinition: IBeastListDefinition
    {
        private readonly BeastBuilder _builder = new();

        public Dictionary<BeastType, BeastDetail> Build()
        {
            _builder.Create(BeastType.Klorslug)
                .Appearance(AppearanceType.BuletteSmallUndead)
                .CombatStats(AbilityType.Vitality, AbilityType.Might)
                .Role(BeastRoleType.Tank)

                
                // Level 1
                .AddLevel()
                .HP(70)
                .FP(4)
                .STM(4)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 7)

                // Level 2
                .AddLevel()
                .HP(64)
                .FP(4)
                .STM(4)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 7)

                // Level 3
                .AddLevel()
                .HP(94)
                .FP(4)
                .STM(4)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 7)

                // Level 4
                .AddLevel()
                .HP(124)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 7)

                // Level 5
                .AddLevel()
                .HP(154)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 8)

                // Level 6
                .AddLevel()
                .HP(184)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 8)

                // Level 7
                .AddLevel()
                .HP(214)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 8)

                // Level 8
                .AddLevel()
                .HP(244)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 8)

                // Level 9
                .AddLevel()
                .HP(274)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 8)

                // Level 10
                .AddLevel()
                .HP(304)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 8)

                // Level 11
                .AddLevel()
                .HP(334)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 8)

                // Level 12
                .AddLevel()
                .HP(364)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 8)

                // Level 13
                .AddLevel()
                .HP(394)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 8)

                // Level 14
                .AddLevel()
                .HP(424)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 8)

                // Level 15
                .AddLevel()
                .HP(454)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 9)

                // Level 16
                .AddLevel()
                .HP(484)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 9)

                // Level 17
                .AddLevel()
                .HP(514)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 9)

                // Level 18
                .AddLevel()
                .HP(544)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 19
                .AddLevel()
                .HP(574)
                .FP(8)
                .STM(8)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 20
                .AddLevel()
                .HP(604)
                .FP(8)
                .STM(8)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 21
                .AddLevel()
                .HP(634)
                .FP(8)
                .STM(8)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 22
                .AddLevel()
                .HP(664)
                .FP(8)
                .STM(8)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 23
                .AddLevel()
                .HP(694)
                .FP(8)
                .STM(8)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 24
                .AddLevel()
                .HP(724)
                .FP(9)
                .STM(9)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 25
                .AddLevel()
                .HP(754)
                .FP(9)
                .STM(9)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 26
                .AddLevel()
                .HP(784)
                .FP(9)
                .STM(9)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 27
                .AddLevel()
                .HP(814)
                .FP(9)
                .STM(9)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 28
                .AddLevel()
                .HP(844)
                .FP(9)
                .STM(9)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 29
                .AddLevel()
                .HP(874)
                .FP(10)
                .STM(10)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 30
                .AddLevel()
                .HP(904)
                .FP(10)
                .STM(10)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 31
                .AddLevel()
                .HP(934)
                .FP(10)
                .STM(10)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 27)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 32
                .AddLevel()
                .HP(964)
                .FP(10)
                .STM(10)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 27)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 10)

                // Level 33
                .AddLevel()
                .HP(994)
                .FP(10)
                .STM(10)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 27)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 10)

                // Level 34
                .AddLevel()
                .HP(1024)
                .FP(11)
                .STM(11)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 27)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 10)

                // Level 35
                .AddLevel()
                .HP(1054)
                .FP(11)
                .STM(11)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 28)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 11)

                // Level 36
                .AddLevel()
                .HP(1084)
                .FP(11)
                .STM(11)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 28)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 11)

                // Level 37
                .AddLevel()
                .HP(1114)
                .FP(11)
                .STM(11)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 28)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 11)

                // Level 38
                .AddLevel()
                .HP(1144)
                .FP(11)
                .STM(11)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 28)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 11)

                // Level 39
                .AddLevel()
                .HP(1174)
                .FP(12)
                .STM(12)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 29)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 11)

                // Level 40
                .AddLevel()
                .HP(1204)
                .FP(12)
                .STM(12)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 29)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 11)

                // Level 41
                .AddLevel()
                .HP(1234)
                .FP(12)
                .STM(12)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 29)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 11)

                // Level 42
                .AddLevel()
                .HP(1264)
                .FP(12)
                .STM(12)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 29)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 11)

                // Level 43
                .AddLevel()
                .HP(1294)
                .FP(12)
                .STM(12)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 30)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 11)

                // Level 44
                .AddLevel()
                .HP(1324)
                .FP(13)
                .STM(13)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 30)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 11)

                // Level 45
                .AddLevel()
                .HP(1354)
                .FP(13)
                .STM(13)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 30)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 12)

                // Level 46
                .AddLevel()
                .HP(1384)
                .FP(13)
                .STM(13)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 30)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 12)

                // Level 47
                .AddLevel()
                .HP(1414)
                .FP(13)
                .STM(13)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 31)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 12)

                // Level 48
                .AddLevel()
                .HP(1444)
                .FP(13)
                .STM(13)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 31)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 12)

                // Level 49
                .AddLevel()
                .HP(1474)
                .FP(14)
                .STM(14)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 31)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 12)

                // Level 50
                .AddLevel()
                .HP(1570)
                .FP(14)
                .STM(14)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 31)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 12)


                ;

            return _builder.Build();
        }
    }
}
