using System.Collections.Generic;
using SWLOR.Game.Server.Core.NWScript.Enum;
using SWLOR.Game.Server.Service.BeastMasteryService;

namespace SWLOR.Game.Server.Feature.BeastDefinition
{
    public class MicrotenchBeastDefinition: IBeastListDefinition
    {
        private readonly BeastBuilder _builder = new();

        public Dictionary<BeastType, BeastDetail> Build()
        {
            _builder.Create(BeastType.Microtench)
                .Appearance(AppearanceType.OctopusSmall)
                .CombatStats(AbilityType.Agility, AbilityType.Vitality)
                .Role(BeastRoleType.Evasion)

                
                // Level 1
                .AddLevel()
                .HP(30)
                .FP(3)
                .STM(3)
                .Stat(AbilityType.Might, 11)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 7)

                // Level 2
                .AddLevel()
                .HP(25)
                .FP(3)
                .STM(3)
                .Stat(AbilityType.Might, 11)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 7)

                // Level 3
                .AddLevel()
                .HP(36)
                .FP(3)
                .STM(4)
                .Stat(AbilityType.Might, 11)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 7)

                // Level 4
                .AddLevel()
                .HP(47)
                .FP(3)
                .STM(4)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 7)

                // Level 5
                .AddLevel()
                .HP(58)
                .FP(3)
                .STM(4)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 7)

                // Level 6
                .AddLevel()
                .HP(69)
                .FP(4)
                .STM(5)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 7)

                // Level 7
                .AddLevel()
                .HP(80)
                .FP(4)
                .STM(5)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 8)

                // Level 8
                .AddLevel()
                .HP(91)
                .FP(4)
                .STM(5)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 8)

                // Level 9
                .AddLevel()
                .HP(102)
                .FP(4)
                .STM(5)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 8)

                // Level 10
                .AddLevel()
                .HP(113)
                .FP(4)
                .STM(6)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 8)

                // Level 11
                .AddLevel()
                .HP(124)
                .FP(4)
                .STM(6)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 8)

                // Level 12
                .AddLevel()
                .HP(135)
                .FP(4)
                .STM(6)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 8)

                // Level 13
                .AddLevel()
                .HP(146)
                .FP(4)
                .STM(7)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 8)

                // Level 14
                .AddLevel()
                .HP(157)
                .FP(4)
                .STM(7)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 8)

                // Level 15
                .AddLevel()
                .HP(168)
                .FP(4)
                .STM(7)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 8)

                // Level 16
                .AddLevel()
                .HP(179)
                .FP(5)
                .STM(8)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 8)

                // Level 17
                .AddLevel()
                .HP(190)
                .FP(5)
                .STM(8)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 8)

                // Level 18
                .AddLevel()
                .HP(201)
                .FP(5)
                .STM(8)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 8)

                // Level 19
                .AddLevel()
                .HP(212)
                .FP(5)
                .STM(8)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 9)

                // Level 20
                .AddLevel()
                .HP(223)
                .FP(5)
                .STM(9)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 9)

                // Level 21
                .AddLevel()
                .HP(234)
                .FP(5)
                .STM(9)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 9)

                // Level 22
                .AddLevel()
                .HP(245)
                .FP(5)
                .STM(9)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 9)

                // Level 23
                .AddLevel()
                .HP(256)
                .FP(5)
                .STM(10)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 9)

                // Level 24
                .AddLevel()
                .HP(267)
                .FP(5)
                .STM(10)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 9)

                // Level 25
                .AddLevel()
                .HP(278)
                .FP(5)
                .STM(10)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 9)

                // Level 26
                .AddLevel()
                .HP(289)
                .FP(6)
                .STM(11)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 9)

                // Level 27
                .AddLevel()
                .HP(300)
                .FP(6)
                .STM(11)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 9)

                // Level 28
                .AddLevel()
                .HP(311)
                .FP(6)
                .STM(11)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 9)

                // Level 29
                .AddLevel()
                .HP(322)
                .FP(6)
                .STM(11)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 9)

                // Level 30
                .AddLevel()
                .HP(333)
                .FP(6)
                .STM(12)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 9)

                // Level 31
                .AddLevel()
                .HP(344)
                .FP(6)
                .STM(12)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 10)

                // Level 32
                .AddLevel()
                .HP(355)
                .FP(6)
                .STM(12)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 10)

                // Level 33
                .AddLevel()
                .HP(366)
                .FP(6)
                .STM(13)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 29)
                .Stat(AbilityType.Social, 10)

                // Level 34
                .AddLevel()
                .HP(377)
                .FP(6)
                .STM(13)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 29)
                .Stat(AbilityType.Social, 10)

                // Level 35
                .AddLevel()
                .HP(388)
                .FP(6)
                .STM(13)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 29)
                .Stat(AbilityType.Social, 10)

                // Level 36
                .AddLevel()
                .HP(399)
                .FP(7)
                .STM(14)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 30)
                .Stat(AbilityType.Social, 10)

                // Level 37
                .AddLevel()
                .HP(410)
                .FP(7)
                .STM(14)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 30)
                .Stat(AbilityType.Social, 10)

                // Level 38
                .AddLevel()
                .HP(421)
                .FP(7)
                .STM(14)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 30)
                .Stat(AbilityType.Social, 10)

                // Level 39
                .AddLevel()
                .HP(432)
                .FP(7)
                .STM(14)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 30)
                .Stat(AbilityType.Social, 10)

                // Level 40
                .AddLevel()
                .HP(443)
                .FP(7)
                .STM(15)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 31)
                .Stat(AbilityType.Social, 10)

                // Level 41
                .AddLevel()
                .HP(454)
                .FP(7)
                .STM(15)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 31)
                .Stat(AbilityType.Social, 10)

                // Level 42
                .AddLevel()
                .HP(465)
                .FP(7)
                .STM(15)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 31)
                .Stat(AbilityType.Social, 10)

                // Level 43
                .AddLevel()
                .HP(476)
                .FP(7)
                .STM(16)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 31)
                .Stat(AbilityType.Social, 11)

                // Level 44
                .AddLevel()
                .HP(487)
                .FP(7)
                .STM(16)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 32)
                .Stat(AbilityType.Social, 11)

                // Level 45
                .AddLevel()
                .HP(498)
                .FP(7)
                .STM(16)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 32)
                .Stat(AbilityType.Social, 11)

                // Level 46
                .AddLevel()
                .HP(509)
                .FP(8)
                .STM(17)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 32)
                .Stat(AbilityType.Social, 11)

                // Level 47
                .AddLevel()
                .HP(520)
                .FP(8)
                .STM(17)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 32)
                .Stat(AbilityType.Social, 11)

                // Level 48
                .AddLevel()
                .HP(531)
                .FP(8)
                .STM(17)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 33)
                .Stat(AbilityType.Social, 11)

                // Level 49
                .AddLevel()
                .HP(542)
                .FP(8)
                .STM(17)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 33)
                .Stat(AbilityType.Social, 11)

                // Level 50
                .AddLevel()
                .HP(570)
                .FP(8)
                .STM(18)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 33)
                .Stat(AbilityType.Social, 11)


                ;

            return _builder.Build();
        }
    }
}
