using System.Collections.Generic;
using SWLOR.Game.Server.Core.NWScript.Enum;
using SWLOR.Game.Server.Service.BeastMasteryService;

namespace SWLOR.Game.Server.Feature.BeastDefinition
{
    public class MorabandSerpentBeastDefinition: IBeastListDefinition
    {
        private readonly BeastBuilder _builder = new();

        public Dictionary<BeastType, BeastDetail> Build()
        {
            _builder.Create(BeastType.MorabandSerpent)
                .Appearance(AppearanceType.SnakeViperSwampLarge)
                .CombatStats(AbilityType.Willpower, AbilityType.Perception)
                .Role(BeastRoleType.Force)

                
                // Level 1
                .AddLevel()
                .HP(20)
                .FP(2)
                .STM(2)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 8)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 7)

                // Level 2
                .AddLevel()
                .HP(36)
                .FP(3)
                .STM(2)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 8)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 7)

                // Level 3
                .AddLevel()
                .HP(53)
                .FP(3)
                .STM(2)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 8)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 7)

                // Level 4
                .AddLevel()
                .HP(70)
                .FP(4)
                .STM(2)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 8)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 7)

                // Level 5
                .AddLevel()
                .HP(87)
                .FP(5)
                .STM(2)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 7)

                // Level 6
                .AddLevel()
                .HP(104)
                .FP(6)
                .STM(3)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 7)

                // Level 7
                .AddLevel()
                .HP(121)
                .FP(6)
                .STM(3)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 8)

                // Level 8
                .AddLevel()
                .HP(138)
                .FP(7)
                .STM(3)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 8)

                // Level 9
                .AddLevel()
                .HP(155)
                .FP(8)
                .STM(3)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 8)

                // Level 10
                .AddLevel()
                .HP(172)
                .FP(8)
                .STM(3)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 8)

                // Level 11
                .AddLevel()
                .HP(189)
                .FP(9)
                .STM(3)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 22)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 8)

                // Level 12
                .AddLevel()
                .HP(206)
                .FP(10)
                .STM(3)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 22)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 8)

                // Level 13
                .AddLevel()
                .HP(223)
                .FP(10)
                .STM(3)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 22)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 8)

                // Level 14
                .AddLevel()
                .HP(240)
                .FP(11)
                .STM(3)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 22)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 8)

                // Level 15
                .AddLevel()
                .HP(257)
                .FP(12)
                .STM(3)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 23)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 8)

                // Level 16
                .AddLevel()
                .HP(274)
                .FP(13)
                .STM(4)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 23)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 8)

                // Level 17
                .AddLevel()
                .HP(291)
                .FP(13)
                .STM(4)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 23)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 8)

                // Level 18
                .AddLevel()
                .HP(308)
                .FP(14)
                .STM(4)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 23)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 8)

                // Level 19
                .AddLevel()
                .HP(325)
                .FP(15)
                .STM(4)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 24)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 9)

                // Level 20
                .AddLevel()
                .HP(342)
                .FP(15)
                .STM(4)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 24)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 9)

                // Level 21
                .AddLevel()
                .HP(359)
                .FP(16)
                .STM(4)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 24)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 22
                .AddLevel()
                .HP(376)
                .FP(17)
                .STM(4)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 24)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 23
                .AddLevel()
                .HP(393)
                .FP(17)
                .STM(4)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 25)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 24
                .AddLevel()
                .HP(410)
                .FP(18)
                .STM(4)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 25)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 25
                .AddLevel()
                .HP(427)
                .FP(19)
                .STM(4)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 25)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 26
                .AddLevel()
                .HP(444)
                .FP(20)
                .STM(5)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 25)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 27
                .AddLevel()
                .HP(461)
                .FP(20)
                .STM(5)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 26)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 28
                .AddLevel()
                .HP(478)
                .FP(21)
                .STM(5)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 26)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 29
                .AddLevel()
                .HP(495)
                .FP(22)
                .STM(5)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 26)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 9)

                // Level 30
                .AddLevel()
                .HP(512)
                .FP(22)
                .STM(5)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 26)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 9)

                // Level 31
                .AddLevel()
                .HP(529)
                .FP(23)
                .STM(5)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 27)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 32
                .AddLevel()
                .HP(546)
                .FP(24)
                .STM(5)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 27)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 33
                .AddLevel()
                .HP(563)
                .FP(24)
                .STM(5)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 27)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 34
                .AddLevel()
                .HP(580)
                .FP(25)
                .STM(5)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 27)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 35
                .AddLevel()
                .HP(597)
                .FP(26)
                .STM(5)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 28)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 36
                .AddLevel()
                .HP(614)
                .FP(27)
                .STM(6)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 28)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 37
                .AddLevel()
                .HP(631)
                .FP(27)
                .STM(6)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 28)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 10)

                // Level 38
                .AddLevel()
                .HP(648)
                .FP(28)
                .STM(6)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 28)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 10)

                // Level 39
                .AddLevel()
                .HP(665)
                .FP(29)
                .STM(6)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 29)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 10)

                // Level 40
                .AddLevel()
                .HP(682)
                .FP(29)
                .STM(6)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 29)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 10)

                // Level 41
                .AddLevel()
                .HP(699)
                .FP(30)
                .STM(6)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 29)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 10)

                // Level 42
                .AddLevel()
                .HP(716)
                .FP(31)
                .STM(6)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 29)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 10)

                // Level 43
                .AddLevel()
                .HP(733)
                .FP(31)
                .STM(6)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 30)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 11)

                // Level 44
                .AddLevel()
                .HP(750)
                .FP(32)
                .STM(6)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 30)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 11)

                // Level 45
                .AddLevel()
                .HP(767)
                .FP(33)
                .STM(6)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 30)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 11)

                // Level 46
                .AddLevel()
                .HP(784)
                .FP(34)
                .STM(7)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 30)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 11)

                // Level 47
                .AddLevel()
                .HP(801)
                .FP(34)
                .STM(7)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 31)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 11)

                // Level 48
                .AddLevel()
                .HP(818)
                .FP(35)
                .STM(7)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 31)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 11)

                // Level 49
                .AddLevel()
                .HP(835)
                .FP(36)
                .STM(7)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 31)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 11)

                // Level 50
                .AddLevel()
                .HP(860)
                .FP(36)
                .STM(7)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 31)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 11)


                ;

            return _builder.Build();
        }
    }
}
