using System.Collections.Generic;
using SWLOR.Game.Server.Core.NWScript.Enum;
using SWLOR.Game.Server.Service.BeastMasteryService;

namespace SWLOR.Game.Server.Feature.BeastDefinition
{
    public class OctotenchBeastDefinition: IBeastListDefinition
    {
        private readonly BeastBuilder _builder = new();

        public Dictionary<BeastType, BeastDetail> Build()
        {
            _builder.Create(BeastType.Octotench)
                .CombatStats(AbilityType.Agility, AbilityType.Vitality)
                .Role(BeastRoleType.Tank)

                
                // Level 1
                .AddLevel()
                .HP(70)
                .FP(4)
                .STM(4)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 2
                .AddLevel()
                .HP(52)
                .FP(4)
                .STM(4)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 3
                .AddLevel()
                .HP(76)
                .FP(4)
                .STM(4)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 7)

                // Level 4
                .AddLevel()
                .HP(100)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 7)

                // Level 5
                .AddLevel()
                .HP(124)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 7)

                // Level 6
                .AddLevel()
                .HP(148)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 7)

                // Level 7
                .AddLevel()
                .HP(172)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 8
                .AddLevel()
                .HP(196)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 9
                .AddLevel()
                .HP(220)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 10
                .AddLevel()
                .HP(244)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 11
                .AddLevel()
                .HP(268)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 8)

                // Level 12
                .AddLevel()
                .HP(292)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 8)

                // Level 13
                .AddLevel()
                .HP(316)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 8)

                // Level 14
                .AddLevel()
                .HP(340)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 8)

                // Level 15
                .AddLevel()
                .HP(364)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 8)

                // Level 16
                .AddLevel()
                .HP(388)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 8)

                // Level 17
                .AddLevel()
                .HP(412)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 8)

                // Level 18
                .AddLevel()
                .HP(436)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 8)

                // Level 19
                .AddLevel()
                .HP(460)
                .FP(8)
                .STM(8)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 9)

                // Level 20
                .AddLevel()
                .HP(484)
                .FP(8)
                .STM(8)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 9)

                // Level 21
                .AddLevel()
                .HP(508)
                .FP(8)
                .STM(8)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 9)

                // Level 22
                .AddLevel()
                .HP(532)
                .FP(8)
                .STM(8)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 9)

                // Level 23
                .AddLevel()
                .HP(556)
                .FP(8)
                .STM(8)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 9)

                // Level 24
                .AddLevel()
                .HP(580)
                .FP(9)
                .STM(9)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 9)

                // Level 25
                .AddLevel()
                .HP(604)
                .FP(9)
                .STM(9)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 9)

                // Level 26
                .AddLevel()
                .HP(628)
                .FP(9)
                .STM(9)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 9)

                // Level 27
                .AddLevel()
                .HP(652)
                .FP(9)
                .STM(9)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 9)

                // Level 28
                .AddLevel()
                .HP(676)
                .FP(9)
                .STM(9)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 9)

                // Level 29
                .AddLevel()
                .HP(700)
                .FP(10)
                .STM(10)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 9)

                // Level 30
                .AddLevel()
                .HP(724)
                .FP(10)
                .STM(10)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 9)

                // Level 31
                .AddLevel()
                .HP(748)
                .FP(10)
                .STM(10)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 10)

                // Level 32
                .AddLevel()
                .HP(772)
                .FP(10)
                .STM(10)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 10)

                // Level 33
                .AddLevel()
                .HP(796)
                .FP(10)
                .STM(10)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 10)

                // Level 34
                .AddLevel()
                .HP(820)
                .FP(11)
                .STM(11)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 10)

                // Level 35
                .AddLevel()
                .HP(844)
                .FP(11)
                .STM(11)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 10)

                // Level 36
                .AddLevel()
                .HP(868)
                .FP(11)
                .STM(11)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 10)

                // Level 37
                .AddLevel()
                .HP(892)
                .FP(11)
                .STM(11)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 10)

                // Level 38
                .AddLevel()
                .HP(916)
                .FP(11)
                .STM(11)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 10)

                // Level 39
                .AddLevel()
                .HP(940)
                .FP(12)
                .STM(12)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 10)

                // Level 40
                .AddLevel()
                .HP(964)
                .FP(12)
                .STM(12)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 10)

                // Level 41
                .AddLevel()
                .HP(988)
                .FP(12)
                .STM(12)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 10)

                // Level 42
                .AddLevel()
                .HP(1012)
                .FP(12)
                .STM(12)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 10)

                // Level 43
                .AddLevel()
                .HP(1036)
                .FP(12)
                .STM(12)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 29)
                .Stat(AbilityType.Social, 11)

                // Level 44
                .AddLevel()
                .HP(1060)
                .FP(13)
                .STM(13)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 29)
                .Stat(AbilityType.Social, 11)

                // Level 45
                .AddLevel()
                .HP(1084)
                .FP(13)
                .STM(13)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 29)
                .Stat(AbilityType.Social, 11)

                // Level 46
                .AddLevel()
                .HP(1108)
                .FP(13)
                .STM(13)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 29)
                .Stat(AbilityType.Social, 11)

                // Level 47
                .AddLevel()
                .HP(1132)
                .FP(13)
                .STM(13)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 30)
                .Stat(AbilityType.Social, 11)

                // Level 48
                .AddLevel()
                .HP(1156)
                .FP(13)
                .STM(13)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 30)
                .Stat(AbilityType.Social, 11)

                // Level 49
                .AddLevel()
                .HP(1180)
                .FP(14)
                .STM(14)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 30)
                .Stat(AbilityType.Social, 11)

                // Level 50
                .AddLevel()
                .HP(1270)
                .FP(14)
                .STM(14)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 30)
                .Stat(AbilityType.Social, 11)


                ;

            return _builder.Build();
        }
    }
}
