using System.Collections.Generic;
using SWLOR.Game.Server.Core.NWScript.Enum;
using SWLOR.Game.Server.Service.BeastMasteryService;

namespace SWLOR.Game.Server.Feature.BeastDefinition
{
    public class PurboleBeastDefinition: IBeastListDefinition
    {
        private readonly BeastBuilder _builder = new();

        public Dictionary<BeastType, BeastDetail> Build()
        {
            _builder.Create(BeastType.Purbole)
                .Appearance(AppearanceType.Gibberling1)
                .CombatStats(AbilityType.Agility, AbilityType.Perception)
                .Role(BeastRoleType.Evasion)

                
                // Level 1
                .AddLevel()
                .HP(30)
                .FP(3)
                .STM(3)
                .Stat(AbilityType.Might, 9)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 5)

                // Level 2
                .AddLevel()
                .HP(21)
                .FP(3)
                .STM(3)
                .Stat(AbilityType.Might, 9)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 5)

                // Level 3
                .AddLevel()
                .HP(30)
                .FP(3)
                .STM(4)
                .Stat(AbilityType.Might, 9)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 5)

                // Level 4
                .AddLevel()
                .HP(39)
                .FP(3)
                .STM(4)
                .Stat(AbilityType.Might, 9)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 5)

                // Level 5
                .AddLevel()
                .HP(48)
                .FP(3)
                .STM(4)
                .Stat(AbilityType.Might, 10)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 5)

                // Level 6
                .AddLevel()
                .HP(57)
                .FP(4)
                .STM(5)
                .Stat(AbilityType.Might, 10)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 5)

                // Level 7
                .AddLevel()
                .HP(66)
                .FP(4)
                .STM(5)
                .Stat(AbilityType.Might, 10)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 5)

                // Level 8
                .AddLevel()
                .HP(75)
                .FP(4)
                .STM(5)
                .Stat(AbilityType.Might, 10)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 5)

                // Level 9
                .AddLevel()
                .HP(84)
                .FP(4)
                .STM(5)
                .Stat(AbilityType.Might, 10)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 6)

                // Level 10
                .AddLevel()
                .HP(93)
                .FP(4)
                .STM(6)
                .Stat(AbilityType.Might, 10)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 6)

                // Level 11
                .AddLevel()
                .HP(102)
                .FP(4)
                .STM(6)
                .Stat(AbilityType.Might, 10)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 6)

                // Level 12
                .AddLevel()
                .HP(111)
                .FP(4)
                .STM(6)
                .Stat(AbilityType.Might, 10)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 6)

                // Level 13
                .AddLevel()
                .HP(120)
                .FP(4)
                .STM(7)
                .Stat(AbilityType.Might, 11)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 6)

                // Level 14
                .AddLevel()
                .HP(129)
                .FP(4)
                .STM(7)
                .Stat(AbilityType.Might, 11)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 6)

                // Level 15
                .AddLevel()
                .HP(138)
                .FP(4)
                .STM(7)
                .Stat(AbilityType.Might, 11)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 6)

                // Level 16
                .AddLevel()
                .HP(147)
                .FP(5)
                .STM(8)
                .Stat(AbilityType.Might, 11)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 6)

                // Level 17
                .AddLevel()
                .HP(156)
                .FP(5)
                .STM(8)
                .Stat(AbilityType.Might, 11)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 6)

                // Level 18
                .AddLevel()
                .HP(165)
                .FP(5)
                .STM(8)
                .Stat(AbilityType.Might, 11)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 6)

                // Level 19
                .AddLevel()
                .HP(174)
                .FP(5)
                .STM(8)
                .Stat(AbilityType.Might, 11)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 6)

                // Level 20
                .AddLevel()
                .HP(183)
                .FP(5)
                .STM(9)
                .Stat(AbilityType.Might, 11)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 6)

                // Level 21
                .AddLevel()
                .HP(192)
                .FP(5)
                .STM(9)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 6)

                // Level 22
                .AddLevel()
                .HP(201)
                .FP(5)
                .STM(9)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 6)

                // Level 23
                .AddLevel()
                .HP(210)
                .FP(5)
                .STM(10)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 6)

                // Level 24
                .AddLevel()
                .HP(219)
                .FP(5)
                .STM(10)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 6)

                // Level 25
                .AddLevel()
                .HP(228)
                .FP(5)
                .STM(10)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 7)

                // Level 26
                .AddLevel()
                .HP(237)
                .FP(6)
                .STM(11)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 7)

                // Level 27
                .AddLevel()
                .HP(246)
                .FP(6)
                .STM(11)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 7)

                // Level 28
                .AddLevel()
                .HP(255)
                .FP(6)
                .STM(11)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 7)

                // Level 29
                .AddLevel()
                .HP(264)
                .FP(6)
                .STM(11)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 27)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 7)

                // Level 30
                .AddLevel()
                .HP(273)
                .FP(6)
                .STM(12)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 27)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 7)

                // Level 31
                .AddLevel()
                .HP(282)
                .FP(6)
                .STM(12)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 27)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 7)

                // Level 32
                .AddLevel()
                .HP(291)
                .FP(6)
                .STM(12)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 27)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 7)

                // Level 33
                .AddLevel()
                .HP(300)
                .FP(6)
                .STM(13)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 28)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 7)

                // Level 34
                .AddLevel()
                .HP(309)
                .FP(6)
                .STM(13)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 28)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 7)

                // Level 35
                .AddLevel()
                .HP(318)
                .FP(6)
                .STM(13)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 28)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 7)

                // Level 36
                .AddLevel()
                .HP(327)
                .FP(7)
                .STM(14)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 29)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 7)

                // Level 37
                .AddLevel()
                .HP(336)
                .FP(7)
                .STM(14)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 29)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 7)

                // Level 38
                .AddLevel()
                .HP(345)
                .FP(7)
                .STM(14)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 29)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 7)

                // Level 39
                .AddLevel()
                .HP(354)
                .FP(7)
                .STM(14)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 29)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 7)

                // Level 40
                .AddLevel()
                .HP(363)
                .FP(7)
                .STM(15)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 30)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 7)

                // Level 41
                .AddLevel()
                .HP(372)
                .FP(7)
                .STM(15)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 30)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 8)

                // Level 42
                .AddLevel()
                .HP(381)
                .FP(7)
                .STM(15)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 30)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 8)

                // Level 43
                .AddLevel()
                .HP(390)
                .FP(7)
                .STM(16)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 30)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 8)

                // Level 44
                .AddLevel()
                .HP(399)
                .FP(7)
                .STM(16)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 31)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 8)

                // Level 45
                .AddLevel()
                .HP(408)
                .FP(7)
                .STM(16)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 31)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 8)

                // Level 46
                .AddLevel()
                .HP(417)
                .FP(8)
                .STM(17)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 31)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 8)

                // Level 47
                .AddLevel()
                .HP(426)
                .FP(8)
                .STM(17)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 31)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 8)

                // Level 48
                .AddLevel()
                .HP(435)
                .FP(8)
                .STM(17)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 32)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 8)

                // Level 49
                .AddLevel()
                .HP(444)
                .FP(8)
                .STM(17)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 32)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 8)

                // Level 50
                .AddLevel()
                .HP(480)
                .FP(8)
                .STM(18)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 32)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 8)


                ;

            return _builder.Build();
        }
    }
}
