using System.Collections.Generic;
using SWLOR.Game.Server.Core.NWScript.Enum;
using SWLOR.Game.Server.Service.BeastMasteryService;

namespace SWLOR.Game.Server.Feature.BeastDefinition
{
    public class RaivorBeastDefinition: IBeastListDefinition
    {
        private readonly BeastBuilder _builder = new();

        public Dictionary<BeastType, BeastDetail> Build()
        {
            _builder.Create(BeastType.Raivor)
                .Appearance(AppearanceType.LizardLargeBrown)
                .CombatStats(AbilityType.Vitality, AbilityType.Perception)
                .Role(BeastRoleType.Balanced)

                
                // Level 1
                .AddLevel()
                .HP(40)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 6)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 10)

                // Level 2
                .AddLevel()
                .HP(41)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 6)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 10)

                // Level 3
                .AddLevel()
                .HP(59)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 6)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 10)

                // Level 4
                .AddLevel()
                .HP(77)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 6)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 10)

                // Level 5
                .AddLevel()
                .HP(95)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 6)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 11)

                // Level 6
                .AddLevel()
                .HP(113)
                .FP(8)
                .STM(8)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 6)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 11)

                // Level 7
                .AddLevel()
                .HP(131)
                .FP(8)
                .STM(8)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 7)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 11)

                // Level 8
                .AddLevel()
                .HP(149)
                .FP(9)
                .STM(9)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 7)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 11)

                // Level 9
                .AddLevel()
                .HP(167)
                .FP(9)
                .STM(9)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 7)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 11)

                // Level 10
                .AddLevel()
                .HP(185)
                .FP(10)
                .STM(10)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 7)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 11)

                // Level 11
                .AddLevel()
                .HP(203)
                .FP(10)
                .STM(10)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 7)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 11)

                // Level 12
                .AddLevel()
                .HP(221)
                .FP(11)
                .STM(11)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 7)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 11)

                // Level 13
                .AddLevel()
                .HP(239)
                .FP(11)
                .STM(11)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 7)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 12)

                // Level 14
                .AddLevel()
                .HP(257)
                .FP(12)
                .STM(12)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 7)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 12)

                // Level 15
                .AddLevel()
                .HP(275)
                .FP(12)
                .STM(12)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 7)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 12)

                // Level 16
                .AddLevel()
                .HP(293)
                .FP(13)
                .STM(13)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 7)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 12)

                // Level 17
                .AddLevel()
                .HP(311)
                .FP(13)
                .STM(13)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 7)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 12)

                // Level 18
                .AddLevel()
                .HP(329)
                .FP(14)
                .STM(14)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 7)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 12)

                // Level 19
                .AddLevel()
                .HP(347)
                .FP(14)
                .STM(14)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 12)

                // Level 20
                .AddLevel()
                .HP(365)
                .FP(15)
                .STM(15)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 12)

                // Level 21
                .AddLevel()
                .HP(383)
                .FP(15)
                .STM(15)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 13)

                // Level 22
                .AddLevel()
                .HP(401)
                .FP(16)
                .STM(16)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 13)

                // Level 23
                .AddLevel()
                .HP(419)
                .FP(16)
                .STM(16)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 13)

                // Level 24
                .AddLevel()
                .HP(437)
                .FP(17)
                .STM(17)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 13)

                // Level 25
                .AddLevel()
                .HP(455)
                .FP(17)
                .STM(17)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 13)

                // Level 26
                .AddLevel()
                .HP(473)
                .FP(18)
                .STM(18)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 13)

                // Level 27
                .AddLevel()
                .HP(491)
                .FP(18)
                .STM(18)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 13)

                // Level 28
                .AddLevel()
                .HP(509)
                .FP(19)
                .STM(19)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 13)

                // Level 29
                .AddLevel()
                .HP(527)
                .FP(19)
                .STM(19)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 14)

                // Level 30
                .AddLevel()
                .HP(545)
                .FP(20)
                .STM(20)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 14)

                // Level 31
                .AddLevel()
                .HP(563)
                .FP(20)
                .STM(20)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 14)

                // Level 32
                .AddLevel()
                .HP(581)
                .FP(21)
                .STM(21)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 14)

                // Level 33
                .AddLevel()
                .HP(599)
                .FP(21)
                .STM(21)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 14)

                // Level 34
                .AddLevel()
                .HP(617)
                .FP(22)
                .STM(22)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 14)

                // Level 35
                .AddLevel()
                .HP(635)
                .FP(22)
                .STM(22)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 14)

                // Level 36
                .AddLevel()
                .HP(653)
                .FP(23)
                .STM(23)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 14)

                // Level 37
                .AddLevel()
                .HP(671)
                .FP(23)
                .STM(23)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 15)

                // Level 38
                .AddLevel()
                .HP(689)
                .FP(24)
                .STM(24)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 15)

                // Level 39
                .AddLevel()
                .HP(707)
                .FP(24)
                .STM(24)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 15)

                // Level 40
                .AddLevel()
                .HP(725)
                .FP(25)
                .STM(25)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 15)

                // Level 41
                .AddLevel()
                .HP(743)
                .FP(25)
                .STM(25)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 15)

                // Level 42
                .AddLevel()
                .HP(761)
                .FP(26)
                .STM(26)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 15)

                // Level 43
                .AddLevel()
                .HP(779)
                .FP(26)
                .STM(26)
                .Stat(AbilityType.Might, 29)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 15)

                // Level 44
                .AddLevel()
                .HP(797)
                .FP(27)
                .STM(27)
                .Stat(AbilityType.Might, 29)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 15)

                // Level 45
                .AddLevel()
                .HP(815)
                .FP(27)
                .STM(27)
                .Stat(AbilityType.Might, 29)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 16)

                // Level 46
                .AddLevel()
                .HP(833)
                .FP(28)
                .STM(28)
                .Stat(AbilityType.Might, 29)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 16)

                // Level 47
                .AddLevel()
                .HP(851)
                .FP(28)
                .STM(28)
                .Stat(AbilityType.Might, 30)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 16)

                // Level 48
                .AddLevel()
                .HP(869)
                .FP(29)
                .STM(29)
                .Stat(AbilityType.Might, 30)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 16)

                // Level 49
                .AddLevel()
                .HP(887)
                .FP(29)
                .STM(29)
                .Stat(AbilityType.Might, 30)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 16)

                // Level 50
                .AddLevel()
                .HP(940)
                .FP(30)
                .STM(30)
                .Stat(AbilityType.Might, 30)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 16)


                ;

            return _builder.Build();
        }
    }
}
