using System.Collections.Generic;
using SWLOR.Game.Server.Core.NWScript.Enum;
using SWLOR.Game.Server.Service.BeastMasteryService;

namespace SWLOR.Game.Server.Feature.BeastDefinition
{
    public class SandBeetleBeastDefinition: IBeastListDefinition
    {
        private readonly BeastBuilder _builder = new();

        public Dictionary<BeastType, BeastDetail> Build()
        {
            _builder.Create(BeastType.SandBeetle)
                .CombatStats(AbilityType.Might, AbilityType.Agility)
                .Role(BeastRoleType.Damage)

                
                // Level 1
                .AddLevel()
                .HP(30)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 6)

                // Level 2
                .AddLevel()
                .HP(29)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 6)

                // Level 3
                .AddLevel()
                .HP(41)
                .FP(5)
                .STM(6)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 6)

                // Level 4
                .AddLevel()
                .HP(53)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 8)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 6)

                // Level 5
                .AddLevel()
                .HP(65)
                .FP(6)
                .STM(7)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 6)

                // Level 6
                .AddLevel()
                .HP(77)
                .FP(6)
                .STM(7)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 6)

                // Level 7
                .AddLevel()
                .HP(89)
                .FP(6)
                .STM(7)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 8
                .AddLevel()
                .HP(101)
                .FP(6)
                .STM(8)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 9
                .AddLevel()
                .HP(113)
                .FP(7)
                .STM(8)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 10
                .AddLevel()
                .HP(125)
                .FP(7)
                .STM(9)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 11
                .AddLevel()
                .HP(137)
                .FP(7)
                .STM(9)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 12
                .AddLevel()
                .HP(149)
                .FP(7)
                .STM(9)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 13
                .AddLevel()
                .HP(161)
                .FP(7)
                .STM(10)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 7)

                // Level 14
                .AddLevel()
                .HP(173)
                .FP(8)
                .STM(10)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 7)

                // Level 15
                .AddLevel()
                .HP(185)
                .FP(8)
                .STM(11)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 7)

                // Level 16
                .AddLevel()
                .HP(197)
                .FP(8)
                .STM(11)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 7)

                // Level 17
                .AddLevel()
                .HP(209)
                .FP(8)
                .STM(11)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 7)

                // Level 18
                .AddLevel()
                .HP(221)
                .FP(8)
                .STM(12)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 7)

                // Level 19
                .AddLevel()
                .HP(233)
                .FP(9)
                .STM(12)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 20
                .AddLevel()
                .HP(245)
                .FP(9)
                .STM(13)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 21
                .AddLevel()
                .HP(257)
                .FP(9)
                .STM(13)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 22
                .AddLevel()
                .HP(269)
                .FP(9)
                .STM(13)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 23
                .AddLevel()
                .HP(281)
                .FP(9)
                .STM(14)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 8)

                // Level 24
                .AddLevel()
                .HP(293)
                .FP(10)
                .STM(14)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 8)

                // Level 25
                .AddLevel()
                .HP(305)
                .FP(10)
                .STM(15)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 8)

                // Level 26
                .AddLevel()
                .HP(317)
                .FP(10)
                .STM(15)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 8)

                // Level 27
                .AddLevel()
                .HP(329)
                .FP(10)
                .STM(15)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 8)

                // Level 28
                .AddLevel()
                .HP(341)
                .FP(10)
                .STM(16)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 8)

                // Level 29
                .AddLevel()
                .HP(353)
                .FP(11)
                .STM(16)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 8)

                // Level 30
                .AddLevel()
                .HP(365)
                .FP(11)
                .STM(17)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 8)

                // Level 31
                .AddLevel()
                .HP(377)
                .FP(11)
                .STM(17)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 9)

                // Level 32
                .AddLevel()
                .HP(389)
                .FP(11)
                .STM(17)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 9)

                // Level 33
                .AddLevel()
                .HP(401)
                .FP(11)
                .STM(18)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 9)

                // Level 34
                .AddLevel()
                .HP(413)
                .FP(12)
                .STM(18)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 9)

                // Level 35
                .AddLevel()
                .HP(425)
                .FP(12)
                .STM(19)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 9)

                // Level 36
                .AddLevel()
                .HP(437)
                .FP(12)
                .STM(19)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 9)

                // Level 37
                .AddLevel()
                .HP(449)
                .FP(12)
                .STM(19)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 9)

                // Level 38
                .AddLevel()
                .HP(461)
                .FP(12)
                .STM(20)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 9)

                // Level 39
                .AddLevel()
                .HP(473)
                .FP(13)
                .STM(20)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 9)

                // Level 40
                .AddLevel()
                .HP(485)
                .FP(13)
                .STM(21)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 9)

                // Level 41
                .AddLevel()
                .HP(497)
                .FP(13)
                .STM(21)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 9)

                // Level 42
                .AddLevel()
                .HP(509)
                .FP(13)
                .STM(21)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 9)

                // Level 43
                .AddLevel()
                .HP(521)
                .FP(13)
                .STM(22)
                .Stat(AbilityType.Might, 29)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 10)

                // Level 44
                .AddLevel()
                .HP(533)
                .FP(14)
                .STM(22)
                .Stat(AbilityType.Might, 29)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 10)

                // Level 45
                .AddLevel()
                .HP(545)
                .FP(14)
                .STM(23)
                .Stat(AbilityType.Might, 29)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 10)

                // Level 46
                .AddLevel()
                .HP(557)
                .FP(14)
                .STM(23)
                .Stat(AbilityType.Might, 29)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 10)

                // Level 47
                .AddLevel()
                .HP(569)
                .FP(14)
                .STM(23)
                .Stat(AbilityType.Might, 30)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 10)

                // Level 48
                .AddLevel()
                .HP(581)
                .FP(14)
                .STM(24)
                .Stat(AbilityType.Might, 30)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 10)

                // Level 49
                .AddLevel()
                .HP(593)
                .FP(15)
                .STM(24)
                .Stat(AbilityType.Might, 30)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 10)

                // Level 50
                .AddLevel()
                .HP(630)
                .FP(15)
                .STM(25)
                .Stat(AbilityType.Might, 30)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 10)


                ;

            return _builder.Build();
        }
    }
}
