using System.Collections.Generic;
using SWLOR.Game.Server.Core.NWScript.Enum;
using SWLOR.Game.Server.Service.BeastMasteryService;

namespace SWLOR.Game.Server.Feature.BeastDefinition
{
    public class SandswimmerBeastDefinition: IBeastListDefinition
    {
        private readonly BeastBuilder _builder = new();

        public Dictionary<BeastType, BeastDetail> Build()
        {
            _builder.Create(BeastType.Sandswimmer)
                .Appearance(AppearanceType.Aranea)
                .CombatStats(AbilityType.Willpower, AbilityType.Vitality)
                .Role(BeastRoleType.Force)

                
                // Level 1
                .AddLevel()
                .HP(20)
                .FP(2)
                .STM(2)
                .Stat(AbilityType.Might, 11)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 5)

                // Level 2
                .AddLevel()
                .HP(30)
                .FP(3)
                .STM(2)
                .Stat(AbilityType.Might, 11)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 5)

                // Level 3
                .AddLevel()
                .HP(44)
                .FP(3)
                .STM(2)
                .Stat(AbilityType.Might, 11)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 5)

                // Level 4
                .AddLevel()
                .HP(58)
                .FP(4)
                .STM(2)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 5)

                // Level 5
                .AddLevel()
                .HP(72)
                .FP(5)
                .STM(2)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 5)

                // Level 6
                .AddLevel()
                .HP(86)
                .FP(6)
                .STM(3)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 5)

                // Level 7
                .AddLevel()
                .HP(100)
                .FP(6)
                .STM(3)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 5)

                // Level 8
                .AddLevel()
                .HP(114)
                .FP(7)
                .STM(3)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 5)

                // Level 9
                .AddLevel()
                .HP(128)
                .FP(8)
                .STM(3)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 6)

                // Level 10
                .AddLevel()
                .HP(142)
                .FP(8)
                .STM(3)
                .Stat(AbilityType.Might, 12)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 6)

                // Level 11
                .AddLevel()
                .HP(156)
                .FP(9)
                .STM(3)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 6)

                // Level 12
                .AddLevel()
                .HP(170)
                .FP(10)
                .STM(3)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 6)

                // Level 13
                .AddLevel()
                .HP(184)
                .FP(10)
                .STM(3)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 6)

                // Level 14
                .AddLevel()
                .HP(198)
                .FP(11)
                .STM(3)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 6)

                // Level 15
                .AddLevel()
                .HP(212)
                .FP(12)
                .STM(3)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 6)

                // Level 16
                .AddLevel()
                .HP(226)
                .FP(13)
                .STM(4)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 6)

                // Level 17
                .AddLevel()
                .HP(240)
                .FP(13)
                .STM(4)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 6)

                // Level 18
                .AddLevel()
                .HP(254)
                .FP(14)
                .STM(4)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 6)

                // Level 19
                .AddLevel()
                .HP(268)
                .FP(15)
                .STM(4)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 6)

                // Level 20
                .AddLevel()
                .HP(282)
                .FP(15)
                .STM(4)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 6)

                // Level 21
                .AddLevel()
                .HP(296)
                .FP(16)
                .STM(4)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 6)

                // Level 22
                .AddLevel()
                .HP(310)
                .FP(17)
                .STM(4)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 6)

                // Level 23
                .AddLevel()
                .HP(324)
                .FP(17)
                .STM(4)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 6)

                // Level 24
                .AddLevel()
                .HP(338)
                .FP(18)
                .STM(4)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 6)

                // Level 25
                .AddLevel()
                .HP(352)
                .FP(19)
                .STM(4)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 22)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 7)

                // Level 26
                .AddLevel()
                .HP(366)
                .FP(20)
                .STM(5)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 22)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 7)

                // Level 27
                .AddLevel()
                .HP(380)
                .FP(20)
                .STM(5)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 22)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 7)

                // Level 28
                .AddLevel()
                .HP(394)
                .FP(21)
                .STM(5)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 22)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 29
                .AddLevel()
                .HP(408)
                .FP(22)
                .STM(5)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 23)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 30
                .AddLevel()
                .HP(422)
                .FP(22)
                .STM(5)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 23)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 31
                .AddLevel()
                .HP(436)
                .FP(23)
                .STM(5)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 23)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 32
                .AddLevel()
                .HP(450)
                .FP(24)
                .STM(5)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 23)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 33
                .AddLevel()
                .HP(464)
                .FP(24)
                .STM(5)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 23)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 34
                .AddLevel()
                .HP(478)
                .FP(25)
                .STM(5)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 24)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 35
                .AddLevel()
                .HP(492)
                .FP(26)
                .STM(5)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 24)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 36
                .AddLevel()
                .HP(506)
                .FP(27)
                .STM(6)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 24)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 37
                .AddLevel()
                .HP(520)
                .FP(27)
                .STM(6)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 24)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 38
                .AddLevel()
                .HP(534)
                .FP(28)
                .STM(6)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 25)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 39
                .AddLevel()
                .HP(548)
                .FP(29)
                .STM(6)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 25)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 40
                .AddLevel()
                .HP(562)
                .FP(29)
                .STM(6)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 25)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 7)

                // Level 41
                .AddLevel()
                .HP(576)
                .FP(30)
                .STM(6)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 25)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 8)

                // Level 42
                .AddLevel()
                .HP(590)
                .FP(31)
                .STM(6)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 25)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 8)

                // Level 43
                .AddLevel()
                .HP(604)
                .FP(31)
                .STM(6)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 26)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 8)

                // Level 44
                .AddLevel()
                .HP(618)
                .FP(32)
                .STM(6)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 26)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 8)

                // Level 45
                .AddLevel()
                .HP(632)
                .FP(33)
                .STM(6)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 26)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 8)

                // Level 46
                .AddLevel()
                .HP(646)
                .FP(34)
                .STM(7)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 26)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 47
                .AddLevel()
                .HP(660)
                .FP(34)
                .STM(7)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 27)
                .Stat(AbilityType.Willpower, 27)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 48
                .AddLevel()
                .HP(674)
                .FP(35)
                .STM(7)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 27)
                .Stat(AbilityType.Willpower, 27)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 49
                .AddLevel()
                .HP(688)
                .FP(36)
                .STM(7)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 27)
                .Stat(AbilityType.Willpower, 27)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 50
                .AddLevel()
                .HP(740)
                .FP(36)
                .STM(7)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 27)
                .Stat(AbilityType.Willpower, 27)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)


                ;

            return _builder.Build();
        }
    }
}
