using System.Collections.Generic;
using SWLOR.Game.Server.Core.NWScript.Enum;
using SWLOR.Game.Server.Service.BeastMasteryService;

namespace SWLOR.Game.Server.Feature.BeastDefinition
{
    public class SandDemonBeastDefinition: IBeastListDefinition
    {
        private readonly BeastBuilder _builder = new();

        public Dictionary<BeastType, BeastDetail> Build()
        {
            _builder.Create(BeastType.SandDemon)
                .Appearance(AppearanceType.SpiderDemon)
                .CombatStats(AbilityType.Vitality, AbilityType.Might)
                .Role(BeastRoleType.Bruiser)

                
                // Level 1
                .AddLevel()
                .HP(50)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 5)

                // Level 2
                .AddLevel()
                .HP(40)
                .FP(6)
                .STM(7)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 5)

                // Level 3
                .AddLevel()
                .HP(57)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 5)

                // Level 4
                .AddLevel()
                .HP(74)
                .FP(7)
                .STM(8)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 5)

                // Level 5
                .AddLevel()
                .HP(91)
                .FP(7)
                .STM(9)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 5)

                // Level 6
                .AddLevel()
                .HP(108)
                .FP(8)
                .STM(10)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 5)

                // Level 7
                .AddLevel()
                .HP(125)
                .FP(8)
                .STM(10)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 5)

                // Level 8
                .AddLevel()
                .HP(142)
                .FP(8)
                .STM(11)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 5)

                // Level 9
                .AddLevel()
                .HP(159)
                .FP(8)
                .STM(12)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 6)

                // Level 10
                .AddLevel()
                .HP(176)
                .FP(9)
                .STM(12)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 6)

                // Level 11
                .AddLevel()
                .HP(193)
                .FP(9)
                .STM(13)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 6)

                // Level 12
                .AddLevel()
                .HP(210)
                .FP(9)
                .STM(14)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 6)

                // Level 13
                .AddLevel()
                .HP(227)
                .FP(10)
                .STM(14)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 6)

                // Level 14
                .AddLevel()
                .HP(244)
                .FP(10)
                .STM(15)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 6)

                // Level 15
                .AddLevel()
                .HP(261)
                .FP(10)
                .STM(16)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 6)

                // Level 16
                .AddLevel()
                .HP(278)
                .FP(11)
                .STM(17)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 6)

                // Level 17
                .AddLevel()
                .HP(295)
                .FP(11)
                .STM(17)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 6)

                // Level 18
                .AddLevel()
                .HP(312)
                .FP(11)
                .STM(18)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 6)

                // Level 19
                .AddLevel()
                .HP(329)
                .FP(11)
                .STM(19)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 6)

                // Level 20
                .AddLevel()
                .HP(346)
                .FP(12)
                .STM(19)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 6)

                // Level 21
                .AddLevel()
                .HP(363)
                .FP(12)
                .STM(20)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 6)

                // Level 22
                .AddLevel()
                .HP(380)
                .FP(12)
                .STM(21)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 6)

                // Level 23
                .AddLevel()
                .HP(397)
                .FP(13)
                .STM(21)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 6)

                // Level 24
                .AddLevel()
                .HP(414)
                .FP(13)
                .STM(22)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 6)

                // Level 25
                .AddLevel()
                .HP(431)
                .FP(13)
                .STM(23)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 7)

                // Level 26
                .AddLevel()
                .HP(448)
                .FP(14)
                .STM(24)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 7)

                // Level 27
                .AddLevel()
                .HP(465)
                .FP(14)
                .STM(24)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 7)

                // Level 28
                .AddLevel()
                .HP(482)
                .FP(14)
                .STM(25)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 29
                .AddLevel()
                .HP(499)
                .FP(14)
                .STM(26)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 30
                .AddLevel()
                .HP(516)
                .FP(15)
                .STM(26)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 31
                .AddLevel()
                .HP(533)
                .FP(15)
                .STM(27)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 32
                .AddLevel()
                .HP(550)
                .FP(15)
                .STM(28)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 33
                .AddLevel()
                .HP(567)
                .FP(16)
                .STM(28)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 34
                .AddLevel()
                .HP(584)
                .FP(16)
                .STM(29)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 35
                .AddLevel()
                .HP(601)
                .FP(16)
                .STM(30)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 36
                .AddLevel()
                .HP(618)
                .FP(17)
                .STM(31)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 37
                .AddLevel()
                .HP(635)
                .FP(17)
                .STM(31)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 38
                .AddLevel()
                .HP(652)
                .FP(17)
                .STM(32)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 39
                .AddLevel()
                .HP(669)
                .FP(17)
                .STM(33)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 40
                .AddLevel()
                .HP(686)
                .FP(18)
                .STM(33)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 7)

                // Level 41
                .AddLevel()
                .HP(703)
                .FP(18)
                .STM(34)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 8)

                // Level 42
                .AddLevel()
                .HP(720)
                .FP(18)
                .STM(35)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 8)

                // Level 43
                .AddLevel()
                .HP(737)
                .FP(19)
                .STM(35)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 27)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 8)

                // Level 44
                .AddLevel()
                .HP(754)
                .FP(19)
                .STM(36)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 27)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 8)

                // Level 45
                .AddLevel()
                .HP(771)
                .FP(19)
                .STM(37)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 27)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 8)

                // Level 46
                .AddLevel()
                .HP(788)
                .FP(20)
                .STM(38)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 27)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 47
                .AddLevel()
                .HP(805)
                .FP(20)
                .STM(38)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 28)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 48
                .AddLevel()
                .HP(822)
                .FP(20)
                .STM(39)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 28)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 49
                .AddLevel()
                .HP(839)
                .FP(20)
                .STM(40)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 28)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 50
                .AddLevel()
                .HP(890)
                .FP(21)
                .STM(40)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 28)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)


                ;

            return _builder.Build();
        }
    }
}
