using System.Collections.Generic;
using SWLOR.Game.Server.Core.NWScript.Enum;
using SWLOR.Game.Server.Service.BeastMasteryService;

namespace SWLOR.Game.Server.Feature.BeastDefinition
{
    public class ScorchellusBeastDefinition: IBeastListDefinition
    {
        private readonly BeastBuilder _builder = new();

        public Dictionary<BeastType, BeastDetail> Build()
        {
            _builder.Create(BeastType.Scorchellus)
                .Appearance(AppearanceType.Scutellus)
                .CombatStats(AbilityType.Vitality, AbilityType.Might)
                .Role(BeastRoleType.Balanced)

                
                // Level 1
                .AddLevel()
                .HP(40)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 9)
                .Stat(AbilityType.Social, 6)

                // Level 2
                .AddLevel()
                .HP(39)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 9)
                .Stat(AbilityType.Social, 6)

                // Level 3
                .AddLevel()
                .HP(56)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 9)
                .Stat(AbilityType.Social, 6)

                // Level 4
                .AddLevel()
                .HP(73)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 9)
                .Stat(AbilityType.Social, 6)

                // Level 5
                .AddLevel()
                .HP(90)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 6)

                // Level 6
                .AddLevel()
                .HP(107)
                .FP(8)
                .STM(8)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 6)

                // Level 7
                .AddLevel()
                .HP(124)
                .FP(8)
                .STM(8)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 7)

                // Level 8
                .AddLevel()
                .HP(141)
                .FP(9)
                .STM(9)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 7)

                // Level 9
                .AddLevel()
                .HP(158)
                .FP(9)
                .STM(9)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 7)

                // Level 10
                .AddLevel()
                .HP(175)
                .FP(10)
                .STM(10)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 7)

                // Level 11
                .AddLevel()
                .HP(192)
                .FP(10)
                .STM(10)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 7)

                // Level 12
                .AddLevel()
                .HP(209)
                .FP(11)
                .STM(11)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 7)

                // Level 13
                .AddLevel()
                .HP(226)
                .FP(11)
                .STM(11)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 7)

                // Level 14
                .AddLevel()
                .HP(243)
                .FP(12)
                .STM(12)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 7)

                // Level 15
                .AddLevel()
                .HP(260)
                .FP(12)
                .STM(12)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 7)

                // Level 16
                .AddLevel()
                .HP(277)
                .FP(13)
                .STM(13)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 7)

                // Level 17
                .AddLevel()
                .HP(294)
                .FP(13)
                .STM(13)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 7)

                // Level 18
                .AddLevel()
                .HP(311)
                .FP(14)
                .STM(14)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 7)

                // Level 19
                .AddLevel()
                .HP(328)
                .FP(14)
                .STM(14)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 8)

                // Level 20
                .AddLevel()
                .HP(345)
                .FP(15)
                .STM(15)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 8)

                // Level 21
                .AddLevel()
                .HP(362)
                .FP(15)
                .STM(15)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 8)

                // Level 22
                .AddLevel()
                .HP(379)
                .FP(16)
                .STM(16)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 8)

                // Level 23
                .AddLevel()
                .HP(396)
                .FP(16)
                .STM(16)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 8)

                // Level 24
                .AddLevel()
                .HP(413)
                .FP(17)
                .STM(17)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 8)

                // Level 25
                .AddLevel()
                .HP(430)
                .FP(17)
                .STM(17)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 8)

                // Level 26
                .AddLevel()
                .HP(447)
                .FP(18)
                .STM(18)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 8)

                // Level 27
                .AddLevel()
                .HP(464)
                .FP(18)
                .STM(18)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 8)

                // Level 28
                .AddLevel()
                .HP(481)
                .FP(19)
                .STM(19)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 8)

                // Level 29
                .AddLevel()
                .HP(498)
                .FP(19)
                .STM(19)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 8)

                // Level 30
                .AddLevel()
                .HP(515)
                .FP(20)
                .STM(20)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 8)

                // Level 31
                .AddLevel()
                .HP(532)
                .FP(20)
                .STM(20)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 32
                .AddLevel()
                .HP(549)
                .FP(21)
                .STM(21)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 33
                .AddLevel()
                .HP(566)
                .FP(21)
                .STM(21)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 34
                .AddLevel()
                .HP(583)
                .FP(22)
                .STM(22)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 35
                .AddLevel()
                .HP(600)
                .FP(22)
                .STM(22)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 36
                .AddLevel()
                .HP(617)
                .FP(23)
                .STM(23)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 37
                .AddLevel()
                .HP(634)
                .FP(23)
                .STM(23)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 9)

                // Level 38
                .AddLevel()
                .HP(651)
                .FP(24)
                .STM(24)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 9)

                // Level 39
                .AddLevel()
                .HP(668)
                .FP(24)
                .STM(24)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 9)

                // Level 40
                .AddLevel()
                .HP(685)
                .FP(25)
                .STM(25)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 9)

                // Level 41
                .AddLevel()
                .HP(702)
                .FP(25)
                .STM(25)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 9)

                // Level 42
                .AddLevel()
                .HP(719)
                .FP(26)
                .STM(26)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 9)

                // Level 43
                .AddLevel()
                .HP(736)
                .FP(26)
                .STM(26)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 44
                .AddLevel()
                .HP(753)
                .FP(27)
                .STM(27)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 45
                .AddLevel()
                .HP(770)
                .FP(27)
                .STM(27)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 10)

                // Level 46
                .AddLevel()
                .HP(787)
                .FP(28)
                .STM(28)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 21)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 10)

                // Level 47
                .AddLevel()
                .HP(804)
                .FP(28)
                .STM(28)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 22)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 10)

                // Level 48
                .AddLevel()
                .HP(821)
                .FP(29)
                .STM(29)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 22)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 10)

                // Level 49
                .AddLevel()
                .HP(838)
                .FP(29)
                .STM(29)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 22)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 10)

                // Level 50
                .AddLevel()
                .HP(880)
                .FP(30)
                .STM(30)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 22)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 10)


                ;

            return _builder.Build();
        }
    }
}
