using System.Collections.Generic;
using SWLOR.Game.Server.Core.NWScript.Enum;
using SWLOR.Game.Server.Service.BeastMasteryService;

namespace SWLOR.Game.Server.Feature.BeastDefinition
{
    public class ShearMiteBeastDefinition: IBeastListDefinition
    {
        private readonly BeastBuilder _builder = new();

        public Dictionary<BeastType, BeastDetail> Build()
        {
            _builder.Create(BeastType.ShearMite)
                .Appearance(AppearanceType.BeetleStag)
                .CombatStats(AbilityType.Agility, AbilityType.Might)
                .Role(BeastRoleType.Damage)

                
                // Level 1
                .AddLevel()
                .HP(30)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 5)

                // Level 2
                .AddLevel()
                .HP(27)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 5)

                // Level 3
                .AddLevel()
                .HP(38)
                .FP(5)
                .STM(6)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 5)

                // Level 4
                .AddLevel()
                .HP(49)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 9)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 5)

                // Level 5
                .AddLevel()
                .HP(60)
                .FP(6)
                .STM(7)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 5)

                // Level 6
                .AddLevel()
                .HP(71)
                .FP(6)
                .STM(7)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 5)

                // Level 7
                .AddLevel()
                .HP(82)
                .FP(6)
                .STM(7)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 5)

                // Level 8
                .AddLevel()
                .HP(93)
                .FP(6)
                .STM(8)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 5)

                // Level 9
                .AddLevel()
                .HP(104)
                .FP(7)
                .STM(8)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 6)

                // Level 10
                .AddLevel()
                .HP(115)
                .FP(7)
                .STM(9)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 6)

                // Level 11
                .AddLevel()
                .HP(126)
                .FP(7)
                .STM(9)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 6)

                // Level 12
                .AddLevel()
                .HP(137)
                .FP(7)
                .STM(9)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 6)

                // Level 13
                .AddLevel()
                .HP(148)
                .FP(7)
                .STM(10)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 6)

                // Level 14
                .AddLevel()
                .HP(159)
                .FP(8)
                .STM(10)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 6)

                // Level 15
                .AddLevel()
                .HP(170)
                .FP(8)
                .STM(11)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 6)

                // Level 16
                .AddLevel()
                .HP(181)
                .FP(8)
                .STM(11)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 6)

                // Level 17
                .AddLevel()
                .HP(192)
                .FP(8)
                .STM(11)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 6)

                // Level 18
                .AddLevel()
                .HP(203)
                .FP(8)
                .STM(12)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 6)

                // Level 19
                .AddLevel()
                .HP(214)
                .FP(9)
                .STM(12)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 6)

                // Level 20
                .AddLevel()
                .HP(225)
                .FP(9)
                .STM(13)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 6)

                // Level 21
                .AddLevel()
                .HP(236)
                .FP(9)
                .STM(13)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 6)

                // Level 22
                .AddLevel()
                .HP(247)
                .FP(9)
                .STM(13)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 6)

                // Level 23
                .AddLevel()
                .HP(258)
                .FP(9)
                .STM(14)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 6)

                // Level 24
                .AddLevel()
                .HP(269)
                .FP(10)
                .STM(14)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 6)

                // Level 25
                .AddLevel()
                .HP(280)
                .FP(10)
                .STM(15)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 7)

                // Level 26
                .AddLevel()
                .HP(291)
                .FP(10)
                .STM(15)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 7)

                // Level 27
                .AddLevel()
                .HP(302)
                .FP(10)
                .STM(15)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 7)

                // Level 28
                .AddLevel()
                .HP(313)
                .FP(10)
                .STM(16)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 7)

                // Level 29
                .AddLevel()
                .HP(324)
                .FP(11)
                .STM(16)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 7)

                // Level 30
                .AddLevel()
                .HP(335)
                .FP(11)
                .STM(17)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 26)
                .Stat(AbilityType.Social, 7)

                // Level 31
                .AddLevel()
                .HP(346)
                .FP(11)
                .STM(17)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 7)

                // Level 32
                .AddLevel()
                .HP(357)
                .FP(11)
                .STM(17)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 7)

                // Level 33
                .AddLevel()
                .HP(368)
                .FP(11)
                .STM(18)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 7)

                // Level 34
                .AddLevel()
                .HP(379)
                .FP(12)
                .STM(18)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 27)
                .Stat(AbilityType.Social, 7)

                // Level 35
                .AddLevel()
                .HP(390)
                .FP(12)
                .STM(19)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 7)

                // Level 36
                .AddLevel()
                .HP(401)
                .FP(12)
                .STM(19)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 7)

                // Level 37
                .AddLevel()
                .HP(412)
                .FP(12)
                .STM(19)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 7)

                // Level 38
                .AddLevel()
                .HP(423)
                .FP(12)
                .STM(20)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 28)
                .Stat(AbilityType.Social, 7)

                // Level 39
                .AddLevel()
                .HP(434)
                .FP(13)
                .STM(20)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 29)
                .Stat(AbilityType.Social, 7)

                // Level 40
                .AddLevel()
                .HP(445)
                .FP(13)
                .STM(21)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 29)
                .Stat(AbilityType.Social, 7)

                // Level 41
                .AddLevel()
                .HP(456)
                .FP(13)
                .STM(21)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 29)
                .Stat(AbilityType.Social, 8)

                // Level 42
                .AddLevel()
                .HP(467)
                .FP(13)
                .STM(21)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 29)
                .Stat(AbilityType.Social, 8)

                // Level 43
                .AddLevel()
                .HP(478)
                .FP(13)
                .STM(22)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 30)
                .Stat(AbilityType.Social, 8)

                // Level 44
                .AddLevel()
                .HP(489)
                .FP(14)
                .STM(22)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 30)
                .Stat(AbilityType.Social, 8)

                // Level 45
                .AddLevel()
                .HP(500)
                .FP(14)
                .STM(23)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 30)
                .Stat(AbilityType.Social, 8)

                // Level 46
                .AddLevel()
                .HP(511)
                .FP(14)
                .STM(23)
                .Stat(AbilityType.Might, 27)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 30)
                .Stat(AbilityType.Social, 8)

                // Level 47
                .AddLevel()
                .HP(522)
                .FP(14)
                .STM(23)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 31)
                .Stat(AbilityType.Social, 8)

                // Level 48
                .AddLevel()
                .HP(533)
                .FP(14)
                .STM(24)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 31)
                .Stat(AbilityType.Social, 8)

                // Level 49
                .AddLevel()
                .HP(544)
                .FP(15)
                .STM(24)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 31)
                .Stat(AbilityType.Social, 8)

                // Level 50
                .AddLevel()
                .HP(590)
                .FP(15)
                .STM(25)
                .Stat(AbilityType.Might, 28)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 31)
                .Stat(AbilityType.Social, 8)


                ;

            return _builder.Build();
        }
    }
}
