using System.Collections.Generic;
using SWLOR.Game.Server.Core.NWScript.Enum;
using SWLOR.Game.Server.Service.BeastMasteryService;

namespace SWLOR.Game.Server.Feature.BeastDefinition
{
    public class ShyrackBeastDefinition: IBeastListDefinition
    {
        private readonly BeastBuilder _builder = new();

        public Dictionary<BeastType, BeastDetail> Build()
        {
            _builder.Create(BeastType.Shyrack)
                .Appearance(AppearanceType.Shyrack)
                .CombatStats(AbilityType.Perception, AbilityType.Might)
                .Role(BeastRoleType.Balanced)

                
                // Level 1
                .AddLevel()
                .HP(40)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 9)
                .Stat(AbilityType.Social, 7)

                // Level 2
                .AddLevel()
                .HP(35)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 9)
                .Stat(AbilityType.Social, 7)

                // Level 3
                .AddLevel()
                .HP(50)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 9)
                .Stat(AbilityType.Social, 7)

                // Level 4
                .AddLevel()
                .HP(65)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 9)
                .Stat(AbilityType.Social, 7)

                // Level 5
                .AddLevel()
                .HP(80)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 8)

                // Level 6
                .AddLevel()
                .HP(95)
                .FP(8)
                .STM(8)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 8)

                // Level 7
                .AddLevel()
                .HP(110)
                .FP(8)
                .STM(8)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 8)

                // Level 8
                .AddLevel()
                .HP(125)
                .FP(9)
                .STM(9)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 8)

                // Level 9
                .AddLevel()
                .HP(140)
                .FP(9)
                .STM(9)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 8)

                // Level 10
                .AddLevel()
                .HP(155)
                .FP(10)
                .STM(10)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 8)

                // Level 11
                .AddLevel()
                .HP(170)
                .FP(10)
                .STM(10)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 8)

                // Level 12
                .AddLevel()
                .HP(185)
                .FP(11)
                .STM(11)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 10)
                .Stat(AbilityType.Social, 8)

                // Level 13
                .AddLevel()
                .HP(200)
                .FP(11)
                .STM(11)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 8)

                // Level 14
                .AddLevel()
                .HP(215)
                .FP(12)
                .STM(12)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 8)

                // Level 15
                .AddLevel()
                .HP(230)
                .FP(12)
                .STM(12)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 9)

                // Level 16
                .AddLevel()
                .HP(245)
                .FP(13)
                .STM(13)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 9)

                // Level 17
                .AddLevel()
                .HP(260)
                .FP(13)
                .STM(13)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 9)

                // Level 18
                .AddLevel()
                .HP(275)
                .FP(14)
                .STM(14)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 9)

                // Level 19
                .AddLevel()
                .HP(290)
                .FP(14)
                .STM(14)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 9)

                // Level 20
                .AddLevel()
                .HP(305)
                .FP(15)
                .STM(15)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 9)

                // Level 21
                .AddLevel()
                .HP(320)
                .FP(15)
                .STM(15)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 9)

                // Level 22
                .AddLevel()
                .HP(335)
                .FP(16)
                .STM(16)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 9)

                // Level 23
                .AddLevel()
                .HP(350)
                .FP(16)
                .STM(16)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 9)

                // Level 24
                .AddLevel()
                .HP(365)
                .FP(17)
                .STM(17)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 9)

                // Level 25
                .AddLevel()
                .HP(380)
                .FP(17)
                .STM(17)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 10)

                // Level 26
                .AddLevel()
                .HP(395)
                .FP(18)
                .STM(18)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 10)

                // Level 27
                .AddLevel()
                .HP(410)
                .FP(18)
                .STM(18)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 10)

                // Level 28
                .AddLevel()
                .HP(425)
                .FP(19)
                .STM(19)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 10)

                // Level 29
                .AddLevel()
                .HP(440)
                .FP(19)
                .STM(19)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 10)

                // Level 30
                .AddLevel()
                .HP(455)
                .FP(20)
                .STM(20)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 10)

                // Level 31
                .AddLevel()
                .HP(470)
                .FP(20)
                .STM(20)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 10)

                // Level 32
                .AddLevel()
                .HP(485)
                .FP(21)
                .STM(21)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 10)

                // Level 33
                .AddLevel()
                .HP(500)
                .FP(21)
                .STM(21)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 10)

                // Level 34
                .AddLevel()
                .HP(515)
                .FP(22)
                .STM(22)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 10)

                // Level 35
                .AddLevel()
                .HP(530)
                .FP(22)
                .STM(22)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 11)

                // Level 36
                .AddLevel()
                .HP(545)
                .FP(23)
                .STM(23)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 11)

                // Level 37
                .AddLevel()
                .HP(560)
                .FP(23)
                .STM(23)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 11)

                // Level 38
                .AddLevel()
                .HP(575)
                .FP(24)
                .STM(24)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 11)

                // Level 39
                .AddLevel()
                .HP(590)
                .FP(24)
                .STM(24)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 11)

                // Level 40
                .AddLevel()
                .HP(605)
                .FP(25)
                .STM(25)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 11)

                // Level 41
                .AddLevel()
                .HP(620)
                .FP(25)
                .STM(25)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 11)

                // Level 42
                .AddLevel()
                .HP(635)
                .FP(26)
                .STM(26)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 11)

                // Level 43
                .AddLevel()
                .HP(650)
                .FP(26)
                .STM(26)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 27)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 11)

                // Level 44
                .AddLevel()
                .HP(665)
                .FP(27)
                .STM(27)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 27)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 11)

                // Level 45
                .AddLevel()
                .HP(680)
                .FP(27)
                .STM(27)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 27)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 12)

                // Level 46
                .AddLevel()
                .HP(695)
                .FP(28)
                .STM(28)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 27)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 12)

                // Level 47
                .AddLevel()
                .HP(710)
                .FP(28)
                .STM(28)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 28)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 12)

                // Level 48
                .AddLevel()
                .HP(725)
                .FP(29)
                .STM(29)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 28)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 12)

                // Level 49
                .AddLevel()
                .HP(740)
                .FP(29)
                .STM(29)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 28)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 12)

                // Level 50
                .AddLevel()
                .HP(790)
                .FP(30)
                .STM(30)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 28)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 12)


                ;

            return _builder.Build();
        }
    }
}
