using System.Collections.Generic;
using SWLOR.Game.Server.Core.NWScript.Enum;
using SWLOR.Game.Server.Service.BeastMasteryService;

namespace SWLOR.Game.Server.Feature.BeastDefinition
{
    public class SprantalBeastDefinition: IBeastListDefinition
    {
        private readonly BeastBuilder _builder = new();

        public Dictionary<BeastType, BeastDetail> Build()
        {
            _builder.Create(BeastType.Sprantal)
                .CombatStats(AbilityType.Perception, AbilityType.Might)
                .Role(BeastRoleType.Damage)

                
                // Level 1
                .AddLevel()
                .HP(30)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 4)

                // Level 2
                .AddLevel()
                .HP(25)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 4)

                // Level 3
                .AddLevel()
                .HP(35)
                .FP(5)
                .STM(6)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 11)
                .Stat(AbilityType.Social, 4)

                // Level 4
                .AddLevel()
                .HP(45)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 4)

                // Level 5
                .AddLevel()
                .HP(55)
                .FP(6)
                .STM(7)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 4)

                // Level 6
                .AddLevel()
                .HP(65)
                .FP(6)
                .STM(7)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 4)

                // Level 7
                .AddLevel()
                .HP(75)
                .FP(6)
                .STM(7)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 4)

                // Level 8
                .AddLevel()
                .HP(85)
                .FP(6)
                .STM(8)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 4)

                // Level 9
                .AddLevel()
                .HP(95)
                .FP(7)
                .STM(8)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 5)

                // Level 10
                .AddLevel()
                .HP(105)
                .FP(7)
                .STM(9)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 5)

                // Level 11
                .AddLevel()
                .HP(115)
                .FP(7)
                .STM(9)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 5)

                // Level 12
                .AddLevel()
                .HP(125)
                .FP(7)
                .STM(9)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 5)

                // Level 13
                .AddLevel()
                .HP(135)
                .FP(7)
                .STM(10)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 5)

                // Level 14
                .AddLevel()
                .HP(145)
                .FP(8)
                .STM(10)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 5)

                // Level 15
                .AddLevel()
                .HP(155)
                .FP(8)
                .STM(11)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 14)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 5)

                // Level 16
                .AddLevel()
                .HP(165)
                .FP(8)
                .STM(11)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 5)

                // Level 17
                .AddLevel()
                .HP(175)
                .FP(8)
                .STM(11)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 5)

                // Level 18
                .AddLevel()
                .HP(185)
                .FP(8)
                .STM(12)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 5)

                // Level 19
                .AddLevel()
                .HP(195)
                .FP(9)
                .STM(12)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 5)

                // Level 20
                .AddLevel()
                .HP(205)
                .FP(9)
                .STM(13)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 5)

                // Level 21
                .AddLevel()
                .HP(215)
                .FP(9)
                .STM(13)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 15)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 5)

                // Level 22
                .AddLevel()
                .HP(225)
                .FP(9)
                .STM(13)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 5)

                // Level 23
                .AddLevel()
                .HP(235)
                .FP(9)
                .STM(14)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 5)

                // Level 24
                .AddLevel()
                .HP(245)
                .FP(10)
                .STM(14)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 5)

                // Level 25
                .AddLevel()
                .HP(255)
                .FP(10)
                .STM(15)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 6)

                // Level 26
                .AddLevel()
                .HP(265)
                .FP(10)
                .STM(15)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 6)

                // Level 27
                .AddLevel()
                .HP(275)
                .FP(10)
                .STM(15)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 6)

                // Level 28
                .AddLevel()
                .HP(285)
                .FP(10)
                .STM(16)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 6)

                // Level 29
                .AddLevel()
                .HP(295)
                .FP(11)
                .STM(16)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 6)

                // Level 30
                .AddLevel()
                .HP(305)
                .FP(11)
                .STM(17)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 6)

                // Level 31
                .AddLevel()
                .HP(315)
                .FP(11)
                .STM(17)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 6)

                // Level 32
                .AddLevel()
                .HP(325)
                .FP(11)
                .STM(17)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 6)

                // Level 33
                .AddLevel()
                .HP(335)
                .FP(11)
                .STM(18)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 6)

                // Level 34
                .AddLevel()
                .HP(345)
                .FP(12)
                .STM(18)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 6)

                // Level 35
                .AddLevel()
                .HP(355)
                .FP(12)
                .STM(19)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 27)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 6)

                // Level 36
                .AddLevel()
                .HP(365)
                .FP(12)
                .STM(19)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 27)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 6)

                // Level 37
                .AddLevel()
                .HP(375)
                .FP(12)
                .STM(19)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 27)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 6)

                // Level 38
                .AddLevel()
                .HP(385)
                .FP(12)
                .STM(20)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 27)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 6)

                // Level 39
                .AddLevel()
                .HP(395)
                .FP(13)
                .STM(20)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 28)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 6)

                // Level 40
                .AddLevel()
                .HP(405)
                .FP(13)
                .STM(21)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 28)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 6)

                // Level 41
                .AddLevel()
                .HP(415)
                .FP(13)
                .STM(21)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 28)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 42
                .AddLevel()
                .HP(425)
                .FP(13)
                .STM(21)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 28)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 43
                .AddLevel()
                .HP(435)
                .FP(13)
                .STM(22)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 29)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 44
                .AddLevel()
                .HP(445)
                .FP(14)
                .STM(22)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 29)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 45
                .AddLevel()
                .HP(455)
                .FP(14)
                .STM(23)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 29)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 46
                .AddLevel()
                .HP(465)
                .FP(14)
                .STM(23)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 29)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 47
                .AddLevel()
                .HP(475)
                .FP(14)
                .STM(23)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 30)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 48
                .AddLevel()
                .HP(485)
                .FP(14)
                .STM(24)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 30)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 49
                .AddLevel()
                .HP(495)
                .FP(15)
                .STM(24)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 30)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 50
                .AddLevel()
                .HP(530)
                .FP(15)
                .STM(25)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 30)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)


                ;

            return _builder.Build();
        }
    }
}
