using System.Collections.Generic;
using SWLOR.Game.Server.Core.NWScript.Enum;
using SWLOR.Game.Server.Service.BeastMasteryService;

namespace SWLOR.Game.Server.Feature.BeastDefinition
{
    public class SsurianBeastDefinition: IBeastListDefinition
    {
        private readonly BeastBuilder _builder = new();

        public Dictionary<BeastType, BeastDetail> Build()
        {
            _builder.Create(BeastType.Ssurian)
                .Appearance(AppearanceType.CrocAztec)
                .CombatStats(AbilityType.Vitality, AbilityType.Perception)
                .Role(BeastRoleType.Tank)

                
                // Level 1
                .AddLevel()
                .HP(70)
                .FP(4)
                .STM(4)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 4)

                // Level 2
                .AddLevel()
                .HP(54)
                .FP(4)
                .STM(4)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 4)

                // Level 3
                .AddLevel()
                .HP(79)
                .FP(4)
                .STM(4)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 4)

                // Level 4
                .AddLevel()
                .HP(104)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 4)

                // Level 5
                .AddLevel()
                .HP(129)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 4)

                // Level 6
                .AddLevel()
                .HP(154)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 4)

                // Level 7
                .AddLevel()
                .HP(179)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 4)

                // Level 8
                .AddLevel()
                .HP(204)
                .FP(5)
                .STM(5)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 4)

                // Level 9
                .AddLevel()
                .HP(229)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 4)

                // Level 10
                .AddLevel()
                .HP(254)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 4)

                // Level 11
                .AddLevel()
                .HP(279)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 4)

                // Level 12
                .AddLevel()
                .HP(304)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 4)

                // Level 13
                .AddLevel()
                .HP(329)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 5)

                // Level 14
                .AddLevel()
                .HP(354)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 5)

                // Level 15
                .AddLevel()
                .HP(379)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 5)

                // Level 16
                .AddLevel()
                .HP(404)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 5)

                // Level 17
                .AddLevel()
                .HP(429)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 5)

                // Level 18
                .AddLevel()
                .HP(454)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 5)

                // Level 19
                .AddLevel()
                .HP(479)
                .FP(8)
                .STM(8)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 5)

                // Level 20
                .AddLevel()
                .HP(504)
                .FP(8)
                .STM(8)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 5)

                // Level 21
                .AddLevel()
                .HP(529)
                .FP(8)
                .STM(8)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 5)

                // Level 22
                .AddLevel()
                .HP(554)
                .FP(8)
                .STM(8)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 5)

                // Level 23
                .AddLevel()
                .HP(579)
                .FP(8)
                .STM(8)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 5)

                // Level 24
                .AddLevel()
                .HP(604)
                .FP(9)
                .STM(9)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 5)

                // Level 25
                .AddLevel()
                .HP(629)
                .FP(9)
                .STM(9)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 5)

                // Level 26
                .AddLevel()
                .HP(654)
                .FP(9)
                .STM(9)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 5)

                // Level 27
                .AddLevel()
                .HP(679)
                .FP(9)
                .STM(9)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 5)

                // Level 28
                .AddLevel()
                .HP(704)
                .FP(9)
                .STM(9)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 5)

                // Level 29
                .AddLevel()
                .HP(729)
                .FP(10)
                .STM(10)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 5)

                // Level 30
                .AddLevel()
                .HP(754)
                .FP(10)
                .STM(10)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 5)

                // Level 31
                .AddLevel()
                .HP(779)
                .FP(10)
                .STM(10)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 5)

                // Level 32
                .AddLevel()
                .HP(804)
                .FP(10)
                .STM(10)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 5)

                // Level 33
                .AddLevel()
                .HP(829)
                .FP(10)
                .STM(10)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 5)

                // Level 34
                .AddLevel()
                .HP(854)
                .FP(11)
                .STM(11)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 5)

                // Level 35
                .AddLevel()
                .HP(879)
                .FP(11)
                .STM(11)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 5)

                // Level 36
                .AddLevel()
                .HP(904)
                .FP(11)
                .STM(11)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 5)

                // Level 37
                .AddLevel()
                .HP(929)
                .FP(11)
                .STM(11)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 6)

                // Level 38
                .AddLevel()
                .HP(954)
                .FP(11)
                .STM(11)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 6)

                // Level 39
                .AddLevel()
                .HP(979)
                .FP(12)
                .STM(12)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 6)

                // Level 40
                .AddLevel()
                .HP(1004)
                .FP(12)
                .STM(12)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 6)

                // Level 41
                .AddLevel()
                .HP(1029)
                .FP(12)
                .STM(12)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 6)

                // Level 42
                .AddLevel()
                .HP(1054)
                .FP(12)
                .STM(12)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 6)

                // Level 43
                .AddLevel()
                .HP(1079)
                .FP(12)
                .STM(12)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 6)

                // Level 44
                .AddLevel()
                .HP(1104)
                .FP(13)
                .STM(13)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 6)

                // Level 45
                .AddLevel()
                .HP(1129)
                .FP(13)
                .STM(13)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 6)

                // Level 46
                .AddLevel()
                .HP(1154)
                .FP(13)
                .STM(13)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 6)

                // Level 47
                .AddLevel()
                .HP(1179)
                .FP(13)
                .STM(13)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 27)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 6)

                // Level 48
                .AddLevel()
                .HP(1204)
                .FP(13)
                .STM(13)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 27)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 6)

                // Level 49
                .AddLevel()
                .HP(1229)
                .FP(14)
                .STM(14)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 27)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 6)

                // Level 50
                .AddLevel()
                .HP(1330)
                .FP(14)
                .STM(14)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 27)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 6)


                ;

            return _builder.Build();
        }
    }
}
