using System.Collections.Generic;
using SWLOR.Game.Server.Core.NWScript.Enum;
using SWLOR.Game.Server.Service.BeastMasteryService;

namespace SWLOR.Game.Server.Feature.BeastDefinition
{
    public class ValleyCairnmogAlphaBeastDefinition: IBeastListDefinition
    {
        private readonly BeastBuilder _builder = new();

        public Dictionary<BeastType, BeastDetail> Build()
        {
            _builder.Create(BeastType.ValleyCairnmogAlpha)
                .Appearance(AppearanceType.MonsterA)
                .CombatStats(AbilityType.Vitality, AbilityType.Might)
                .Role(BeastRoleType.Bruiser)

                
                // Level 1
                .AddLevel()
                .HP(50)
                .FP(6)
                .STM(6)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 9)

                // Level 2
                .AddLevel()
                .HP(36)
                .FP(6)
                .STM(7)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 16)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 9)

                // Level 3
                .AddLevel()
                .HP(51)
                .FP(7)
                .STM(7)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 10)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 12)
                .Stat(AbilityType.Social, 9)

                // Level 4
                .AddLevel()
                .HP(66)
                .FP(7)
                .STM(8)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 9)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 9)

                // Level 5
                .AddLevel()
                .HP(81)
                .FP(7)
                .STM(9)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 10)

                // Level 6
                .AddLevel()
                .HP(96)
                .FP(8)
                .STM(10)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 10)

                // Level 7
                .AddLevel()
                .HP(111)
                .FP(8)
                .STM(10)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 17)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 10)

                // Level 8
                .AddLevel()
                .HP(126)
                .FP(8)
                .STM(11)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 10)

                // Level 9
                .AddLevel()
                .HP(141)
                .FP(8)
                .STM(12)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 10)

                // Level 10
                .AddLevel()
                .HP(156)
                .FP(9)
                .STM(12)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 11)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 11
                .AddLevel()
                .HP(171)
                .FP(9)
                .STM(13)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 12
                .AddLevel()
                .HP(186)
                .FP(9)
                .STM(14)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 18)
                .Stat(AbilityType.Willpower, 10)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 10)

                // Level 13
                .AddLevel()
                .HP(201)
                .FP(10)
                .STM(14)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 11)

                // Level 14
                .AddLevel()
                .HP(216)
                .FP(10)
                .STM(15)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 11)

                // Level 15
                .AddLevel()
                .HP(231)
                .FP(10)
                .STM(16)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 11)

                // Level 16
                .AddLevel()
                .HP(246)
                .FP(11)
                .STM(17)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 11)

                // Level 17
                .AddLevel()
                .HP(261)
                .FP(11)
                .STM(17)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 12)
                .Stat(AbilityType.Vitality, 19)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 11)

                // Level 18
                .AddLevel()
                .HP(276)
                .FP(11)
                .STM(18)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 11)

                // Level 19
                .AddLevel()
                .HP(291)
                .FP(11)
                .STM(19)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 11)

                // Level 20
                .AddLevel()
                .HP(306)
                .FP(12)
                .STM(19)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 11)

                // Level 21
                .AddLevel()
                .HP(321)
                .FP(12)
                .STM(20)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 12)

                // Level 22
                .AddLevel()
                .HP(336)
                .FP(12)
                .STM(21)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 20)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 12)

                // Level 23
                .AddLevel()
                .HP(351)
                .FP(13)
                .STM(21)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 12)

                // Level 24
                .AddLevel()
                .HP(366)
                .FP(13)
                .STM(22)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 13)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 12)

                // Level 25
                .AddLevel()
                .HP(381)
                .FP(13)
                .STM(23)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 12)

                // Level 26
                .AddLevel()
                .HP(396)
                .FP(14)
                .STM(24)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 21)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 12)

                // Level 27
                .AddLevel()
                .HP(411)
                .FP(14)
                .STM(24)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 12)

                // Level 28
                .AddLevel()
                .HP(426)
                .FP(14)
                .STM(25)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 12)

                // Level 29
                .AddLevel()
                .HP(441)
                .FP(14)
                .STM(26)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 13)

                // Level 30
                .AddLevel()
                .HP(456)
                .FP(15)
                .STM(26)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 13)

                // Level 31
                .AddLevel()
                .HP(471)
                .FP(15)
                .STM(27)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 14)
                .Stat(AbilityType.Vitality, 22)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 13)

                // Level 32
                .AddLevel()
                .HP(486)
                .FP(15)
                .STM(28)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 13)

                // Level 33
                .AddLevel()
                .HP(501)
                .FP(16)
                .STM(28)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 13)

                // Level 34
                .AddLevel()
                .HP(516)
                .FP(16)
                .STM(29)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 13)

                // Level 35
                .AddLevel()
                .HP(531)
                .FP(16)
                .STM(30)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 13)

                // Level 36
                .AddLevel()
                .HP(546)
                .FP(17)
                .STM(31)
                .Stat(AbilityType.Might, 23)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 23)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 13)

                // Level 37
                .AddLevel()
                .HP(561)
                .FP(17)
                .STM(31)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 14)

                // Level 38
                .AddLevel()
                .HP(576)
                .FP(17)
                .STM(32)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 15)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 14)

                // Level 39
                .AddLevel()
                .HP(591)
                .FP(17)
                .STM(33)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 14)

                // Level 40
                .AddLevel()
                .HP(606)
                .FP(18)
                .STM(33)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 14)

                // Level 41
                .AddLevel()
                .HP(621)
                .FP(18)
                .STM(34)
                .Stat(AbilityType.Might, 24)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 24)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 14)

                // Level 42
                .AddLevel()
                .HP(636)
                .FP(18)
                .STM(35)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 14)

                // Level 43
                .AddLevel()
                .HP(651)
                .FP(19)
                .STM(35)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 14)

                // Level 44
                .AddLevel()
                .HP(666)
                .FP(19)
                .STM(36)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 14)

                // Level 45
                .AddLevel()
                .HP(681)
                .FP(19)
                .STM(37)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 16)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 15)

                // Level 46
                .AddLevel()
                .HP(696)
                .FP(20)
                .STM(38)
                .Stat(AbilityType.Might, 25)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 25)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 15)

                // Level 47
                .AddLevel()
                .HP(711)
                .FP(20)
                .STM(38)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 15)

                // Level 48
                .AddLevel()
                .HP(726)
                .FP(20)
                .STM(39)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 15)

                // Level 49
                .AddLevel()
                .HP(741)
                .FP(20)
                .STM(40)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 15)

                // Level 50
                .AddLevel()
                .HP(830)
                .FP(21)
                .STM(40)
                .Stat(AbilityType.Might, 26)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 26)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 15)


                ;

            return _builder.Build();
        }
    }
}
