using System.Collections.Generic;
using SWLOR.Game.Server.Core.NWScript.Enum;
using SWLOR.Game.Server.Service.BeastMasteryService;

namespace SWLOR.Game.Server.Feature.BeastDefinition
{
    public class WildwoodsKinrathBeastDefinition: IBeastListDefinition
    {
        private readonly BeastBuilder _builder = new();

        public Dictionary<BeastType, BeastDetail> Build()
        {
            _builder.Create(BeastType.WildwoodsKinrath)
                .Appearance(AppearanceType.Kinrath)
                .CombatStats(AbilityType.Perception, AbilityType.Agility)
                .Role(BeastRoleType.Evasion)

                
                // Level 1
                .AddLevel()
                .HP(30)
                .FP(3)
                .STM(3)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 8)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 11)

                // Level 2
                .AddLevel()
                .HP(27)
                .FP(3)
                .STM(3)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 17)
                .Stat(AbilityType.Vitality, 8)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 11)

                // Level 3
                .AddLevel()
                .HP(39)
                .FP(3)
                .STM(4)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 8)
                .Stat(AbilityType.Willpower, 11)
                .Stat(AbilityType.Agility, 13)
                .Stat(AbilityType.Social, 11)

                // Level 4
                .AddLevel()
                .HP(51)
                .FP(3)
                .STM(4)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 8)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 12)

                // Level 5
                .AddLevel()
                .HP(63)
                .FP(3)
                .STM(4)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 12)

                // Level 6
                .AddLevel()
                .HP(75)
                .FP(4)
                .STM(5)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 12)

                // Level 7
                .AddLevel()
                .HP(87)
                .FP(4)
                .STM(5)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 12)

                // Level 8
                .AddLevel()
                .HP(99)
                .FP(4)
                .STM(5)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 12)

                // Level 9
                .AddLevel()
                .HP(111)
                .FP(4)
                .STM(5)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 14)
                .Stat(AbilityType.Social, 12)

                // Level 10
                .AddLevel()
                .HP(123)
                .FP(4)
                .STM(6)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 12)

                // Level 11
                .AddLevel()
                .HP(135)
                .FP(4)
                .STM(6)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 13)

                // Level 12
                .AddLevel()
                .HP(147)
                .FP(4)
                .STM(6)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 13)

                // Level 13
                .AddLevel()
                .HP(159)
                .FP(4)
                .STM(7)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 13)

                // Level 14
                .AddLevel()
                .HP(171)
                .FP(4)
                .STM(7)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 13)

                // Level 15
                .AddLevel()
                .HP(183)
                .FP(4)
                .STM(7)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 13)

                // Level 16
                .AddLevel()
                .HP(195)
                .FP(5)
                .STM(8)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 13)

                // Level 17
                .AddLevel()
                .HP(207)
                .FP(5)
                .STM(8)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 13)

                // Level 18
                .AddLevel()
                .HP(219)
                .FP(5)
                .STM(8)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 14)

                // Level 19
                .AddLevel()
                .HP(231)
                .FP(5)
                .STM(8)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 14)

                // Level 20
                .AddLevel()
                .HP(243)
                .FP(5)
                .STM(9)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 14)

                // Level 21
                .AddLevel()
                .HP(255)
                .FP(5)
                .STM(9)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 14)

                // Level 22
                .AddLevel()
                .HP(267)
                .FP(5)
                .STM(9)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 14)

                // Level 23
                .AddLevel()
                .HP(279)
                .FP(5)
                .STM(10)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 14)

                // Level 24
                .AddLevel()
                .HP(291)
                .FP(5)
                .STM(10)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 14)

                // Level 25
                .AddLevel()
                .HP(303)
                .FP(5)
                .STM(10)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 15)

                // Level 26
                .AddLevel()
                .HP(315)
                .FP(6)
                .STM(11)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 15)

                // Level 27
                .AddLevel()
                .HP(327)
                .FP(6)
                .STM(11)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 15)

                // Level 28
                .AddLevel()
                .HP(339)
                .FP(6)
                .STM(11)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 15)

                // Level 29
                .AddLevel()
                .HP(351)
                .FP(6)
                .STM(11)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 15)

                // Level 30
                .AddLevel()
                .HP(363)
                .FP(6)
                .STM(12)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 15)

                // Level 31
                .AddLevel()
                .HP(375)
                .FP(6)
                .STM(12)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 15)

                // Level 32
                .AddLevel()
                .HP(387)
                .FP(6)
                .STM(12)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 16)

                // Level 33
                .AddLevel()
                .HP(399)
                .FP(6)
                .STM(13)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 16)

                // Level 34
                .AddLevel()
                .HP(411)
                .FP(6)
                .STM(13)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 16)

                // Level 35
                .AddLevel()
                .HP(423)
                .FP(6)
                .STM(13)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 16)

                // Level 36
                .AddLevel()
                .HP(435)
                .FP(7)
                .STM(14)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 16)

                // Level 37
                .AddLevel()
                .HP(447)
                .FP(7)
                .STM(14)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 16)

                // Level 38
                .AddLevel()
                .HP(459)
                .FP(7)
                .STM(14)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 16)

                // Level 39
                .AddLevel()
                .HP(471)
                .FP(7)
                .STM(14)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 17)

                // Level 40
                .AddLevel()
                .HP(483)
                .FP(7)
                .STM(15)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 17)

                // Level 41
                .AddLevel()
                .HP(495)
                .FP(7)
                .STM(15)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 17)

                // Level 42
                .AddLevel()
                .HP(507)
                .FP(7)
                .STM(15)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 17)

                // Level 43
                .AddLevel()
                .HP(519)
                .FP(7)
                .STM(16)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 27)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 17)

                // Level 44
                .AddLevel()
                .HP(531)
                .FP(7)
                .STM(16)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 27)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 17)

                // Level 45
                .AddLevel()
                .HP(543)
                .FP(7)
                .STM(16)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 27)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 17)

                // Level 46
                .AddLevel()
                .HP(555)
                .FP(8)
                .STM(17)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 27)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 18)

                // Level 47
                .AddLevel()
                .HP(567)
                .FP(8)
                .STM(17)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 28)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 18)

                // Level 48
                .AddLevel()
                .HP(579)
                .FP(8)
                .STM(17)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 28)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 18)

                // Level 49
                .AddLevel()
                .HP(591)
                .FP(8)
                .STM(17)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 28)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 18)

                // Level 50
                .AddLevel()
                .HP(660)
                .FP(8)
                .STM(18)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 28)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 18)


                ;

            return _builder.Build();
        }
    }
}
