using System.Collections.Generic;
using SWLOR.Game.Server.Core.NWScript.Enum;
using SWLOR.Game.Server.Service.BeastMasteryService;

namespace SWLOR.Game.Server.Feature.BeastDefinition
{
    public class WompratBeastDefinition: IBeastListDefinition
    {
        private readonly BeastBuilder _builder = new();

        public Dictionary<BeastType, BeastDetail> Build()
        {
            _builder.Create(BeastType.Womprat)
                .Appearance(AppearanceType.RodentCapybara)
                .CombatStats(AbilityType.Perception, AbilityType.Agility)
                .Role(BeastRoleType.Evasion)

                
                // Level 1
                .AddLevel()
                .HP(30)
                .FP(3)
                .STM(3)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 8)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 6)

                // Level 2
                .AddLevel()
                .HP(29)
                .FP(3)
                .STM(3)
                .Stat(AbilityType.Might, 13)
                .Stat(AbilityType.Perception, 18)
                .Stat(AbilityType.Vitality, 8)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 15)
                .Stat(AbilityType.Social, 6)

                // Level 3
                .AddLevel()
                .HP(42)
                .FP(3)
                .STM(4)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 8)
                .Stat(AbilityType.Willpower, 12)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 6)

                // Level 4
                .AddLevel()
                .HP(55)
                .FP(3)
                .STM(4)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 8)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 6)

                // Level 5
                .AddLevel()
                .HP(68)
                .FP(3)
                .STM(4)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 6)

                // Level 6
                .AddLevel()
                .HP(81)
                .FP(4)
                .STM(5)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 19)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 6)

                // Level 7
                .AddLevel()
                .HP(94)
                .FP(4)
                .STM(5)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 16)
                .Stat(AbilityType.Social, 7)

                // Level 8
                .AddLevel()
                .HP(107)
                .FP(4)
                .STM(5)
                .Stat(AbilityType.Might, 14)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 9
                .AddLevel()
                .HP(120)
                .FP(4)
                .STM(5)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 13)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 10
                .AddLevel()
                .HP(133)
                .FP(4)
                .STM(6)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 20)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 11
                .AddLevel()
                .HP(146)
                .FP(4)
                .STM(6)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 12
                .AddLevel()
                .HP(159)
                .FP(4)
                .STM(6)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 17)
                .Stat(AbilityType.Social, 7)

                // Level 13
                .AddLevel()
                .HP(172)
                .FP(4)
                .STM(7)
                .Stat(AbilityType.Might, 15)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 14
                .AddLevel()
                .HP(185)
                .FP(4)
                .STM(7)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 21)
                .Stat(AbilityType.Vitality, 9)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 15
                .AddLevel()
                .HP(198)
                .FP(4)
                .STM(7)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 14)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 16
                .AddLevel()
                .HP(211)
                .FP(5)
                .STM(8)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 17
                .AddLevel()
                .HP(224)
                .FP(5)
                .STM(8)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 18)
                .Stat(AbilityType.Social, 7)

                // Level 18
                .AddLevel()
                .HP(237)
                .FP(5)
                .STM(8)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 22)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 7)

                // Level 19
                .AddLevel()
                .HP(250)
                .FP(5)
                .STM(8)
                .Stat(AbilityType.Might, 16)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 8)

                // Level 20
                .AddLevel()
                .HP(263)
                .FP(5)
                .STM(9)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 8)

                // Level 21
                .AddLevel()
                .HP(276)
                .FP(5)
                .STM(9)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 15)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 8)

                // Level 22
                .AddLevel()
                .HP(289)
                .FP(5)
                .STM(9)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 23)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 19)
                .Stat(AbilityType.Social, 8)

                // Level 23
                .AddLevel()
                .HP(302)
                .FP(5)
                .STM(10)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 24
                .AddLevel()
                .HP(315)
                .FP(5)
                .STM(10)
                .Stat(AbilityType.Might, 17)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 10)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 25
                .AddLevel()
                .HP(328)
                .FP(5)
                .STM(10)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 26
                .AddLevel()
                .HP(341)
                .FP(6)
                .STM(11)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 24)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 20)
                .Stat(AbilityType.Social, 8)

                // Level 27
                .AddLevel()
                .HP(354)
                .FP(6)
                .STM(11)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 16)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 8)

                // Level 28
                .AddLevel()
                .HP(367)
                .FP(6)
                .STM(11)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 8)

                // Level 29
                .AddLevel()
                .HP(380)
                .FP(6)
                .STM(11)
                .Stat(AbilityType.Might, 18)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 8)

                // Level 30
                .AddLevel()
                .HP(393)
                .FP(6)
                .STM(12)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 25)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 8)

                // Level 31
                .AddLevel()
                .HP(406)
                .FP(6)
                .STM(12)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 21)
                .Stat(AbilityType.Social, 9)

                // Level 32
                .AddLevel()
                .HP(419)
                .FP(6)
                .STM(12)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 9)

                // Level 33
                .AddLevel()
                .HP(432)
                .FP(6)
                .STM(13)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 17)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 9)

                // Level 34
                .AddLevel()
                .HP(445)
                .FP(6)
                .STM(13)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 26)
                .Stat(AbilityType.Vitality, 11)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 9)

                // Level 35
                .AddLevel()
                .HP(458)
                .FP(6)
                .STM(13)
                .Stat(AbilityType.Might, 19)
                .Stat(AbilityType.Perception, 27)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 9)

                // Level 36
                .AddLevel()
                .HP(471)
                .FP(7)
                .STM(14)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 27)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 22)
                .Stat(AbilityType.Social, 9)

                // Level 37
                .AddLevel()
                .HP(484)
                .FP(7)
                .STM(14)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 27)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 9)

                // Level 38
                .AddLevel()
                .HP(497)
                .FP(7)
                .STM(14)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 27)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 9)

                // Level 39
                .AddLevel()
                .HP(510)
                .FP(7)
                .STM(14)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 28)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 18)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 9)

                // Level 40
                .AddLevel()
                .HP(523)
                .FP(7)
                .STM(15)
                .Stat(AbilityType.Might, 20)
                .Stat(AbilityType.Perception, 28)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 9)

                // Level 41
                .AddLevel()
                .HP(536)
                .FP(7)
                .STM(15)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 28)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 23)
                .Stat(AbilityType.Social, 9)

                // Level 42
                .AddLevel()
                .HP(549)
                .FP(7)
                .STM(15)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 28)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 9)

                // Level 43
                .AddLevel()
                .HP(562)
                .FP(7)
                .STM(16)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 29)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 10)

                // Level 44
                .AddLevel()
                .HP(575)
                .FP(7)
                .STM(16)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 29)
                .Stat(AbilityType.Vitality, 12)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 10)

                // Level 45
                .AddLevel()
                .HP(588)
                .FP(7)
                .STM(16)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 29)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 19)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 10)

                // Level 46
                .AddLevel()
                .HP(601)
                .FP(8)
                .STM(17)
                .Stat(AbilityType.Might, 21)
                .Stat(AbilityType.Perception, 29)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 24)
                .Stat(AbilityType.Social, 10)

                // Level 47
                .AddLevel()
                .HP(614)
                .FP(8)
                .STM(17)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 30)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 10)

                // Level 48
                .AddLevel()
                .HP(627)
                .FP(8)
                .STM(17)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 30)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 10)

                // Level 49
                .AddLevel()
                .HP(640)
                .FP(8)
                .STM(17)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 30)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 10)

                // Level 50
                .AddLevel()
                .HP(690)
                .FP(8)
                .STM(18)
                .Stat(AbilityType.Might, 22)
                .Stat(AbilityType.Perception, 30)
                .Stat(AbilityType.Vitality, 13)
                .Stat(AbilityType.Willpower, 20)
                .Stat(AbilityType.Agility, 25)
                .Stat(AbilityType.Social, 10)


                ;

            return _builder.Build();
        }
    }
}
