// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWLOR.CLI.LegacyMigration
{
    public partial class Area
    {
        public string Id { get; set; }
        public string Resref { get; set; }
        public string Name { get; set; }
        public string Tag { get; set; }
        public int ResourceSpawnTableId { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public bool IsBuildable { get; set; }
        public string NorthwestOwner { get; set; }
        public string NortheastOwner { get; set; }
        public string SouthwestOwner { get; set; }
        public string SoutheastOwner { get; set; }
        public bool IsActive { get; set; }
        public int PurchasePrice { get; set; }
        public int DailyUpkeep { get; set; }
        public bool AutoSpawnResources { get; set; }
        public int ResourceQuality { get; set; }
        public int? NorthwestLootTableId { get; set; }
        public int? NortheastLootTableId { get; set; }
        public int? SouthwestLootTableId { get; set; }
        public int? SoutheastLootTableId { get; set; }
        public int MaxResourceQuality { get; set; }
        public int ClusterId { get; set; }

        public virtual Player NortheastOwnerNavigation { get; set; }
        public virtual Player NorthwestOwnerNavigation { get; set; }
        public virtual Player SoutheastOwnerNavigation { get; set; }
        public virtual Player SouthwestOwnerNavigation { get; set; }
    }
}