// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWLOR.CLI.LegacyMigration
{
    public partial class Authorizeddm
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Cdkey { get; set; }
        public int Dmrole { get; set; }
        public bool IsActive { get; set; }
    }
}