// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWLOR.CLI.LegacyMigration
{
    public partial class Bankitem
    {
        public string Id { get; set; }
        public int BankId { get; set; }
        public string PlayerId { get; set; }
        public string ItemId { get; set; }
        public string ItemName { get; set; }
        public string ItemTag { get; set; }
        public string ItemResref { get; set; }
        public string ItemObject { get; set; }
        public DateTime DateStored { get; set; }
        public int ClusterId { get; set; }

        public virtual Bank Bank { get; set; }
        public virtual Player Player { get; set; }
    }
}