// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWLOR.CLI.LegacyMigration
{
    public partial class Pcobjectvisibility
    {
        public string Id { get; set; }
        public string PlayerId { get; set; }
        public string VisibilityObjectId { get; set; }
        public bool IsVisible { get; set; }
        public int ClusterId { get; set; }

        public virtual Player Player { get; set; }
    }
}