// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWLOR.CLI.LegacyMigration
{
    public partial class Pcquestkilltargetprogress
    {
        public string Id { get; set; }
        public string PlayerId { get; set; }
        public string PcquestStatusId { get; set; }
        public int NpcgroupId { get; set; }
        public int RemainingToKill { get; set; }
        public int ClusterId { get; set; }

        public virtual Pcqueststatus PcquestStatus { get; set; }
        public virtual Player Player { get; set; }
    }
}