// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWLOR.CLI.LegacyMigration
{
    public partial class Pcqueststatus
    {
        public Pcqueststatus()
        {
            Pcquestitemprogress = new HashSet<Pcquestitemprogress>();
            Pcquestkilltargetprogress = new HashSet<Pcquestkilltargetprogress>();
        }

        public string Id { get; set; }
        public string PlayerId { get; set; }
        public int QuestId { get; set; }
        public DateTime? CompletionDate { get; set; }
        public int? SelectedItemRewardId { get; set; }
        public int ClusterId { get; set; }
        public int TimesCompleted { get; set; }
        public int QuestState { get; set; }

        public virtual Player Player { get; set; }
        public virtual ICollection<Pcquestitemprogress> Pcquestitemprogress { get; set; }
        public virtual ICollection<Pcquestkilltargetprogress> Pcquestkilltargetprogress { get; set; }
    }
}