// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWLOR.CLI.LegacyMigration
{
    public partial class Serverconfiguration
    {
        public int Id { get; set; }
        public string ServerName { get; set; }
        public string MessageOfTheDay { get; set; }
        public int ModuleVersion { get; set; }
        public DateTime LastGuildTaskUpdate { get; set; }
    }
}