using SWLOR.NWN.API.NWScript.Enum;
using SWLOR.Shared.Domain.StatusEffect.Enums;
using SWLOR.Shared.Domain.StatusEffect.ValueObjects;
using SWLOR.Component.StatusEffect.Contracts;

namespace SWLOR.Component.StatusEffect.Service
{
    /// <summary>
    /// Service responsible for managing status effect data and state.
    /// </summary>
    public class StatusEffectDataService : IStatusEffectDataService
    {
        public Dictionary<StatusEffectType, StatusEffectDetail> StatusEffects { get; } = new();
        public Dictionary<uint, Dictionary<StatusEffectType, StatusEffectGroup>> CreaturesWithStatusEffects { get; } = new();
        public Dictionary<uint, Dictionary<StatusEffectType, StatusEffectGroup>> LoggedOutPlayersWithEffects { get; } = new();
        public Dictionary<EffectIconType, List<StatusEffectType>> EffectIconToStatusEffects { get; } = new();

        public Dictionary<EffectIconType, AbilityType> AbilityIncreaseIconType { get; } = new()
        {
            { EffectIconType.AbilityIncreaseSTR, AbilityType.Might },
            { EffectIconType.AbilityDecreaseSTR, AbilityType.Might },
            { EffectIconType.AbilityIncreaseDEX, AbilityType.Perception },
            { EffectIconType.AbilityDecreaseDEX, AbilityType.Perception },
            { EffectIconType.AbilityIncreaseCON, AbilityType.Vitality },
            { EffectIconType.AbilityDecreaseCON, AbilityType.Vitality },
            { EffectIconType.AbilityIncreaseINT, AbilityType.Agility },
            { EffectIconType.AbilityDecreaseINT, AbilityType.Agility },
            { EffectIconType.AbilityIncreaseWIS, AbilityType.Willpower },
            { EffectIconType.AbilityDecreaseWIS, AbilityType.Willpower },
            { EffectIconType.AbilityIncreaseCHA, AbilityType.Social },
            { EffectIconType.AbilityDecreaseCHA, AbilityType.Social },
        };

        public Dictionary<EffectIconType, EffectScriptType> EffectIconToEffectType { get; } = new()
        {
            { EffectIconType.Invalid, EffectScriptType.Invalideffect },
            { EffectIconType.DamageResistance, EffectScriptType.DamageResistance },
            { EffectIconType.Regenerate, EffectScriptType.Regenerate },
            { EffectIconType.DamageReduction, EffectScriptType.DamageReduction },
            { EffectIconType.TemporaryHitpoints, EffectScriptType.TemporaryHitpoints },
            { EffectIconType.Entangle, EffectScriptType.Entangle },
            { EffectIconType.Invulnerable, EffectScriptType.Invulnerable },
            { EffectIconType.Fatigue, EffectScriptType.Invalideffect },
            { EffectIconType.Deaf, EffectScriptType.Deaf },
            { EffectIconType.Immunity, EffectScriptType.Immunity },
            { EffectIconType.EnemyAttackBonus, EffectScriptType.EnemyAttackBonus },
            { EffectIconType.Charmed, EffectScriptType.Charmed },
            { EffectIconType.Confused, EffectScriptType.Confused },
            { EffectIconType.Frightened, EffectScriptType.Frightened },
            { EffectIconType.Dominated, EffectScriptType.Dominated },
            { EffectIconType.Paralyze, EffectScriptType.Paralyze },
            { EffectIconType.Dazed, EffectScriptType.Dazed },
            { EffectIconType.Stunned, EffectScriptType.Stunned },
            { EffectIconType.Sleep, EffectScriptType.Sleep },
            { EffectIconType.Poison, EffectScriptType.Poison },
            { EffectIconType.Disease, EffectScriptType.Disease },
            { EffectIconType.Curse, EffectScriptType.Curse },
            { EffectIconType.Silence, EffectScriptType.Silence },
            { EffectIconType.Turned, EffectScriptType.Turned },
            { EffectIconType.Haste, EffectScriptType.Haste },
            { EffectIconType.Slow, EffectScriptType.Slow },
            { EffectIconType.AbilityIncreaseSTR, EffectScriptType.AbilityIncrease },
            { EffectIconType.AbilityDecreaseSTR, EffectScriptType.AbilityDecrease },
            { EffectIconType.AttackIncrease, EffectScriptType.AttackIncrease },
            { EffectIconType.AttackDecrease, EffectScriptType.AttackDecrease },
            { EffectIconType.DamageIncrease, EffectScriptType.DamageIncrease },
            { EffectIconType.DamageDecrease, EffectScriptType.DamageDecrease },
            { EffectIconType.DamageImmunityIncrease, EffectScriptType.DamageImmunityIncrease },
            { EffectIconType.DamageImmunityDecrease, EffectScriptType.DamageImmunityDecrease },
            { EffectIconType.ACIncrease, EffectScriptType.ACIncrease },
            { EffectIconType.ACDecrease, EffectScriptType.ACDecrease },
            { EffectIconType.MovementSpeedIncrease, EffectScriptType.MovementSpeedIncrease },
            { EffectIconType.MovementSpeedDecrease, EffectScriptType.MovementSpeedDecrease },
            { EffectIconType.SavingThrowIncrease, EffectScriptType.SavingThrowDecrease },
            { EffectIconType.SpellResistanceIncrease, EffectScriptType.SpellResistanceIncrease },
            { EffectIconType.SpellResistanceDecrease, EffectScriptType.SpellResistanceDecrease },
            { EffectIconType.SkillIncrease, EffectScriptType.SkillIncrease },
            { EffectIconType.SkillDecrease, EffectScriptType.SkillDecrease },
            { EffectIconType.Invisibility, EffectScriptType.Invisibility },
            { EffectIconType.ImprovedInvisibility, EffectScriptType.ImprovedInvisibility },
            { EffectIconType.Darkness, EffectScriptType.Darkness },
            { EffectIconType.DispelMagicAll, EffectScriptType.DispelMagicAll },
            { EffectIconType.ElementalShield, EffectScriptType.ElementalShield },
            { EffectIconType.LevelDrain, EffectScriptType.NegativeLevel },
            { EffectIconType.Polymorph, EffectScriptType.Polymorph },
            { EffectIconType.Sanctuary, EffectScriptType.Sanctuary },
            { EffectIconType.TrueSeeing, EffectScriptType.TrueSeeing },
            { EffectIconType.SeeInvisibility, EffectScriptType.SeeInvisible },
            { EffectIconType.Timestop, EffectScriptType.Timestop },
            { EffectIconType.Blindness, EffectScriptType.Blindness },
            { EffectIconType.SpellLevelAbsorption, EffectScriptType.SpellLevelAbsorption },
            { EffectIconType.DispelMagicBest, EffectScriptType.DispelMagicBest },
            { EffectIconType.AbilityIncreaseDEX, EffectScriptType.AbilityIncrease },
            { EffectIconType.AbilityDecreaseDEX, EffectScriptType.AbilityDecrease },
            { EffectIconType.AbilityIncreaseCON, EffectScriptType.AbilityIncrease },
            { EffectIconType.AbilityDecreaseCON, EffectScriptType.AbilityDecrease },
            { EffectIconType.AbilityIncreaseINT, EffectScriptType.AbilityIncrease },
            { EffectIconType.AbilityDecreaseINT, EffectScriptType.AbilityDecrease },
            { EffectIconType.AbilityIncreaseWIS, EffectScriptType.AbilityIncrease },
            { EffectIconType.AbilityDecreaseWIS, EffectScriptType.AbilityDecrease },
            { EffectIconType.AbilityIncreaseCHA, EffectScriptType.AbilityIncrease },
            { EffectIconType.AbilityDecreaseCHA, EffectScriptType.AbilityDecrease },
            { EffectIconType.ImmunityAll, EffectScriptType.Immunity },
            { EffectIconType.ImmunityMind, EffectScriptType.Immunity },
            { EffectIconType.ImmunityPoison, EffectScriptType.Immunity },
            { EffectIconType.ImmunityDisease, EffectScriptType.Immunity },
            { EffectIconType.ImmunityFear, EffectScriptType.Immunity },
            { EffectIconType.ImmunityTrap, EffectScriptType.Immunity },
            { EffectIconType.ImmunityParalysis, EffectScriptType.Immunity },
            { EffectIconType.ImmunityBlindness, EffectScriptType.Immunity },
            { EffectIconType.ImmunityDeafness, EffectScriptType.Immunity },
            { EffectIconType.ImmunitySlow, EffectScriptType.Immunity },
            { EffectIconType.ImmunityEntangle, EffectScriptType.Immunity },
            { EffectIconType.ImmunitySilence, EffectScriptType.Immunity },
            { EffectIconType.ImmunityStun, EffectScriptType.Immunity },
            { EffectIconType.ImmunitySleep, EffectScriptType.Immunity },
            { EffectIconType.ImmunityCharm, EffectScriptType.Immunity },
            { EffectIconType.ImmunityDominate, EffectScriptType.Immunity },
            { EffectIconType.ImmunityConfuse, EffectScriptType.Immunity },
            { EffectIconType.ImmunityCurse, EffectScriptType.Immunity },
            { EffectIconType.ImmunityDazed, EffectScriptType.Immunity },
            { EffectIconType.ImmunityAbilityDecrease, EffectScriptType.Immunity },
            { EffectIconType.ImmunityAttackDecrease, EffectScriptType.Immunity },
            { EffectIconType.ImmunityDamageDecrease, EffectScriptType.Immunity },
            { EffectIconType.ImmunityDamageImmunityDecrease, EffectScriptType.Immunity },
            { EffectIconType.ImmunityACDecrease, EffectScriptType.Immunity },
            { EffectIconType.ImmunityMovementSpeedDecrease, EffectScriptType.Immunity },
            { EffectIconType.ImmunitySavingThrowDecrease, EffectScriptType.Immunity },
            { EffectIconType.ImmunitySpellResistanceDecrease, EffectScriptType.Immunity },
            { EffectIconType.ImmunitySkillDecrease, EffectScriptType.Immunity },
            { EffectIconType.ImmunityKnockdown, EffectScriptType.Immunity },
            { EffectIconType.ImmunityNegativeLevel, EffectScriptType.Immunity },
            { EffectIconType.ImmunitySneakAttack, EffectScriptType.Immunity },
            { EffectIconType.ImmunityCriticalHit, EffectScriptType.Immunity },
            { EffectIconType.ImmunityDeathMagic, EffectScriptType.Immunity },
            { EffectIconType.ReflexSaveIncreased, EffectScriptType.SavingThrowIncrease },
            { EffectIconType.FortitudeSaveIncreased, EffectScriptType.SavingThrowIncrease },
            { EffectIconType.WillSaveIncreased, EffectScriptType.SavingThrowIncrease },
            { EffectIconType.Taunted, EffectScriptType.Invalideffect },
            { EffectIconType.SpellImmunity, EffectScriptType.SpellImmunity },
            { EffectIconType.Etherealness, EffectScriptType.Ethereal },
            { EffectIconType.Concealment, EffectScriptType.Concealment },
            { EffectIconType.Petrified, EffectScriptType.Petrify },
            { EffectIconType.EffectSpellFailure, EffectScriptType.SpellFailure },
            { EffectIconType.DamageImmunityMagic, EffectScriptType.DamageImmunityIncrease },
            { EffectIconType.DamageImmunityAcid, EffectScriptType.DamageImmunityIncrease },
            { EffectIconType.DamageImmunityCold, EffectScriptType.DamageImmunityIncrease },
            { EffectIconType.DamageImmunityDivine, EffectScriptType.DamageImmunityIncrease },
            { EffectIconType.DamageImmunityElectrical, EffectScriptType.DamageImmunityIncrease },
            { EffectIconType.DamageImmunityFire, EffectScriptType.DamageImmunityIncrease },
            { EffectIconType.DamageImmunityNegative, EffectScriptType.DamageImmunityIncrease },
            { EffectIconType.DamageImmunityPositive, EffectScriptType.DamageImmunityIncrease },
            { EffectIconType.DamageImmunitySonic, EffectScriptType.DamageImmunityIncrease },
            { EffectIconType.DamageImmunityMagicDecrease, EffectScriptType.DamageImmunityDecrease },
            { EffectIconType.DamageImmunityAcidDecrease, EffectScriptType.DamageImmunityDecrease },
            { EffectIconType.DamageImmunityColdDecrease, EffectScriptType.DamageImmunityDecrease },
            { EffectIconType.DamageImmunityDivineDecrease, EffectScriptType.DamageImmunityDecrease },
            { EffectIconType.DamageImmunityElectricalDecrease, EffectScriptType.DamageImmunityDecrease },
            { EffectIconType.DamageImmunityFireDecrease, EffectScriptType.DamageImmunityDecrease },
            { EffectIconType.DamageImmunityNegativeDecrease, EffectScriptType.DamageImmunityDecrease },
            { EffectIconType.DamageImmunityPositiveDecrease, EffectScriptType.DamageImmunityDecrease },
            { EffectIconType.DamageImmunitySonicDecrease, EffectScriptType.DamageImmunityDecrease },
            { EffectIconType.Charge, EffectScriptType.MovementSpeedIncrease },
            { EffectIconType.Dedication, EffectScriptType.Invalideffect },
            { EffectIconType.FrenziedShout, EffectScriptType.Invalideffect },
            { EffectIconType.Rejuvenation, EffectScriptType.Regenerate },
            { EffectIconType.SoldiersPrecision, EffectScriptType.AttackIncrease },
            { EffectIconType.SoldiersSpeed, EffectScriptType.MovementSpeedIncrease },
            { EffectIconType.SoldiersStrike, EffectScriptType.DamageIncrease },
        };
    }
}
