// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Katar
{
    public class GuardCounterAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.GuardCounter1, PerkType.GuardCounter)
                    .Name("Guard Counter I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.GuardCounter, 30.0f),
                SkillType.Katar,
                8,
                0,
                null,
                null,
                3,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                () => new GeneratedWeaponAbilityProfile
                {
                    ExtraDamageIfRecentGuardedHit = 8,
                    RecentGuardedHitWindowSeconds = 30
                });

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.GuardCounter2, PerkType.GuardCounter)
                    .Name("Guard Counter II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.GuardCounter, 30.0f),
                SkillType.Katar,
                18,
                0,
                null,
                null,
                5,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                () => new GeneratedWeaponAbilityProfile
                {
                    ExtraDamageIfRecentGuardedHit = 12,
                    RecentGuardedHitWindowSeconds = 30
                });

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.GuardCounter3, PerkType.GuardCounter)
                    .Name("Guard Counter III")
                    .Level(3)
                    .HasRecastDelay(RecastGroup.GuardCounter, 45.0f),
                SkillType.Katar,
                28,
                30,
                typeof(DazedStatusEffect),
                null,
                8,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                () => new GeneratedWeaponAbilityProfile
                {
                    ExtraDamageIfRecentGuardedHit = 17,
                    RecentGuardedHitWindowSeconds = 30,
                    ProtectedTargetHitWindowSeconds = 30,
                    RequireRecentGuardedHitForConditionalStatus = true,
                    ConditionalTargetStatusEffect = typeof(DazedStatusEffect),
                    ConditionalTargetStatusDurationSeconds = 30
                });

            return builder.Build();
        }
    }
}
