// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Katar
{
    public class InterruptingSweepAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.InterruptingSweep1, PerkType.InterruptingSweep)
                    .Name("Interrupting Sweep I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.InterruptingSweep, 30.0f),
                SkillType.Katar,
                16,
                0,
                null,
                null,
                6,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.InterruptingSweep1,
                AbilityTargetingShapeType.Sphere,
                5.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    ClearTargetActionsOnHit = true
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.InterruptingSweep2, PerkType.InterruptingSweep)
                    .Name("Interrupting Sweep II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.InterruptingSweep, 30.0f),
                SkillType.Katar,
                30,
                0,
                null,
                null,
                9,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.InterruptingSweep2,
                AbilityTargetingShapeType.Sphere,
                5.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    ClearTargetActionsOnHit = true
                });

            return builder.Build();
        }
    }
}
