<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SWLOR.NWN.Formats</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Nwn.Formats.Exceptions.NwnFormatException" Alias="NwnFormatException" />
    <ProjectReference Include="$(NwnToolsetSourceRoot)\src\Nwn.Formats\Nwn.Formats.csproj"
                      Condition="'$(NwnToolsetSourceRoot)' != ''" />
    <PackageReference Include="Nwn.Formats" Version="0.1.0-dev.60"
                      Condition="'$(NwnToolsetSourceRoot)' == ''" />
  </ItemGroup>
</Project>
