using System.Collections.Generic;
using SWLOR.Game.Server.Service.CraftService;
using SWLOR.Game.Server.Service.SkillService;

namespace SWLOR.Game.Server.Feature.RecipeDefinition.EngineeringRecipeDefinition
{
    public class DroidInstructionRecipes : IRecipeListDefinition
    {
        private readonly RecipeBuilder _builder = new();

        public Dictionary<RecipeType, RecipeDetail> BuildRecipes()
        {
            Tier1();
            Tier2();
            Tier3();
            Tier4();
            Tier5();

            return _builder.Build();
        }

        private void Tier1()
        {
            CreateTier(10, "jade", "elec_ruined", "quadrenium",
                new DroidInstructionRecipe(RecipeType.InstructionAdrenalStim1, "id_adrenal1"),
                new DroidInstructionRecipe(RecipeType.InstructionAimedShot1, "id_aimedshot1"),
                new DroidInstructionRecipe(RecipeType.InstructionBlasterBeacon1, "id_blastbeac1"),
                new DroidInstructionRecipe(RecipeType.InstructionConcussionGrenade1, "id_concgren1"),
                new DroidInstructionRecipe(RecipeType.InstructionCrossCut1, "id_cross_cut1"),
                new DroidInstructionRecipe(RecipeType.InstructionDeflectorShield1, "id_defshield1"),
                new DroidInstructionRecipe(RecipeType.InstructionDisablingStrike1, "id_disastri1"),
                new DroidInstructionRecipe(RecipeType.InstructionDisarmingShot1, "id_disashot1"),
                new DroidInstructionRecipe(RecipeType.InstructionExplosiveToss1, "id_expltoss1"),
                new DroidInstructionRecipe(RecipeType.InstructionFlamethrower1, "id_flamethrow1"),
                new DroidInstructionRecipe(RecipeType.InstructionFortressStrike1, "id_fortstri1"),
                new DroidInstructionRecipe(RecipeType.InstructionFragGrenade1, "id_fraggren1"),
                new DroidInstructionRecipe(RecipeType.InstructionGuardCounter1, "id_guardcounter1"),
                new DroidInstructionRecipe(RecipeType.InstructionHookingStrike1, "id_hookstri1"),
                new DroidInstructionRecipe(RecipeType.InstructionIncendiaryField1, "id_incfield1"),
                new DroidInstructionRecipe(RecipeType.InstructionIonGrenade1, "id_iongren1"),
                new DroidInstructionRecipe(RecipeType.InstructionLaceratingTwinCut1, "id_lacetwincut1"),
                new DroidInstructionRecipe(RecipeType.InstructionLineBreaker1, "id_linebreaker1"),
                new DroidInstructionRecipe(RecipeType.InstructionMedKit1, "id_medkit1"),
                new DroidInstructionRecipe(RecipeType.InstructionPathogenStrike1, "id_pathstri1"),
                new DroidInstructionRecipe(RecipeType.InstructionPiercingToss1, "id_piercingtoss1"),
                new DroidInstructionRecipe(RecipeType.InstructionProvoke1, "id_provoke1"),
                new DroidInstructionRecipe(RecipeType.InstructionQuickDraw1, "id_quick_draw1"),
                new DroidInstructionRecipe(RecipeType.InstructionRiotBlade1, "id_riotblade1"),
                new DroidInstructionRecipe(RecipeType.InstructionShieldBash1, "id_shieldbash1"),
                new DroidInstructionRecipe(RecipeType.InstructionShielding1, "id_shielding1"),
                new DroidInstructionRecipe(RecipeType.InstructionSlam1, "id_staff_slam1"),
                new DroidInstructionRecipe(RecipeType.InstructionSonicBurst1, "id_sonicburst1"),
                new DroidInstructionRecipe(RecipeType.InstructionSoulStrike1, "id_soulstrike1"),
                new DroidInstructionRecipe(RecipeType.InstructionSuppressingShot1, "id_suppr_shot1"),
                new DroidInstructionRecipe(RecipeType.InstructionTreatmentKit1, "id_treatkit1"),
                new DroidInstructionRecipe(RecipeType.InstructionVeiledStrike1, "id_veiledstrike1"),
                new DroidInstructionRecipe(RecipeType.InstructionVigorThrust1, "id_vigorthrust1"),
                new DroidInstructionRecipe(RecipeType.InstructionWeaponJam, "id_weaponjam"));
        }

        private void Tier2()
        {
            CreateTier(20, "agate", "elec_flawed", "vintrium",
                new DroidInstructionRecipe(RecipeType.InstructionAdrenalStim2, "id_adrenal2"),
                new DroidInstructionRecipe(RecipeType.InstructionAimedShot2, "id_aimedshot2"),
                new DroidInstructionRecipe(RecipeType.InstructionAntitoxin, "id_antitoxin"),
                new DroidInstructionRecipe(RecipeType.InstructionArcProjector1, "id_arcproj1"),
                new DroidInstructionRecipe(RecipeType.InstructionBackstab1, "id_backstab_atk1"),
                new DroidInstructionRecipe(RecipeType.InstructionBladeVortex1, "id_bladevortex1"),
                new DroidInstructionRecipe(RecipeType.InstructionBlasterBeacon2, "id_blastbeac2"),
                new DroidInstructionRecipe(RecipeType.InstructionConcussiveToss1, "id_conctoss1"),
                new DroidInstructionRecipe(RecipeType.InstructionCoveringStrike1, "id_covestri1"),
                new DroidInstructionRecipe(RecipeType.InstructionCripplingShot1, "id_cripshot1"),
                new DroidInstructionRecipe(RecipeType.InstructionCripplingSlice1, "id_cripslic1"),
                new DroidInstructionRecipe(RecipeType.InstructionCrossCut2, "id_cross_cut2"),
                new DroidInstructionRecipe(RecipeType.InstructionDeflectorShield2, "id_defshield2"),
                new DroidInstructionRecipe(RecipeType.InstructionDisablingStrike2, "id_disastri2"),
                new DroidInstructionRecipe(RecipeType.InstructionDisarmingShot2, "id_disashot2"),
                new DroidInstructionRecipe(RecipeType.InstructionDisruptionField1, "id_disrfiel1"),
                new DroidInstructionRecipe(RecipeType.InstructionDoubleShot1, "id_doubleshot1"),
                new DroidInstructionRecipe(RecipeType.InstructionEarthshatter1, "id_earthshatter1"),
                new DroidInstructionRecipe(RecipeType.InstructionExplosiveToss2, "id_expltoss2"),
                new DroidInstructionRecipe(RecipeType.InstructionFanTheHammer1, "id_fanthehammer1"),
                new DroidInstructionRecipe(RecipeType.InstructionFlash, "id_flash"),
                new DroidInstructionRecipe(RecipeType.InstructionFlashGrenade, "id_flashgren"),
                new DroidInstructionRecipe(RecipeType.InstructionFlashToss1, "id_flashtoss1"),
                new DroidInstructionRecipe(RecipeType.InstructionFortressStrike2, "id_fortstri2"),
                new DroidInstructionRecipe(RecipeType.InstructionFragGrenade2, "id_fraggren2"),
                new DroidInstructionRecipe(RecipeType.InstructionGroundQuake1, "id_groundquake1"),
                new DroidInstructionRecipe(RecipeType.InstructionGuardCounter2, "id_guardcounter2"),
                new DroidInstructionRecipe(RecipeType.InstructionHamperingBarrage1, "id_hampbarr1"),
                new DroidInstructionRecipe(RecipeType.InstructionHeadshot1, "id_headshot1"),
                new DroidInstructionRecipe(RecipeType.InstructionHookingStrike2, "id_hookstri2"),
                new DroidInstructionRecipe(RecipeType.InstructionInterruptingShot1, "id_inteshot1"),
                new DroidInstructionRecipe(RecipeType.InstructionInterruptingSweep1, "id_inteswee1"),
                new DroidInstructionRecipe(RecipeType.InstructionInterruptionStrike1, "id_intestri1"),
                new DroidInstructionRecipe(RecipeType.InstructionIonLance1, "id_ionlance1"),
                new DroidInstructionRecipe(RecipeType.InstructionJointLock1, "id_jointlock1"),
                new DroidInstructionRecipe(RecipeType.InstructionKoltoMist1, "id_koltomist1"),
                new DroidInstructionRecipe(RecipeType.InstructionLaceratingTwinCut2, "id_lacetwincut2"),
                new DroidInstructionRecipe(RecipeType.InstructionLegSweep1, "id_leg_sweep1"),
                new DroidInstructionRecipe(RecipeType.InstructionLineBreaker2, "id_linebreaker2"),
                new DroidInstructionRecipe(RecipeType.InstructionMedKit2, "id_medkit2"),
                new DroidInstructionRecipe(RecipeType.InstructionPainSuppressant1, "id_painsupp1"),
                new DroidInstructionRecipe(RecipeType.InstructionPathogenStrike2, "id_pathstri2"),
                new DroidInstructionRecipe(RecipeType.InstructionPiercingRound1, "id_pierroun1"),
                new DroidInstructionRecipe(RecipeType.InstructionPiercingToss2, "id_piercingtoss2"),
                new DroidInstructionRecipe(RecipeType.InstructionPinningToss1, "id_pinningtoss1"),
                new DroidInstructionRecipe(RecipeType.InstructionPointBlankBurst1, "id_poinblanburs1"),
                new DroidInstructionRecipe(RecipeType.InstructionPowerCell1, "id_powercell1"),
                new DroidInstructionRecipe(RecipeType.InstructionProvoke2, "id_provoke2"),
                new DroidInstructionRecipe(RecipeType.InstructionQuickDraw2, "id_quick_draw2"),
                new DroidInstructionRecipe(RecipeType.InstructionRailDart1, "id_raildart1"),
                new DroidInstructionRecipe(RecipeType.InstructionRemoteCharge1, "id_remcharge1"),
                new DroidInstructionRecipe(RecipeType.InstructionRendingStrike1, "id_rendstri1"),
                new DroidInstructionRecipe(RecipeType.InstructionResuscitation1, "id_resusc1"),
                new DroidInstructionRecipe(RecipeType.InstructionRibBreaker1, "id_ribbreaker1"),
                new DroidInstructionRecipe(RecipeType.InstructionRiotBlade2, "id_riotblade2"),
                new DroidInstructionRecipe(RecipeType.InstructionSacrificialBlade, "id_sacrblad"),
                new DroidInstructionRecipe(RecipeType.InstructionSavageCleave1, "id_savagecleave1"),
                new DroidInstructionRecipe(RecipeType.InstructionSerratedArc1, "id_serratedarc1"),
                new DroidInstructionRecipe(RecipeType.InstructionSeveringToss1, "id_severingtoss1"),
                new DroidInstructionRecipe(RecipeType.InstructionShieldBash2, "id_shieldbash2"),
                new DroidInstructionRecipe(RecipeType.InstructionShieldWall1, "id_shieldwall1"),
                new DroidInstructionRecipe(RecipeType.InstructionShielding2, "id_shielding2"),
                new DroidInstructionRecipe(RecipeType.InstructionSignalJammer, "id_sigjammer"),
                new DroidInstructionRecipe(RecipeType.InstructionSlam2, "id_staff_slam2"),
                new DroidInstructionRecipe(RecipeType.InstructionSoulBurst, "id_soulburst"),
                new DroidInstructionRecipe(RecipeType.InstructionSoulStrike2, "id_soulstrike2"),
                new DroidInstructionRecipe(RecipeType.InstructionSpinningWhirl1, "id_spinwhir1"),
                new DroidInstructionRecipe(RecipeType.InstructionTwinGuardStance, "id_twinguarstan"),
                new DroidInstructionRecipe(RecipeType.InstructionSuppressingShot2, "id_suppr_shot2"),
                new DroidInstructionRecipe(RecipeType.InstructionSuppressiveLine1, "id_suppr_line1"),
                new DroidInstructionRecipe(RecipeType.InstructionSweepingFlank1, "id_sweeflan1"),
                new DroidInstructionRecipe(RecipeType.InstructionSweepingGuard, "id_sweeguar"),
                new DroidInstructionRecipe(RecipeType.InstructionTreatmentKit2, "id_treatkit2"),
                new DroidInstructionRecipe(RecipeType.InstructionTwinRupture1, "id_twinrupture1"),
                new DroidInstructionRecipe(RecipeType.InstructionVeiledStrike2, "id_veiledstrike2"),
                new DroidInstructionRecipe(RecipeType.InstructionVigorThrust2, "id_vigorthrust2"),
                new DroidInstructionRecipe(RecipeType.InstructionVirulentBlade1, "id_virublad1"),
                new DroidInstructionRecipe(RecipeType.InstructionVolatileCompound1, "id_volacomp1"),
                new DroidInstructionRecipe(RecipeType.InstructionWristRocket1, "id_wristrck1"));
        }

        private void Tier3()
        {
            CreateTier(30, "citrine", "elec_good", "ionite",
                new DroidInstructionRecipe(RecipeType.InstructionAdhesiveGrenade1, "id_adhgren1"),
                new DroidInstructionRecipe(RecipeType.InstructionAimedShot3, "id_aimedshot3"),
                new DroidInstructionRecipe(RecipeType.InstructionAssassinsStance, "id_assastan"),
                new DroidInstructionRecipe(RecipeType.InstructionBastionStance, "id_baststan"),
                new DroidInstructionRecipe(RecipeType.InstructionBerserkerStance, "id_bersstan"),
                new DroidInstructionRecipe(RecipeType.InstructionCrossCut3, "id_cross_cut3"),
                new DroidInstructionRecipe(RecipeType.InstructionCrusherStance, "id_crusstan"),
                new DroidInstructionRecipe(RecipeType.InstructionCycloneStance, "id_cyclstan"),
                new DroidInstructionRecipe(RecipeType.InstructionDefensiveStance, "id_defestan"),
                new DroidInstructionRecipe(RecipeType.InstructionDisablingStrike3, "id_disastri3"),
                new DroidInstructionRecipe(RecipeType.InstructionDisarmingShot3, "id_disashot3"),
                new DroidInstructionRecipe(RecipeType.InstructionExplosiveToss3, "id_expltoss3"),
                new DroidInstructionRecipe(RecipeType.InstructionFlamethrower2, "id_flamethrow2"),
                new DroidInstructionRecipe(RecipeType.InstructionFlurryStance, "id_flurrystance"),
                new DroidInstructionRecipe(RecipeType.InstructionFocusStim1, "id_focusstim1"),
                new DroidInstructionRecipe(RecipeType.InstructionGamblerStance, "id_gambstan"),
                new DroidInstructionRecipe(RecipeType.InstructionHookingStrike3, "id_hookstri3"),
                new DroidInstructionRecipe(RecipeType.InstructionIncendiaryField2, "id_incfield2"),
                new DroidInstructionRecipe(RecipeType.InstructionInfusion1, "id_infusion1"),
                new DroidInstructionRecipe(RecipeType.InstructionIonGrenade2, "id_iongren2"),
                new DroidInstructionRecipe(RecipeType.InstructionLaceratingTwinCut3, "id_lacetwincut3"),
                new DroidInstructionRecipe(RecipeType.InstructionLaceratorStance, "id_lacestan"),
                new DroidInstructionRecipe(RecipeType.InstructionLineBreaker3, "id_linebreaker3"),
                new DroidInstructionRecipe(RecipeType.InstructionMedKit3, "id_medkit3"),
                new DroidInstructionRecipe(RecipeType.InstructionOrdnanceStance, "id_ordnstan"),
                new DroidInstructionRecipe(RecipeType.InstructionPathogenStrike3, "id_pathstri3"),
                new DroidInstructionRecipe(RecipeType.InstructionPerceptiveStance, "id_percstan"),
                new DroidInstructionRecipe(RecipeType.InstructionPiercingToss3, "id_piercingtoss3"),
                new DroidInstructionRecipe(RecipeType.InstructionPowerCell2, "id_powercell2"),
                new DroidInstructionRecipe(RecipeType.InstructionQuickDraw3, "id_quick_draw3"),
                new DroidInstructionRecipe(RecipeType.InstructionRampart, "id_rampart"),
                new DroidInstructionRecipe(RecipeType.InstructionRemoteCharge2, "id_remcharge2"),
                new DroidInstructionRecipe(RecipeType.InstructionRiotBlade3, "id_riotblade3"),
                new DroidInstructionRecipe(RecipeType.InstructionScrapperStance, "id_scrastan"),
                new DroidInstructionRecipe(RecipeType.InstructionSentinelStance, "id_sentstan"),
                new DroidInstructionRecipe(RecipeType.InstructionShadowflowStance, "id_shadstan"),
                new DroidInstructionRecipe(RecipeType.InstructionShieldBash3, "id_shieldbash3"),
                new DroidInstructionRecipe(RecipeType.InstructionShockBeacon1, "id_shockbeac1"),
                new DroidInstructionRecipe(RecipeType.InstructionSkirmisherStance, "id_skirstan"),
                new DroidInstructionRecipe(RecipeType.InstructionSlam3, "id_staff_slam3"),
                new DroidInstructionRecipe(RecipeType.InstructionSniperStance, "id_sniperstance"),
                new DroidInstructionRecipe(RecipeType.InstructionSonicBurst2, "id_sonicburst2"),
                new DroidInstructionRecipe(RecipeType.InstructionSoulDevourer, "id_souldevourer"),
                new DroidInstructionRecipe(RecipeType.InstructionSoulStrike3, "id_soulstrike3"),
                new DroidInstructionRecipe(RecipeType.InstructionSuppressingShot3, "id_suppr_shot3"),
                new DroidInstructionRecipe(RecipeType.InstructionSuppressionStance, "id_suppr_stance"),
                new DroidInstructionRecipe(RecipeType.InstructionVeiledStrike3, "id_veiledstrike3"),
                new DroidInstructionRecipe(RecipeType.InstructionVigorStance, "id_vigorstance"),
                new DroidInstructionRecipe(RecipeType.InstructionVigorThrust3, "id_vigorthrust3"),
                new DroidInstructionRecipe(RecipeType.InstructionWhirlingGuard, "id_whirguar"),
                new DroidInstructionRecipe(RecipeType.InstructionWristRocket2, "id_wristrck2"));
        }

        private void Tier4()
        {
            CreateTier(40, "ruby", "elec_imperfect", "katrium",
                new DroidInstructionRecipe(RecipeType.InstructionAdhesiveGrenade2, "id_adhgren2"),
                new DroidInstructionRecipe(RecipeType.InstructionAdrenalStim3, "id_adrenal3"),
                new DroidInstructionRecipe(RecipeType.InstructionArcProjector2, "id_arcproj2"),
                new DroidInstructionRecipe(RecipeType.InstructionBackstab2, "id_backstab_atk2"),
                new DroidInstructionRecipe(RecipeType.InstructionBladeVortex2, "id_bladevortex2"),
                new DroidInstructionRecipe(RecipeType.InstructionBlasterBeacon3, "id_blastbeac3"),
                new DroidInstructionRecipe(RecipeType.InstructionBlazingSpikes, "id_blazspik"),
                new DroidInstructionRecipe(RecipeType.InstructionClusterGrenade, "id_clustgren"),
                new DroidInstructionRecipe(RecipeType.InstructionConcussionGrenade2, "id_concgren2"),
                new DroidInstructionRecipe(RecipeType.InstructionConcussiveToss2, "id_conctoss2"),
                new DroidInstructionRecipe(RecipeType.InstructionCoveringStrike2, "id_covestri2"),
                new DroidInstructionRecipe(RecipeType.InstructionCoveringStrike3, "id_covestri3"),
                new DroidInstructionRecipe(RecipeType.InstructionCripplingShot2, "id_cripshot2"),
                new DroidInstructionRecipe(RecipeType.InstructionCripplingShot3, "id_cripshot3"),
                new DroidInstructionRecipe(RecipeType.InstructionCripplingSlice2, "id_cripslic2"),
                new DroidInstructionRecipe(RecipeType.InstructionCripplingSlice3, "id_cripslic3"),
                new DroidInstructionRecipe(RecipeType.InstructionCryoSprayer, "id_cryospray"),
                new DroidInstructionRecipe(RecipeType.InstructionDeflectorShield3, "id_defshield3"),
                new DroidInstructionRecipe(RecipeType.InstructionDisruptionField2, "id_disrfiel2"),
                new DroidInstructionRecipe(RecipeType.InstructionDisruptionPulse, "id_disrpulse"),
                new DroidInstructionRecipe(RecipeType.InstructionDoubleShot2, "id_doubleshot2"),
                new DroidInstructionRecipe(RecipeType.InstructionDoubleShot3, "id_doubleshot3"),
                new DroidInstructionRecipe(RecipeType.InstructionEarthshatter2, "id_earthshatter2"),
                new DroidInstructionRecipe(RecipeType.InstructionFanTheHammer2, "id_fanthehammer2"),
                new DroidInstructionRecipe(RecipeType.InstructionFlashToss2, "id_flashtoss2"),
                new DroidInstructionRecipe(RecipeType.InstructionFlashToss3, "id_flashtoss3"),
                new DroidInstructionRecipe(RecipeType.InstructionFortressStrike3, "id_fortstri3"),
                new DroidInstructionRecipe(RecipeType.InstructionFragGrenade3, "id_fraggren3"),
                new DroidInstructionRecipe(RecipeType.InstructionGroundQuake2, "id_groundquake2"),
                new DroidInstructionRecipe(RecipeType.InstructionGuardCounter3, "id_guardcounter3"),
                new DroidInstructionRecipe(RecipeType.InstructionHamperingBarrage2, "id_hampbarr2"),
                new DroidInstructionRecipe(RecipeType.InstructionHeadshot2, "id_headshot2"),
                new DroidInstructionRecipe(RecipeType.InstructionInterruptingShot2, "id_inteshot2"),
                new DroidInstructionRecipe(RecipeType.InstructionInterruptingShot3, "id_inteshot3"),
                new DroidInstructionRecipe(RecipeType.InstructionInterruptingSweep2, "id_inteswee2"),
                new DroidInstructionRecipe(RecipeType.InstructionInterruptionStrike2, "id_intestri2"),
                new DroidInstructionRecipe(RecipeType.InstructionInterruptionStrike3, "id_intestri3"),
                new DroidInstructionRecipe(RecipeType.InstructionIonLance2, "id_ionlance2"),
                new DroidInstructionRecipe(RecipeType.InstructionJointLock2, "id_jointlock2"),
                new DroidInstructionRecipe(RecipeType.InstructionJointLock3, "id_jointlock3"),
                new DroidInstructionRecipe(RecipeType.InstructionKoltoMist2, "id_koltomist2"),
                new DroidInstructionRecipe(RecipeType.InstructionLegSweep2, "id_leg_sweep2"),
                new DroidInstructionRecipe(RecipeType.InstructionLegSweep3, "id_leg_sweep3"),
                new DroidInstructionRecipe(RecipeType.InstructionMedKit4, "id_medkit4"),
                new DroidInstructionRecipe(RecipeType.InstructionPainSuppressant2, "id_painsupp2"),
                new DroidInstructionRecipe(RecipeType.InstructionPiercingRound2, "id_pierroun2"),
                new DroidInstructionRecipe(RecipeType.InstructionPiercingRound3, "id_pierroun3"),
                new DroidInstructionRecipe(RecipeType.InstructionPinningToss2, "id_pinningtoss2"),
                new DroidInstructionRecipe(RecipeType.InstructionPinningToss3, "id_pinningtoss3"),
                new DroidInstructionRecipe(RecipeType.InstructionPointBlankBurst2, "id_poinblanburs2"),
                new DroidInstructionRecipe(RecipeType.InstructionRailDart2, "id_raildart2"),
                new DroidInstructionRecipe(RecipeType.InstructionRendingStrike2, "id_rendstri2"),
                new DroidInstructionRecipe(RecipeType.InstructionResuscitation2, "id_resusc2"),
                new DroidInstructionRecipe(RecipeType.InstructionRibBreaker2, "id_ribbreaker2"),
                new DroidInstructionRecipe(RecipeType.InstructionRibBreaker3, "id_ribbreaker3"),
                new DroidInstructionRecipe(RecipeType.InstructionSavageCleave2, "id_savagecleave2"),
                new DroidInstructionRecipe(RecipeType.InstructionSavageCleave3, "id_savagecleave3"),
                new DroidInstructionRecipe(RecipeType.InstructionSerratedArc2, "id_serratedarc2"),
                new DroidInstructionRecipe(RecipeType.InstructionSerratedArc3, "id_serratedarc3"),
                new DroidInstructionRecipe(RecipeType.InstructionSeveringToss2, "id_severingtoss2"),
                new DroidInstructionRecipe(RecipeType.InstructionShelterCircle, "id_shelcirc"),
                new DroidInstructionRecipe(RecipeType.InstructionShieldWall2, "id_shieldwall2"),
                new DroidInstructionRecipe(RecipeType.InstructionShielding3, "id_shielding3"),
                new DroidInstructionRecipe(RecipeType.InstructionShockBeacon2, "id_shockbeac2"),
                new DroidInstructionRecipe(RecipeType.InstructionSoulStorm, "id_soulstorm"),
                new DroidInstructionRecipe(RecipeType.InstructionSpinningWhirl2, "id_spinwhir2"),
                new DroidInstructionRecipe(RecipeType.InstructionSpinningWhirl3, "id_spinwhir3"),
                new DroidInstructionRecipe(RecipeType.InstructionSuppressiveLine2, "id_suppr_line2"),
                new DroidInstructionRecipe(RecipeType.InstructionSweepingFlank2, "id_sweeflan2"),
                new DroidInstructionRecipe(RecipeType.InstructionSweepingFlank3, "id_sweeflan3"),
                new DroidInstructionRecipe(RecipeType.InstructionTwinIntercept, "id_twininte"),
                new DroidInstructionRecipe(RecipeType.InstructionTwinRupture2, "id_twinrupture2"),
                new DroidInstructionRecipe(RecipeType.InstructionVirulentBlade2, "id_virublad2"),
                new DroidInstructionRecipe(RecipeType.InstructionVirulentBlade3, "id_virublad3"),
                new DroidInstructionRecipe(RecipeType.InstructionVolatileCompound2, "id_volacomp2"));
        }

        private void Tier5()
        {
            CreateTier(50, "emerald", "elec_high", "zinsiam",
                new DroidInstructionRecipe(RecipeType.InstructionAbsoluteDefense, "id_absodefe"),
                new DroidInstructionRecipe(RecipeType.InstructionAdamantineGuard, "id_adamguar"),
                new DroidInstructionRecipe(RecipeType.InstructionAimedShot4, "id_aimedshot4"),
                new DroidInstructionRecipe(RecipeType.InstructionArcProjector3, "id_arcproj3"),
                new DroidInstructionRecipe(RecipeType.InstructionCripplingDefense, "id_cripdefe"),
                new DroidInstructionRecipe(RecipeType.InstructionCrossCut4, "id_cross_cut4"),
                new DroidInstructionRecipe(RecipeType.InstructionDeadMansHand, "id_deadmanshand"),
                new DroidInstructionRecipe(RecipeType.InstructionDisablingStrike4, "id_disastri4"),
                new DroidInstructionRecipe(RecipeType.InstructionDisarmingShot4, "id_disashot4"),
                new DroidInstructionRecipe(RecipeType.InstructionEmergencyBunker, "id_emgbunker"),
                new DroidInstructionRecipe(RecipeType.InstructionEmergencyCocktail, "id_emgcocktail"),
                new DroidInstructionRecipe(RecipeType.InstructionEmergencyTriage, "id_emgtriage"),
                new DroidInstructionRecipe(RecipeType.InstructionEscapeArtist, "id_escapeartist"),
                new DroidInstructionRecipe(RecipeType.InstructionExplosiveToss4, "id_expltoss4"),
                new DroidInstructionRecipe(RecipeType.InstructionFlamethrower3, "id_flamethrow3"),
                new DroidInstructionRecipe(RecipeType.InstructionFocusStim2, "id_focusstim2"),
                new DroidInstructionRecipe(RecipeType.InstructionForcebane, "id_forcebane"),
                new DroidInstructionRecipe(RecipeType.InstructionGroupDeflector, "id_groupdef"),
                new DroidInstructionRecipe(RecipeType.InstructionHookingStrike4, "id_hookstri4"),
                new DroidInstructionRecipe(RecipeType.InstructionIncendiaryField3, "id_incfield3"),
                new DroidInstructionRecipe(RecipeType.InstructionInfusion2, "id_infusion2"),
                new DroidInstructionRecipe(RecipeType.InstructionInvincible, "id_invincible"),
                new DroidInstructionRecipe(RecipeType.InstructionIonLance3, "id_ionlance3"),
                new DroidInstructionRecipe(RecipeType.InstructionIronWallStance, "id_ironwallstan"),
                new DroidInstructionRecipe(RecipeType.InstructionKillBox, "id_killbox"),
                new DroidInstructionRecipe(RecipeType.InstructionKillzoneBeacon, "id_killbeacon"),
                new DroidInstructionRecipe(RecipeType.InstructionLaceratingTwinCut4, "id_lacetwincut4"),
                new DroidInstructionRecipe(RecipeType.InstructionLastWord, "id_lastword"),
                new DroidInstructionRecipe(RecipeType.InstructionLineBreaker4, "id_linebreaker4"),
                new DroidInstructionRecipe(RecipeType.InstructionOneShot, "id_oneshot"),
                new DroidInstructionRecipe(RecipeType.InstructionOverloadBarrage, "id_overbarrage"),
                new DroidInstructionRecipe(RecipeType.InstructionPathogenStrike4, "id_pathstri4"),
                new DroidInstructionRecipe(RecipeType.InstructionPerfectFlurry, "id_perfflur"),
                new DroidInstructionRecipe(RecipeType.InstructionPiercingToss4, "id_piercingtoss4"),
                new DroidInstructionRecipe(RecipeType.InstructionPowerCell3, "id_powercell3"),
                new DroidInstructionRecipe(RecipeType.InstructionQuickDraw4, "id_quick_draw4"),
                new DroidInstructionRecipe(RecipeType.InstructionRailDart3, "id_raildart3"),
                new DroidInstructionRecipe(RecipeType.InstructionRainOfSteel, "id_rainofsteel"),
                new DroidInstructionRecipe(RecipeType.InstructionRedBloom, "id_redbloom"),
                new DroidInstructionRecipe(RecipeType.InstructionRiotBlade4, "id_riotblade4"),
                new DroidInstructionRecipe(RecipeType.InstructionScrapheapLockdown, "id_scralock"),
                new DroidInstructionRecipe(RecipeType.InstructionShieldBash4, "id_shieldbash4"),
                new DroidInstructionRecipe(RecipeType.InstructionSlam4, "id_staff_slam4"),
                new DroidInstructionRecipe(RecipeType.InstructionSonicBurst3, "id_sonicburst3"),
                new DroidInstructionRecipe(RecipeType.InstructionSuppressingShot4, "id_suppr_shot4"),
                new DroidInstructionRecipe(RecipeType.InstructionTempestBloom, "id_tempestbloom"),
                new DroidInstructionRecipe(RecipeType.InstructionThermalDetonator, "id_thermdeton"),
                new DroidInstructionRecipe(RecipeType.InstructionTreatmentKit3, "id_treatkit3"),
                new DroidInstructionRecipe(RecipeType.InstructionUnmovingCenter, "id_unmocent"),
                new DroidInstructionRecipe(RecipeType.InstructionVeiledStrike4, "id_veiledstrike4"),
                new DroidInstructionRecipe(RecipeType.InstructionVigorThrust4, "id_vigorthrust4"),
                new DroidInstructionRecipe(RecipeType.InstructionViralCascade, "id_viralcascade"),
                new DroidInstructionRecipe(RecipeType.InstructionWorldbreaker, "id_worldbreaker"),
                new DroidInstructionRecipe(RecipeType.InstructionWristRocket3, "id_wristrck3"));
        }

        private void CreateTier(
            int level,
            string gemResref,
            string electronicResref,
            string metalResref,
            params DroidInstructionRecipe[] recipes)
        {
            foreach (var recipe in recipes)
            {
                _builder.Create(recipe.Type, SkillType.Engineering)
                    .Category(RecipeCategoryType.DroidInstruction)
                    .Resref(recipe.Resref)
                    .Level(level)
                    .Quantity(1)
                    .Component(gemResref, 1)
                    .Component(electronicResref, 2)
                    .Component(metalResref, 1);
            }
        }

        private readonly record struct DroidInstructionRecipe(RecipeType Type, string Resref);
    }
}
