{
 "title": "Server Performance",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Player Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Players",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "NWNX_Tracking.Activity",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tickrate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Ticks / second" }
   ],
   "targets": [
    {
     "alias": "$1",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "NWNX_Profiler.GameTickRate",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$1 (mean last 10)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "NWNX_Profiler.GameTickRate",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Time breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "$tag_EventName",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "EventName" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "NWNX_Profiler.TimingEvent",
     "select": [
      [
       { "params": [ "ns" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Object counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "AI Levels",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Count " }
   ],
   "targets": [
    {
     "alias": "$tag_Level",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "Level" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "NWNX_Profiler.AIUpdateListObjects",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queued Events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "none", "label": "Count " }
   ],
   "targets": [
    {
     "alias": "$1",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "NWNX_Profiler.AIQueuedEvents",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}