namespace SWLOR.Game.Server.NWScript.Enumerations
{
    public enum ActionType
    {
        MoveToPoint = 0,
        PickUpItem = 1,
        DropItem = 2,
        AttackObject = 3,
        CastSpell = 4,
        OpenDoor = 5,
        CloseDoor = 6,
        DialogObject = 7,
        DisableTrap = 8,
        RecoverTrap = 9,
        FlagTrap = 10,
        ExamineTrap = 11,
        SetTrap = 12,
        OpenLock = 13,
        Lock = 14,
        UseObject = 15,
        AnimalEmpathy = 16,
        Rest = 17,
        Taunt = 18,
        ItemCastSpell = 19,
        CounterSpell = 31,
        Heal = 33,
        Pickpocket = 34,
        Follow = 35,
        Wait = 36,
        Sit = 37,
        SmiteGood = 40,
        KiDamage = 41,
        RandomWalk = 43,
        Invalid = 65535,
    }
}
