namespace SWLOR.Game.Server.NWScript.Enumerations
{
    public enum Aoe
    {
        Per_Fogacid = 0,
        Per_Fogfire = 1,
        Per_Fogstink = 2,
        Per_Fogkill = 3,
        Per_Fogmind = 4,
        Per_Wallfire = 5,
        Per_Wallwind = 6,
        Per_Wallblade = 7,
        Per_Web = 8,
        Per_Entangle = 9,
        Per_Darkness = 11,
        Mob_Circevil = 12,
        Mob_Circgood = 13,
        Mob_Circlaw = 14,
        Mob_Circchaos = 15,
        Mob_Fear = 16,
        Mob_Blinding = 17,
        Mob_Unearthly = 18,
        Mob_Menace = 19,
        Mob_Unnatural = 20,
        Mob_Stun = 21,
        Mob_Protection = 22,
        Mob_Fire = 23,
        Mob_Frost = 24,
        Mob_Electrical = 25,
        Per_Fogghoul = 26,
        Mob_Tyrant_Fog = 27,
        Per_Storm = 28,
        Per_Invis_Sphere = 29,
        Mob_Silence = 30,
        Per_Delay_Blast_Fireball = 31,
        Per_Grease = 32,
        Per_Creeping_Doom = 33,
        Per_Evards_Black_Tentacles = 34,
        Mob_Invisibility_Purge = 35,
        Mob_Dragon_Fear = 36,
        Per_Custom_Aoe = 37,
        Per_Glyph_Of_Warding = 38,
        Per_Fog_Of_Bewilderment = 39,
        Per_Vine_Mine_Camouflage = 40,
        Mob_Tide_Of_Battle = 41,
        Per_Stonehold = 42,
        Per_Overmind = 43,
        Mob_Horrificappearance = 44,
        Mob_Troglodyte_Stench = 45,

    }
}
