namespace SWLOR.Game.Server.NWScript.Enumerations
{
    public enum TrapBaseType
    {
        Minor_Spike = 0,
        Average_Spike = 1,
        Strong_Spike = 2,
        Deadly_Spike = 3,
        Minor_Holy = 4,
        Average_Holy = 5,
        Strong_Holy = 6,
        Deadly_Holy = 7,
        Minor_Tangle = 8,
        Average_Tangle = 9,
        Strong_Tangle = 10,
        Deadly_Tangle = 11,
        Minor_Acid = 12,
        Average_Acid = 13,
        Strong_Acid = 14,
        Deadly_Acid = 15,
        Minor_Fire = 16,
        Average_Fire = 17,
        Strong_Fire = 18,
        Deadly_Fire = 19,
        Minor_Electrical = 20,
        Average_Electrical = 21,
        Strong_Electrical = 22,
        Deadly_Electrical = 23,
        Minor_Gas = 24,
        Average_Gas = 25,
        Strong_Gas = 26,
        Deadly_Gas = 27,
        Minor_Frost = 28,
        Average_Frost = 29,
        Strong_Frost = 30,
        Deadly_Frost = 31,
        Minor_Negative = 32,
        Average_Negative = 33,
        Strong_Negative = 34,
        Deadly_Negative = 35,
        Minor_Sonic = 36,
        Average_Sonic = 37,
        Strong_Sonic = 38,
        Deadly_Sonic = 39,
        Minor_Acid_Splash = 40,
        Average_Acid_Splash = 41,
        Strong_Acid_Splash = 42,
        Deadly_Acid_Splash = 43,
        Epic_Electrical = 44,
        Epic_Fire = 45,
        Epic_Frost = 46,
        Epic_Sonic = 47,

    }
}
