namespace SWLOR.Game.Server.NWScript.Enumerations
{
    public enum VoiceChat
    {
        Attack = 0,
        Battlecry1 = 1,
        Battlecry2 = 2,
        Battlecry3 = 3,
        Healme = 4,
        Help = 5,
        Enemies = 6,
        Flee = 7,
        Taunt = 8,
        Guardme = 9,
        Hold = 10,
        Gattack1 = 11,
        Gattack2 = 12,
        Gattack3 = 13,
        Pain1 = 14,
        Pain2 = 15,
        Pain3 = 16,
        Neardeath = 17,
        Death = 18,
        Poisoned = 19,
        Spellfailed = 20,
        Weaponsucks = 21,
        Followme = 22,
        Lookhere = 23,
        Group = 24,
        Moveover = 25,
        Picklock = 26,
        Search = 27,
        Hide = 28,
        Cando = 29,
        Cantdo = 30,
        Taskcomplete = 31,
        Encumbered = 32,
        Selected = 33,
        Hello = 34,
        Yes = 35,
        No = 36,
        Stop = 37,
        Rest = 38,
        Bored = 39,
        Goodbye = 40,
        Thanks = 41,
        Laugh = 42,
        Cuss = 43,
        Cheer = 44,
        Talktome = 45,
        Goodidea = 46,
        Badidea = 47,
        Threaten = 48,

    }
}
