using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SWLOR.Game.Server.Service.CraftService
{
    internal enum EnhancementSubType
    {
        Invalid = 0,
        DefensePhysical = 1,
        DefenseForce = 2,
        DefenseFire = 3,
        DefensePoison = 4,
        DefenseElectrical = 5,
        DefenseIce = 6,
        Evasion = 7,
        HP = 8,
        FP = 9,
        Stamina = 10,
        Vitality = 11,
        Social = 12,
        Willpower = 13,
        ControlSmithery = 14,
        CraftsmanshipSmithery = 15,
        
        DMGPhysical = 18,
        DMGForce = 19,
        DMGFire = 20,
        DMGPoison = 21,
        DMGElectrical = 22,
        DMGIce = 23,
        Might = 24,
        Perception = 25,
        Accuracy = 26,
        RecastReduction = 27,
        StructureBonus = 28,
        FoodBonusHPRegen = 29,
        FoodBonusFPRegen = 30,
        FoodBonusSTMRegen = 31,
        FoodBonusRestRegen = 32,
        FoodBonusXPBonus = 33,
        FoodBonusRecastReduction = 34,
        FoodBonusDuration = 35,
        FoodBonusHP = 36,
        FoodBonusFP = 37,
        FoodBonusSTM = 38,
        ControlEngineering = 39,
        CraftsmanshipEngineering = 40,
        ControlFabrication = 41,
        CraftsmanshipFabrication = 42,
        ControlAgriculture = 43,
        CraftsmanshipAgriculture = 44,
        ModuleBonus = 45,
        StarshipHull = 46,
        StarshipCapacitor = 47,
        StarshipShield = 48,
        StarshipShieldRechargeRate = 49,
        StarshipEMDamage = 50,
        StarshipThermalDamage = 51,
        StarshipExplosiveDamage = 52,
        StarshipAccuracy = 53,
        StarshipEvasion = 54,
        StarshipThermalDefense = 55,
        StarshipExplosiveDefense = 56,
        StarshipEMDefense = 57,
        Agility = 58,
        // 59 is free
        FoodBonusAttack = 60,
        FoodBonusAccuracy = 61,
        FoodBonusPhysicalDefense = 62,
        FoodBonusForceDefense = 63,
        FoodBonusPoisonDefense = 64,
        FoodBonusFireDefense = 65,
        FoodBonusIceDefense = 66,
        FoodBonusElectricalDefense = 67,
        FoodBonusEvasion = 68,
        FoodBonusControlSmithery = 69,
        FoodBonusCraftsmanshipSmithery = 70,
        FoodBonusControlFabrication = 71,
        FoodBonusCraftsmanshipFabrication = 72,
        FoodBonusControlEngineering = 73,
        FoodBonusCraftsmanshipEngineering = 74,
        FoodBonusControlAgriculture = 75,
        FoodBonusCraftsmanshipAgriculture = 76,
        FoodBonusMight = 77,
        FoodBonusPerception = 78,
        FoodBonusVitality = 79,
        FoodBonusWillpower = 80,
        FoodBonusAgility = 81,
        FoodBonusSocial = 82,
        Attack = 83,
        ForceAttack = 84,
        
        // 83-101 are free
        
        DroidAISlot = 102,
        DroidHP = 103,
        DroidSTM = 104,
        DroidMGT = 105,
        DroidPER = 106,
        DroidVIT = 107,
        DroidWIL = 108,
        DroidAGI = 109,
        DroidSOC = 110,
        Droid1Handed = 111,
        Droid2Handed = 112,
        DroidMartialArts = 113,
        DroidRanged = 114,


    }
}
