CREATE TABLE [dbo].[Areas] (
    [AreaID]               NVARCHAR (60)  NOT NULL,
    [Resref]               NVARCHAR (16)  NOT NULL,
    [Name]                 NVARCHAR (128) NOT NULL,
    [Tag]                  NVARCHAR (32)  NOT NULL,
    [ResourceSpawnTableID] INT            DEFAULT ((0)) NOT NULL,
    [Width]                INT            DEFAULT ((0)) NOT NULL,
    [Height]               INT            DEFAULT ((0)) NOT NULL,
    [IsBuildable]          BIT            DEFAULT ((0)) NOT NULL,
    [NorthwestOwner]       NVARCHAR (60)  NULL,
    [NortheastOwner]       NVARCHAR (60)  NULL,
    [SouthwestOwner]       NVARCHAR (60)  NULL,
    [SoutheastOwner]       NVARCHAR (60)  NULL,
    [IsActive]             BIT            DEFAULT ((0)) NOT NULL,
    [PurchasePrice]        INT            DEFAULT ((0)) NOT NULL,
    [DailyUpkeep]          INT            DEFAULT ((0)) NOT NULL,
    [Walkmesh]             NVARCHAR (MAX) NULL,
    [DateLastBaked]        DATETIME2 (7)  DEFAULT (getutcdate()) NOT NULL,
    [AutoSpawnResources]   BIT            DEFAULT ((0)) NOT NULL,
    [ResourceQuality]      INT            DEFAULT ((0)) NOT NULL,
    [NorthwestLootTableID] INT            NULL,
    [NortheastLootTableID] INT            NULL,
    [SouthwestLootTableID] INT            NULL,
    [SoutheastLootTableID] INT            NULL,
    PRIMARY KEY CLUSTERED ([AreaID] ASC),
    CONSTRAINT [FK_Areas_NortheastLootTableID] FOREIGN KEY ([NortheastLootTableID]) REFERENCES [dbo].[LootTables] ([LootTableID]),
    CONSTRAINT [FK_Areas_NortheastOwner] FOREIGN KEY ([NortheastOwner]) REFERENCES [dbo].[PlayerCharacters] ([PlayerID]),
    CONSTRAINT [FK_Areas_NorthwestLootTableID] FOREIGN KEY ([NorthwestLootTableID]) REFERENCES [dbo].[LootTables] ([LootTableID]),
    CONSTRAINT [FK_Areas_NorthwestOwner] FOREIGN KEY ([NorthwestOwner]) REFERENCES [dbo].[PlayerCharacters] ([PlayerID]),
    CONSTRAINT [FK_Areas_ResourceSpawnTableID] FOREIGN KEY ([ResourceSpawnTableID]) REFERENCES [dbo].[Spawns] ([SpawnID]),
    CONSTRAINT [FK_Areas_SoutheastLootTableID] FOREIGN KEY ([SoutheastLootTableID]) REFERENCES [dbo].[LootTables] ([LootTableID]),
    CONSTRAINT [FK_Areas_SoutheastOwner] FOREIGN KEY ([SoutheastOwner]) REFERENCES [dbo].[PlayerCharacters] ([PlayerID]),
    CONSTRAINT [FK_Areas_SouthwestLootTableID] FOREIGN KEY ([SouthwestLootTableID]) REFERENCES [dbo].[LootTables] ([LootTableID]),
    CONSTRAINT [FK_Areas_SouthwestOwner] FOREIGN KEY ([SouthwestOwner]) REFERENCES [dbo].[PlayerCharacters] ([PlayerID]),
    CONSTRAINT [UQ_Areas_Resref] UNIQUE NONCLUSTERED ([Resref] ASC)
);

