CREATE TABLE [dbo].[CraftBlueprints] (
    [CraftBlueprintID]         BIGINT        NOT NULL,
    [CraftCategoryID]          BIGINT        NOT NULL,
    [BaseLevel]                INT           NOT NULL,
    [ItemName]                 NVARCHAR (64) NOT NULL,
    [ItemResref]               NVARCHAR (16) NOT NULL,
    [Quantity]                 INT           NOT NULL,
    [SkillID]                  INT           NOT NULL,
    [CraftDeviceID]            INT           NOT NULL,
    [PerkID]                   INT           NULL,
    [RequiredPerkLevel]        INT           CONSTRAINT [DF__CraftBlue__Requi__6166761E] DEFAULT ((0)) NOT NULL,
    [IsActive]                 BIT           CONSTRAINT [DF__CraftBlue__IsAct__625A9A57] DEFAULT ((0)) NOT NULL,
    [MainComponentTypeID]      INT           DEFAULT ((0)) NOT NULL,
    [MainMinimum]              INT           DEFAULT ((0)) NOT NULL,
    [SecondaryComponentTypeID] INT           DEFAULT ((0)) NOT NULL,
    [SecondaryMinimum]         INT           DEFAULT ((0)) NOT NULL,
    [TertiaryComponentTypeID]  INT           DEFAULT ((0)) NOT NULL,
    [TertiaryMinimum]          INT           DEFAULT ((0)) NOT NULL,
    [EnhancementSlots]         INT           DEFAULT ((0)) NOT NULL,
    [MainMaximum]              INT           DEFAULT ((0)) NOT NULL,
    [SecondaryMaximum]         INT           DEFAULT ((0)) NOT NULL,
    [TertiaryMaximum]          INT           DEFAULT ((0)) NOT NULL,
    [BaseStructureID]          INT           NULL,
    CONSTRAINT [PK__CraftBlu__DE6FED170EBF2383] PRIMARY KEY CLUSTERED ([CraftBlueprintID] ASC),
    FOREIGN KEY ([BaseStructureID]) REFERENCES [dbo].[BaseStructures] ([BaseStructureID]),
    CONSTRAINT [fk_CraftBlueprints_CraftCategoryID] FOREIGN KEY ([CraftCategoryID]) REFERENCES [dbo].[CraftBlueprintCategories] ([CraftBlueprintCategoryID]),
    CONSTRAINT [FK_CraftBlueprints_CraftDeviceID] FOREIGN KEY ([CraftDeviceID]) REFERENCES [dbo].[CraftDevices] ([CraftDeviceID]),
    CONSTRAINT [fk_CraftBlueprints_MainComponentTypeID] FOREIGN KEY ([MainComponentTypeID]) REFERENCES [dbo].[ComponentTypes] ([ComponentTypeID]),
    CONSTRAINT [FK_CraftBlueprints_PerkID] FOREIGN KEY ([PerkID]) REFERENCES [dbo].[Perks] ([PerkID]),
    CONSTRAINT [fk_CraftBlueprints_SecondaryComponentTypeID] FOREIGN KEY ([SecondaryComponentTypeID]) REFERENCES [dbo].[ComponentTypes] ([ComponentTypeID]),
    CONSTRAINT [FK_CraftBlueprints_SkillID] FOREIGN KEY ([SkillID]) REFERENCES [dbo].[Skills] ([SkillID]),
    CONSTRAINT [fk_CraftBlueprints_TertiaryComponentTypeID] FOREIGN KEY ([TertiaryComponentTypeID]) REFERENCES [dbo].[ComponentTypes] ([ComponentTypeID])
);

