CREATE TABLE [dbo].[PlayerCharacters] (
    [PlayerID]                          NVARCHAR (60)  NOT NULL,
    [CharacterName]                     NVARCHAR (MAX) NULL,
    [HitPoints]                         INT            NOT NULL,
    [LocationAreaResref]                NVARCHAR (16)  NULL,
    [LocationX]                         FLOAT (53)     NOT NULL,
    [LocationY]                         FLOAT (53)     NOT NULL,
    [LocationZ]                         FLOAT (53)     NOT NULL,
    [LocationOrientation]               FLOAT (53)     NOT NULL,
    [CreateTimestamp]                   DATETIME2 (0)  CONSTRAINT [df_PlayerCharacters_CreateTimestamp] DEFAULT (getutcdate()) NOT NULL,
    [UnallocatedSP]                     INT            NOT NULL,
    [HPRegenerationAmount]              INT            NOT NULL,
    [RegenerationTick]                  INT            NOT NULL,
    [RegenerationRate]                  INT            NOT NULL,
    [VersionNumber]                     INT            NOT NULL,
    [MaxFP]                             INT            CONSTRAINT [DF__PlayerCha__MaxMa__1B9317B3] DEFAULT ((0)) NOT NULL,
    [CurrentFP]                         INT            CONSTRAINT [DF__PlayerCha__Curre__1C873BEC] DEFAULT ((0)) NOT NULL,
    [CurrentFPTick]                     INT            CONSTRAINT [DF__PlayerCha__Curre__1D7B6025] DEFAULT ((0)) NOT NULL,
    [RespawnAreaResref]                 NVARCHAR (16)  CONSTRAINT [DF__PlayerCha__Respa__1F63A897] DEFAULT ('') NULL,
    [RespawnLocationX]                  FLOAT (53)     CONSTRAINT [DF__PlayerCha__Respa__2057CCD0] DEFAULT ((0.0)) NOT NULL,
    [RespawnLocationY]                  FLOAT (53)     CONSTRAINT [DF__PlayerCha__Respa__214BF109] DEFAULT ((0.0)) NOT NULL,
    [RespawnLocationZ]                  FLOAT (53)     CONSTRAINT [DF__PlayerCha__Respa__22401542] DEFAULT ((0.0)) NOT NULL,
    [RespawnLocationOrientation]        FLOAT (53)     CONSTRAINT [DF__PlayerCha__Respa__2334397B] DEFAULT ((0.0)) NOT NULL,
    [DateSanctuaryEnds]                 DATETIME2 (7)  CONSTRAINT [DF__PlayerCha__DateS__24285DB4] DEFAULT (dateadd(hour,(72),getutcdate())) NOT NULL,
    [IsSanctuaryOverrideEnabled]        BIT            CONSTRAINT [DF__PlayerCha__IsSan__251C81ED] DEFAULT ((0)) NOT NULL,
    [STRBase]                           INT            CONSTRAINT [DF__PlayerCha__STRBa__2610A626] DEFAULT ((0)) NOT NULL,
    [DEXBase]                           INT            CONSTRAINT [DF__PlayerCha__DEXBa__2704CA5F] DEFAULT ((0)) NOT NULL,
    [CONBase]                           INT            CONSTRAINT [DF__PlayerCha__CONBa__27F8EE98] DEFAULT ((0)) NOT NULL,
    [INTBase]                           INT            CONSTRAINT [DF__PlayerCha__INTBa__28ED12D1] DEFAULT ((0)) NOT NULL,
    [WISBase]                           INT            CONSTRAINT [DF__PlayerCha__WISBa__29E1370A] DEFAULT ((0)) NOT NULL,
    [CHABase]                           INT            CONSTRAINT [DF__PlayerCha__CHABa__2AD55B43] DEFAULT ((0)) NOT NULL,
    [TotalSPAcquired]                   INT            CONSTRAINT [DF__PlayerCha__Total__2BC97F7C] DEFAULT ((0)) NOT NULL,
    [DisplayHelmet]                     BIT            DEFAULT ((1)) NOT NULL,
    [PrimaryResidencePCBaseStructureID] INT            NULL,
    [DatePerkRefundAvailable]           DATETIME2 (7)  NULL,
    [AssociationID]                     INT            NOT NULL,
    [DisplayHolonet]                    BIT            DEFAULT ((1)) NOT NULL,
    [DisplayDiscord]                    BIT            DEFAULT ((1)) NOT NULL,
    [PrimaryResidencePCBaseID]          INT            NULL,
    CONSTRAINT [PK__PlayerCh__4A4E74A8046BDEBE] PRIMARY KEY CLUSTERED ([PlayerID] ASC),
    CONSTRAINT [FK_PlayerCharacters_AssociationID] FOREIGN KEY ([AssociationID]) REFERENCES [dbo].[Associations] ([AssociationID]),
    CONSTRAINT [FK_PlayerCharacters_PrimaryResidencePCBaseID] FOREIGN KEY ([PrimaryResidencePCBaseID]) REFERENCES [dbo].[PCBases] ([PCBaseID]),
    CONSTRAINT [FK_PlayerCharacters_PrimaryResidencePCBaseStructureID] FOREIGN KEY ([PrimaryResidencePCBaseStructureID]) REFERENCES [dbo].[PCBaseStructures] ([PCBaseStructureID])
);

