CREATE TABLE [dbo].[Quests] (
    [QuestID]                           INT            IDENTITY (1, 1) NOT NULL,
    [Name]                              NVARCHAR (100) NOT NULL,
    [JournalTag]                        NVARCHAR (32)  NOT NULL,
    [FameRegionID]                      INT            NOT NULL,
    [RequiredFameAmount]                INT            NOT NULL,
    [AllowRewardSelection]              BIT            CONSTRAINT [DF__Quests__AllowRew__2CBDA3B5] DEFAULT ((0)) NOT NULL,
    [RewardGold]                        INT            NOT NULL,
    [RewardKeyItemID]                   INT            NULL,
    [RewardFame]                        INT            NOT NULL,
    [IsRepeatable]                      BIT            CONSTRAINT [DF__Quests__IsRepeat__2DB1C7EE] DEFAULT ((0)) NOT NULL,
    [MapNoteTag]                        NVARCHAR (32)  NOT NULL,
    [StartKeyItemID]                    INT            NULL,
    [RemoveStartKeyItemAfterCompletion] BIT            CONSTRAINT [DF__Quests__RemoveSt__2EA5EC27] DEFAULT ((0)) NOT NULL,
    [OnAcceptRule]                      NVARCHAR (32)  DEFAULT ('') NOT NULL,
    [OnAdvanceRule]                     NVARCHAR (32)  DEFAULT ('') NOT NULL,
    [OnCompleteRule]                    NVARCHAR (32)  DEFAULT ('') NOT NULL,
    [OnKillTargetRule]                  NVARCHAR (32)  DEFAULT ('') NOT NULL,
    [OnAcceptArgs]                      NVARCHAR (256) DEFAULT ('') NOT NULL,
    [OnAdvanceArgs]                     NVARCHAR (256) DEFAULT ('') NOT NULL,
    [OnCompleteArgs]                    NVARCHAR (256) DEFAULT ('') NOT NULL,
    [OnKillTargetArgs]                  NVARCHAR (256) DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_Quests_QuestID] PRIMARY KEY CLUSTERED ([QuestID] ASC),
    CONSTRAINT [FK_Quests_FameRegionID] FOREIGN KEY ([FameRegionID]) REFERENCES [dbo].[FameRegions] ([FameRegionID]),
    CONSTRAINT [FK_Quests_RewardKeyItemID] FOREIGN KEY ([RewardKeyItemID]) REFERENCES [dbo].[KeyItems] ([KeyItemID]),
    CONSTRAINT [FK_Quests_TemporaryKeyItemID] FOREIGN KEY ([StartKeyItemID]) REFERENCES [dbo].[KeyItems] ([KeyItemID])
);

