using System.Collections.Generic;
using SWLOR.Game.Server.Service.SkillService;

namespace SWLOR.Game.Server.Service.MasteryService
{
    /// <summary>
    /// A single row of the initial mastery catalog seed, sourced from the design team's
    /// mastery-catalog.json export. Consumed by <see cref="Mastery.SeedCatalog"/>.
    /// </summary>
    public class MasteryCatalogSeedEntry
    {
        public string Name { get; }
        public MasteryCategoryType Category { get; }
        public string Description { get; }
        public MasteryRarityType Rarity { get; }
        public SkillType? AssociatedSkill { get; }

        public MasteryCatalogSeedEntry(
            string name,
            MasteryCategoryType category,
            string description,
            MasteryRarityType rarity,
            SkillType? associatedSkill)
        {
            Name = name;
            Category = category;
            Description = description;
            Rarity = rarity;
            AssociatedSkill = associatedSkill;
        }
    }

    /// <summary>
    /// Static seed data generated from mastery-catalog.json (99 entries). See
    /// <see cref="Mastery.SeedCatalog"/> for the idempotent insertion logic that consumes this list.
    /// </summary>
    public static class MasteryCatalogSeed
    {
        public static readonly IReadOnlyList<MasteryCatalogSeedEntry> Entries = new List<MasteryCatalogSeedEntry>
        {
            new MasteryCatalogSeedEntry("Chef", MasteryCategoryType.CraftAgriculture, "Mastering culinary arts, chefs prepare delicious meals using various ingredients, providing sustenance and buffs to allies", MasteryRarityType.Standard, SkillType.Agriculture),
            new MasteryCatalogSeedEntry("Industrial Farming", MasteryCategoryType.CraftAgriculture, "Experts in industrial farming optimize crop production, ensuring high yields and efficient cultivation of agricultural resources.", MasteryRarityType.Standard, SkillType.Agriculture),
            new MasteryCatalogSeedEntry("Xenobotany", MasteryCategoryType.CraftAgriculture, "Proficient in xenobotany, individuals study and cultivate exotic alien plants, harnessing their unique properties for medicinal, culinary, or industrial purposes.", MasteryRarityType.Standard, SkillType.Agriculture),
            new MasteryCatalogSeedEntry("Fishing", MasteryCategoryType.CraftAgriculture, "Skilled fishermen excel in catching aquatic creatures, providing a fresh food source and valuable resources from rivers, lakes, or oceans.", MasteryRarityType.Standard, SkillType.Agriculture),
            new MasteryCatalogSeedEntry("Endure Pain", MasteryCategoryType.Armor, "Those skilled in enduring pain can withstand physical punishment and resist discomfort, enabling them to endure prolonged combat situations or harsh environmental conditions.", MasteryRarityType.Standard, SkillType.Armor),
            new MasteryCatalogSeedEntry("EVA Operative", MasteryCategoryType.Armor, "Trained in extravehicular activity (EVA), operatives excel in operating outside spacecraft or stations, performing repairs, maintenance, or tactical maneuvers in the vacuum of space.", MasteryRarityType.Standard, SkillType.Armor),
            new MasteryCatalogSeedEntry("Power Armor Operation", MasteryCategoryType.Armor, "Proficient in power armor operation, individuals can effectively utilize advanced armored suits for enhanced protection, mobility, and combat capabilities in hazardous or hostile environments.", MasteryRarityType.Standard, SkillType.Armor),
            new MasteryCatalogSeedEntry("Beast Handler", MasteryCategoryType.BeastMastery, "Skilled in beast handling, individuals can train and care for a variety of creatures, fostering bonds and commanding them in combat or other tasks.", MasteryRarityType.Standard, SkillType.BeastMastery),
            new MasteryCatalogSeedEntry("Xenobiology", MasteryCategoryType.BeastMastery, "Proficient in xenobiology, individuals study and understand the biology and behavior of alien creatures, enabling them to interact with, manipulate and intuitively understand exotic life forms.", MasteryRarityType.Standard, SkillType.BeastMastery),
            new MasteryCatalogSeedEntry("Genetics", MasteryCategoryType.BeastMastery, "Experts in genetics possess knowledge of manipulating and breeding creatures to enhance desired traits or create new species, allowing for the creation of powerful and specialized beasts.", MasteryRarityType.Rare, SkillType.BeastMastery),
            new MasteryCatalogSeedEntry("Chemist", MasteryCategoryType.Devices, "Experts in chemistry, individuals proficient in this skill can create and manipulate various chemical compounds for a variety of purposes, including medicine, explosives, or enhancements.", MasteryRarityType.Standard, SkillType.Devices),
            new MasteryCatalogSeedEntry("Sapper", MasteryCategoryType.Devices, "Skilled in demolition and sabotage, individuals with this expertise can construct and disarm explosive devices, breach fortified structures, or disrupt enemy operations.", MasteryRarityType.Standard, SkillType.Devices),
            new MasteryCatalogSeedEntry("Shield Tech", MasteryCategoryType.Devices, "Masters of shield technology, individuals proficient in this skill can design, operate, and maintain energy shields for personal protection or defensive fortifications, providing enhanced defense against enemy attacks.", MasteryRarityType.Standard, SkillType.Devices),
            new MasteryCatalogSeedEntry("Droidcraft", MasteryCategoryType.CraftEngineering, "Skilled in droidcraft, individuals can construct, repair, and modify droids of various types, ranging from protocol droids to combat models, enhancing their functionality and performance.", MasteryRarityType.Standard, SkillType.Engineering),
            new MasteryCatalogSeedEntry("Shipwright", MasteryCategoryType.CraftEngineering, "Masters of shipwright, individuals proficient in this skill can design, construct, and maintain spacecraft of all sizes, from starfighters to capital ships, ensuring optimal performance and functionality.", MasteryRarityType.Standard, SkillType.Engineering),
            new MasteryCatalogSeedEntry("Technician", MasteryCategoryType.CraftEngineering, "Proficient in general technical skills, technicians excel in repairing, maintaining, and troubleshooting a wide range of mechanical and electronic systems, from weapons and vehicles to communication devices and sensors.", MasteryRarityType.Standard, SkillType.Engineering),
            new MasteryCatalogSeedEntry("Warship Engineer", MasteryCategoryType.CraftEngineering, "Specialized in warship engineering, individuals with this expertise focus on the design, construction, and maintenance of military vessels, optimizing their performance for combat operations and strategic missions.", MasteryRarityType.Standard, SkillType.Engineering),
            new MasteryCatalogSeedEntry("Architect", MasteryCategoryType.CraftFabrication, "Skilled in architecture, individuals proficient in this skill can design and plan the construction of buildings, structures, and facilities, considering both aesthetic and functional aspects to create efficient and visually appealing spaces.", MasteryRarityType.Standard, SkillType.Fabrication),
            new MasteryCatalogSeedEntry("City Planner", MasteryCategoryType.CraftFabrication, "Masters of city planning, individuals with this expertise can design and develop urban environments, managing infrastructure, zoning, and land use to create sustainable and livable cities for their inhabitants.", MasteryRarityType.Standard, SkillType.Fabrication),
            new MasteryCatalogSeedEntry("Interior Design", MasteryCategoryType.CraftFabrication, "Experts in interior design possess the ability to enhance the aesthetics and functionality of interior spaces, selecting furnishings, decorations, and layouts to create comfortable and visually pleasing environments tailored to specific needs and preferences.", MasteryRarityType.Standard, SkillType.Fabrication),
            new MasteryCatalogSeedEntry("Doctor", MasteryCategoryType.FirstAid, "Skilled in general medicine, doctors are trained to diagnose and treat a wide range of illnesses and injuries, providing medical care and expertise to promote health and well-being.", MasteryRarityType.Standard, SkillType.FirstAid),
            new MasteryCatalogSeedEntry("Field Medic", MasteryCategoryType.FirstAid, "Specializing in emergency medical care, field medics are trained to provide rapid treatment and stabilization of injuries in combat or other high-stress situations, often operating in challenging and hazardous environments.", MasteryRarityType.Standard, SkillType.FirstAid),
            new MasteryCatalogSeedEntry("Surgeon", MasteryCategoryType.FirstAid, "Masters of surgical techniques, surgeons possess advanced skills in performing complex surgical procedures to repair injuries, remove tumors, or transplant organs, often in high-pressure and life-threatening situations.", MasteryRarityType.Standard, SkillType.FirstAid),
            new MasteryCatalogSeedEntry("Cloning", MasteryCategoryType.FirstAid, "Experts in cloning technology, individuals with this expertise can manipulate genetic material to create clones of living organisms, providing opportunities for organ transplantation, genetic modification, or replication of valuable individuals for research or other purposes.", MasteryRarityType.Standard, SkillType.FirstAid),
            new MasteryCatalogSeedEntry("Battle Meditation", MasteryCategoryType.ForceUniversal, "A Force technique allowing individuals to influence the outcome of large-scale conflicts by bolstering allies' morale, coordination, and combat effectiveness, while sowing confusion and doubt among enemies.", MasteryRarityType.Standard, SkillType.Force),
            new MasteryCatalogSeedEntry("Concealment", MasteryCategoryType.ForceUniversal, "The ability to mask one's presence in the Force, rendering oneself undetectable to Force-sensitive beings and evading detection or scrutiny.", MasteryRarityType.Standard, SkillType.Force),
            new MasteryCatalogSeedEntry("Enhance Attribute", MasteryCategoryType.ForceUniversal, "A Force ability that temporarily boosts the user's physical attributes, such as strength, speed, or agility, allowing them to perform tasks at a higher level of proficiency.", MasteryRarityType.Standard, SkillType.Force),
            new MasteryCatalogSeedEntry("Instinctive Astrogation", MasteryCategoryType.ForceUniversal, "An intuitive and instinctual aptitude for navigating through hyperspace, enabling accurate and efficient travel across vast distances without the need for precise calculations.", MasteryRarityType.Standard, SkillType.Force),
            new MasteryCatalogSeedEntry("Mentalism", MasteryCategoryType.ForceUniversal, "The practice of influencing or perceiving the thoughts, emotions, and intentions of others through the power of the Force, allowing for persuasion, manipulation, and empathic understanding. Darker forms of mentalism allow one to control enemies, while lighter forms of it are more along the lines of suggestion and guidance. Practicing mentalism carelessly will quickly cause one to fall to the Dark Side.", MasteryRarityType.Standard, SkillType.Force),
            new MasteryCatalogSeedEntry("Sense", MasteryCategoryType.ForceUniversal, "Heightened sensory perception granted by the Force, providing awareness of one's surroundings. It can manifest in different ways, sometimes allowing a form of foresight that manifests as strong feelings conveyed to Sensitives through the Force regarding danger, among other things.", MasteryRarityType.Standard, SkillType.Force),
            new MasteryCatalogSeedEntry("Telekinesis", MasteryCategoryType.ForceUniversal, "The ability to manipulate objects and exert force using the power of the Force, allowing for the movement of physical objects through sheer mental focus. It can also involve the projection of raw telekinetic force.", MasteryRarityType.Standard, SkillType.Force),
            new MasteryCatalogSeedEntry("Tutaminis", MasteryCategoryType.ForceUniversal, "The skill of absorbing and dissipating energy, allowing Force-sensitive individuals to deflect blaster bolts, absorb impacts, and resist attacks.", MasteryRarityType.Standard, SkillType.Force),
            new MasteryCatalogSeedEntry("Precognition/Foresight", MasteryCategoryType.ForceUniversal, "A force power allowing the individual to sometimes get glimpses into future events, guiding premonitions or warnings. Battle Precognition was a variant of precognition that allowed one to sense and foretell the flows of the Force while engaged in battle.", MasteryRarityType.Standard, SkillType.Force),
            new MasteryCatalogSeedEntry("Alter Environment", MasteryCategoryType.ForceUniversal, "A Force power enabling individuals to manipulate the natural world around them, allowing one to influence the weather, or control things like fire, water, and wind. Only highly advanced practitioners can summon things like lightning with this, and only with considerable effort and even then not with much precision.", MasteryRarityType.Rare, SkillType.Force),
            new MasteryCatalogSeedEntry("Shatterpoint", MasteryCategoryType.ForceUniversal, "A rare and powerful ability to perceive weaknesses and vulnerabilities in objects, individuals, or events, allowing for strategic exploitation or manipulation. Lower ranks of Shatterpoint are limited to weaknesses in objects and people. On rare occasions a practitioner of Shatterpoint may discover non-physical shatterpoints, such as sensing that an individual is the shatterpoint of a particular battle or war.", MasteryRarityType.Rare, SkillType.Force),
            new MasteryCatalogSeedEntry("Sith Language", MasteryCategoryType.ForceUniversal, "Mastery of an ancient language associated with the Sith, allowing for communication and understanding of Sith texts, rituals, and lore. A cursed language, those who speak it or even understand it without having fallen to the Dark Side are often haunted by it.", MasteryRarityType.Rare, SkillType.Force),
            new MasteryCatalogSeedEntry("Healing", MasteryCategoryType.ForceLightSide, "A Force ability enabling individuals to accelerate the natural healing process, mend wounds, and alleviate pain or injury in themselves or others.", MasteryRarityType.Standard, SkillType.Force),
            new MasteryCatalogSeedEntry("Imbue Force", MasteryCategoryType.ForceLightSide, "The power to infuse objects and weapons with the Force, enhancing their capabilities or sometimes imbuing them with specific properties or abilities.", MasteryRarityType.Standard, SkillType.Force),
            new MasteryCatalogSeedEntry("Inner Tranquillity", MasteryCategoryType.ForceLightSide, "Achieving a state of inner peace and harmony through meditation and connection with the Force, granting clarity of mind, emotional balance, and resilience to external disturbances. A core trait of all light side users, those who embody this tranquility often surrender their own will to the Force, allowing themselves to become its instrument.", MasteryRarityType.Standard, SkillType.Force),
            new MasteryCatalogSeedEntry("Plant Surge", MasteryCategoryType.ForceLightSide, "Manipulation of plant life through the Force, enabling individuals to accelerate growth, control vegetation, or influence the health and vitality of plants.", MasteryRarityType.Standard, SkillType.Force),
            new MasteryCatalogSeedEntry("Purification", MasteryCategoryType.ForceLightSide, "A Force ability used for cleansing the Kyber crystals and objects tainted by the Dark Side of the Force. Force-Sensitive individuals can utilize this to restore balance by removing corruption, therefore restoring these items to their original state.", MasteryRarityType.Standard, SkillType.Force),
            new MasteryCatalogSeedEntry("Cloak", MasteryCategoryType.ForceLightSide, "A stealth-oriented Force ability that shrouds the user in an invisible cloak, rendering them undetectable to both visual and technological surveillance. By bending light and distorting perception, practitioners of Cloak can move unseen and evade detection. It's important to note that this does nothing to stop one from being detected through non-light based senses, such as smell, sound, or even just the Force.", MasteryRarityType.Rare, SkillType.Force),
            new MasteryCatalogSeedEntry("Light", MasteryCategoryType.ForceLightSide, "Force Light is a powerful manifestation of the light side of the Force, radiating pure energy and purity to dispel darkness and weaken the influence of the dark side. It comes at a risk, however, as extremely powerful dark forces can reflect this upon the user. It is also difficult to destroy darkness with it, but rather tends to weaken and suppress it.", MasteryRarityType.Rare, SkillType.Force),
            new MasteryCatalogSeedEntry("Clouding", MasteryCategoryType.ForceDarkSide, "A Force ability that allows users to cloak their presence in the Force and intentions, obscuring them from the perception of others. It creates a mental haze or fog, making it challenging for individuals to sense the user's thoughts, emotions, or location. This ability can be used defensively to evade detection or offensively to deceive opponents, creating confusion and uncertainty in their minds.", MasteryRarityType.Standard, SkillType.Force),
            new MasteryCatalogSeedEntry("Depths of Rage", MasteryCategoryType.ForceDarkSide, "A Force ability that let users to tap into their inner turmoil and anger, fueling their strength and aggression in combat. It grants increased power and resilience while in the throes of fury. However, the Dark Side always extracts a toll. By surrendering to your passions you lose a bit of yourself.", MasteryRarityType.Standard, SkillType.Force),
            new MasteryCatalogSeedEntry("Force Drain", MasteryCategoryType.ForceDarkSide, "A Force ability that allows users to siphon the life force from living beings, draining their energy to replenish their own strength or vitality.", MasteryRarityType.Standard, SkillType.Force),
            new MasteryCatalogSeedEntry("Lightning", MasteryCategoryType.ForceDarkSide, "An offensive power that enables users to conjure bolts of crackling energy, unleashing devastating attacks on enemies.", MasteryRarityType.Standard, SkillType.Force),
            new MasteryCatalogSeedEntry("Sith Alchemy", MasteryCategoryType.ForceDarkSide, "Sith Alchemy, rooted in the dark side of the Force, manipulates matter and energy to achieve malevolent ends, from crafting powerful artifacts to mutating life forms. Practitioners of Sith Alchemy harness its dark power to reshape reality and fulfill their sinister ambitions.", MasteryRarityType.Standard, SkillType.Force),
            new MasteryCatalogSeedEntry("Sith Sorcery", MasteryCategoryType.ForceDarkSide, "It is a dark and forbidden practice, tapping into the malevolent energies of the dark side of the Force to wield powerful and often destructive abilities. Through Sith Sorcery, practitioners can manipulate minds, conjure dark illusions, and unleash devastating curses upon their enemies.", MasteryRarityType.Standard, SkillType.Force),
            new MasteryCatalogSeedEntry("Mechu Deru", MasteryCategoryType.ForceDarkSide, "A specialized Force skill that grants users control over technology, enabling them to interface with machines, override security systems, or manipulate electronic devices with their mind by infusing them with the power of the Dark Side of the Force.", MasteryRarityType.Rare, SkillType.Force),
            new MasteryCatalogSeedEntry("Necromancy", MasteryCategoryType.ForceDarkSide, "A forbidden and macabre practice that delves into the realm of death and decay. Practitioners can animate corpses and control them for their own purposes.", MasteryRarityType.Rare, SkillType.Force),
            new MasteryCatalogSeedEntry("Foreman", MasteryCategoryType.Gathering, "This skill allows efficient management of resource operations. As a Foreman, one coordinates workers and maximizes resource yields in activities like mining or scavenging.", MasteryRarityType.Standard, SkillType.Gathering),
            new MasteryCatalogSeedEntry("Pathfinding and Prospecting", MasteryCategoryType.Gathering, "This skill enables individuals to navigate terrain and identify resources efficiently. Users can chart routes, find hidden paths, and locate valuable areas for mining or exploration.", MasteryRarityType.Standard, SkillType.Gathering),
            new MasteryCatalogSeedEntry("Demoralizing Presence", MasteryCategoryType.Leadership, "Individuals with this skill have a commanding aura that can sow doubt and weaken the resolve of their adversaries, reducing their effectiveness in combat or negotiations.", MasteryRarityType.Standard, SkillType.Leadership),
            new MasteryCatalogSeedEntry("Diplomacy", MasteryCategoryType.Leadership, "Masters of diplomacy excel in the art of negotiation and conflict resolution, using tact, persuasion, and compromise to achieve mutually beneficial agreements and maintain peaceful relations between factions or individuals.", MasteryRarityType.Standard, SkillType.Leadership),
            new MasteryCatalogSeedEntry("Inspiring Presence", MasteryCategoryType.Leadership, "Leaders with an inspiring presence possess charisma and confidence, motivating and uplifting their allies with their words and actions, boosting morale and fostering unity in challenging situations.", MasteryRarityType.Standard, SkillType.Leadership),
            new MasteryCatalogSeedEntry("Tactics & Strategy", MasteryCategoryType.Leadership, "Skilled in tactics and strategy, individuals proficient in this skill can analyze situations, formulate plans, and coordinate actions to achieve strategic objectives, whether in combat, business, or other endeavors.", MasteryRarityType.Standard, SkillType.Leadership),
            new MasteryCatalogSeedEntry("Echani Martial Arts", MasteryCategoryType.MartialArts, "Practitioners of Echani Martial Arts are trained in a fluid and precise combat style that emphasizes grace, agility, and counters. This martial art focuses on redirecting an opponent's energy and using their movements against them.", MasteryRarityType.Standard, null),
            new MasteryCatalogSeedEntry("Teras Kasi", MasteryCategoryType.MartialArts, "When facing Force-sensitive opponents, practitioners of Teras Kasi rely on their exceptional physical abilities and combat skills to level the playing field. By combining lightning-fast strikes, precise timing, and relentless aggression, they aim to exploit vulnerabilities and disrupt the flow of their opponents' Force abilities.", MasteryRarityType.Standard, null),
            new MasteryCatalogSeedEntry("Form I: Shii Cho", MasteryCategoryType.CombatLightsaber, "A basic and versatile form focusing on wide, sweeping strikes and basic defensive maneuvers, suitable for beginners and adaptable to various combat situations.", MasteryRarityType.Standard, SkillType.Lightsaber),
            new MasteryCatalogSeedEntry("Form II: Makashi", MasteryCategoryType.CombatLightsaber, "A refined and elegant form emphasizing precision strikes and fluid movements, designed for dueling and countering opponents' attacks with grace and finesse.", MasteryRarityType.Standard, SkillType.Lightsaber),
            new MasteryCatalogSeedEntry("Form III: Soresu", MasteryCategoryType.CombatLightsaber, "A defensive form centered on tight, efficient movements and deflections, offering unparalleled protection against blaster fire and lightsaber attacks, ideal for prolonged engagements and surviving against multiple opponents.", MasteryRarityType.Standard, SkillType.Lightsaber),
            new MasteryCatalogSeedEntry("Form IV: Ataru", MasteryCategoryType.CombatLightsaber, "An acrobatic and aggressive form characterized by fast-paced movements and powerful strikes, leveraging agility and momentum to overwhelm opponents with relentless assaults.", MasteryRarityType.Standard, SkillType.Lightsaber),
            new MasteryCatalogSeedEntry("Form V: Shien / Djem So", MasteryCategoryType.CombatLightsaber, "A balanced form blending offense and defense, incorporating both powerful strikes and effective blocking techniques, suitable for engaging single opponents or deflecting blaster fire in combat.", MasteryRarityType.Standard, SkillType.Lightsaber),
            new MasteryCatalogSeedEntry("Form VI: Niman", MasteryCategoryType.CombatLightsaber, "A well-rounded form combining elements of other forms, offering versatility and adaptability in combat, allowing practitioners to switch between offensive and defensive tactics as needed.", MasteryRarityType.Standard, SkillType.Lightsaber),
            new MasteryCatalogSeedEntry("Form VII: Juyo", MasteryCategoryType.CombatLightsaber, "A highly aggressive and unpredictable form focusing on raw power and ferocity, utilizing unorthodox techniques and unpredictable movements to confound and overwhelm opponents.", MasteryRarityType.Standard, SkillType.Lightsaber),
            new MasteryCatalogSeedEntry("Dun Moch", MasteryCategoryType.CombatLightsaber, "A psychological tactic involving taunts and insults aimed at undermining opponents' confidence and focus, exploiting emotional vulnerabilities to gain an advantage in combat.", MasteryRarityType.Standard, SkillType.Lightsaber),
            new MasteryCatalogSeedEntry("Jar'Kai", MasteryCategoryType.CombatLightsaber, "A dual-wielding technique allowing practitioners to wield two lightsabers simultaneously, doubling offensive capabilities and providing versatility in combat situations. It's most notably used by lightsaber wielders, though the style is adaptable to other weapons.", MasteryRarityType.Standard, SkillType.Lightsaber),
            new MasteryCatalogSeedEntry("Advanced Weapons", MasteryCategoryType.Piloting, "Mastery in advanced weapons equips pilots with the ability to effectively utilize cutting-edge weaponry, including missiles, torpedoes, and advanced energy weapons, maximizing damage output and precision in combat.", MasteryRarityType.Standard, SkillType.Piloting),
            new MasteryCatalogSeedEntry("Astrogation", MasteryCategoryType.Piloting, "Astrogation proficiency enables pilots to plot precise and efficient hyperspace routes, navigate complex star systems, and calculate jump coordinates with accuracy, ensuring safe and swift travel through space. Skilled astrogators are also highly knowledgeable on stellar phenomenon.", MasteryRarityType.Standard, SkillType.Piloting),
            new MasteryCatalogSeedEntry("Dogfighting", MasteryCategoryType.Piloting, "Skilled dogfighters excel in close-quarters aerial combat, employing evasive maneuvers, precise targeting, and tactical positioning to outmaneuver and outgun opponents in intense dogfights.", MasteryRarityType.Standard, SkillType.Piloting),
            new MasteryCatalogSeedEntry("Warship Operation", MasteryCategoryType.Piloting, "Proficiency in warship operation allows pilots to command and operate capital ships and other large vessels, coordinating fleet movements, managing ship systems, and directing crew members in battle or strategic engagements.", MasteryRarityType.Standard, SkillType.Piloting),
            new MasteryCatalogSeedEntry("Forgeworks Operation", MasteryCategoryType.CraftSmithing, "Mastery in forgeworks operation enables smiths to efficiently operate and manage forges, furnaces, and other metalworking equipment, facilitating the crafting and shaping of metal into various forms and structures.", MasteryRarityType.Standard, SkillType.Smithery),
            new MasteryCatalogSeedEntry("Beskar Smithing", MasteryCategoryType.CraftSmithing, "Mandalorian artisans craft armor and weaponry from beskar, a revered metal known for its strength and connection to Mandalorian culture. It is also known for its unique ability to withstand lightsaber strikes, making it highly sought after by warriors seeking superior protection in combat.", MasteryRarityType.Rare, SkillType.Smithery),
            new MasteryCatalogSeedEntry("Reconnaissance", MasteryCategoryType.General, "Proficiency in reconnaissance enables individuals to gather intelligence, scout terrain, and assess enemy movements with precision, providing critical information for strategic planning and tactical operations.", MasteryRarityType.Standard, SkillType.Espionage),
            new MasteryCatalogSeedEntry("Slicing", MasteryCategoryType.General, "Experts in slicing possess advanced hacking and computer infiltration skills, allowing them to access and manipulate electronic systems, override security protocols, or extract valuable data from secure networks.", MasteryRarityType.Standard, null),
            new MasteryCatalogSeedEntry("Stealth", MasteryCategoryType.General, "Mastery in stealth allows individuals to move silently and remain undetected, blending into their surroundings and evading detection by enemies or surveillance systems with ease.", MasteryRarityType.Standard, SkillType.Espionage),
            new MasteryCatalogSeedEntry("Training - Agility", MasteryCategoryType.General, "Training in agility focuses on improving flexibility, speed, and coordination, enhancing physical dexterity and maneuverability in combat or athletic pursuits.", MasteryRarityType.Standard, null),
            new MasteryCatalogSeedEntry("Training - Strength", MasteryCategoryType.General, "Training in strength focuses on building muscle mass and increasing physical power, improving raw strength and endurance for tasks requiring brute force or resilience.", MasteryRarityType.Standard, null),
            new MasteryCatalogSeedEntry("Assault", MasteryCategoryType.Ranged, "Aggressive and dynamic, assault specialists lead coordinated attacks, swiftly advancing on enemy positions to overwhelm them with relentless pressure. They excel in close-quarters combat, emphasizing mobility and adaptability to maintain an offensive presence on the battlefield.", MasteryRarityType.Standard, null),
            new MasteryCatalogSeedEntry("Gunslinger", MasteryCategoryType.Ranged, "Swift and accurate, gunslingers excel in close to mid-range combat, delivering deadly shots with precision and speed. They thrive in fast-paced engagements, dominating the battlefield with their expert marksmanship and agility.", MasteryRarityType.Standard, null),
            new MasteryCatalogSeedEntry("Heavy Weapons", MasteryCategoryType.Ranged, "These specialists excel in overwhelming enemies with sheer firepower, utilizing heavy firearms like machine guns and rocket launchers. Their approach emphasizes suppression and domination, providing crucial support in combat situations requiring overwhelming force.", MasteryRarityType.Standard, null),
            new MasteryCatalogSeedEntry("Katar", MasteryCategoryType.CombatWeapons, "Mastery in the katar allows for agile and precise close-quarters combat, emphasizing swift strikes and piercing attacks.", MasteryRarityType.Standard, SkillType.Katar),
            new MasteryCatalogSeedEntry("Pistol", MasteryCategoryType.CombatWeapons, "Proficiency with pistols enables accurate and rapid fire in mid-range combat, offering versatility and mobility in combat engagements.", MasteryRarityType.Standard, SkillType.Pistol),
            new MasteryCatalogSeedEntry("Polearm", MasteryCategoryType.CombatWeapons, "Skilled in the polearm, individuals wield long-handled weapons with reach and power, excelling in both offensive and defensive maneuvers.", MasteryRarityType.Standard, SkillType.Spear),
            new MasteryCatalogSeedEntry("Rifle", MasteryCategoryType.CombatWeapons, "Mastery in rifles allows for precise and powerful long-range attacks, providing superior accuracy and firepower on the battlefield.", MasteryRarityType.Standard, SkillType.Rifle),
            new MasteryCatalogSeedEntry("Shield", MasteryCategoryType.CombatWeapons, "Proficiency with shields provides enhanced defense and versatility in combat, offering protection from enemy attacks and enabling strategic maneuvers.", MasteryRarityType.Standard, null),
            new MasteryCatalogSeedEntry("Shuriken", MasteryCategoryType.CombatWeapons, "Mastery in shuriken allows for precise and deadly throwing techniques, offering silent and swift attacks in close to mid-range combat.", MasteryRarityType.Standard, SkillType.Throwing),
            new MasteryCatalogSeedEntry("Sniper Rifle", MasteryCategoryType.CombatWeapons, "Skilled in the sniper rifle, individuals deliver accurate and lethal shots from long distances, providing crucial support and reconnaissance capabilities on the battlefield.", MasteryRarityType.Standard, SkillType.Rifle),
            new MasteryCatalogSeedEntry("Staff", MasteryCategoryType.CombatWeapons, "Proficiency with the staff allows for versatile and fluid combat techniques, offering both offensive strikes and defensive maneuvers in close-quarters combat.", MasteryRarityType.Standard, SkillType.Staff),
            new MasteryCatalogSeedEntry("Twin Blade", MasteryCategoryType.CombatWeapons, "Mastery in the twin blade enables swift and deadly dual-wielding techniques, offering increased offensive capabilities and versatility in combat engagements.", MasteryRarityType.Standard, SkillType.TwinBlade),
            new MasteryCatalogSeedEntry("Vibroblade", MasteryCategoryType.CombatWeapons, "Skilled in the vibroblade, individuals wield melee weapons enhanced with vibrating blades, providing increased cutting power and penetration in close-quarters combat.", MasteryRarityType.Standard, SkillType.Vibroblade),
            new MasteryCatalogSeedEntry("Vibroblade - Finesse", MasteryCategoryType.CombatWeapons, "Agile and precise, finesse vibroblade fighters deliver swift, accurate strikes to exploit enemy weaknesses.", MasteryRarityType.Standard, SkillType.Vibroknife),
            new MasteryCatalogSeedEntry("Vibroblade - Heavy", MasteryCategoryType.CombatWeapons, "Powerful and forceful, heavy vibroblade combatants overpower opponents with devastating blows.", MasteryRarityType.Standard, SkillType.HeavyVibroblade),
            new MasteryCatalogSeedEntry("Nanotechnology", MasteryCategoryType.ForceUniversal, "Manipulation of matter at the molecular scale. Not available for play.", MasteryRarityType.OffLimit, SkillType.Force),
            new MasteryCatalogSeedEntry("Psychometry", MasteryCategoryType.ForceUniversal, "Reading the history of objects through the Force. Not available for play.", MasteryRarityType.OffLimit, SkillType.Force),
            new MasteryCatalogSeedEntry("Force Storm", MasteryCategoryType.ForceUniversal, "Conjuring destructive hyperspace wormholes. Not available for play.", MasteryRarityType.OffLimit, SkillType.Force),
            new MasteryCatalogSeedEntry("Sever Force", MasteryCategoryType.ForceUniversal, "Cutting a being off from the Force. Not available for play.", MasteryRarityType.OffLimit, SkillType.Force),
            new MasteryCatalogSeedEntry("Teleport", MasteryCategoryType.ForceUniversal, "Instantaneous relocation through the Force. Not available for play.", MasteryRarityType.OffLimit, SkillType.Force),
        };
    }
}
