// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System.Collections.Generic;
using SWLOR.Game.Server.Enumeration;
using SWLOR.Game.Server.Feature.QuestDefinition;
using SWLOR.Game.Server.Service.CombatService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.PerkDefinition
{
    public class LightsaberPerkDefinition: IPerkListDefinition
    {
        private readonly PerkBuilder _builder = new();

        public Dictionary<PerkType, PerkDetail> BuildPerks()
        {
            SeveringStrike();
            DeflectionTraining();
            SeveranceRiposte();
            LegSlash();
            SeveranceFlow();
            SurgeStrike();
            FocusedStance();
            BladeBlitz();
            Purify();
            SaberStorm();
            WardBond();
            GuardiansOath();
            ReactiveWard();
            GuardiansChallenge();
            DeflectivePresence();
            PunishingGuard();
            ImpenetrableGuard();
            GuardiansInfluence();
            OverwhelmingDefense();
            GuardianMaster();

            return _builder.Build();
        }

        private void SeveringStrike()
        {
            _builder.Create(PerkCategoryType.LightsaberDefense, PerkType.SeveringStrike)
                .Name("Severing Strike")

                .AddPerkLevel()
                .GrantsFeat(FeatType.SeveringStrike1)
                .Description("Deals weapon DMG + 8. Inflicts Sunder, reducing Defense and Force Defense by 10% for 30 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.Lightsaber, 2)
                .RequirementCharacterType(CharacterType.ForceSensitive)

                .AddPerkLevel()
                .GrantsFeat(FeatType.SeveringStrike2)
                .Description("Deals weapon DMG + 18. Inflicts Sunder, reducing Defense and Force Defense by 12% for 30 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.Lightsaber, 12)
                .RequirementCharacterType(CharacterType.ForceSensitive)

                .AddPerkLevel()
                .GrantsFeat(FeatType.SeveringStrike3)
                .Description("Deals weapon DMG + 28. Inflicts Sunder, reducing Defense and Force Defense by 15% for 30 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.Lightsaber, 28)
                .RequirementCharacterType(CharacterType.ForceSensitive)

                .AddPerkLevel()
                .GrantsFeat(FeatType.SeveringStrike4)
                .Description("Deals weapon DMG + 38. Inflicts Sunder, reducing Defense and Force Defense by 18% for 30 seconds.")
                .Price(5)
                .RequirementSkill(SkillType.Lightsaber, 40)
                .RequirementCharacterType(CharacterType.ForceSensitive);
        }

        private void DeflectionTraining()
        {
            _builder.Create(PerkCategoryType.LightsaberDefense, PerkType.DeflectionTraining)
                .Name("Deflection Training")

                .AddPerkLevel()
                .GrantsFeat(FeatType.DeflectionTrainingTrait)
                .Description("After you deflect an attack, your next hostile attack within 30 seconds gains +10% Critical Rate.")
                .IncreasesStat(StatType.DeflectionNextSkillAbilitySkillType, (int)SkillType.Lightsaber)
                .IncreasesStat(StatType.DeflectionNextSkillAbilityCriticalRatePercentAdjustment, 10)
                .IncreasesStat(StatType.DeflectionNextSkillAbilityCriticalRateWindowSeconds, 30)
                .Price(2)
                .RequirementSkill(SkillType.Lightsaber, 5)
                .RequirementCharacterType(CharacterType.ForceSensitive);
        }

        private void SeveranceRiposte()
        {
            _builder.Create(PerkCategoryType.LightsaberDefense, PerkType.SeveranceRiposte)
                .Name("Severance Riposte")

                .AddPerkLevel()
                .GrantsFeat(FeatType.SeveranceRiposteTrait)
                .Description("After you deflect an attack, your next hostile combat ability within 30 seconds deals +8 DMG.")
                .IncreasesStat(StatType.DeflectionNextSkillAbilitySkillType, (int)SkillType.Lightsaber)
                .IncreasesStat(StatType.DeflectionNextSkillAbilityDamageBonus, 8)
                .IncreasesStat(StatType.DeflectionNextSkillAbilityDamageBonusWindowSeconds, 30)
                .Price(2)
                .RequirementSkill(SkillType.Lightsaber, 8)
                .RequirementCharacterType(CharacterType.ForceSensitive)

                .AddPerkLevel()
                .Description("After you deflect an attack, your next hostile combat ability within 30 seconds deals +14 DMG.")
                .IncreasesStat(StatType.DeflectionNextSkillAbilitySkillType, (int)SkillType.Lightsaber)
                .IncreasesStat(StatType.DeflectionNextSkillAbilityDamageBonus, 14)
                .IncreasesStat(StatType.DeflectionNextSkillAbilityDamageBonusWindowSeconds, 30)
                .Price(4)
                .RequirementSkill(SkillType.Lightsaber, 22)
                .RequirementCharacterType(CharacterType.ForceSensitive)

                .AddPerkLevel()
                .Description("After you deflect an attack, your next hostile combat ability within 30 seconds deals +20 DMG.")
                .IncreasesStat(StatType.DeflectionNextSkillAbilitySkillType, (int)SkillType.Lightsaber)
                .IncreasesStat(StatType.DeflectionNextSkillAbilityDamageBonus, 20)
                .IncreasesStat(StatType.DeflectionNextSkillAbilityDamageBonusWindowSeconds, 30)
                .Price(4)
                .RequirementSkill(SkillType.Lightsaber, 45)
                .RequirementCharacterType(CharacterType.ForceSensitive);
        }

        private void LegSlash()
        {
            _builder.Create(PerkCategoryType.LightsaberDefense, PerkType.LegSlash)
                .Name("Leg Slash")

                .AddPerkLevel()
                .GrantsFeat(FeatType.LegSlash1)
                .Description("Deals weapon DMG + 12 and inflicts Disoriented, reducing Accuracy and Evasion by 10% for 30 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.Lightsaber, 10)
                .RequirementCharacterType(CharacterType.ForceSensitive)

                .AddPerkLevel()
                .GrantsFeat(FeatType.LegSlash2)
                .Description("Deals weapon DMG + 24 and inflicts Disoriented, reducing Accuracy and Evasion by 15% for 30 seconds.")
                .Price(4)
                .RequirementSkill(SkillType.Lightsaber, 30)
                .RequirementCharacterType(CharacterType.ForceSensitive)

                .AddPerkLevel()
                .GrantsFeat(FeatType.LegSlash3)
                .Description("Deals weapon DMG + 36 and inflicts Disoriented, reducing Accuracy and Evasion by 20% for 30 seconds.")
                .Price(4)
                .RequirementSkill(SkillType.Lightsaber, 38)
                .RequirementCharacterType(CharacterType.ForceSensitive);
        }

        private void SeveranceFlow()
        {
            _builder.Create(PerkCategoryType.LightsaberDefense, PerkType.SeveranceFlow)
                .Name("Severance Flow")

                .AddPerkLevel()
                .GrantsFeat(FeatType.SeveranceFlowTrait)
                .Description("After using a hostile Lightsaber ability, gain +6 Attack Deflection for 30 seconds and restore 2 FP when you deflect.")
                .IncreasesStat(StatType.AbilityUsedAttackDeflectionSkillType, (int)SkillType.Lightsaber)
                .IncreasesStat(StatType.AbilityUsedAttackDeflection, 6)
                .IncreasesStat(StatType.AbilityUsedAttackDeflectionDurationSeconds, 30)
                .IncreasesStat(StatType.AbilityUsedAttackDeflectionFPRestore, 2)
                .Price(4)
                .RequirementSkill(SkillType.Lightsaber, 15)
                .RequirementCharacterType(CharacterType.ForceSensitive);
        }

        private void SurgeStrike()
        {
            _builder.Create(PerkCategoryType.LightsaberDefense, PerkType.SurgeStrike)
                .Name("Surge Strike")

                .AddPerkLevel()
                .GrantsFeat(FeatType.SurgeStrike1)
                .Description("Deals weapon DMG + 16. If used within 30 seconds after you deflect an attack, also inflicts Force Disruption for 30 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.Lightsaber, 18)
                .RequirementCharacterType(CharacterType.ForceSensitive)

                .AddPerkLevel()
                .GrantsFeat(FeatType.SurgeStrike2)
                .Description("Deals weapon DMG + 30. If used within 30 seconds after you deflect an attack, also inflicts Force Disruption for 30 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.Lightsaber, 32)
                .RequirementCharacterType(CharacterType.ForceSensitive);
        }

        private void FocusedStance()
        {
            _builder.Create(PerkCategoryType.LightsaberDefense, PerkType.FocusedStance)
                .Name("Focused Stance")

                .AddPerkLevel()
                .GrantsFeat(FeatType.FocusedStance1)
                .Description("While active, attacks against Sundered targets gain +10% Accuracy and +8% Critical Rate, but area damage is reduced by 15%.")
                .Price(4)
                .RequirementSkill(SkillType.Lightsaber, 20)
                .RequirementCharacterType(CharacterType.ForceSensitive);
        }

        private void BladeBlitz()
        {
            _builder.Create(PerkCategoryType.LightsaberDefense, PerkType.BladeBlitz)
                .Name("Blade Blitz")

                .AddPerkLevel()
                .GrantsFeat(FeatType.BladeBlitzTrait)
                .Description("After landing a critical hit, your next auto-attack within 30 seconds is quickened to your fastest possible swing speed.")
                .IncreasesStat(StatType.CriticalNextAutoAttackNoDelayTriggerSkillType, (int)SkillType.Lightsaber)
                .IncreasesStat(StatType.CriticalNextAutoAttackNoDelaySkillType, (int)SkillType.Lightsaber)
                .IncreasesStat(StatType.CriticalNextAutoAttackNoDelayDurationSeconds, 30)
                .Price(4)
                .RequirementSkill(SkillType.Lightsaber, 25)
                .RequirementCharacterType(CharacterType.ForceSensitive);
        }

        private void Purify()
        {
            _builder.Create(PerkCategoryType.LightsaberDefense, PerkType.Purify)
                .Name("Purify")

                .AddPerkLevel()
                .GrantsFeat(FeatType.PurifyTrait)
                .Description("After using a hostile combat ability, remove one debuff from yourself. This can trigger once every 20 seconds.")
                .IncreasesStat(StatType.LightsaberOffensePurify, 1)
                .IncreasesStat(StatType.LightsaberOffensePurifyCooldownSeconds, 20)
                .Price(2)
                .RequirementSkill(SkillType.Lightsaber, 35)
                .RequirementCharacterType(CharacterType.ForceSensitive);
        }

        private void SaberStorm()
        {
            _builder.Create(PerkCategoryType.LightsaberDefense, PerkType.SaberStorm)
                .Name("Saber Storm")

                .AddPerkLevel()
                .GrantsFeat(FeatType.SaberStorm1)
                .Description("Deals weapon DMG + 45 to a single target. Sundered targets take +30 DMG and suffer Sunder for 45 seconds.")
                .Price(6)
                .RequirementSkill(SkillType.Lightsaber, 50)
                .RequirementCharacterType(CharacterType.ForceSensitive)
                .RequirementQuest(LightsaberCapstoneQuestDefinition.SaberStormMasteryQuestId);
        }

        private void WardBond()
        {
            _builder.Create(PerkCategoryType.LightsaberOffense, PerkType.WardBond)
                .Name("Ward Bond")

                .AddPerkLevel()
                .GrantsFeat(FeatType.WardBond1)
                .Description("Target ally becomes your ward for 45 seconds. They gain +6% Defense and Force Defense, and 30% of their incoming damage is shared to you while within 8m. Only one ward or guard link may protect a target.")
                .Price(2)
                .RequirementSkill(SkillType.Lightsaber, 2)
                .RequirementCharacterType(CharacterType.ForceSensitive)

                .AddPerkLevel()
                .GrantsFeat(FeatType.WardBond2)
                .Description("Target ally becomes your ward for 45 seconds. They gain +8% Defense and Force Defense, and 35% of their incoming damage is shared to you while within 8m. Only one ward or guard link may protect a target.")
                .Price(2)
                .RequirementSkill(SkillType.Lightsaber, 12)
                .RequirementCharacterType(CharacterType.ForceSensitive)

                .AddPerkLevel()
                .GrantsFeat(FeatType.WardBond3)
                .Description("Target ally becomes your ward for 45 seconds. They gain +10% Defense and Force Defense, and 40% of their incoming damage is shared to you while within 8m. Only one ward or guard link may protect a target.")
                .Price(3)
                .RequirementSkill(SkillType.Lightsaber, 28)
                .RequirementCharacterType(CharacterType.ForceSensitive)

                .AddPerkLevel()
                .GrantsFeat(FeatType.WardBond4)
                .Description("Target ally becomes your ward for 45 seconds. They gain +12% Defense and Force Defense, and 45% of their incoming damage is shared to you while within 8m. Only one ward or guard link may protect a target.")
                .Price(5)
                .RequirementSkill(SkillType.Lightsaber, 40)
                .RequirementCharacterType(CharacterType.ForceSensitive);
        }

        private void GuardiansOath()
        {
            _builder.Create(PerkCategoryType.LightsaberOffense, PerkType.GuardiansOath)
                .Name("Guardian's Oath")

                .AddPerkLevel()
                .GrantsFeat(FeatType.GuardiansOathTrait)
                .Description("You may maintain one ward at a time. While your ward is within 8m, you generate +15% Enmity and your ward gains +5% Accuracy.")
                .IncreasesStat(StatType.GuardEnmityPercentAdjustment, 15)
                .Price(2)
                .RequirementSkill(SkillType.Lightsaber, 5)
                .RequirementCharacterType(CharacterType.ForceSensitive);
        }

        private void ReactiveWard()
        {
            _builder.Create(PerkCategoryType.LightsaberOffense, PerkType.ReactiveWard)
                .Name("Reactive Ward")

                .AddPerkLevel()
                .GrantsFeat(FeatType.ReactiveWardTrait)
                .Description("After you deflect an attack, your ward gains +5% Guard for 30 seconds if they are within 8m.")
                .IncreasesStat(StatType.DeflectionNearbyAllyGuard, 5)
                .IncreasesStat(StatType.DeflectionNearbyAllyGuardDurationSeconds, 30)
                .Price(2)
                .RequirementSkill(SkillType.Lightsaber, 8)
                .RequirementCharacterType(CharacterType.ForceSensitive)

                .AddPerkLevel()
                .Description("After you deflect an attack, your ward gains +8% Guard for 30 seconds if they are within 8m.")
                .IncreasesStat(StatType.DeflectionNearbyAllyGuard, 8)
                .IncreasesStat(StatType.DeflectionNearbyAllyGuardDurationSeconds, 30)
                .Price(4)
                .RequirementSkill(SkillType.Lightsaber, 22)
                .RequirementCharacterType(CharacterType.ForceSensitive)

                .AddPerkLevel()
                .Description("After you deflect an attack, your ward gains +10% Guard for 30 seconds if they are within 8m.")
                .IncreasesStat(StatType.DeflectionNearbyAllyGuard, 10)
                .IncreasesStat(StatType.DeflectionNearbyAllyGuardDurationSeconds, 30)
                .Price(4)
                .RequirementSkill(SkillType.Lightsaber, 45)
                .RequirementCharacterType(CharacterType.ForceSensitive);
        }

        private void GuardiansChallenge()
        {
            _builder.Create(PerkCategoryType.LightsaberOffense, PerkType.GuardiansChallenge)
                .Name("Guardian's Challenge")

                .AddPerkLevel()
                .GrantsFeat(FeatType.GuardiansChallenge1)
                .Description("Deals weapon DMG + 12 to a target. If this target has hit your ward in the last 30 seconds, gain +20% Enmity toward it for 30 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.Lightsaber, 10)
                .RequirementCharacterType(CharacterType.ForceSensitive)

                .AddPerkLevel()
                .GrantsFeat(FeatType.GuardiansChallenge2)
                .Description("Deals weapon DMG + 24 to a target. If this target has hit your ward in the last 30 seconds, gain +30% Enmity toward it for 30 seconds.")
                .Price(4)
                .RequirementSkill(SkillType.Lightsaber, 30)
                .RequirementCharacterType(CharacterType.ForceSensitive)

                .AddPerkLevel()
                .GrantsFeat(FeatType.GuardiansChallenge3)
                .Description("Deals weapon DMG + 36 to a target. If this target has hit your ward in the last 30 seconds, gain +40% Enmity toward it for 30 seconds.")
                .Price(4)
                .RequirementSkill(SkillType.Lightsaber, 38)
                .RequirementCharacterType(CharacterType.ForceSensitive);
        }

        private void DeflectivePresence()
        {
            _builder.Create(PerkCategoryType.LightsaberOffense, PerkType.DeflectivePresence)
                .Name("Deflective Presence")

                .AddPerkLevel()
                .GrantsFeat(FeatType.DeflectivePresenceTrait)
                .Description("After using a Ward ability, gain +6 Attack Deflection for 30 seconds and restore 2 FP when you deflect.")
                .IncreasesStat(StatType.AbilityUsedPerkCategoryAttackDeflectionCategoryType, (int)PerkCategoryType.LightsaberOffense)
                .IncreasesStat(StatType.AbilityUsedPerkCategoryAttackDeflection, 6)
                .IncreasesStat(StatType.AbilityUsedPerkCategoryAttackDeflectionDurationSeconds, 30)
                .IncreasesStat(StatType.AbilityUsedPerkCategoryAttackDeflectionFPRestore, 2)
                .Price(4)
                .RequirementSkill(SkillType.Lightsaber, 15)
                .RequirementCharacterType(CharacterType.ForceSensitive);
        }

        private void PunishingGuard()
        {
            _builder.Create(PerkCategoryType.LightsaberOffense, PerkType.PunishingGuard)
                .Name("Punishing Guard")

                .AddPerkLevel()
                .GrantsFeat(FeatType.PunishingGuard1)
                .Description("Deals weapon DMG + 16. If the target attacked your ward in the last 30 seconds, also inflicts Dazed for 30 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.Lightsaber, 18)
                .RequirementCharacterType(CharacterType.ForceSensitive)

                .AddPerkLevel()
                .GrantsFeat(FeatType.PunishingGuard2)
                .Description("Deals weapon DMG + 30. If the target attacked your ward in the last 30 seconds, also inflicts Dazed for 30 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.Lightsaber, 32)
                .RequirementCharacterType(CharacterType.ForceSensitive);
        }

        private void ImpenetrableGuard()
        {
            _builder.Create(PerkCategoryType.LightsaberOffense, PerkType.ImpenetrableGuard)
                .Name("Impenetrable Guard")

                .AddPerkLevel()
                .GrantsFeat(FeatType.ImpenetrableGuard1)
                .Description("While active, your ward gains +5% Defense and Force Defense, and you generate +20% Enmity, but Attack and Force Attack are reduced by 20%.")
                .Price(4)
                .RequirementSkill(SkillType.Lightsaber, 20)
                .RequirementCharacterType(CharacterType.ForceSensitive);
        }

        private void GuardiansInfluence()
        {
            _builder.Create(PerkCategoryType.LightsaberOffense, PerkType.GuardiansInfluence)
                .Name("Guardian's Influence")

                .AddPerkLevel()
                .GrantsFeat(FeatType.GuardiansInfluenceTrait)
                .Description("Ward abilities grant you and your ward +10% Defense and Force Defense for 30 seconds while within 8m.")
                .IncreasesStat(StatType.WardAbilityDefensePercentAdjustment, 10)
                .IncreasesStat(StatType.WardAbilityForceDefensePercentAdjustment, 10)
                .IncreasesStat(StatType.WardAbilityDefenseDurationSeconds, 30)
                .IncreasesStat(StatType.WardAbilityDefenseCategoryId, (int)PerkCategoryType.LightsaberOffense)
                .Price(4)
                .RequirementSkill(SkillType.Lightsaber, 25)
                .RequirementCharacterType(CharacterType.ForceSensitive);
        }

        private void OverwhelmingDefense()
        {
            _builder.Create(PerkCategoryType.LightsaberOffense, PerkType.OverwhelmingDefense)
                .Name("Overwhelming Defense")

                .AddPerkLevel()
                .GrantsFeat(FeatType.OverwhelmingDefenseTrait)
                .Description("After your shared ward damage is triggered, your next Lightsaber hostile combat ability within 30 seconds deals +10 DMG.")
                .IncreasesStat(StatType.WardSharedDamageNextSkillAbilityDamageBonus, 10)
                .IncreasesStat(StatType.WardSharedDamageNextSkillAbilityWindowSeconds, 30)
                .Price(2)
                .RequirementSkill(SkillType.Lightsaber, 35)
                .RequirementCharacterType(CharacterType.ForceSensitive);
        }

        private void GuardianMaster()
        {
            _builder.Create(PerkCategoryType.LightsaberOffense, PerkType.GuardianMaster)
                .Name("Guardian Master")

                .AddPerkLevel()
                .GrantsFeat(FeatType.GuardianMaster1)
                .Description("Target ally becomes your ward for 45 seconds. They gain +15% Defense, +15% Force Defense, and +15% Guard, and 50% of their incoming damage is shared to you while within 8m. Only one ward or guard link may protect a target.")
                .Price(6)
                .RequirementSkill(SkillType.Lightsaber, 50)
                .RequirementCharacterType(CharacterType.ForceSensitive)
                .RequirementQuest(LightsaberCapstoneQuestDefinition.GuardianMasterMasteryQuestId);
        }

    }
}
