// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System.Collections.Generic;
using SWLOR.Game.Server.Enumeration;
using SWLOR.Game.Server.Feature.QuestDefinition;
using SWLOR.Game.Server.Service.CombatService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.PerkDefinition
{
    public class ThrowingPerkDefinition: IPerkListDefinition
    {
        private readonly PerkBuilder _builder = new();

        public Dictionary<PerkType, PerkDetail> BuildPerks()
        {
            ExplosiveToss();
            PayloadPouch();
            ShrapnelCasing();
            FlashToss();
            ClusterPouch();
            ConcussiveToss();
            OrdnanceStance();
            SaturationToss();
            BombardiersRhythm();
            RainOfSteel();
            PiercingToss();
            ReturningGrip();
            FlurryBleed();
            PinningToss();
            RicochetToss();
            SeveringToss();
            FlurryStance();
            DeepWound();
            BleedingTempo();
            PerfectFlurry();

            return _builder.Build();
        }

        private void ExplosiveToss()
        {
            _builder.Create(PerkCategoryType.ThrowingBombardier, PerkType.ExplosiveToss)
                .Name("Explosive Toss")

                .AddPerkLevel()
                .GrantsFeat(FeatType.ExplosiveToss1)
                .Description("Deals weapon DMG + 7 to enemies in a 5m-radius area at the target location and inflicts Burn for 30 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.Throwing, 2)

                .AddPerkLevel()
                .GrantsFeat(FeatType.ExplosiveToss2)
                .Description("Deals weapon DMG + 15 to enemies in a 5m-radius area at the target location and inflicts Burn for 30 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.Throwing, 12)

                .AddPerkLevel()
                .GrantsFeat(FeatType.ExplosiveToss3)
                .Description("Deals weapon DMG + 24 to enemies in a 5m-radius area at the target location and inflicts Burn for 30 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.Throwing, 28)

                .AddPerkLevel()
                .GrantsFeat(FeatType.ExplosiveToss4)
                .Description("Deals weapon DMG + 32 to enemies in a 5m-radius area at the target location and inflicts Burn for 30 seconds.")
                .Price(5)
                .RequirementSkill(SkillType.Throwing, 40);
        }

        private void PayloadPouch()
        {
            _builder.Create(PerkCategoryType.ThrowingBombardier, PerkType.PayloadPouch)
                .Name("Payload Pouch")

                .AddPerkLevel()
                .GrantsFeat(FeatType.PayloadPouchTrait)
                .Description("Thrown attacks have a 15% chance to deal +8 area DMG around the target.")
                .IncreasesStat(StatType.AutoAttackDamageBonusChance, 15)
                .IncreasesStat(StatType.AutoAttackDamageBonus, 8)
                .Price(2)
                .RequirementSkill(SkillType.Throwing, 5);
        }

        private void ShrapnelCasing()
        {
            _builder.Create(PerkCategoryType.ThrowingBombardier, PerkType.ShrapnelCasing)
                .Name("Shrapnel Casing")

                .AddPerkLevel()
                .GrantsFeat(FeatType.ShrapnelCasingTrait)
                .Description("Thrown area abilities inflict fragmentation for 3 physical damage every 3 seconds for 30 seconds.")
                .IncreasesStat(StatType.AreaAbilityFragmentationDamage, 3)
                .IncreasesStat(StatType.AreaAbilityFragmentationSkillType, (int)SkillType.Throwing)
                .IncreasesStat(StatType.AreaAbilityFragmentationPulseSeconds, 3)
                .IncreasesStat(StatType.AreaAbilityFragmentationDurationSeconds, 30)
                .Price(2)
                .RequirementSkill(SkillType.Throwing, 8)

                .AddPerkLevel()
                .Description("Thrown area abilities inflict fragmentation for 5 physical damage every 3 seconds for 30 seconds.")
                .IncreasesStat(StatType.AreaAbilityFragmentationDamage, 5)
                .IncreasesStat(StatType.AreaAbilityFragmentationSkillType, (int)SkillType.Throwing)
                .IncreasesStat(StatType.AreaAbilityFragmentationPulseSeconds, 3)
                .IncreasesStat(StatType.AreaAbilityFragmentationDurationSeconds, 30)
                .Price(4)
                .RequirementSkill(SkillType.Throwing, 22)

                .AddPerkLevel()
                .Description("Thrown area abilities inflict fragmentation for 7 physical damage every 3 seconds for 30 seconds.")
                .IncreasesStat(StatType.AreaAbilityFragmentationDamage, 7)
                .IncreasesStat(StatType.AreaAbilityFragmentationSkillType, (int)SkillType.Throwing)
                .IncreasesStat(StatType.AreaAbilityFragmentationPulseSeconds, 3)
                .IncreasesStat(StatType.AreaAbilityFragmentationDurationSeconds, 30)
                .Price(4)
                .RequirementSkill(SkillType.Throwing, 45);
        }

        private void FlashToss()
        {
            _builder.Create(PerkCategoryType.ThrowingBombardier, PerkType.FlashToss)
                .Name("Flash Toss")

                .AddPerkLevel()
                .GrantsFeat(FeatType.FlashToss1)
                .Description("Deals weapon DMG + 12 and inflicts Blind for 15 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.Throwing, 10)

                .AddPerkLevel()
                .GrantsFeat(FeatType.FlashToss2)
                .Description("Deals weapon DMG + 24 and inflicts Blind for 15 seconds.")
                .Price(4)
                .RequirementSkill(SkillType.Throwing, 30)

                .AddPerkLevel()
                .GrantsFeat(FeatType.FlashToss3)
                .Description("Deals weapon DMG + 36 and inflicts Blind for 15 seconds.")
                .Price(4)
                .RequirementSkill(SkillType.Throwing, 38);
        }

        private void ClusterPouch()
        {
            _builder.Create(PerkCategoryType.ThrowingBombardier, PerkType.ClusterPouch)
                .Name("Cluster Pouch")

                .AddPerkLevel()
                .GrantsFeat(FeatType.ClusterPouchTrait)
                .Description("Area thrown abilities hit one additional enemy within 5m for +10 DMG.")
                .IncreasesStat(StatType.ThrowingBombardierClusterStormDamageBonus, 10)
                .IncreasesStat(StatType.ThrowingBombardierClusterStormMaximumTargets, 1)
                .Price(4)
                .RequirementSkill(SkillType.Throwing, 15);
        }

        private void ConcussiveToss()
        {
            _builder.Create(PerkCategoryType.ThrowingBombardier, PerkType.ConcussiveToss)
                .Name("Concussive Toss")

                .AddPerkLevel()
                .GrantsFeat(FeatType.ConcussiveToss1)
                .Description("Deals weapon DMG + 16 to enemies within 5m of you and inflicts Dazed for 15 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.Throwing, 18)

                .AddPerkLevel()
                .GrantsFeat(FeatType.ConcussiveToss2)
                .Description("Deals weapon DMG + 30 to enemies within 5m of you and inflicts Dazed for 15 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.Throwing, 32);
        }

        private void OrdnanceStance()
        {
            _builder.Create(PerkCategoryType.ThrowingBombardier, PerkType.OrdnanceStance)
                .Name("Ordnance Stance")

                .AddPerkLevel()
                .GrantsFeat(FeatType.OrdnanceStance1)
                .Description("While active, thrown area abilities deal +10% damage, but single-target thrown damage is reduced by 10%.")
                .Price(4)
                .RequirementSkill(SkillType.Throwing, 20);
        }

        private void SaturationToss()
        {
            _builder.Create(PerkCategoryType.ThrowingBombardier, PerkType.SaturationToss)
                .Name("Saturation Toss")

                .AddPerkLevel()
                .GrantsFeat(FeatType.SaturationTossTrait)
                .Description("Targets hit by two or more thrown area abilities within 30 seconds suffer Exposed for 30 seconds.")
                .IncreasesStat(StatType.AreaAbilityTargetHitSequenceSkillType, (int)SkillType.Throwing)
                .IncreasesStat(StatType.AreaAbilityTargetHitSequenceCountRequired, 2)
                .IncreasesStat(StatType.AreaAbilityTargetHitSequenceWindowSeconds, 30)
                .IncreasesStat(StatType.AreaAbilityTargetHitSequenceExposedDurationSeconds, 30)
                .Price(4)
                .RequirementSkill(SkillType.Throwing, 25);
        }

        private void BombardiersRhythm()
        {
            _builder.Create(PerkCategoryType.ThrowingBombardier, PerkType.BombardiersRhythm)
                .Name("Bombardier's Rhythm")

                .AddPerkLevel()
                .GrantsFeat(FeatType.BombardiersRhythmTrait)
                .Description("After an ordnance ability hits 2 or more enemies, restore 4 STM.")
                .IncreasesStat(StatType.ThrowingAreaAbilityMinTargetsStaminaRestoreThreshold, 2)
                .IncreasesStat(StatType.ThrowingAreaAbilityMinTargetsStaminaRestore, 4)
                .Price(2)
                .RequirementSkill(SkillType.Throwing, 35);
        }

        private void RainOfSteel()
        {
            _builder.Create(PerkCategoryType.ThrowingBombardier, PerkType.RainOfSteel)
                .Name("Rain of Steel")

                .AddPerkLevel()
                .GrantsFeat(FeatType.RainOfSteel1)
                .Description("Deals weapon DMG + 20 to enemies within 5m of you. For 45 seconds, thrown area abilities leave fragmentation zones that deal 8 physical DMG every 6 seconds.")
                .Price(6)
                .RequirementSkill(SkillType.Throwing, 50)
                .RequirementQuest(ThrowingCapstoneQuestDefinition.RainOfSteelMasteryQuestId);
        }

        private void PiercingToss()
        {
            _builder.Create(PerkCategoryType.ThrowingDeadeye, PerkType.PiercingToss)
                .Name("Piercing Toss")

                .AddPerkLevel()
                .GrantsFeat(FeatType.PiercingToss1)
                .Description("Deals weapon DMG + 8 and inflicts Bleed for 30 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.Throwing, 2)

                .AddPerkLevel()
                .GrantsFeat(FeatType.PiercingToss2)
                .Description("Deals weapon DMG + 18 and inflicts Bleed for 36 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.Throwing, 12)

                .AddPerkLevel()
                .GrantsFeat(FeatType.PiercingToss3)
                .Description("Deals weapon DMG + 28 and inflicts Bleed for 45 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.Throwing, 28)

                .AddPerkLevel()
                .GrantsFeat(FeatType.PiercingToss4)
                .Description("Deals weapon DMG + 38 and inflicts Bleed for 60 seconds.")
                .Price(5)
                .RequirementSkill(SkillType.Throwing, 40);
        }

        private void ReturningGrip()
        {
            _builder.Create(PerkCategoryType.ThrowingDeadeye, PerkType.ReturningGrip)
                .Name("Returning Grip")

                .AddPerkLevel()
                .GrantsFeat(FeatType.ReturningGripTrait)
                .Description("After a thrown ability hits a bleeding target, restore 2 STM.")
                .IncreasesStat(StatType.SkillAbilityBleedingTargetStaminaRestoreSkillType, (int)SkillType.Throwing)
                .IncreasesStat(StatType.SkillAbilityBleedingTargetStaminaRestoreChance, 100)
                .IncreasesStat(StatType.SkillAbilityBleedingTargetStaminaRestore, 2)
                .Price(2)
                .RequirementSkill(SkillType.Throwing, 5);
        }

        private void FlurryBleed()
        {
            _builder.Create(PerkCategoryType.ThrowingDeadeye, PerkType.FlurryBleed)
                .Name("Flurry Bleed")

                .AddPerkLevel()
                .GrantsFeat(FeatType.FlurryBleedTrait)
                .Description("Thrown abilities against bleeding targets deal +4 DMG and refresh Bleed by 6 seconds.")
                .IncreasesStat(StatType.AbilityDamageToBleedingTargetSkillType, (int)SkillType.Throwing)
                .IncreasesStat(StatType.AbilityDamageToBleedingTargetBonus, 4)
                .IncreasesStat(StatType.BleedingTargetAbilityBleedDurationExtensionSeconds, 6)
                .Price(2)
                .RequirementSkill(SkillType.Throwing, 8)

                .AddPerkLevel()
                .Description("Thrown abilities against bleeding targets deal +8 DMG and refresh Bleed by 6 seconds.")
                .IncreasesStat(StatType.AbilityDamageToBleedingTargetSkillType, (int)SkillType.Throwing)
                .IncreasesStat(StatType.AbilityDamageToBleedingTargetBonus, 8)
                .IncreasesStat(StatType.BleedingTargetAbilityBleedDurationExtensionSeconds, 6)
                .Price(4)
                .RequirementSkill(SkillType.Throwing, 22)

                .AddPerkLevel()
                .Description("Thrown abilities against bleeding targets deal +12 DMG and refresh Bleed by 6 seconds.")
                .IncreasesStat(StatType.AbilityDamageToBleedingTargetSkillType, (int)SkillType.Throwing)
                .IncreasesStat(StatType.AbilityDamageToBleedingTargetBonus, 12)
                .IncreasesStat(StatType.BleedingTargetAbilityBleedDurationExtensionSeconds, 6)
                .Price(4)
                .RequirementSkill(SkillType.Throwing, 45);
        }

        private void PinningToss()
        {
            _builder.Create(PerkCategoryType.ThrowingDeadeye, PerkType.PinningToss)
                .Name("Pinning Toss")

                .AddPerkLevel()
                .GrantsFeat(FeatType.PinningToss1)
                .Description("Deals weapon DMG + 12 and inflicts Hamstring for 30 seconds. Bleeding targets also suffer Disoriented for 30 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.Throwing, 10)

                .AddPerkLevel()
                .GrantsFeat(FeatType.PinningToss2)
                .Description("Deals weapon DMG + 24 and inflicts Hamstring for 30 seconds. Bleeding targets also suffer Disoriented for 30 seconds.")
                .Price(4)
                .RequirementSkill(SkillType.Throwing, 30)

                .AddPerkLevel()
                .GrantsFeat(FeatType.PinningToss3)
                .Description("Deals weapon DMG + 36 and inflicts Hamstring for 30 seconds. Bleeding targets also suffer Disoriented for 30 seconds.")
                .Price(4)
                .RequirementSkill(SkillType.Throwing, 38);
        }

        private void RicochetToss()
        {
            _builder.Create(PerkCategoryType.ThrowingDeadeye, PerkType.RicochetToss)
                .Name("Ricochet Toss")

                .AddPerkLevel()
                .GrantsFeat(FeatType.RicochetTossTrait)
                .Description("Thrown abilities against bleeding targets have a 25% chance to hit one enemy within 5m for +12 DMG.")
                .IncreasesStat(StatType.AbilityDamageToBleedingTargetSkillType, (int)SkillType.Throwing)
                .Price(4)
                .RequirementSkill(SkillType.Throwing, 15);
        }

        private void SeveringToss()
        {
            _builder.Create(PerkCategoryType.ThrowingDeadeye, PerkType.SeveringToss)
                .Name("Severing Toss")

                .AddPerkLevel()
                .GrantsFeat(FeatType.SeveringToss1)
                .Description("Deals weapon DMG + 16. Bleeding targets suffer Hemorrhage for 30 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.Throwing, 18)

                .AddPerkLevel()
                .GrantsFeat(FeatType.SeveringToss2)
                .Description("Deals weapon DMG + 30. Bleeding targets suffer Hemorrhage for 30 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.Throwing, 32);
        }

        private void FlurryStance()
        {
            _builder.Create(PerkCategoryType.ThrowingDeadeye, PerkType.FlurryStance)
                .Name("Flurry Stance")

                .AddPerkLevel()
                .GrantsFeat(FeatType.FlurryStance1)
                .Description("While active, thrown attacks against bleeding targets gain +10% Haste, but your Defense is reduced by 10%.")
                .Price(4)
                .RequirementSkill(SkillType.Throwing, 20);
        }

        private void DeepWound()
        {
            _builder.Create(PerkCategoryType.ThrowingDeadeye, PerkType.DeepWound)
                .Name("Deep Wound")

                .AddPerkLevel()
                .GrantsFeat(FeatType.DeepWoundTrait)
                .Description("Bleed effects you apply deal +20% damage to targets below 50% HP.")
                .IncreasesStat(StatType.TargetLowHPStatusDamageThresholdPercent, 50)
                .IncreasesStat(StatType.TargetLowHPStatusDamageStatusCategory, (int)StatusEffectCategory.Bleeding)
                .IncreasesStat(StatType.TargetLowHPStatusDamagePercentAdjustment, 20)
                .Price(4)
                .RequirementSkill(SkillType.Throwing, 25);
        }

        private void BleedingTempo()
        {
            _builder.Create(PerkCategoryType.ThrowingDeadeye, PerkType.BleedingTempo)
                .Name("Bleeding Tempo")

                .AddPerkLevel()
                .GrantsFeat(FeatType.BleedingTempoTrait)
                .Description("When Bleed expires on a target, your next thrown ability within 30 seconds costs 3 less STM.")
                .IncreasesStat(StatType.BleedingStatusExpiredNextSkillAbilityStaminaCostAdjustment, -3)
                .IncreasesStat(StatType.BleedingStatusExpiredNextSkillAbilitySkillType, (int)SkillType.Throwing)
                .IncreasesStat(StatType.BleedingStatusExpiredNextSkillAbilityWindowSeconds, 30)
                .Price(2)
                .RequirementSkill(SkillType.Throwing, 35);
        }

        private void PerfectFlurry()
        {
            _builder.Create(PerkCategoryType.ThrowingDeadeye, PerkType.PerfectFlurry)
                .Name("Perfect Flurry")

                .AddPerkLevel()
                .GrantsFeat(FeatType.PerfectFlurry1)
                .Description("Deals weapon DMG + 30. Bleeding targets take +45 DMG and spread Bleed to enemies within 5m for 45 seconds.")
                .Price(6)
                .RequirementSkill(SkillType.Throwing, 50)
                .RequirementQuest(ThrowingCapstoneQuestDefinition.PerfectFlurryMasteryQuestId);
        }

    }
}
