// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System.Collections.Generic;
using SWLOR.Game.Server.Enumeration;
using SWLOR.Game.Server.Feature.QuestDefinition;
using SWLOR.Game.Server.Service.CombatService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.PerkDefinition
{
    public class TwinBladePerkDefinition: IPerkListDefinition
    {
        private readonly PerkBuilder _builder = new();

        public Dictionary<PerkType, PerkDetail> BuildPerks()
        {
            CrossCut();
            Momentum();
            SpinningRhythm();
            SpinningWhirl();
            FlowingFootwork();
            BladeVortex();
            CycloneStance();
            SweepingAdvance();
            EdgeRhythm();
            TempestBloom();
            LaceratingTwinCut();
            BloodWake();
            BleedSpread();
            SerratedArc();
            PredatoryPressure();
            TwinRupture();
            LaceratorStance();
            SanguineTempo();
            ArterialReading();
            RedBloom();

            return _builder.Build();
        }

        private void CrossCut()
        {
            _builder.Create(PerkCategoryType.TwinBladeCyclone, PerkType.CrossCut)
                .Name("Cross Cut")

                .AddPerkLevel()
                .GrantsFeat(FeatType.CrossCut1)
                .Description("Instantly attacks twice, each for weapon DMG + 6. If both attacks hit, gain a stack of Momentum for 30 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.TwinBlade, 2)

                .AddPerkLevel()
                .GrantsFeat(FeatType.CrossCut2)
                .Description("Instantly attacks twice, each for weapon DMG + 13. If both attacks hit, gain a stack of Momentum for 30 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.TwinBlade, 12)

                .AddPerkLevel()
                .GrantsFeat(FeatType.CrossCut3)
                .Description("Instantly attacks twice, each for weapon DMG + 20. If both attacks hit, gain a stack of Momentum for 30 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.TwinBlade, 28)

                .AddPerkLevel()
                .GrantsFeat(FeatType.CrossCut4)
                .Description("Instantly attacks twice, each for weapon DMG + 27. If both attacks hit, gain a stack of Momentum for 30 seconds.")
                .Price(5)
                .RequirementSkill(SkillType.TwinBlade, 40);
        }

        private void Momentum()
        {
            _builder.Create(PerkCategoryType.TwinBladeCyclone, PerkType.Momentum)
                .Name("Momentum")

                .AddPerkLevel()
                .GrantsFeat(FeatType.MomentumTrait)
                .Description("Abilities that hit 2 or more enemies grant +5% Haste for 30 seconds, stacking up to +15%.")
                .IncreasesStat(StatType.AreaAbilityHasteStackMinimumTargets, 2)
                .IncreasesStat(StatType.AreaAbilityHastePerStack, 5)
                .IncreasesStat(StatType.AreaAbilityHasteStackDurationSeconds, 30)
                .IncreasesStat(StatType.AreaAbilityHasteStackMaximumPercent, 15)
                .Price(2)
                .RequirementSkill(SkillType.TwinBlade, 5);
        }

        private void SpinningRhythm()
        {
            _builder.Create(PerkCategoryType.TwinBladeCyclone, PerkType.SpinningRhythm)
                .Name("Spinning Rhythm")

                .AddPerkLevel()
                .GrantsFeat(FeatType.SpinningRhythmTrait)
                .Description("Area combat abilities grant +2% Haste for 30 seconds per enemy hit beyond the first, up to three stacks.")
                .IncreasesStat(StatType.AreaAbilityHasteStackMinimumTargets, 2)
                .IncreasesStat(StatType.AreaAbilityHasteStacksPerAdditionalTarget, 1)
                .IncreasesStat(StatType.AreaAbilityHastePerStack, 2)
                .IncreasesStat(StatType.AreaAbilityHasteStackDurationSeconds, 30)
                .IncreasesStat(StatType.AreaAbilityHasteStackMaximumPercent, 6)
                .Price(2)
                .RequirementSkill(SkillType.TwinBlade, 8)

                .AddPerkLevel()
                .Description("Area combat abilities grant +3% Haste for 30 seconds per enemy hit beyond the first, up to three stacks.")
                .IncreasesStat(StatType.AreaAbilityHasteStackMinimumTargets, 2)
                .IncreasesStat(StatType.AreaAbilityHasteStacksPerAdditionalTarget, 1)
                .IncreasesStat(StatType.AreaAbilityHastePerStack, 3)
                .IncreasesStat(StatType.AreaAbilityHasteStackDurationSeconds, 30)
                .IncreasesStat(StatType.AreaAbilityHasteStackMaximumPercent, 9)
                .Price(4)
                .RequirementSkill(SkillType.TwinBlade, 22)

                .AddPerkLevel()
                .Description("Area combat abilities grant +4% Haste for 30 seconds per enemy hit beyond the first, up to three stacks.")
                .IncreasesStat(StatType.AreaAbilityHasteStackMinimumTargets, 2)
                .IncreasesStat(StatType.AreaAbilityHasteStacksPerAdditionalTarget, 1)
                .IncreasesStat(StatType.AreaAbilityHastePerStack, 4)
                .IncreasesStat(StatType.AreaAbilityHasteStackDurationSeconds, 30)
                .IncreasesStat(StatType.AreaAbilityHasteStackMaximumPercent, 12)
                .Price(4)
                .RequirementSkill(SkillType.TwinBlade, 45);
        }

        private void SpinningWhirl()
        {
            _builder.Create(PerkCategoryType.TwinBladeCyclone, PerkType.SpinningWhirl)
                .Name("Spinning Whirl")

                .AddPerkLevel()
                .GrantsFeat(FeatType.SpinningWhirl1)
                .Description("Attacks up to 3 enemies within 5m for weapon DMG + 10 each.")
                .Price(2)
                .RequirementSkill(SkillType.TwinBlade, 10)

                .AddPerkLevel()
                .GrantsFeat(FeatType.SpinningWhirl2)
                .Description("Attacks up to 3 enemies within 5m for weapon DMG + 20 each.")
                .Price(4)
                .RequirementSkill(SkillType.TwinBlade, 30)

                .AddPerkLevel()
                .GrantsFeat(FeatType.SpinningWhirl3)
                .Description("Attacks up to 3 enemies within 5m for weapon DMG + 30 each.")
                .Price(4)
                .RequirementSkill(SkillType.TwinBlade, 38);
        }

        private void FlowingFootwork()
        {
            _builder.Create(PerkCategoryType.TwinBladeCyclone, PerkType.FlowingFootwork)
                .Name("Flowing Footwork")

                .AddPerkLevel()
                .GrantsFeat(FeatType.FlowingFootworkTrait)
                .Description("After using an area combat ability, gain +10% Evasion for 30 seconds.")
                .IncreasesStat(StatType.AreaAbilityUsedEvasionPercentAdjustment, 10)
                .IncreasesStat(StatType.AreaAbilityUsedEvasionDurationSeconds, 30)
                .Price(4)
                .RequirementSkill(SkillType.TwinBlade, 15);
        }

        private void BladeVortex()
        {
            _builder.Create(PerkCategoryType.TwinBladeCyclone, PerkType.BladeVortex)
                .Name("Blade Vortex")

                .AddPerkLevel()
                .GrantsFeat(FeatType.BladeVortex1)
                .Description("Deals weapon DMG + 18 to enemies within 5m. If this hits 3 or more enemies, restore 4 STM.")
                .Price(3)
                .RequirementSkill(SkillType.TwinBlade, 18)

                .AddPerkLevel()
                .GrantsFeat(FeatType.BladeVortex2)
                .Description("Deals weapon DMG + 30 to enemies within 5m. If this hits 3 or more enemies, restore 6 STM.")
                .Price(3)
                .RequirementSkill(SkillType.TwinBlade, 32);
        }

        private void CycloneStance()
        {
            _builder.Create(PerkCategoryType.TwinBladeCyclone, PerkType.CycloneStance)
                .Name("Cyclone Stance")

                .AddPerkLevel()
                .GrantsFeat(FeatType.CycloneStance1)
                .Description("While active, grants +15% Haste and +10% Attack, but reduces Defense by 20%.")
                .Price(4)
                .RequirementSkill(SkillType.TwinBlade, 20);
        }

        private void SweepingAdvance()
        {
            _builder.Create(PerkCategoryType.TwinBladeCyclone, PerkType.SweepingAdvance)
                .Name("Sweeping Advance")

                .AddPerkLevel()
                .GrantsFeat(FeatType.SweepingAdvanceTrait)
                .Description("Area combat abilities restore 2 STM per target hit, up to 6 STM.")
                .IncreasesStat(StatType.AreaHitStaminaRestorePerTarget, 2)
                .IncreasesStat(StatType.AreaHitStaminaRestoreMaximum, 6)
                .Price(4)
                .RequirementSkill(SkillType.TwinBlade, 25);
        }

        private void EdgeRhythm()
        {
            _builder.Create(PerkCategoryType.TwinBladeCyclone, PerkType.EdgeRhythm)
                .Name("Edge Rhythm")

                .AddPerkLevel()
                .GrantsFeat(FeatType.EdgeRhythmTrait)
                .Description("Every third auto-attack deals +15 DMG to one enemy within 5m.")
                .IncreasesStat(StatType.AutoAttackCycleRequiredCount, 3)
                .IncreasesStat(StatType.AutoAttackCycleDamage, 15)
                .IncreasesStat(StatType.AutoAttackCycleRadiusMeters, 5)
                .Price(2)
                .RequirementSkill(SkillType.TwinBlade, 35);
        }

        private void TempestBloom()
        {
            _builder.Create(PerkCategoryType.TwinBladeCyclone, PerkType.TempestBloom)
                .Name("Tempest Bloom")

                .AddPerkLevel()
                .GrantsFeat(FeatType.TempestBloom1)
                .Description("Deal weapon DMG + 25 to enemies within 5m. For 45 seconds, each hostile area ability that lands creates one immediate pulse for 8 physical DMG to enemies within 5m of its first struck target.")
                .Price(6)
                .RequirementSkill(SkillType.TwinBlade, 50)
                .RequirementQuest(TwinBladeCapstoneQuestDefinition.TempestBloomMasteryQuestId);
        }

        private void LaceratingTwinCut()
        {
            _builder.Create(PerkCategoryType.TwinBladeDuelist, PerkType.LaceratingTwinCut)
                .Name("Lacerating Twin Cut")

                .AddPerkLevel()
                .GrantsFeat(FeatType.LaceratingTwinCut1)
                .Description("Strikes twice for weapon DMG + 5 each and inflicts Bleed for 30 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.TwinBlade, 2)

                .AddPerkLevel()
                .GrantsFeat(FeatType.LaceratingTwinCut2)
                .Description("Strikes twice for weapon DMG + 11 each and inflicts Bleed for 36 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.TwinBlade, 12)

                .AddPerkLevel()
                .GrantsFeat(FeatType.LaceratingTwinCut3)
                .Description("Strikes twice for weapon DMG + 17 each and inflicts Bleed for 45 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.TwinBlade, 28)

                .AddPerkLevel()
                .GrantsFeat(FeatType.LaceratingTwinCut4)
                .Description("Strikes twice for weapon DMG + 23 each and inflicts Bleed for 60 seconds.")
                .Price(5)
                .RequirementSkill(SkillType.TwinBlade, 40);
        }

        private void BloodWake()
        {
            _builder.Create(PerkCategoryType.TwinBladeDuelist, PerkType.BloodWake)
                .Name("Blood Wake")

                .AddPerkLevel()
                .GrantsFeat(FeatType.BloodWakeTrait)
                .Description("When you defeat a bleeding enemy, enemies within 5m are inflicted with Bleed for 30 seconds.")
                .IncreasesStat(StatType.DefeatedBleedingEnemyNearbyBleedDurationSeconds, 30)
                .Price(2)
                .RequirementSkill(SkillType.TwinBlade, 5);
        }

        private void BleedSpread()
        {
            _builder.Create(PerkCategoryType.TwinBladeDuelist, PerkType.BleedSpread)
                .Name("Bleed Spread")

                .AddPerkLevel()
                .GrantsFeat(FeatType.BleedSpreadTrait)
                .Description("Your physical combat abilities against bleeding targets have a 15% chance to spread Bleed to one enemy within 5m.")
                .IncreasesStat(StatType.BleedingTargetAbilityBleedSpreadChance, 15)
                .IncreasesStat(StatType.BleedingTargetAbilityBleedSpreadDurationSeconds, 30)
                .IncreasesStat(StatType.BleedingTargetAbilityBleedSpreadMaxTargets, 1)
                .Price(2)
                .RequirementSkill(SkillType.TwinBlade, 8)

                .AddPerkLevel()
                .Description("Your physical combat abilities against bleeding targets have a 25% chance to spread Bleed to one enemy within 5m.")
                .IncreasesStat(StatType.BleedingTargetAbilityBleedSpreadChance, 25)
                .IncreasesStat(StatType.BleedingTargetAbilityBleedSpreadDurationSeconds, 30)
                .IncreasesStat(StatType.BleedingTargetAbilityBleedSpreadMaxTargets, 1)
                .Price(4)
                .RequirementSkill(SkillType.TwinBlade, 22)

                .AddPerkLevel()
                .Description("Your physical combat abilities against bleeding targets have a 35% chance to spread Bleed to one enemy within 5m.")
                .IncreasesStat(StatType.BleedingTargetAbilityBleedSpreadChance, 35)
                .IncreasesStat(StatType.BleedingTargetAbilityBleedSpreadDurationSeconds, 30)
                .IncreasesStat(StatType.BleedingTargetAbilityBleedSpreadMaxTargets, 1)
                .Price(4)
                .RequirementSkill(SkillType.TwinBlade, 45);
        }

        private void SerratedArc()
        {
            _builder.Create(PerkCategoryType.TwinBladeDuelist, PerkType.SerratedArc)
                .Name("Serrated Arc")

                .AddPerkLevel()
                .GrantsFeat(FeatType.SerratedArc1)
                .Description("Deals weapon DMG + 10 to enemies within 5m. Bleeding targets spread Bleed to one additional enemy within 5m.")
                .Price(2)
                .RequirementSkill(SkillType.TwinBlade, 10)

                .AddPerkLevel()
                .GrantsFeat(FeatType.SerratedArc2)
                .Description("Deals weapon DMG + 20 to enemies within 5m. Bleeding targets spread Bleed to one additional enemy within 5m.")
                .Price(4)
                .RequirementSkill(SkillType.TwinBlade, 30)

                .AddPerkLevel()
                .GrantsFeat(FeatType.SerratedArc3)
                .Description("Deals weapon DMG + 30 to enemies within 5m. Bleeding targets spread Bleed to one additional enemy within 5m.")
                .Price(4)
                .RequirementSkill(SkillType.TwinBlade, 38);
        }

        private void PredatoryPressure()
        {
            _builder.Create(PerkCategoryType.TwinBladeDuelist, PerkType.PredatoryPressure)
                .Name("Predatory Pressure")

                .AddPerkLevel()
                .GrantsFeat(FeatType.PredatoryPressureTrait)
                .Description("Each bleeding enemy within 10m grants +2% Attack, up to +12%.")
                .IncreasesStat(StatType.NearbyStatusTargetAttackStatusCategory, (int)StatusEffectCategory.Bleeding)
                .IncreasesStat(StatType.NearbyStatusTargetAttackPercentPerTarget, 2)
                .IncreasesStat(StatType.NearbyStatusTargetAttackRadiusMeters, 10)
                .IncreasesStat(StatType.NearbyStatusTargetAttackPercentMaximum, 12)
                .Price(4)
                .RequirementSkill(SkillType.TwinBlade, 15);
        }

        private void TwinRupture()
        {
            _builder.Create(PerkCategoryType.TwinBladeDuelist, PerkType.TwinRupture)
                .Name("Twin Rupture")

                .AddPerkLevel()
                .GrantsFeat(FeatType.TwinRupture1)
                .Description("Deals weapon DMG + 18. Bleeding targets suffer Hemorrhage for 30 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.TwinBlade, 18)

                .AddPerkLevel()
                .GrantsFeat(FeatType.TwinRupture2)
                .Description("Deals weapon DMG + 32. Bleeding targets suffer Hemorrhage for 30 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.TwinBlade, 32);
        }

        private void LaceratorStance()
        {
            _builder.Create(PerkCategoryType.TwinBladeDuelist, PerkType.LaceratorStance)
                .Name("Lacerator Stance")

                .AddPerkLevel()
                .GrantsFeat(FeatType.LaceratorStance1)
                .Description("While active, your attacks against bleeding targets deal +10% damage, but your Evasion is reduced by 10%.")
                .Price(4)
                .RequirementSkill(SkillType.TwinBlade, 20);
        }

        private void SanguineTempo()
        {
            _builder.Create(PerkCategoryType.TwinBladeDuelist, PerkType.SanguineTempo)
                .Name("Sanguine Tempo")

                .AddPerkLevel()
                .GrantsFeat(FeatType.SanguineTempoTrait)
                .Description("Attacking a bleeding target restores 1 STM. This can trigger once every 4 seconds.")
                .IncreasesStat(StatType.SkillDamageBleedingTargetStaminaRestoreSkillType, (int)SkillType.TwinBlade)
                .IncreasesStat(StatType.SkillDamageBleedingTargetStaminaRestoreChance, 100)
                .IncreasesStat(StatType.SkillDamageBleedingTargetStaminaRestore, 1)
                .IncreasesStat(StatType.SkillDamageBleedingTargetStaminaRestoreCooldownSeconds, 4)
                .Price(4)
                .RequirementSkill(SkillType.TwinBlade, 25);
        }

        private void ArterialReading()
        {
            _builder.Create(PerkCategoryType.TwinBladeDuelist, PerkType.ArterialReading)
                .Name("Arterial Reading")

                .AddPerkLevel()
                .GrantsFeat(FeatType.ArterialReadingTrait)
                .Description("Gain +10% Critical Rate against bleeding targets.")
                .IncreasesStat(StatType.TargetStatusCriticalRateStatusCategory, (int)StatusEffectCategory.Bleeding)
                .IncreasesStat(StatType.TargetStatusCriticalRatePercentAdjustment, 10)
                .Price(2)
                .RequirementSkill(SkillType.TwinBlade, 35);
        }

        private void RedBloom()
        {
            _builder.Create(PerkCategoryType.TwinBladeDuelist, PerkType.RedBloom)
                .Name("Red Bloom")

                .AddPerkLevel()
                .GrantsFeat(FeatType.RedBloom1)
                .Description("Deals weapon DMG + 20 to enemies within 5m. Bleeding enemies take +40 DMG and spread Hemorrhage for 30 seconds.")
                .Price(6)
                .RequirementSkill(SkillType.TwinBlade, 50)
                .RequirementQuest(TwinBladeCapstoneQuestDefinition.RedBloomMasteryQuestId);
        }

    }
}
