// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System.Collections.Generic;
using SWLOR.Game.Server.Enumeration;
using SWLOR.Game.Server.Feature.QuestDefinition;
using SWLOR.Game.Server.Service.CombatService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.PerkDefinition
{
    public class VibroknifePerkDefinition: IPerkListDefinition
    {
        private readonly PerkBuilder _builder = new();

        public Dictionary<PerkType, PerkDetail> BuildPerks()
        {
            PathogenStrike();
            Hypermetabolize();
            Debilitate();
            VirulentBlade();
            Infection();
            VolatileCompound();
            AssassinsStance();
            VenomTempo();
            Propagation();
            ViralCascade();
            VeiledStrike();
            ButchersTempo();
            FirstStrike();
            CripplingSlice();
            VenaticRecovery();
            Backstab();
            ShadowflowStance();
            CheapShot();
            Hobbled();
            EscapeArtist();

            return _builder.Build();
        }

        private void PathogenStrike()
        {
            _builder.Create(PerkCategoryType.VibroknifeShadow, PerkType.PathogenStrike)
                .Name("Pathogen Strike")

                .AddPerkLevel()
                .GrantsFeat(FeatType.PathogenStrike1)
                .Description("Deals weapon DMG + 6. Extends your Venom and Infection effects on the target by 4 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 2)

                .AddPerkLevel()
                .GrantsFeat(FeatType.PathogenStrike2)
                .Description("Deals weapon DMG + 12. Extends your Venom and Infection effects on the target by 4 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 12)

                .AddPerkLevel()
                .GrantsFeat(FeatType.PathogenStrike3)
                .Description("Deals weapon DMG + 16. Extends your Venom and Infection effects on the target by 6 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.Vibroknife, 28)

                .AddPerkLevel()
                .GrantsFeat(FeatType.PathogenStrike4)
                .Description("Deals weapon DMG + 19. Extends your Venom and Infection effects on the target by 6 seconds.")
                .Price(5)
                .RequirementSkill(SkillType.Vibroknife, 40);
        }

        private void Hypermetabolize()
        {
            _builder.Create(PerkCategoryType.VibroknifeShadow, PerkType.Hypermetabolize)
                .Name("Hypermetabolize")

                .AddPerkLevel()
                .GrantsFeat(FeatType.HypermetabolizeTrait)
                .Description("Reduces incoming healing on targets affected by your Venom by 15%.")
                .IncreasesStat(StatType.SourceStatusHealingReceivedRequiredCategory, (int)StatusEffectCategory.Venom)
                .IncreasesStat(StatType.SourceStatusHealingReceivedPercentAdjustment, -15)
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 5);
        }

        private void Debilitate()
        {
            _builder.Create(PerkCategoryType.VibroknifeShadow, PerkType.Debilitate)
                .Name("Debilitate")

                .AddPerkLevel()
                .GrantsFeat(FeatType.DebilitateTrait)
                .Description("Your hostile combat abilities deal +4 DMG to targets affected by your Venom.")
                .IncreasesStat(StatType.AbilityDamageToSourceAppliedStatusTargetBonusCategory, (int)StatusEffectCategory.Venom)
                .IncreasesStat(StatType.AbilityDamageToSourceAppliedStatusTargetBonus, 4)
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 8)

                .AddPerkLevel()
                .Description("Your hostile combat abilities deal +8 DMG to targets affected by your Venom.")
                .IncreasesStat(StatType.AbilityDamageToSourceAppliedStatusTargetBonusCategory, (int)StatusEffectCategory.Venom)
                .IncreasesStat(StatType.AbilityDamageToSourceAppliedStatusTargetBonus, 8)
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 22)

                .AddPerkLevel()
                .Description("Your hostile combat abilities deal +12 DMG to targets affected by your Venom.")
                .IncreasesStat(StatType.AbilityDamageToSourceAppliedStatusTargetBonusCategory, (int)StatusEffectCategory.Venom)
                .IncreasesStat(StatType.AbilityDamageToSourceAppliedStatusTargetBonus, 12)
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 45);
        }

        private void VirulentBlade()
        {
            _builder.Create(PerkCategoryType.VibroknifeShadow, PerkType.VirulentBlade)
                .Name("Virulent Blade")

                .AddPerkLevel()
                .GrantsFeat(FeatType.VirulentBlade1)
                .Description("Deals weapon DMG + 9. Inflicts Venom for 30 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 10)

                .AddPerkLevel()
                .GrantsFeat(FeatType.VirulentBlade2)
                .Description("Deals weapon DMG + 12. Inflicts Venom for 30 seconds.")
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 30)

                .AddPerkLevel()
                .GrantsFeat(FeatType.VirulentBlade3)
                .Description("Deals weapon DMG + 16. Inflicts Venom for 30 seconds.")
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 38);
        }

        private void Infection()
        {
            _builder.Create(PerkCategoryType.VibroknifeShadow, PerkType.Infection)
                .Name("Infection")

                .AddPerkLevel()
                .GrantsFeat(FeatType.InfectionTrait)
                .Description("Successfully landing an attack or hostile combat ability on a target affected by your Venom applies a stack of Infection. Infection deals 2 Poison DMG per stack every 6 seconds, max 5 stacks. Stacks last 18 seconds.")
                .IncreasesStat(StatType.SourceStatusStackRequiredCategory, (int)StatusEffectCategory.Venom)
                .IncreasesStat(StatType.SourceStatusStackAppliedCategory, (int)StatusEffectCategory.Infection)
                .IncreasesStat(StatType.SourceStatusStackMaximum, 5)
                .IncreasesStat(StatType.SourceStatusStackDurationSeconds, 18)
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 15);
        }

        private void VolatileCompound()
        {
            _builder.Create(PerkCategoryType.VibroknifeShadow, PerkType.VolatileCompound)
                .Name("Volatile Compound")

                .AddPerkLevel()
                .GrantsFeat(FeatType.VolatileCompound1)
                .Description("Deals weapon DMG + 20 and inflicts -15 Poison Resistance for 30 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.Vibroknife, 18)

                .AddPerkLevel()
                .GrantsFeat(FeatType.VolatileCompound2)
                .Description("Deals weapon DMG + 30 and inflicts -25 Poison Resistance for 30 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.Vibroknife, 32);
        }

        private void AssassinsStance()
        {
            _builder.Create(PerkCategoryType.VibroknifeShadow, PerkType.AssassinsStance)
                .Name("Assassin's Stance")

                .AddPerkLevel()
                .GrantsFeat(FeatType.AssassinsStance1)
                .Description("While active, grants +20% Poison Damage, but reduces Attack by 10%.")
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 20);
        }

        private void VenomTempo()
        {
            _builder.Create(PerkCategoryType.VibroknifeShadow, PerkType.VenomTempo)
                .Name("Venom Tempo")

                .AddPerkLevel()
                .GrantsFeat(FeatType.VenomTempoTrait)
                .Description("After successfully landing a hostile combat ability, your next auto-attack comes out instantly.")
                .IncreasesStat(StatType.HostileAbilityHitNextAutoAttackNoDelayAllSkills, 1)
                .IncreasesStat(StatType.HostileAbilityHitNextAutoAttackNoDelayDurationSeconds, 30)
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 25);
        }

        private void Propagation()
        {
            _builder.Create(PerkCategoryType.VibroknifeShadow, PerkType.Propagation)
                .Name("Propagation")

                .AddPerkLevel()
                .GrantsFeat(FeatType.PropagationTrait)
                .Description("Every third auto-attack on a target affected by your Venom deals an additional +15 Poison DMG.")
                .IncreasesStat(StatType.SourceStatusAutoAttackCycleRequiredCategory, (int)StatusEffectCategory.Venom)
                .IncreasesStat(StatType.SourceStatusAutoAttackCycleSkillType, (int)SkillType.Vibroknife)
                .IncreasesStat(StatType.SourceStatusAutoAttackCycleRequiredCount, 3)
                .IncreasesStat(StatType.SourceStatusAutoAttackCycleDamage, 15)
                .IncreasesStat(StatType.SourceStatusAutoAttackCycleDamageType, (int)CombatDamageType.Poison)
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 35);
        }

        private void ViralCascade()
        {
            _builder.Create(PerkCategoryType.VibroknifeShadow, PerkType.ViralCascade)
                .Name("Viral Cascade")

                .AddPerkLevel()
                .GrantsFeat(FeatType.ViralCascade1)
                .Description("Deals weapon DMG + 30, deals an additional +20 DMG if the target is inflicted with your Venom and +8 DMG per stack of your Infection on the target. Consumes your Venom and Infection stacks from the target.")
                .Price(6)
                .RequirementSkill(SkillType.Vibroknife, 50)
                .RequirementQuest(VibroknifeCapstoneQuestDefinition.VitalRuptureMasteryQuestId);
        }

        private void VeiledStrike()
        {
            _builder.Create(PerkCategoryType.VibroknifeSaboteur, PerkType.VeiledStrike)
                .Name("Veiled Strike")

                .AddPerkLevel()
                .GrantsFeat(FeatType.VeiledStrike1)
                .Description("On your next attack, deal +6 DMG and an additional +6 DMG if the target is inflicted with Exposed.")
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 2)

                .AddPerkLevel()
                .GrantsFeat(FeatType.VeiledStrike2)
                .Description("On your next attack, deal +10 DMG and an additional +8 DMG if the target is inflicted with Exposed.")
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 12)

                .AddPerkLevel()
                .GrantsFeat(FeatType.VeiledStrike3)
                .Description("On your next attack, deal +14 DMG and an additional +10 DMG if the target is inflicted with Exposed.")
                .Price(3)
                .RequirementSkill(SkillType.Vibroknife, 28)

                .AddPerkLevel()
                .GrantsFeat(FeatType.VeiledStrike4)
                .Description("On your next attack, deal +16 DMG and an additional +12 DMG if the target is inflicted with Exposed.")
                .Price(5)
                .RequirementSkill(SkillType.Vibroknife, 40);
        }

        private void ButchersTempo()
        {
            _builder.Create(PerkCategoryType.VibroknifeSaboteur, PerkType.ButchersTempo)
                .Name("Butcher's Tempo")

                .AddPerkLevel()
                .GrantsFeat(FeatType.ButchersTempoTrait)
                .Description("After using a hostile combat ability, gain +5% Attack for 18 seconds, stacking up to 15%.")
                .IncreasesStat(StatType.HostileAbilityUsedAttackPercentAdjustment, 5)
                .IncreasesStat(StatType.HostileAbilityUsedAttackPercentAdjustmentDurationSeconds, 18)
                .IncreasesStat(StatType.HostileAbilityUsedAttackPercentAdjustmentMaximum, 15)
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 5);
        }

        private void FirstStrike()
        {
            _builder.Create(PerkCategoryType.VibroknifeSaboteur, PerkType.FirstStrike)
                .Name("First Strike")

                .AddPerkLevel()
                .GrantsFeat(FeatType.FirstStrikeTrait)
                .Description("Entering combat grants 3 stacks of First Strike. Each stack is consumed by a successfully landed hostile combat ability to deal +8 DMG. Once all stacks are consumed, First Strike recharges once every 90 seconds.")
                .IncreasesStat(StatType.FirstHostileAbilityHitDamageBonus, 8)
                .IncreasesStat(StatType.FirstHostileAbilityHitMaximumCount, 3)
                .IncreasesStat(StatType.FirstHostileAbilityHitCooldownSeconds, 90)
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 8)

                .AddPerkLevel()
                .Description("Entering combat grants 3 stacks of First Strike. Each stack is consumed by a successfully landed hostile combat ability to deal +12 DMG. Once all stacks are consumed, First Strike recharges once every 90 seconds.")
                .IncreasesStat(StatType.FirstHostileAbilityHitDamageBonus, 12)
                .IncreasesStat(StatType.FirstHostileAbilityHitMaximumCount, 3)
                .IncreasesStat(StatType.FirstHostileAbilityHitCooldownSeconds, 90)
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 22)

                .AddPerkLevel()
                .Description("Entering combat grants 3 stacks of First Strike. Each stack is consumed by a successfully landed hostile combat ability to deal +16 DMG. Once all stacks are consumed, First Strike recharges once every 90 seconds.")
                .IncreasesStat(StatType.FirstHostileAbilityHitDamageBonus, 16)
                .IncreasesStat(StatType.FirstHostileAbilityHitMaximumCount, 3)
                .IncreasesStat(StatType.FirstHostileAbilityHitCooldownSeconds, 90)
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 45);
        }

        private void CripplingSlice()
        {
            _builder.Create(PerkCategoryType.VibroknifeSaboteur, PerkType.CripplingSlice)
                .Name("Crippling Slice")

                .AddPerkLevel()
                .GrantsFeat(FeatType.CripplingSlice1)
                .Description("Deals weapon DMG + 10 and inflicts Exposed for 30 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 10)

                .AddPerkLevel()
                .GrantsFeat(FeatType.CripplingSlice2)
                .Description("Deals weapon DMG + 20 and inflicts Exposed for 30 seconds.")
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 30)

                .AddPerkLevel()
                .GrantsFeat(FeatType.CripplingSlice3)
                .Description("Deals weapon DMG + 28 and inflicts Exposed for 30 seconds.")
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 38);
        }

        private void VenaticRecovery()
        {
            _builder.Create(PerkCategoryType.VibroknifeSaboteur, PerkType.VenaticRecovery)
                .Name("Venatic Recovery")

                .AddPerkLevel()
                .GrantsFeat(FeatType.VenaticRecoveryTrait)
                .Description("Your first attack in combat restores 15 STM. This can trigger once every 60 seconds.")
                .IncreasesStat(StatType.FirstCombatAttackStaminaRestore, 15)
                .IncreasesStat(StatType.FirstCombatAttackStaminaRestoreCooldownSeconds, 60)
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 15);
        }

        private void Backstab()
        {
            _builder.Create(PerkCategoryType.VibroknifeSaboteur, PerkType.Backstab)
                .Name("Backstab")

                .AddPerkLevel()
                .GrantsFeat(FeatType.Backstab1)
                .Description("Deals weapon DMG + 20. If you are behind your target, deal an additional +10 DMG and inflict Knockdown for 6 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.Vibroknife, 18)

                .AddPerkLevel()
                .GrantsFeat(FeatType.Backstab2)
                .Description("Deals weapon DMG + 25. If you are behind your target, deal an additional +20 DMG and inflict Knockdown for 6 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.Vibroknife, 32);
        }

        private void ShadowflowStance()
        {
            _builder.Create(PerkCategoryType.VibroknifeSaboteur, PerkType.ShadowflowStance)
                .Name("Shadowflow Stance")

                .AddPerkLevel()
                .GrantsFeat(FeatType.ShadowflowStance1)
                .Description("While active, your Vibroknife auto-attacks inflict Hamstring for 18 seconds, but your Defense is reduced by 20%.")
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 20);
        }

        private void CheapShot()
        {
            _builder.Create(PerkCategoryType.VibroknifeSaboteur, PerkType.CheapShot)
                .Name("Cheap Shot")

                .AddPerkLevel()
                .GrantsFeat(FeatType.CheapShotTrait)
                .Description("Auto-attacks and hostile combat abilities deal an additional +10 DMG to targets inflicted with Dazed, Stunned, or Knockdown, or while you are Stealthed or Invisible.")
                .IncreasesStat(StatType.DirectDamageToStatusCategoryOrStealthBonus, 10)
                .IncreasesStat(StatType.DirectDamageToStatusCategoryOrStealthBonusCategory, (int)StatusEffectCategory.Incapacitating)
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 25);
        }

        private void Hobbled()
        {
            _builder.Create(PerkCategoryType.VibroknifeSaboteur, PerkType.Hobbled)
                .Name("Hobbled")

                .AddPerkLevel()
                .GrantsFeat(FeatType.HobbledTrait)
                .Description("Exposed and Disoriented debuffs you apply also drain 6 STM from the target. This can trigger once every 12 seconds.")
                .IncreasesStat(StatType.StatusAppliedTargetStaminaDrainRequiredCategory, (int)StatusEffectCategory.StaminaDrainTrigger)
                .IncreasesStat(StatType.StatusAppliedTargetStaminaDrain, 6)
                .IncreasesStat(StatType.StatusAppliedTargetStaminaDrainCooldownSeconds, 12)
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 35);
        }

        private void EscapeArtist()
        {
            _builder.Create(PerkCategoryType.VibroknifeSaboteur, PerkType.EscapeArtist)
                .Name("Escape Artist")

                .AddPerkLevel()
                .GrantsFeat(FeatType.EscapeArtist1)
                .Description("Deals weapon DMG + 30 and Blinds the target for 12 seconds and grants Invisibility for 30 seconds.")
                .Price(6)
                .RequirementSkill(SkillType.Vibroknife, 50)
                .RequirementQuest(VibroknifeCapstoneQuestDefinition.SystemicShutdownMasteryQuestId);
        }

    }
}
