// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System.Collections.Generic;
using SWLOR.Game.Server.Enumeration;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.PerkDefinition
{
    public class VibroknifePerkDefinition: IPerkListDefinition
    {
        private readonly PerkBuilder _builder = new();

        public Dictionary<PerkType, PerkDetail> BuildPerks()
        {
            LaceratingCut();
            BloodPattern();
            RuptureSetup();
            RuptureStrike();
            ComboPressure();
            Hemorrhage();
            ShadowflowStance();
            OpenArtery();
            MeasuredCuts();
            VitalRupture();
            EnfeeblingStrike();
            CalculatedStrikes();
            SapVitality();
            Hamstring();
            ExploitWeakness();
            NerveStrike();
            DebilitatingStance();
            CascadeFailure();
            AfflictionMastery();
            SystemicShutdown();

            return _builder.Build();
        }

        private void LaceratingCut()
        {
            _builder.Create(PerkCategoryType.VibroknifeShadow, PerkType.LaceratingCut)
                .Name("Lacerating Cut")

                .AddPerkLevel()
                .GrantsFeat(FeatType.LaceratingCut1)
                .Description("Deals weapon DMG + 8. Inflicts Bleed for 30 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 2)

                .AddPerkLevel()
                .GrantsFeat(FeatType.LaceratingCut2)
                .Description("Deals weapon DMG + 18. Inflicts Bleed for 36 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 12)

                .AddPerkLevel()
                .GrantsFeat(FeatType.LaceratingCut3)
                .Description("Deals weapon DMG + 28. Inflicts Bleed for 45 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.Vibroknife, 28)

                .AddPerkLevel()
                .GrantsFeat(FeatType.LaceratingCut4)
                .Description("Deals weapon DMG + 38. Inflicts Bleed for 60 seconds.")
                .Price(5)
                .RequirementSkill(SkillType.Vibroknife, 40);
        }

        private void BloodPattern()
        {
            _builder.Create(PerkCategoryType.VibroknifeShadow, PerkType.BloodPattern)
                .Name("Blood Pattern")

                .AddPerkLevel()
                .GrantsFeat(FeatType.BloodPatternTrait)
                .Description("Critical hits extend your Bleed and Hemorrhage effects on the target by 6 seconds. This can trigger once every 8 seconds.")
                .IncreasesStat(StatType.CriticalBleedingStatusDurationExtensionSeconds, 6)
                .IncreasesStat(StatType.CriticalBleedingStatusDurationExtensionCooldownSeconds, 8)
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 5);
        }

        private void RuptureSetup()
        {
            _builder.Create(PerkCategoryType.VibroknifeShadow, PerkType.RuptureSetup)
                .Name("Rupture Setup")

                .AddPerkLevel()
                .GrantsFeat(FeatType.RuptureSetupTrait)
                .Description("Your physical combat abilities deal +4 DMG to bleeding or hemorrhaging targets.")
                .IncreasesStat(StatType.AbilityDamageToBleedingTargetSkillType, (int)SkillType.Vibroknife)
                .IncreasesStat(StatType.AbilityDamageToBleedingTargetBonus, 4)
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 8)

                .AddPerkLevel()
                .Description("Your physical combat abilities deal +8 DMG to bleeding or hemorrhaging targets.")
                .IncreasesStat(StatType.AbilityDamageToBleedingTargetSkillType, (int)SkillType.Vibroknife)
                .IncreasesStat(StatType.AbilityDamageToBleedingTargetBonus, 8)
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 22)

                .AddPerkLevel()
                .Description("Your physical combat abilities deal +12 DMG to bleeding or hemorrhaging targets.")
                .IncreasesStat(StatType.AbilityDamageToBleedingTargetSkillType, (int)SkillType.Vibroknife)
                .IncreasesStat(StatType.AbilityDamageToBleedingTargetBonus, 12)
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 45);
        }

        private void RuptureStrike()
        {
            _builder.Create(PerkCategoryType.VibroknifeShadow, PerkType.RuptureStrike)
                .Name("Rupture Strike")

                .AddPerkLevel()
                .GrantsFeat(FeatType.RuptureStrike1)
                .Description("Deals weapon DMG + 10. If the target is bleeding, consumes Bleed to inflict Hemorrhage for 30 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 10)

                .AddPerkLevel()
                .GrantsFeat(FeatType.RuptureStrike2)
                .Description("Deals weapon DMG + 22. If the target is bleeding, consumes Bleed to inflict Hemorrhage for 30 seconds.")
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 30)

                .AddPerkLevel()
                .GrantsFeat(FeatType.RuptureStrike3)
                .Description("Deals weapon DMG + 34. If the target is bleeding, consumes Bleed to inflict Hemorrhage for 30 seconds.")
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 38);
        }

        private void ComboPressure()
        {
            _builder.Create(PerkCategoryType.VibroknifeShadow, PerkType.ComboPressure)
                .Name("Combo Pressure")

                .AddPerkLevel()
                .GrantsFeat(FeatType.ComboPressureTrait)
                .Description("Using two different hostile combat abilities within 30 seconds makes your next attack inflict Bleed for 30 seconds.")
                .IncreasesStat(StatType.HostileAbilitySequenceWindowSeconds, 30)
                .IncreasesStat(StatType.HostileAbilitySequenceNextAttackBleedDurationSeconds, 30)
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 15);
        }

        private void Hemorrhage()
        {
            _builder.Create(PerkCategoryType.VibroknifeShadow, PerkType.Hemorrhage)
                .Name("Hemorrhage")

                .AddPerkLevel()
                .GrantsFeat(FeatType.Hemorrhage1)
                .Description("Deals weapon DMG + 16 and causes the target to bleed for 6 physical damage every 3 seconds for 30 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.Vibroknife, 18)

                .AddPerkLevel()
                .GrantsFeat(FeatType.Hemorrhage2)
                .Description("Deals weapon DMG + 30 and causes the target to bleed for 10 physical damage every 3 seconds for 30 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.Vibroknife, 32);
        }

        private void ShadowflowStance()
        {
            _builder.Create(PerkCategoryType.VibroknifeShadow, PerkType.ShadowflowStance)
                .Name("Shadowflow Stance")

                .AddPerkLevel()
                .GrantsFeat(FeatType.ShadowflowStance1)
                .Description("While active, grants +10% Critical Rate and +15% Bleed duration, but reduces Defense by 15%.")
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 20);
        }

        private void OpenArtery()
        {
            _builder.Create(PerkCategoryType.VibroknifeShadow, PerkType.OpenArtery)
                .Name("Open Artery")

                .AddPerkLevel()
                .GrantsFeat(FeatType.OpenArteryTrait)
                .Description("Bleed and Hemorrhage effects you apply last 25% longer.")
                .IncreasesStat(StatType.OutgoingDebuffDurationPercentAdjustment, 25)
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 25);
        }

        private void MeasuredCuts()
        {
            _builder.Create(PerkCategoryType.VibroknifeShadow, PerkType.MeasuredCuts)
                .Name("Measured Cuts")

                .AddPerkLevel()
                .GrantsFeat(FeatType.MeasuredCutsTrait)
                .Description("Every third hostile combat ability you land on the same target restores 4 STM.")
                .IncreasesStat(StatType.SameTargetHostileAbilityHitCountRequired, 3)
                .IncreasesStat(StatType.SameTargetHostileAbilityStaminaRestore, 4)
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 35);
        }

        private void VitalRupture()
        {
            _builder.Create(PerkCategoryType.VibroknifeShadow, PerkType.VitalRupture)
                .Name("Vital Rupture")

                .AddPerkLevel()
                .GrantsFeat(FeatType.VitalRupture1)
                .Description("Deals weapon DMG + 30. Bleeding targets take +45 DMG and suffer Hemorrhage for 45 seconds.")
                .Price(6)
                .RequirementSkill(SkillType.Vibroknife, 50);
        }

        private void EnfeeblingStrike()
        {
            _builder.Create(PerkCategoryType.VibroknifeSaboteur, PerkType.EnfeeblingStrike)
                .Name("Enfeebling Strike")

                .AddPerkLevel()
                .GrantsFeat(FeatType.EnfeeblingStrike1)
                .Description("Deals weapon DMG + 10. Inflicts Weakened, reducing Attack by 10% for 30 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 2)

                .AddPerkLevel()
                .GrantsFeat(FeatType.EnfeeblingStrike2)
                .Description("Deals weapon DMG + 22. Inflicts Weakened, reducing Attack by 15% for 30 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 12)

                .AddPerkLevel()
                .GrantsFeat(FeatType.EnfeeblingStrike3)
                .Description("Deals weapon DMG + 34. Inflicts Weakened, reducing Attack by 20% for 30 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.Vibroknife, 28)

                .AddPerkLevel()
                .GrantsFeat(FeatType.EnfeeblingStrike4)
                .Description("Deals weapon DMG + 44. Inflicts Weakened, reducing Attack by 20% for 30 seconds.")
                .Price(5)
                .RequirementSkill(SkillType.Vibroknife, 40);
        }

        private void CalculatedStrikes()
        {
            _builder.Create(PerkCategoryType.VibroknifeSaboteur, PerkType.CalculatedStrikes)
                .Name("Calculated Strikes")

                .AddPerkLevel()
                .GrantsFeat(FeatType.CalculatedStrikesTrait)
                .Description("Auto-attacks have a 15% chance to reduce the target's Accuracy by 10% for 30 seconds.")
                .IncreasesStat(StatType.AutoAttackTargetAccuracyPercentAdjustmentChance, 15)
                .IncreasesStat(StatType.AutoAttackTargetAccuracyPercentAdjustment, -10)
                .IncreasesStat(StatType.AutoAttackTargetAccuracyPercentAdjustmentDurationSeconds, 30)
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 5);
        }

        private void SapVitality()
        {
            _builder.Create(PerkCategoryType.VibroknifeSaboteur, PerkType.SapVitality)
                .Name("Sap Vitality")

                .AddPerkLevel()
                .GrantsFeat(FeatType.SapVitalityTrait)
                .Description("Your hostile debuffs also drain 2 STM from the target. This can trigger once every 6 seconds per target.")
                .IncreasesStat(StatType.VibroknifeSaboteurSapVitalityRank, 2)
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 8)

                .AddPerkLevel()
                .Description("Your hostile debuffs also drain 4 STM from the target. This can trigger once every 6 seconds per target.")
                .IncreasesStat(StatType.VibroknifeSaboteurSapVitalityRank, 4)
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 22)

                .AddPerkLevel()
                .Description("Your hostile debuffs also drain 6 STM from the target. This can trigger once every 6 seconds per target.")
                .IncreasesStat(StatType.VibroknifeSaboteurSapVitalityRank, 6)
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 45);
        }

        private void Hamstring()
        {
            _builder.Create(PerkCategoryType.VibroknifeSaboteur, PerkType.Hamstring)
                .Name("Hamstring")

                .AddPerkLevel()
                .GrantsFeat(FeatType.Hamstring1)
                .Description("Your next attack deals +8 DMG and inflicts Hamstring, reducing movement speed by 20% for 30 seconds.")
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 10)

                .AddPerkLevel()
                .GrantsFeat(FeatType.Hamstring2)
                .Description("Your next attack deals +18 DMG and inflicts Hamstring, reducing movement speed by 20% for 30 seconds.")
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 30)

                .AddPerkLevel()
                .GrantsFeat(FeatType.Hamstring3)
                .Description("Your next attack deals +28 DMG and inflicts Hamstring, reducing movement speed by 20% for 30 seconds.")
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 38);
        }

        private void ExploitWeakness()
        {
            _builder.Create(PerkCategoryType.VibroknifeSaboteur, PerkType.ExploitWeakness)
                .Name("Exploit Weakness")

                .AddPerkLevel()
                .GrantsFeat(FeatType.ExploitWeaknessTrait)
                .Description("Deal +10% damage to enemies affected by any hostile debuff you applied.")
                .IncreasesStat(StatType.DamageToSourceAppliedStatusTargetCategory, (int)StatusEffectCategory.Debuff)
                .IncreasesStat(StatType.DamageToSourceAppliedStatusTargetPercentAdjustment, 10)
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 15);
        }

        private void NerveStrike()
        {
            _builder.Create(PerkCategoryType.VibroknifeSaboteur, PerkType.NerveStrike)
                .Name("Nerve Strike")

                .AddPerkLevel()
                .GrantsFeat(FeatType.NerveStrike1)
                .Description("Deals weapon DMG + 18. Inflicts Disoriented, reducing Accuracy and Evasion by 10% for 30 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.Vibroknife, 18)

                .AddPerkLevel()
                .GrantsFeat(FeatType.NerveStrike2)
                .Description("Deals weapon DMG + 30. Inflicts Disoriented, reducing Accuracy and Evasion by 15% for 30 seconds.")
                .Price(3)
                .RequirementSkill(SkillType.Vibroknife, 32);
        }

        private void DebilitatingStance()
        {
            _builder.Create(PerkCategoryType.VibroknifeSaboteur, PerkType.DebilitatingStance)
                .Name("Debilitating Stance")

                .AddPerkLevel()
                .GrantsFeat(FeatType.DebilitatingStance1)
                .Description("While active, your attacks inflict Hamstring for 30 seconds, but your Attack is reduced by 10%.")
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 20);
        }

        private void CascadeFailure()
        {
            _builder.Create(PerkCategoryType.VibroknifeSaboteur, PerkType.CascadeFailure)
                .Name("Cascade Failure")

                .AddPerkLevel()
                .GrantsFeat(FeatType.CascadeFailureTrait)
                .Description("Critical hits against debuffed targets reduce the target's Defense by 10% for 30 seconds.")
                .IncreasesStat(StatType.CriticalTargetDefensePercentAdjustment, -10)
                .IncreasesStat(StatType.CriticalTargetDefenseDurationSeconds, 30)
                .Price(4)
                .RequirementSkill(SkillType.Vibroknife, 25);
        }

        private void AfflictionMastery()
        {
            _builder.Create(PerkCategoryType.VibroknifeSaboteur, PerkType.AfflictionMastery)
                .Name("Affliction Mastery")

                .AddPerkLevel()
                .GrantsFeat(FeatType.AfflictionMasteryTrait)
                .Description("Debuffs you apply last 25% longer.")
                .IncreasesStat(StatType.OutgoingDebuffDurationPercentAdjustment, 25)
                .Price(2)
                .RequirementSkill(SkillType.Vibroknife, 35);
        }

        private void SystemicShutdown()
        {
            _builder.Create(PerkCategoryType.VibroknifeSaboteur, PerkType.SystemicShutdown)
                .Name("Systemic Shutdown")

                .AddPerkLevel()
                .GrantsFeat(FeatType.SystemicShutdown1)
                .Description("Enemies in the area take weapon DMG + 20 and suffer Weakened, Hamstring, Exhausted, and Disoriented for 45 seconds.")
                .Price(6)
                .RequirementSkill(SkillType.Vibroknife, 50);
        }

    }
}
