// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Rifle
{
    public class AimedShotAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.AimedShot1, PerkType.AimedShot)
                    .Name("Aimed Shot I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.AimedShot, 18.0f),
                SkillType.Rifle,
                8,
                3,
                null,
                null,
                3,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.PointPistol,
                30.0f,
                AbilityType.Perception,
                new GeneratedWeaponAbilityProfile
                {
                    IdleWindowSeconds = 3.0f,
                    ExtraDamageIfIdle = 8
                });

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.AimedShot2, PerkType.AimedShot)
                    .Name("Aimed Shot II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.AimedShot, 18.0f),
                SkillType.Rifle,
                18,
                3,
                null,
                null,
                5,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.PointPistol,
                30.0f,
                AbilityType.Perception,
                new GeneratedWeaponAbilityProfile
                {
                    IdleWindowSeconds = 3.0f,
                    ExtraDamageIfIdle = 14
                });

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.AimedShot3, PerkType.AimedShot)
                    .Name("Aimed Shot III")
                    .Level(3)
                    .HasRecastDelay(RecastGroup.AimedShot, 18.0f),
                SkillType.Rifle,
                28,
                3,
                null,
                null,
                8,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.PointPistol,
                30.0f,
                AbilityType.Perception,
                new GeneratedWeaponAbilityProfile
                {
                    IdleWindowSeconds = 3.0f,
                    ExtraDamageIfIdle = 20
                });

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.AimedShot4, PerkType.AimedShot)
                    .Name("Aimed Shot IV")
                    .Level(4)
                    .HasRecastDelay(RecastGroup.AimedShot, 18.0f),
                SkillType.Rifle,
                38,
                3,
                null,
                null,
                12,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.PointPistol,
                30.0f,
                AbilityType.Perception,
                new GeneratedWeaponAbilityProfile
                {
                    IdleWindowSeconds = 3.0f,
                    ExtraDamageIfIdle = 26
                });

            return builder.Build();
        }
    }
}
