// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Rifle
{
    public class HeadshotAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.Headshot1, PerkType.Headshot)
                    .Name("Headshot I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.Headshot, 30.0f),
                SkillType.Rifle,
                16,
                0,
                null,
                null,
                6,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.PointPistol,
                30.0f,
                AbilityType.Perception,
                new GeneratedWeaponAbilityProfile
                {
                    CriticalRatePercentAdjustment = 15,
                    SelfCriticalRatePercent = 15
                });

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.Headshot2, PerkType.Headshot)
                    .Name("Headshot II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.Headshot, 30.0f),
                SkillType.Rifle,
                30,
                0,
                null,
                null,
                9,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.PointPistol,
                30.0f,
                AbilityType.Perception,
                new GeneratedWeaponAbilityProfile
                {
                    CriticalRatePercentAdjustment = 25,
                    SelfCriticalRatePercent = 25
                });

            return builder.Build();
        }
    }
}
