// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Rifle
{
    public class KillBoxAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.KillBox1, PerkType.KillBox)
                    .Name("Kill Box")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.Capstone, 90.0f),
                SkillType.Rifle,
                20,
                45,
                null,
                null,
                15,
                0,
                2.0f,
                true,
                true,
                false,
                Spell.KillBox1,
                AbilityTargetingShapeType.Sphere,
                8.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.PointPistol,
                30.0f,
                AbilityType.Perception,
                new GeneratedWeaponAbilityProfile
                {
                    TemporaryDefeatedEnemyEffectDurationSeconds = 45,
                    StatusEffectFactory = () => new KillBoxStatusEffect(0, 3)
                });

            return builder.Build();
        }
    }
}
