// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Rifle
{
    public class PiercingRoundAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.PiercingRound1, PerkType.PiercingRound)
                    .Name("Piercing Round I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.PiercingRound, 24.0f),
                SkillType.Rifle,
                12,
                0,
                null,
                null,
                4,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.PiercingRound1,
                AbilityTargetingShapeType.Rect,
                20.0f,
                3.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.PointPistol,
                30.0f,
                AbilityType.Perception,
                new WeaponAbilityProfile
                {
                    DefenseIgnorePercent = 10
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.PiercingRound2, PerkType.PiercingRound)
                    .Name("Piercing Round II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.PiercingRound, 24.0f),
                SkillType.Rifle,
                24,
                0,
                null,
                null,
                8,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.PiercingRound2,
                AbilityTargetingShapeType.Rect,
                20.0f,
                3.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.PointPistol,
                30.0f,
                AbilityType.Perception,
                new WeaponAbilityProfile
                {
                    DefenseIgnorePercent = 15
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.PiercingRound3, PerkType.PiercingRound)
                    .Name("Piercing Round III")
                    .Level(3)
                    .HasRecastDelay(RecastGroup.PiercingRound, 24.0f),
                SkillType.Rifle,
                36,
                0,
                null,
                null,
                10,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.PiercingRound3,
                AbilityTargetingShapeType.Rect,
                20.0f,
                3.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.PointPistol,
                30.0f,
                AbilityType.Perception,
                new WeaponAbilityProfile
                {
                    DefenseIgnorePercent = 20
                });

            return builder.Build();
        }
    }
}
