// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Rifle
{
    public class SuppressingShotAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.SuppressingShot1, PerkType.SuppressingShot)
                    .Name("Suppressing Shot I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.SuppressingShot, 18.0f),
                SkillType.Rifle,
                8,
                30,
                null,
                null,
                3,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.PointPistol,
                30.0f,
                AbilityType.Perception,
                new WeaponAbilityProfile
                {
                    ApplySuppressionStackOnHit = true,
                    SuppressionStackDurationSeconds = 30,
                    SuppressionStackEvasionPenaltyPercent = 2
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.SuppressingShot2, PerkType.SuppressingShot)
                    .Name("Suppressing Shot II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.SuppressingShot, 18.0f),
                SkillType.Rifle,
                18,
                30,
                null,
                null,
                5,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.PointPistol,
                30.0f,
                AbilityType.Perception,
                new WeaponAbilityProfile
                {
                    ApplySuppressionStackOnHit = true,
                    SuppressionStackDurationSeconds = 30,
                    SuppressionStackEvasionPenaltyPercent = 3
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.SuppressingShot3, PerkType.SuppressingShot)
                    .Name("Suppressing Shot III")
                    .Level(3)
                    .HasRecastDelay(RecastGroup.SuppressingShot, 18.0f),
                SkillType.Rifle,
                28,
                30,
                null,
                null,
                8,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.PointPistol,
                30.0f,
                AbilityType.Perception,
                new WeaponAbilityProfile
                {
                    ApplySuppressionStackOnHit = true,
                    SuppressionStackDurationSeconds = 30,
                    SuppressionStackEvasionPenaltyPercent = 4
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.SuppressingShot4, PerkType.SuppressingShot)
                    .Name("Suppressing Shot IV")
                    .Level(4)
                    .HasRecastDelay(RecastGroup.SuppressingShot, 18.0f),
                SkillType.Rifle,
                38,
                30,
                null,
                null,
                12,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.PointPistol,
                30.0f,
                AbilityType.Perception,
                new WeaponAbilityProfile
                {
                    ApplySuppressionStackOnHit = true,
                    SuppressionStackDurationSeconds = 30,
                    SuppressionStackEvasionPenaltyPercent = 5
                });

            return builder.Build();
        }
    }
}
