// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Rifle
{
    public class SuppressiveLineAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.SuppressiveLine1, PerkType.SuppressiveLine)
                    .Name("Suppressive Line I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.SuppressiveLine, 30.0f),
                SkillType.Rifle,
                16,
                30,
                null,
                null,
                6,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.SuppressiveLine1,
                AbilityTargetingShapeType.Rect,
                20.0f,
                3.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.PointPistol,
                30.0f,
                AbilityType.Perception,
                new WeaponAbilityProfile
                {
                    SuppressionDisorientedRequiredStacks = 2,
                    SuppressionDisorientedDurationSeconds = 30
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.SuppressiveLine2, PerkType.SuppressiveLine)
                    .Name("Suppressive Line II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.SuppressiveLine, 30.0f),
                SkillType.Rifle,
                30,
                30,
                null,
                null,
                9,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.SuppressiveLine2,
                AbilityTargetingShapeType.Rect,
                20.0f,
                3.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.PointPistol,
                30.0f,
                AbilityType.Perception,
                new WeaponAbilityProfile
                {
                    SuppressionDisorientedRequiredStacks = 2,
                    SuppressionDisorientedDurationSeconds = 30
                });

            return builder.Build();
        }
    }
}
