namespace SWLOR.Game.Server.Enumeration
{
    public enum ComponentBonusType
    {
        Unknown = 0,
        ModSocketRed = 1,
        ModSocketBlue = 2,
        ModSocketGreen = 3,
        ModSocketYellow = 4,
        ModSocketPrismatic = 5,
        DurabilityUp = 6,
        ChargesUp = 7,
        ACUp = 8,
        RestUp = 9,
        HarvestingUp = 10,
        CooldownRecoveryUp = 11,
        ArmorsmithUp = 12,
        WeaponsmithUp = 13,
        CookingUp = 14,
        EngineeringUp = 15,
        HPUp = 16,
        FPUp = 17,
        EnmityUp = 18,
        EnmityDown = 19,
        DarkPotencyUp = 20,
        LightPotencyUp = 21,
        LuckUp = 22,
        MeditateUp = 23,
        MedicineUp = 24,
        HPRegenUp = 25,
        FPRegenUp = 26,
        BaseAttackBonusUp = 27,
        SneakAttackUp = 28,
        DamageUp = 29,
        DarkPotencyDown = 30,
        LightPotencyDown = 31,
        FabricationUp = 32,
        StructureBonusUp = 33,
        ScanningUp = 34,
        StrengthUp = 35,
        DexterityUp = 36,
        ConstitutionUp = 37,
        WisdomUp = 38,
        IntelligenceUp = 39,
        CharismaUp = 40,
        AttackBonusUp = 41,
        DurationUp = 42,
        MindPotencyUp = 43,
        MindPotencyDown = 44,
        ElectricalPotencyUp = 45,
        ElectricalPotencyDown = 46,
        ForcePotencyUp = 47,
        ForcePotencyDown = 48,
        ForceAccuracyUp = 49,
        ForceAccuracyDown = 50,
        ForceDefenseUp = 51,
        ForceDefenseDown = 52,
        ElectricalDefenseUp = 53,
        ElectricalDefenseDown = 54,
        MindDefenseUp = 55,
        MindDefenseDown = 56,
        LightDefenseUp = 57,
        LightDefenseDown = 58,
        DarkDefenseUp = 59,
        DarkDefenseDown = 60,
        ScavengingUp = 61,
        PilotingUp = 62
        

    }
}
