namespace SWLOR.Game.Server.Enumeration
{
    public enum ComponentType
    {
        None = -1,
        RawOre = 1,
        Metal = 2,
        Organic = 3,
        SmallBlade = 4,
        MediumBlade = 5,
        LargeBlade = 6,
        Shaft = 7,
        SmallHandle = 8,
        MediumHandle = 9,
        LargeHandle = 10,
        Enhancement = 11,
        Fiber = 12,
        Leather = 13,
        Cloth = 14,
        Electronics = 15,
        WoodBatonFrame = 16,
        MetalBatonFrame = 17,
        RangedWeaponCore = 18,
        RifleBarrel = 19,
        PistolBarrel = 20,
        PowerCrystal = 21,
        SaberHilt = 22,
        Seeds = 23,
        BlueCrystal = 24,
        RedCrystal = 25,
        GreenCrystal = 26,
        YellowCrystal = 27,
        BlueCluster = 28,
        RedCluster = 29,
        GreenCluster = 30,
        YellowCluster = 31,
        PowerCluster = 32,
        HeavyArmorCore = 33,
        LightArmorCore = 34,
        ForceArmorCore = 35,
        HeavyArmorSegment = 36,
        LightArmorSegment = 37,
        ForceArmorSegment = 38,
        SmallStructureFrame = 39,
        MediumStructureFrame = 40,
        LargeStructureFrame = 41,
        ComputingModule = 42,
        ConstructionParts = 43,
        Mainframe = 44,
        PowerRelay = 45,
        PowerCore = 46
    }
}
