namespace SWLOR.Game.Server.Enumeration
{
    public enum CustomItemPropertyType
    {
        Unknown = -1,
        RecommendedLevel = 100,
        RestBonus = 101,
        HarvestingBonus = 102,
        CastingSpeed = 103,
        ComponentType = 104,
        CraftBonusWeaponsmith = 105,
        CraftBonusArmorsmith = 106,
        CraftBonusCooking = 107,
        Durability = 108,
        MaxDurability = 109,
        AssociatedSkill = 110,
        CraftTierLevel = 111,
        CraftBonusEngineering = 112,
        HPBonus = 113,
        FPBonus = 114,
        EnmityRate = 115,
        ItemType = 116,
        ArmorClass = 117,
        DarkAbilityBonus = 118,
        LightAbilityBonus = 119,
        SummoningBonus = 120,
        LuckBonus = 121,
        MeditateBonus = 122,
        MedicineBonus = 123,
        HPRegenBonus = 124,
        FPRegenBonus = 125,
        BaseAttackBonus = 126,
        ModSlotRed = 127,
        ModSlotBlue = 128,
        ModSlotGreen = 129,
        ModSlotYellow = 130,
        ModSlotPrismatic = 131,
        RedMod = 132,
        BlueMod = 133,
        GreenMod = 134,
        YellowMod = 135,
        LevelIncrease = 136,
        ComponentBonus = 137,
        ComponentItemTypeRestriction = 138,
        CraftBonusFabrication = 139,
        StructureBonus = 140,
        ScanningBonus = 141
    }
}
