namespace SWLOR.Game.Server.Enumeration
{
    public enum CustomItemPropertyType
    {
        Unknown = -1,
        RecommendedLevel = 100,
        LoggingBonus = 101,
        MiningBonus = 102,
        CastingSpeed = 103,
        ComponentType = 104,
        CraftBonusWeaponsmith = 105,
        CraftBonusArmorsmith = 106,
        CraftBonusCooking = 107,
        Durability = 108,
        MaxDurability = 109,
        AssociatedSkill = 110,
        CraftTierLevel = 111,
        CraftBonusEngineering = 112,
        HPBonus = 113,
        ManaBonus = 114,
        EnmityRate = 115,
        ItemType = 116,
        ArmorClass = 117,
        EvocationBonus = 118,
        AlterationBonus = 119,
        SummoningBonus = 120,
        LuckBonus = 121,
        MeditateBonus = 122,
        FirstAidBonus = 123,
        HPRegenBonus = 124,
        ManaRegenBonus = 125,
        BaseAttackBonus = 126,
        RunicSlotRed = 127,
        RunicSlotBlue = 128,
        RunicSlotGreen = 129,
        RunicSlotYellow = 130,
        RunicSlotPrismatic = 131,
        RedRune = 132,
        BlueRune = 133,
        GreenRune = 134,
        YellowRune = 135,
        LevelIncrease = 136,
        ComponentBonus = 137
    }
}
