using System;
using System.Collections.Generic;

namespace SWLOR.Game.Server.Enumeration
{
    public enum LootTable
    {
        [LootTable("Invalid")]
        Invalid = 0,
        [LootTable("Fiberplast - Tier 1")]
        [LootTableItem("fiberp_ruined", 1, 70, true, "")]
        [LootTableItem("fiberp_flawed", 1, 30, true, "")]
        FiberplastTier1 = 1,
        [LootTable("Fiberplast - Tier 2")]
        [LootTableItem("fiberp_flawed", 1, 70, true, "")]
        [LootTableItem("fiberp_poor", 1, 30, true, "")]
        FiberplastTier2 = 2,
        [LootTable("Fiberplast - Tier 3")]
        [LootTableItem("fiberp_poor", 1, 70, true, "")]
        [LootTableItem("fiberp_quality", 1, 30, true, "")]
        FiberplastTier3 = 3,
        [LootTable("Fiberplast - Tier 4")]
        [LootTableItem("fiberp_quality", 1, 70, true, "")]
        [LootTableItem("fiberp_od", 1, 30, true, "")]
        FiberplastTier4 = 4,
        [LootTable("Fiberplast - Tier 5")]
        [LootTableItem("fiberp_od", 1, 70, true, "")]
        [LootTableItem("fiberp_imperfect", 1, 30, true, "")]
        FiberplastTier5 = 5,
        [LootTable("Fiberplast - Tier 6")]
        [LootTableItem("fiberp_imperfect", 1, 70, true, "")]
        [LootTableItem("fiberp_high", 1, 30, true, "")]
        FiberplastTier6 = 6,
        [LootTable("Fiberplast - Tier 7")]
        [LootTableItem("fiberp_high", 1, 70, true, "")]
        [LootTableItem("fiberp_premium", 1, 30, true, "")]
        FiberplastTier7 = 7,
        [LootTable("Fiberplast - Tier 8")]
        [LootTableItem("fiberp_premium", 1, 70, true, "")]
        [LootTableItem("fiberp_flawless", 1, 30, true, "")]
        FiberplastTier8 = 8,
        [LootTable("Fiberplast - Tier 9")]
        [LootTableItem("fiberp_flawless", 1, 70, true, "")]
        [LootTableItem("fiberp_perfect", 1, 30, true, "")]
        FiberplastTier9 = 9,
        [LootTable("Fiberplast - Tier 10")]
        [LootTableItem("fiberp_perfect", 1, 50, true, "")]
        [LootTableItem("fiberp_flawless", 1, 50, true, "")]
        FiberplastTier10 = 10,
        [LootTable("CZ-220 Scavenge - Scrap Metal")]
        [LootTableItem("scrap_metal", 1, 10, true, "")]
        CZ220ScavengeScrapMetal = 11,
        [LootTable("CZ-220 Mynocks")]
        [LootTableItem("mynock_wing", 1, 3, true, "")]
        [LootTableItem("lth_destroyed", 1, 10, true, "")]
        [LootTableItem("mynock_meat", 1, 10, true, "")]
        [LootTableItem("mynock_tooth", 1, 12, true, "")]
        CZ220Mynocks = 12,
        [LootTable("CZ-220 Malfunctioning Droids")]
        [LootTableItem("scrap_metal", 1, 10, true, "")]
        [LootTableItem("elec_destroyed", 1, 6, true, "")]
        [LootTableItem("power_crystal_po", 1, 6, true, "")]
        CZ220MalfunctioningDroids = 13,
        [LootTable("CZ-220 Colicoid Experiment")]
        [LootTableItem("colicoid_leg_a", 1, 10, true, "")]
        [LootTableItem("colicoid_leg_w", 1, 10, true, "")]
        [LootTableItem("colicoid_leg_e", 1, 10, true, "")]
        [LootTableItem("colicoid_leg_f", 1, 10, true, "")]
        [LootTableItem("colicoid_leg_c", 1, 10, true, "")]
        CZ220ColicoidExperiment = 14,
        [LootTable("Base Drill - Viscara Wildlands NE")]
        [LootTableItem("c_cluster_power", 1, 15, true, "")]
        [LootTableItem("raw_plagionite", 1, 10, true, "")]
        [LootTableItem("raw_scordspar", 1, 30, true, "")]
        [LootTableItem("plexite_gem", 1, 8, true, "")]
        [LootTableItem("raw_veldite", 1, 70, true, "")]
        [LootTableItem("corylus", 1, 6, true, "")]
        [LootTableItem("omedia", 1, 8, true, "")]
        [LootTableItem("pawisis", 1, 8, true, "")]
        [LootTableItem("pefoate", 1, 8, true, "")]
        [LootTableItem("sygium_gem", 1, 2, true, "")]
        [LootTableItem("regvis_gem", 1, 2, true, "")]
        [LootTableItem("vendusii_gem", 1, 1, true, "")]
        [LootTableItem("hollinium", 1, 15, true, "")]
        [LootTableItem("rruchi", 1, 5, true, "")]
        [LootTableItem("f_crystal_blue", 1, 2, true, "")]
        BaseDrillViscaraWildlandsNE = 15,
        [LootTable("Kath Hounds - Viscara")]
        [LootTableItem("k_hound_fur", 1, 5, true, "")]
        [LootTableItem("k_hound_tooth", 1, 5, true, "")]
        [LootTableItem("lth_flawed", 1, 7, true, "")]
        [LootTableItem("lth_ruined", 1, 15, true, "")]
        KathHoundsViscara = 16,
        [LootTable("Base Drill - Viscara Wildlands NW")]
        [LootTableItem("raw_scordspar", 1, 30, true, "")]
        [LootTableItem("plexite_gem", 1, 8, true, "")]
        [LootTableItem("raw_veldite", 1, 70, true, "")]
        [LootTableItem("corylus", 1, 6, true, "")]
        [LootTableItem("omedia", 1, 8, true, "")]
        [LootTableItem("pawisis", 1, 8, true, "")]
        [LootTableItem("tinnuchi", 1, 5, true, "")]
        [LootTableItem("sygium_gem", 1, 2, true, "")]
        [LootTableItem("regvis_gem", 1, 2, true, "")]
        [LootTableItem("vendusii_gem", 1, 1, true, "")]
        [LootTableItem("c_cluster_power", 1, 15, true, "")]
        [LootTableItem("raw_plagionite", 1, 10, true, "")]
        [LootTableItem("pefoate", 1, 8, true, "")]
        [LootTableItem("hollinium", 1, 15, true, "")]
        [LootTableItem("f_crystal_red", 1, 2, true, "")]
        BaseDrillViscaraWildlandsNW = 17,
        [LootTable("Base Drill - Viscara Wildlands SE")]
        [LootTableItem("vendusii_gem", 1, 1, true, "")]
        [LootTableItem("regvis_gem", 1, 2, true, "")]
        [LootTableItem("sygium_gem", 1, 2, true, "")]
        [LootTableItem("pefoate", 1, 8, true, "")]
        [LootTableItem("pawisis", 1, 8, true, "")]
        [LootTableItem("omedia", 1, 8, true, "")]
        [LootTableItem("hollinium", 1, 15, true, "")]
        [LootTableItem("raw_veldite", 1, 70, true, "")]
        [LootTableItem("plexite_gem", 1, 8, true, "")]
        [LootTableItem("raw_scordspar", 1, 30, true, "")]
        [LootTableItem("raw_plagionite", 1, 10, true, "")]
        [LootTableItem("c_cluster_power", 1, 15, true, "")]
        [LootTableItem("corylus", 1, 6, true, "")]
        [LootTableItem("stalluchi", 1, 5, true, "")]
        [LootTableItem("f_crystal_yellow", 1, 2, true, "")]
        BaseDrillViscaraWildlandsSE = 18,
        [LootTable("Base Drill - Viscara Wildlands SW")]
        [LootTableItem("vendusii_gem", 1, 1, true, "")]
        [LootTableItem("regvis_gem", 1, 2, true, "")]
        [LootTableItem("sygium_gem", 1, 2, true, "")]
        [LootTableItem("pefoate", 1, 8, true, "")]
        [LootTableItem("pawisis", 1, 8, true, "")]
        [LootTableItem("omedia", 1, 8, true, "")]
        [LootTableItem("hollinium", 1, 15, true, "")]
        [LootTableItem("raw_veldite", 1, 70, true, "")]
        [LootTableItem("plexite_gem", 1, 8, true, "")]
        [LootTableItem("raw_scordspar", 1, 30, true, "")]
        [LootTableItem("raw_plagionite", 1, 10, true, "")]
        [LootTableItem("c_cluster_power", 1, 15, true, "")]
        [LootTableItem("corylus", 1, 6, true, "")]
        [LootTableItem("uunuchi", 1, 5, true, "")]
        [LootTableItem("f_crystal_green", 1, 2, true, "")]
        BaseDrillViscaraWildlandsSW = 19,
        [LootTable("Mandalorian Facility")]
        [LootTableItem("healing_kit", 1, 1, true, "")]
        [LootTableItem("bandages", 1, 8, true, "")]
        [LootTableItem("m_lvibro_parts", 1, 5, true, "")]
        [LootTableItem("m_vibro_parts", 1, 5, true, "")]
        [LootTableItem("man_tags", 1, 10, true, "")]
        [LootTableItem("m_plexiplate", 1, 2, true, "")]
        [LootTableItem("m_e_cell", 1, 6, true, "")]
        [LootTableItem("m_plate", 1, 5, true, "")]
        [LootTableItem("nw_it_gold001", 17, 5, true, "")]
        [LootTableItem("m_blast_parts", 1, 5, true, "")]
        [LootTableItem("nw_it_gold001", 25, 2, true, "")]
        MandalorianFacility = 20,
        [LootTable("Mandalorian Facility Scavenge Sites")]
        [LootTableItem("force_pack_1", 1, 2, true, "")]
        [LootTableItem("m_electronics", 1, 6, true, "")]
        [LootTableItem("power_crystal_fa", 1, 5, true, "")]
        [LootTableItem("man_tags", 1, 10, true, "")]
        [LootTableItem("man_metal", 1, 5, true, "")]
        [LootTableItem("healing_kit", 1, 2, true, "")]
        [LootTableItem("bandages", 1, 5, true, "")]
        MandalorianFacilityScavengeSites = 21,
        [LootTable("Mandalorian Leader")]
        [LootTableItem("stim_dex1", 1, 2, true, "")]
        [LootTableItem("stim_str1", 1, 2, true, "")]
        [LootTableItem("stim_wis1", 1, 2, true, "")]
        [LootTableItem("stim_cha1", 1, 2, true, "")]
        [LootTableItem("man_helm", 1, 3, true, "")]
        [LootTableItem("m_plexiplate", 1, 10, true, "")]
        [LootTableItem("m_ls_parts", 1, 10, true, "")]
        [LootTableItem("m_polearm_parts", 1, 10, true, "")]
        [LootTableItem("v_power_cell", 1, 1, true, "")]
        [LootTableItem("herb_m", 1, 5, true, "")]
        [LootTableItem("stim_con1", 1, 2, true, "")]
        [LootTableItem("stim_int1", 1, 2, true, "")]
        [LootTableItem("greatsword_mando", 1, 1, true, "")]
        MandalorianLeader = 22,
        [LootTable("Viscara - Wildwoods Looters")]
        [LootTableItem("nw_it_gold001", 5, 25, true, "")]
        [LootTableItem("nw_it_gold001", 10, 10, true, "")]
        [LootTableItem("nw_it_gold001", 15, 5, true, "")]
        [LootTableItem("nw_it_gold001", 20, 1, true, "")]
        [LootTableItem("elec_flawed", 1, 50, true, "")]
        [LootTableItem("elec_poor", 1, 40, true, "")]
        [LootTableItem("des_light_chest", 1, 5, true, "")]
        [LootTableItem("des_light_boots", 1, 10, true, "")]
        [LootTableItem("des_light_belt", 1, 10, true, "")]
        [LootTableItem("des_light_amm", 1, 4, true, "")]
        [LootTableItem("des_light_helm", 1, 8, true, "")]
        [LootTableItem("des_force_chest", 1, 5, true, "")]
        [LootTableItem("des_force_boots", 1, 10, true, "")]
        [LootTableItem("des_force_belt", 1, 10, true, "")]
        [LootTableItem("des_force_amm", 1, 4, true, "")]
        [LootTableItem("des_force_helm", 1, 8, true, "")]
        [LootTableItem("des_heavy_chest", 1, 5, true, "")]
        [LootTableItem("des_heavy_boots", 1, 10, true, "")]
        [LootTableItem("des_heavy_belt", 1, 10, true, "")]
        [LootTableItem("des_heavy_amm", 1, 4, true, "")]
        ViscaraWildwoodsLooters = 23,
        [LootTable("Viscara - Wildwoods Gimpassa")]
        [LootTableItem("lth_flawed", 1, 10, true, "")]
        [LootTableItem("gimp_shell", 1, 2, true, "")]
        [LootTableItem("lth_poor", 1, 3, true, "")]
        [LootTableItem("gimp_tooth", 1, 5, true, "")]
        ViscaraWildwoodsGimpassa = 24,
        [LootTable("Viscara - Wildwoods Kinrath")]
        [LootTableItem("kinrath_limb", 1, 5, true, "")]
        [LootTableItem("kinrath_meat", 1, 10, true, "")]
        [LootTableItem("kinrath_silk", 1, 20, true, "")]
        ViscaraWildwoodsKinrath = 25,
        [LootTable("Viscara - Valley Cairnmog")]
        [LootTableItem("cairnmog_meat", 1, 7, true, "")]
        [LootTableItem("lth_quality", 1, 3, true, "")]
        [LootTableItem("lth_poor", 1, 10, true, "")]
        [LootTableItem("cairnmog_spine", 1, 9, true, "")]
        [LootTableItem("cairnmog_blood", 1, 5, true, "")]
        ViscaraValleyCairnmog = 26,
        [LootTable("Base Drill - Viscara Wildwoods NE")]
        [LootTableItem("c_cluster_power", 1, 4, true, "")]
        [LootTableItem("medcina", 1, 8, true, "")]
        [LootTableItem("fabrino", 1, 8, true, "")]
        [LootTableItem("coqina", 1, 8, true, "")]
        [LootTableItem("engina", 1, 8, true, "")]
        [LootTableItem("arvvina", 1, 8, true, "")]
        [LootTableItem("weevina", 1, 8, true, "")]
        [LootTableItem("plexite_gem", 1, 8, true, "")]
        [LootTableItem("nibullan", 1, 4, true, "")]
        [LootTableItem("harvino", 1, 8, true, "")]
        [LootTableItem("corylus", 1, 9, true, "")]
        [LootTableItem("porlang", 1, 1, true, "")]
        [LootTableItem("raw_plagionite", 1, 10, true, "")]
        [LootTableItem("raw_veldite", 1, 2, true, "")]
        [LootTableItem("raw_scordspar", 1, 20, true, "")]
        [LootTableItem("hzzuntil", 1, 4, true, "")]
        [LootTableItem("ultranio", 1, 1, true, "")]
        [LootTableItem("f_crystal_blue", 1, 2, true, "")]
        BaseDrillViscaraWildwoodsNE = 27,
        [LootTable("Base Drill - Viscara Wildwoods NW")]
        [LootTableItem("c_cluster_power", 1, 4, true, "")]
        [LootTableItem("medcina", 1, 8, true, "")]
        [LootTableItem("fabrino", 1, 8, true, "")]
        [LootTableItem("coqina", 1, 8, true, "")]
        [LootTableItem("engina", 1, 8, true, "")]
        [LootTableItem("arvvina", 1, 8, true, "")]
        [LootTableItem("weevina", 1, 8, true, "")]
        [LootTableItem("plexite_gem", 1, 8, true, "")]
        [LootTableItem("nibullan", 1, 4, true, "")]
        [LootTableItem("harvino", 1, 8, true, "")]
        [LootTableItem("corylus", 1, 9, true, "")]
        [LootTableItem("porlang", 1, 1, true, "")]
        [LootTableItem("raw_plagionite", 1, 10, true, "")]
        [LootTableItem("raw_veldite", 1, 2, true, "")]
        [LootTableItem("raw_scordspar", 1, 20, true, "")]
        [LootTableItem("hzzuntil", 1, 4, true, "")]
        [LootTableItem("ultranio", 1, 1, true, "")]
        [LootTableItem("f_crystal_red", 1, 2, true, "")]
        BaseDrillViscaraWildwoodsNW = 28,
        [LootTable("Base Drill - Viscara Wildwoods SE")]
        [LootTableItem("c_cluster_power", 1, 4, true, "")]
        [LootTableItem("medcina", 1, 8, true, "")]
        [LootTableItem("fabrino", 1, 8, true, "")]
        [LootTableItem("coqina", 1, 8, true, "")]
        [LootTableItem("engina", 1, 8, true, "")]
        [LootTableItem("arvvina", 1, 8, true, "")]
        [LootTableItem("weevina", 1, 8, true, "")]
        [LootTableItem("plexite_gem", 1, 8, true, "")]
        [LootTableItem("nibullan", 1, 4, true, "")]
        [LootTableItem("harvino", 1, 8, true, "")]
        [LootTableItem("corylus", 1, 9, true, "")]
        [LootTableItem("porlang", 1, 1, true, "")]
        [LootTableItem("raw_plagionite", 1, 10, true, "")]
        [LootTableItem("raw_veldite", 1, 2, true, "")]
        [LootTableItem("raw_scordspar", 1, 20, true, "")]
        [LootTableItem("hzzuntil", 1, 4, true, "")]
        [LootTableItem("ultranio", 1, 1, true, "")]
        [LootTableItem("f_crystal_yellow", 1, 2, true, "")]
        BaseDrillViscaraWildwoodsSE = 29,
        [LootTable("Base Drill - Viscara Wildwoods SW")]
        [LootTableItem("c_cluster_power", 1, 4, true, "")]
        [LootTableItem("medcina", 1, 8, true, "")]
        [LootTableItem("fabrino", 1, 8, true, "")]
        [LootTableItem("coqina", 1, 8, true, "")]
        [LootTableItem("engina", 1, 8, true, "")]
        [LootTableItem("arvvina", 1, 8, true, "")]
        [LootTableItem("weevina", 1, 8, true, "")]
        [LootTableItem("plexite_gem", 1, 8, true, "")]
        [LootTableItem("nibullan", 1, 4, true, "")]
        [LootTableItem("harvino", 1, 8, true, "")]
        [LootTableItem("corylus", 1, 9, true, "")]
        [LootTableItem("porlang", 1, 1, true, "")]
        [LootTableItem("raw_plagionite", 1, 10, true, "")]
        [LootTableItem("raw_veldite", 1, 2, true, "")]
        [LootTableItem("raw_scordspar", 1, 20, true, "")]
        [LootTableItem("hzzuntil", 1, 4, true, "")]
        [LootTableItem("ultranio", 1, 1, true, "")]
        [LootTableItem("f_crystal_green", 1, 2, true, "")]
        BaseDrillViscaraWildwoodsSW = 30,
        [LootTable("Viscara - Mountain Valley NE")]
        [LootTableItem("stalluchi", 1, 6, true, "")]
        [LootTableItem("vendusii_gem", 1, 4, true, "")]
        [LootTableItem("ultranio", 1, 3, true, "")]
        [LootTableItem("raw_keromber", 1, 10, true, "")]
        [LootTableItem("c_cluster_power", 1, 5, true, "")]
        [LootTableItem("raw_scordspar", 1, 30, true, "")]
        [LootTableItem("raw_plagionite", 1, 20, true, "")]
        [LootTableItem("plexite_gem", 1, 6, true, "")]
        [LootTableItem("tinnuchi", 1, 1, true, "")]
        [LootTableItem("f_crystal_blue", 1, 2, true, "")]
        ViscaraMountainValleyNE = 31,
        [LootTable("Viscara - Mountain Valley NW")]
        [LootTableItem("stalluchi", 1, 6, true, "")]
        [LootTableItem("vendusii_gem", 1, 4, true, "")]
        [LootTableItem("ultranio", 1, 3, true, "")]
        [LootTableItem("raw_keromber", 1, 10, true, "")]
        [LootTableItem("c_cluster_power", 1, 5, true, "")]
        [LootTableItem("raw_scordspar", 1, 30, true, "")]
        [LootTableItem("raw_plagionite", 1, 20, true, "")]
        [LootTableItem("plexite_gem", 1, 6, true, "")]
        [LootTableItem("tinnuchi", 1, 1, true, "")]
        [LootTableItem("f_crystal_red", 1, 2, true, "")]
        ViscaraMountainValleyNW = 32,
        [LootTable("Viscara - Mountain Valley SE")]
        [LootTableItem("stalluchi", 1, 6, true, "")]
        [LootTableItem("vendusii_gem", 1, 4, true, "")]
        [LootTableItem("ultranio", 1, 3, true, "")]
        [LootTableItem("raw_keromber", 1, 10, true, "")]
        [LootTableItem("c_cluster_power", 1, 5, true, "")]
        [LootTableItem("raw_scordspar", 1, 30, true, "")]
        [LootTableItem("raw_plagionite", 1, 20, true, "")]
        [LootTableItem("plexite_gem", 1, 6, true, "")]
        [LootTableItem("tinnuchi", 1, 1, true, "")]
        [LootTableItem("f_crystal_yellow", 1, 2, true, "")]
        ViscaraMountainValleySE = 33,
        [LootTable("Viscara - Mountain Valley SW")]
        [LootTableItem("stalluchi", 1, 6, true, "")]
        [LootTableItem("vendusii_gem", 1, 4, true, "")]
        [LootTableItem("ultranio", 1, 3, true, "")]
        [LootTableItem("raw_keromber", 1, 10, true, "")]
        [LootTableItem("c_cluster_power", 1, 5, true, "")]
        [LootTableItem("raw_scordspar", 1, 30, true, "")]
        [LootTableItem("raw_plagionite", 1, 20, true, "")]
        [LootTableItem("plexite_gem", 1, 6, true, "")]
        [LootTableItem("tinnuchi", 1, 1, true, "")]
        [LootTableItem("f_crystal_green", 1, 2, true, "")]
        ViscaraMountainValleySW = 34,
        [LootTable("Viscara - Deep Mountains NE")]
        [LootTableItem("tinnuchi", 1, 1, true, "")]
        [LootTableItem("plexite_gem", 1, 6, true, "")]
        [LootTableItem("raw_plagionite", 1, 30, true, "")]
        [LootTableItem("c_cluster_power", 1, 5, true, "")]
        [LootTableItem("stalluchi", 1, 6, true, "")]
        [LootTableItem("ultranio", 1, 3, true, "")]
        [LootTableItem("vendusii_gem", 1, 4, true, "")]
        [LootTableItem("raw_jasioclase", 1, 5, true, "")]
        [LootTableItem("raw_keromber", 1, 20, true, "")]
        [LootTableItem("coonlank_blue", 1, 1, true, "")]
        [LootTableItem("f_crystal_blue", 1, 2, true, "")]
        ViscaraDeepMountainsNE = 35,
        [LootTable("Viscara - Deep Mountains NW")]
        [LootTableItem("raw_jasioclase", 1, 5, true, "")]
        [LootTableItem("vendusii_gem", 1, 4, true, "")]
        [LootTableItem("ultranio", 1, 3, true, "")]
        [LootTableItem("raw_keromber", 1, 20, true, "")]
        [LootTableItem("c_cluster_power", 1, 5, true, "")]
        [LootTableItem("raw_plagionite", 1, 30, true, "")]
        [LootTableItem("plexite_gem", 1, 6, true, "")]
        [LootTableItem("tinnuchi", 1, 1, true, "")]
        [LootTableItem("stalluchi", 1, 6, true, "")]
        [LootTableItem("coonlank_red", 1, 1, true, "")]
        [LootTableItem("f_crystal_red", 1, 2, true, "")]
        ViscaraDeepMountainsNW = 36,
        [LootTable("Viscara - Deep Mountains SE")]
        [LootTableItem("vendusii_gem", 1, 4, true, "")]
        [LootTableItem("ultranio", 1, 3, true, "")]
        [LootTableItem("raw_keromber", 1, 20, true, "")]
        [LootTableItem("c_cluster_power", 1, 5, true, "")]
        [LootTableItem("raw_jasioclase", 1, 5, true, "")]
        [LootTableItem("plexite_gem", 1, 6, true, "")]
        [LootTableItem("tinnuchi", 1, 1, true, "")]
        [LootTableItem("stalluchi", 1, 6, true, "")]
        [LootTableItem("raw_plagionite", 1, 30, true, "")]
        [LootTableItem("coonlank_yellow", 1, 1, true, "")]
        [LootTableItem("f_crystal_yellow", 1, 2, true, "")]
        ViscaraDeepMountainsSE = 37,
        [LootTable("Viscara - Deep Mountains SW")]
        [LootTableItem("raw_jasioclase", 1, 5, true, "")]
        [LootTableItem("vendusii_gem", 1, 4, true, "")]
        [LootTableItem("ultranio", 1, 3, true, "")]
        [LootTableItem("raw_keromber", 1, 20, true, "")]
        [LootTableItem("c_cluster_power", 1, 5, true, "")]
        [LootTableItem("raw_plagionite", 1, 30, true, "")]
        [LootTableItem("plexite_gem", 1, 6, true, "")]
        [LootTableItem("tinnuchi", 1, 1, true, "")]
        [LootTableItem("stalluchi", 1, 6, true, "")]
        [LootTableItem("coonlank_green", 1, 1, true, "")]
        [LootTableItem("f_crystal_green", 1, 2, true, "")]
        ViscaraDeepMountainsSW = 38,
        [LootTable("Viscara - Coxxion Base (Instance)")]
        [LootTableItem("nw_it_gold001", 30, 10, true, "")]
        [LootTableItem("cox_meat", 1, 7, true, "")]
        [LootTableItem("fiberp_flawed", 1, 3, true, "")]
        [LootTableItem("club_cox", 1, 1, true, "")]
        [LootTableItem("spear_cox", 1, 1, true, "")]
        [LootTableItem("herb_question", 1, 10, true, "")]
        [LootTableItem("power_crystal_po", 1, 4, true, "")]
        [LootTableItem("const_parts_cox", 1, 5, true, "")]
        [LootTableItem("power_crystal_fa", 1, 1, true, "")]
        [LootTableItem("r_light_chest", 1, 5, true, "")]
        [LootTableItem("r_light_boots", 1, 10, true, "")]
        [LootTableItem("r_light_belt", 1, 10, true, "")]
        [LootTableItem("r_light_amm", 1, 4, true, "")]
        [LootTableItem("r_light_helm", 1, 8, true, "")]
        [LootTableItem("r_force_chest", 1, 5, true, "")]
        [LootTableItem("r_force_boots", 1, 10, true, "")]
        [LootTableItem("r_force_belt", 1, 10, true, "")]
        [LootTableItem("r_force_amm", 1, 4, true, "")]
        [LootTableItem("r_force_helm", 1, 8, true, "")]
        [LootTableItem("r_heavy_chest", 1, 5, true, "")]
        [LootTableItem("r_heavy_boots", 1, 10, true, "")]
        [LootTableItem("r_heavy_belt", 1, 10, true, "")]
        [LootTableItem("r_heavy_amm", 1, 4, true, "")]
        [LootTableItem("r_heavy_helm", 1, 8, true, "")]
        ViscaraCoxxionBaseInstance = 39,
        [LootTable("Viscara - Coxxion Base Scavenge Points")]
        [LootTableItem("p_crystal_yellow", 1, 10, true, "")]
        [LootTableItem("p_crystal_blue", 1, 10, true, "")]
        [LootTableItem("p_crystal_red", 1, 10, true, "")]
        [LootTableItem("nw_it_gold001", 15, 10, true, "")]
        [LootTableItem("const_parts_cox", 1, 5, true, "")]
        [LootTableItem("cosian_wood", 1, 6, true, "")]
        [LootTableItem("p_crystal_green", 1, 10, true, "")]
        [LootTableItem("cox_electronics", 1, 4, true, "")]
        [LootTableItem("rruchi", 1, 1, true, "")]
        ViscaraCoxxionBaseScavengePoints = 40,
        [LootTable("Viscara - Coxxion Base Leader 1")]
        [LootTableItem("ls_parts_dest", 1, 10, true, "")]
        ViscaraCoxxionBaseLeader1 = 41,
        [LootTable("Viscara - Coxxion Base Leader 2")]
        [LootTableItem("rruchi", 1, 1, true, "")]
        [LootTableItem("morningstar_cox", 1, 2, true, "")]
        [LootTableItem("cox_visor", 1, 10, true, "")]
        [LootTableItem("small_shield_fle", 1, 10, true, "")]
        [LootTableItem("cox_electronics", 1, 1, true, "")]
        [LootTableItem("power_crystal_fl", 1, 5, true, "")]
        [LootTableItem("cox_metal", 1, 2, true, "")]
        [LootTableItem("cox_helmlight", 1, 10, true, "")]
        [LootTableItem("cox_hood001", 1, 1, true, "")]
        ViscaraCoxxionBaseLeader2 = 42,
        [LootTable("Viscara - Deep Mountains Raivors")]
        [LootTableItem("raivor_meat", 1, 10, true, "")]
        [LootTableItem("raivor_claw", 1, 10, true, "")]
        [LootTableItem("raivor_tail_bone", 1, 10, true, "")]
        ViscaraDeepMountainsRaivors = 43,
        [LootTable("Kath Hounds 2 - Viscara")]
        [LootTableItem("kath_meat_1", 1, 10, true, "")]
        KathHounds2Viscara = 44,
        [LootTable("CZ-220 Scavenge - Fiberplast")]
        [LootTableItem("fiberp_destroyed", 1, 10, true, "")]
        CZ220ScavengeFiberplast = 45,
        [LootTable("Viscara - Crystal Cavern Spiders")]
        [LootTableItem("p_crystal_blue", 1, 10, true, "")]
        [LootTableItem("p_crystal_red", 1, 10, true, "")]
        [LootTableItem("p_crystal_green", 1, 10, true, "")]
        [LootTableItem("p_crystal_yellow", 1, 10, true, "")]
        ViscaraCrystalCavernSpiders = 46,
        [LootTable("Viscara - Herb Patch")]
        [LootTableItem("herb_v", 1, 30, true, "")]
        ViscaraHerbPatch = 47,
        [LootTable("Viscara - Warocas")]
        [LootTableItem("warocas_beak", 1, 20, true, "")]
        [LootTableItem("waro_feathers", 1, 5, true, "")]
        [LootTableItem("lth_ruined", 1, 15, true, "")]
        [LootTableItem("warocas_meat", 1, 25, true, "")]
        ViscaraWarocas = 48,
        [LootTable("Viscara - Warocas (Rares)")]
        [LootTableItem("waro_leg", 1, 20, true, "")]
        [LootTableItem("lth_flawed", 1, 30, true, "")]
        ViscaraWarocasRares = 49,
        [LootTable("Viscara - Valley Nashtah")]
        [LootTableItem("nashtah_meat", 1, 30, true, "")]
        [LootTableItem("nash_scale", 1, 10, true, "")]
        [LootTableItem("nash_tail", 1, 2, true, "")]
        ViscaraValleyNashtah = 50,
        [LootTable("Space - Basic Loot")]
        [LootTableItem("rruchi", 1, 3, true, "")]
        [LootTableItem("stalluchi", 1, 3, true, "")]
        [LootTableItem("tinnuchi", 1, 3, true, "")]
        [LootTableItem("plexite_gem", 1, 2, true, "")]
        [LootTableItem("ultranio", 1, 1, true, "")]
        [LootTableItem("coonlank_yellow", 1, 1, true, "")]
        [LootTableItem("coonlank_red", 1, 1, true, "")]
        [LootTableItem("coonlank_blue", 1, 1, true, "")]
        [LootTableItem("coonlank_green", 1, 1, true, "")]
        [LootTableItem("vendusii_gem", 1, 1, true, "")]
        [LootTableItem("hzzuntil", 1, 1, true, "")]
        [LootTableItem("corylus", 1, 2, true, "")]
        [LootTableItem("porlang", 1, 3, true, "")]
        [LootTableItem("harvino", 1, 3, true, "")]
        [LootTableItem("arvvina", 1, 2, true, "")]
        [LootTableItem("engina", 1, 2, true, "")]
        [LootTableItem("fabrina", 1, 2, true, "")]
        [LootTableItem("coqina", 1, 2, true, "")]
        [LootTableItem("weevina", 1, 2, true, "")]
        [LootTableItem("medcina", 1, 2, true, "")]
        [LootTableItem("uunichi", 1, 3, true, "")]
        [LootTableItem("pawisis", 1, 5, true, "")]
        [LootTableItem("pefoate", 1, 5, true, "")]
        [LootTableItem("sygium_gem", 1, 1, true, "")]
        [LootTableItem("regvis_gem", 1, 1, true, "")]
        [LootTableItem("hollinium", 1, 3, true, "")]
        [LootTableItem("omedia", 1, 5, true, "")]
        [LootTableItem("nibullan", 1, 3, true, "")]
        [LootTableItem("ass_power", 1, 1, true, "")]
        SpaceBasicLoot = 51,
        [LootTable("Starship Pirates - Basic")]
        [LootTableItem("stronidium", 20, 20, true, "")]
        [LootTableItem("fuel_cell", 5, 20, true, "")]
        [LootTableItem("ass_power", 1, 1, true, "")]
        StarshipPiratesBasic = 52,
        [LootTable("Starship Pirates - Rare")]
        [LootTableItem("sswpn1", 1, 10, true, "")]
        [LootTableItem("ssshld1", 1, 10, true, "")]
        [LootTableItem("ssspd1", 1, 10, true, "")]
        [LootTableItem("ssrang1", 1, 10, true, "")]
        [LootTableItem("ssfuel1", 1, 10, true, "")]
        [LootTableItem("ssstron1", 1, 10, true, "")]
        [LootTableItem("ssstlth1", 1, 10, true, "")]
        [LootTableItem("ssscan1", 1, 10, true, "")]
        [LootTableItem("sswpn2", 1, 1, true, "")]
        [LootTableItem("ssshld2", 1, 1, true, "")]
        [LootTableItem("ssspd2", 1, 1, true, "")]
        [LootTableItem("ssrang2", 1, 1, true, "")]
        [LootTableItem("ssfuel2", 1, 1, true, "")]
        [LootTableItem("ssstron2", 1, 1, true, "")]
        [LootTableItem("ssstlth2", 1, 1, true, "")]
        [LootTableItem("ssscan2", 1, 1, true, "")]
        [LootTableItem("ass_power", 1, 1, true, "")]
        StarshipPiratesRare = 53,
        [LootTable("Reassembly Fuel Cell")]
        [LootTableItem("ass_power", 1, 10, true, "")]
        ReassemblyFuelCell = 54,
        [LootTable("Mon Cala Coral Isles 1 - Northeast")]
        [LootTableItem("raw_veldite", 1, 5, true, "")]
        [LootTableItem("raw_scordspar", 1, 5, true, "")]
        [LootTableItem("raw_keromber", 1, 20, true, "")]
        [LootTableItem("raw_plagionite", 1, 20, true, "")]
        [LootTableItem("raw_jasioclase", 1, 40, true, "")]
        [LootTableItem("raw_hemorgite", 1, 40, true, "")]
        [LootTableItem("hollinium", 1, 3, true, "")]
        [LootTableItem("harvino", 1, 3, true, "")]
        [LootTableItem("stalluchi", 1, 3, true, "")]
        [LootTableItem("engina", 1, 3, true, "")]
        [LootTableItem("f_crystal_green", 1, 3, true, "")]
        [LootTableItem("corylus", 1, 3, true, "")]
        [LootTableItem("coonlank_green", 1, 3, true, "")]
        MonCalaCoralIsles1Northeast = 90,
        [LootTable("Mon Cala Coral Isles 1 - Northwest")]
        [LootTableItem("raw_veldite", 1, 5, true, "")]
        [LootTableItem("raw_scordspar", 1, 5, true, "")]
        [LootTableItem("raw_keromber", 1, 20, true, "")]
        [LootTableItem("raw_plagionite", 1, 20, true, "")]
        [LootTableItem("raw_jasioclase", 1, 40, true, "")]
        [LootTableItem("raw_hemorgite", 1, 40, true, "")]
        [LootTableItem("hollinium", 1, 3, true, "")]
        [LootTableItem("harvino", 1, 3, true, "")]
        [LootTableItem("gorruchi", 1, 3, true, "")]
        [LootTableItem("fabrino", 1, 3, true, "")]
        [LootTableItem("f_crystal_yellow", 1, 3, true, "")]
        [LootTableItem("corylus", 1, 3, true, "")]
        [LootTableItem("coonlank_yellow", 1, 3, true, "")]
        MonCalaCoralIsles1Northwest = 91,
        [LootTable("Mon Cala Coral Isles 1 - Southeast")]
        [LootTableItem("raw_veldite", 1, 5, true, "")]
        [LootTableItem("raw_scordspar", 1, 5, true, "")]
        [LootTableItem("raw_keromber", 1, 20, true, "")]
        [LootTableItem("raw_plagionite", 1, 20, true, "")]
        [LootTableItem("raw_jasioclase", 1, 40, true, "")]
        [LootTableItem("raw_hemorgite", 1, 40, true, "")]
        [LootTableItem("hollinium", 1, 3, true, "")]
        [LootTableItem("harvino", 1, 3, true, "")]
        [LootTableItem("gorruchi", 1, 3, true, "")]
        [LootTableItem("weevina", 1, 3, true, "")]
        [LootTableItem("f_crystal_red", 1, 3, true, "")]
        [LootTableItem("corylus", 1, 3, true, "")]
        [LootTableItem("coonlank_red", 1, 3, true, "")]
        MonCalaCoralIsles1Southeast = 92,
        [LootTable("Mon Cala Coral Isles 1 - Southwest")]
        [LootTableItem("raw_veldite", 1, 5, true, "")]
        [LootTableItem("raw_scordspar", 1, 5, true, "")]
        [LootTableItem("raw_keromber", 1, 20, true, "")]
        [LootTableItem("raw_plagionite", 1, 20, true, "")]
        [LootTableItem("raw_jasioclase", 1, 40, true, "")]
        [LootTableItem("raw_hemorgite", 1, 40, true, "")]
        [LootTableItem("hollinium", 1, 3, true, "")]
        [LootTableItem("harvino", 1, 3, true, "")]
        [LootTableItem("gorruchi", 1, 3, true, "")]
        [LootTableItem("arvvina", 1, 3, true, "")]
        [LootTableItem("f_crystal_blue", 1, 3, true, "")]
        [LootTableItem("porlang", 1, 3, true, "")]
        [LootTableItem("coonlank_blue", 1, 3, true, "")]
        MonCalaCoralIsles1Southwest = 93,
        [LootTable("Mon Cala Coral Isles 2 - Northeast")]
        [LootTableItem("raw_veldite", 1, 5, true, "")]
        [LootTableItem("raw_scordspar", 1, 5, true, "")]
        [LootTableItem("raw_keromber", 1, 20, true, "")]
        [LootTableItem("raw_plagionite", 1, 20, true, "")]
        [LootTableItem("raw_jasioclase", 1, 40, true, "")]
        [LootTableItem("raw_hemorgite", 1, 40, true, "")]
        [LootTableItem("hollinium", 1, 3, true, "")]
        [LootTableItem("harvino", 1, 3, true, "")]
        [LootTableItem("stalluchi", 1, 3, true, "")]
        [LootTableItem("medcina", 1, 3, true, "")]
        [LootTableItem("f_crystal_green", 1, 3, true, "")]
        [LootTableItem("sygium_gem", 1, 3, true, "")]
        [LootTableItem("coonlank_green", 1, 3, true, "")]
        MonCalaCoralIsles2Northeast = 94,
        [LootTable("Mon Cala Coral Isles 2 - Northwest")]
        [LootTableItem("raw_veldite", 1, 5, true, "")]
        [LootTableItem("raw_scordspar", 1, 5, true, "")]
        [LootTableItem("raw_keromber", 1, 20, true, "")]
        [LootTableItem("raw_plagionite", 1, 20, true, "")]
        [LootTableItem("raw_jasioclase", 1, 40, true, "")]
        [LootTableItem("raw_hemorgite", 1, 40, true, "")]
        [LootTableItem("hollinium", 1, 3, true, "")]
        [LootTableItem("harvino", 1, 3, true, "")]
        [LootTableItem("gorruchi", 1, 3, true, "")]
        [LootTableItem("engina", 1, 3, true, "")]
        [LootTableItem("f_crystal_yellow", 1, 3, true, "")]
        [LootTableItem("corylus", 1, 3, true, "")]
        [LootTableItem("coonlank_yellow", 1, 3, true, "")]
        MonCalaCoralIsles2Northwest = 95,
        [LootTable("Mon Cala Coral Isles 2 - Southeast")]
        [LootTableItem("raw_veldite", 1, 5, true, "")]
        [LootTableItem("raw_scordspar", 1, 5, true, "")]
        [LootTableItem("raw_keromber", 1, 20, true, "")]
        [LootTableItem("raw_plagionite", 1, 20, true, "")]
        [LootTableItem("raw_jasioclase", 1, 40, true, "")]
        [LootTableItem("raw_hemorgite", 1, 40, true, "")]
        [LootTableItem("hollinium", 1, 3, true, "")]
        [LootTableItem("harvino", 1, 3, true, "")]
        [LootTableItem("pefoate", 1, 3, true, "")]
        [LootTableItem("pawisis", 1, 3, true, "")]
        [LootTableItem("f_crystal_red", 1, 3, true, "")]
        [LootTableItem("corylus", 1, 3, true, "")]
        [LootTableItem("coonlank_red", 1, 3, true, "")]
        MonCalaCoralIsles2Southeast = 96,
        [LootTable("Mon Cala Coral Isles 2 - Southwest")]
        [LootTableItem("raw_veldite", 1, 5, true, "")]
        [LootTableItem("raw_scordspar", 1, 5, true, "")]
        [LootTableItem("raw_keromber", 1, 20, true, "")]
        [LootTableItem("raw_plagionite", 1, 20, true, "")]
        [LootTableItem("raw_jasioclase", 1, 40, true, "")]
        [LootTableItem("raw_hemorgite", 1, 40, true, "")]
        [LootTableItem("hollinium", 1, 3, true, "")]
        [LootTableItem("harvino", 1, 3, true, "")]
        [LootTableItem("pawisis", 1, 3, true, "")]
        [LootTableItem("pefoate", 1, 3, true, "")]
        [LootTableItem("f_crystal_blue", 1, 3, true, "")]
        [LootTableItem("porlang", 1, 3, true, "")]
        [LootTableItem("coonlank_blue", 1, 3, true, "")]
        MonCalaCoralIsles2Southwest = 97,
        [LootTable("Mon Cala Eco Terrorists")]
        [LootTableItem("nw_it_gold001", 30, 20, true, "")]
        [LootTableItem("nw_it_gold001", 50, 5, true, "")]
        [LootTableItem("elec_imperfect", 1, 20, true, "")]
        [LootTableItem("elec_good", 1, 5, true, "")]
        [LootTableItem("pr_light_chest", 1, 5, true, "")]
        [LootTableItem("pr_light_boots", 1, 10, true, "")]
        [LootTableItem("pr_light_belt", 1, 10, true, "")]
        [LootTableItem("pr_light_amm", 1, 4, true, "")]
        [LootTableItem("pr_light_helm", 1, 8, true, "")]
        [LootTableItem("pr_force_chest", 1, 5, true, "")]
        [LootTableItem("pr_force_boots", 1, 10, true, "")]
        [LootTableItem("pr_force_belt", 1, 10, true, "")]
        [LootTableItem("pr_force_amm", 1, 4, true, "")]
        [LootTableItem("pr_force_helm", 1, 8, true, "")]
        [LootTableItem("pr_heavy_chest", 1, 5, true, "")]
        [LootTableItem("pr_heavy_boots", 1, 10, true, "")]
        [LootTableItem("pr_heavy_belt", 1, 10, true, "")]
        [LootTableItem("pr_heavy_amm", 1, 4, true, "")]
        [LootTableItem("pr_heavy_helm", 1, 8, true, "")]
        MonCalaEcoTerrorists = 98,
        [LootTable("Mon Cala Fauna")]
        [LootTableItem("cox_meat", 1, 50, true, "")]
        [LootTableItem("lth_good", 1, 20, true, "")]
        [LootTableItem("lth_imperfect", 1, 30, true, "")]
        MonCalaFauna = 99,
        [LootTable("Mon Cala AmphiHydrus")]
        [LootTableItem("amphi_brain", 1, 10, true, "")]
        [LootTableItem("amphi_brain2", 1, 10, true, "")]
        MonCalaAmphiHydrus = 100,
        [LootTable("Mon Cala Eco Terrorist Leader")]
        [LootTableItem("nw_it_gold001", 60, 20, true, "")]
        [LootTableItem("nw_it_gold001", 100, 5, true, "")]
        [LootTableItem("elec_imperfect", 1, 5, true, "")]
        [LootTableItem("elec_good", 1, 10, true, "")]
        [LootTableItem("c_cluster_green", 1, 10, true, "")]
        [LootTableItem("ecot_lthr_drop", 1, 1, true, "")]
        MonCalaEcoTerroristLeader = 101,
        [LootTable("Tatooine Womprat")]
        [LootTableItem("womprathide", 1, 5, true, "")]
        [LootTableItem("womprattooth", 1, 5, true, "")]
        [LootTableItem("wompratclaw", 1, 5, true, "")]
        [LootTableItem("wompratmeat", 1, 5, true, "")]
        TatooineWomprat = 102,
        [LootTable("Tatooine Sandswimmer")]
        [LootTableItem("sandswimmerfin", 1, 5, true, "")]
        [LootTableItem("sandswimmerh", 1, 5, true, "")]
        [LootTableItem("sandswimmerleg", 1, 5, true, "")]
        TatooineSandswimmer = 103,
        [LootTable("Tatooine Wraid")]
        [LootTableItem("wraidskin", 1, 5, true, "")]
        [LootTableItem("wraidtooth", 1, 5, true, "")]
        TatooineWraid = 104,
        [LootTable("Tatooine Sand Demon")]
        [LootTableItem("sanddemonclaw", 1, 10, true, "")]
        [LootTableItem("sanddemonhide", 1, 10, true, "")]
        TatooineSandDemon = 105,
        [LootTable("Tatooine Tusken Raider")]
        [LootTableItem("tusk_highe", 1, 5, true, "")]
        [LootTableItem("tusk_leather", 1, 5, true, "")]
        [LootTableItem("t_blast_parts", 1, 5, true, "")]
        TatooineTuskenRaider = 106,
        [LootTable("Tatooine Tusken Camp Scavenge Points")]
        [LootTableItem("const_parts_tsk", 1, 10, true, "")]
        [LootTableItem("tsk_electronics", 1, 5, true, "")]
        [LootTableItem("tsk_metal", 1, 1, true, "")]
        TatooineTuskenCampScavengePoints = 107,
        [LootTable("Hutlar - Byysk")]
        [LootTableItem("spear_byssk", 1, 10, true, "")]
        [LootTableItem("quarterstaff_byy", 1, 10, true, "")]
        [LootTableItem("longsword_byysk", 1, 10, true, "")]
        [LootTableItem("dart_byysk", 1, 10, true, "")]
        [LootTableItem("axe_byysk", 1, 10, true, "")]
        [LootTableItem("force_robe_byysk", 1, 3, true, "")]
        [LootTableItem("breastplate_byys", 1, 1, true, "")]
        [LootTableItem("tunic_byysk", 1, 2, true, "")]
        [LootTableItem("byysk_shield", 1, 1, true, "")]
        [LootTableItem("powerglove_byysk", 1, 4, true, "")]
        [LootTableItem("stim_cha1", 1, 2, true, "")]
        [LootTableItem("stim_dex1", 1, 2, true, "")]
        [LootTableItem("stim_wis1", 1, 2, true, "")]
        [LootTableItem("qa_light_chest", 1, 5, true, "")]
        [LootTableItem("qa_light_boots", 1, 10, true, "")]
        [LootTableItem("qa_light_belt", 1, 10, true, "")]
        [LootTableItem("qa_light_amm", 1, 4, true, "")]
        [LootTableItem("qa_light_helm", 1, 8, true, "")]
        [LootTableItem("qa_force_chest", 1, 5, true, "")]
        [LootTableItem("qa_force_boots", 1, 10, true, "")]
        [LootTableItem("qa_force_belt", 1, 10, true, "")]
        [LootTableItem("qa_force_amm", 1, 4, true, "")]
        [LootTableItem("qa_force_helm", 1, 8, true, "")]
        [LootTableItem("qa_heavy_chest", 1, 5, true, "")]
        [LootTableItem("qa_heavy_boots", 1, 10, true, "")]
        [LootTableItem("qa_heavy_belt", 1, 10, true, "")]
        [LootTableItem("qa_heavy_amm", 1, 4, true, "")]
        [LootTableItem("qa_heavy_helm", 1, 8, true, "")]
        HutlarByysk = 110,
        [LootTable("Qion Tundra - Northeast")]
        [LootTableItem("p_crystal_blue", 1, 40, true, "")]
        [LootTableItem("p_crystal_red", 1, 40, true, "")]
        [LootTableItem("p_crystal_green", 1, 40, true, "")]
        [LootTableItem("p_crystal_yellow", 1, 40, true, "")]
        [LootTableItem("c_cluster_blue", 1, 5, true, "")]
        [LootTableItem("power_crystal_im", 1, 10, true, "")]
        [LootTableItem("raw_croknor", 1, 20, true, "")]
        [LootTableItem("raw_hemorgite", 1, 15, true, "")]
        [LootTableItem("corylus", 1, 5, true, "")]
        [LootTableItem("coonlank_blue", 1, 5, true, "")]
        QionTundraNortheast = 111,
        [LootTable("Qion Tundra - Northwest")]
        [LootTableItem("p_crystal_blue", 1, 40, true, "")]
        [LootTableItem("p_crystal_red", 1, 40, true, "")]
        [LootTableItem("p_crystal_green", 1, 40, true, "")]
        [LootTableItem("p_crystal_yellow", 1, 40, true, "")]
        [LootTableItem("c_cluster_yellow", 1, 5, true, "")]
        [LootTableItem("power_crystal_im", 1, 10, true, "")]
        [LootTableItem("raw_croknor", 1, 20, true, "")]
        [LootTableItem("raw_hemorgite", 1, 15, true, "")]
        [LootTableItem("corylus", 1, 5, true, "")]
        [LootTableItem("coonlank_yellow", 1, 5, true, "")]
        QionTundraNorthwest = 112,
        [LootTable("Qion Tundra - Southeast")]
        [LootTableItem("p_crystal_blue", 1, 40, true, "")]
        [LootTableItem("p_crystal_red", 1, 40, true, "")]
        [LootTableItem("p_crystal_green", 1, 40, true, "")]
        [LootTableItem("p_crystal_yellow", 1, 40, true, "")]
        [LootTableItem("c_cluster_red", 1, 5, true, "")]
        [LootTableItem("power_crystal_im", 1, 10, true, "")]
        [LootTableItem("raw_croknor", 1, 20, true, "")]
        [LootTableItem("raw_hemorgite", 1, 15, true, "")]
        [LootTableItem("corylus", 1, 5, true, "")]
        [LootTableItem("coonlank_red", 1, 5, true, "")]
        QionTundraSoutheast = 113,
        [LootTable("Qion Tundra - Southwest")]
        [LootTableItem("p_crystal_blue", 1, 40, true, "")]
        [LootTableItem("p_crystal_red", 1, 40, true, "")]
        [LootTableItem("p_crystal_green", 1, 40, true, "")]
        [LootTableItem("p_crystal_yellow", 1, 40, true, "")]
        [LootTableItem("c_cluster_green", 1, 5, true, "")]
        [LootTableItem("power_crystal_im", 1, 10, true, "")]
        [LootTableItem("raw_croknor", 1, 20, true, "")]
        [LootTableItem("raw_hemorgite", 1, 15, true, "")]
        [LootTableItem("corylus", 1, 5, true, "")]
        [LootTableItem("coonlank_green", 1, 5, true, "")]
        QionTundraSouthwest = 114,
        [LootTable("Hutlar - Byysk Rare Items")]
        [LootTableItem("byysk_def_ring", 1, 5, true, "")]
        [LootTableItem("bag_byysk", 1, 5, true, "")]
        HutlarByyskRareItems = 115,
        [LootTable("Hutlar - Qion Slugs")]
        [LootTableItem("elec_slime", 1, 10, true, "")]
        [LootTableItem("slug_bile", 1, 6, true, "")]
        [LootTableItem("slug_tooth", 1, 8, true, "")]
        HutlarQionSlugs = 116,
        [LootTable("Hutlar - Qion Tigers")]
        [LootTableItem("lth_imperfect", 1, 20, true, "")]
        [LootTableItem("lth_high", 1, 30, true, "")]
        [LootTableItem("qion_tiger_fang", 1, 10, true, "")]
        [LootTableItem("tiger_blood", 1, 8, true, "")]
        HutlarQionTigers = 117,

    }

    public class LootTableAttribute : Attribute
    {
        public string Name { get; set; }
        public HashSet<LootTableItemAttribute> LootTableItems { get; set; }

        public LootTableAttribute(string name)
        {
            Name = name;
            LootTableItems = new HashSet<LootTableItemAttribute>();
        }
    }

    [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
    public class LootTableItemAttribute : Attribute
    {
        public string Resref { get; set; }
        public int MaxQuantity { get; set; }
        public int Weight { get; set; }
        public bool IsActive { get; set; }
        public string SpawnRule { get; set; }

        public LootTableItemAttribute(string resref, int maxQuantity, int weight, bool isActive, string spawnRule)
        {
            Resref = resref;
            MaxQuantity = maxQuantity;
            Weight = weight;
            IsActive = isActive;
            SpawnRule = spawnRule;
        }
    }
}
