namespace SWLOR.Game.Server.Enumeration
{
    public enum RecipeType
    {
        Invalid = 0,

        // Smithery: 1-1000
        BasicHeavyVibrobladeGA = 1,
        BasicVibrobladeBA = 2,
        BasicVibrobladeBS = 3,
        BasicFinesseVibrobladeD = 4,
        BasicHeavyVibrobladeGS = 5,
        BasicVibrobladeLS = 6,
        BasicFinesseVibrobladeR = 7,
        BasicVibrobladeK = 8,
        BasicFinesseVibrobladeSS = 9,
        BasicBatonC = 10,
        BasicBatonM = 11,
        BasicBatonMS = 12,
        BasicQuarterstaff = 13,
        BasicFinesseVibrobladeK = 14,
        BasicKnuckles = 15,
        BasicPolearmH = 16,
        BasicPolearmS = 17,
        BasicBlasterPistol = 18,
        BasicBlasterRifle = 19,
        BasicDart = 20,
        BasicShuriken = 21,
        BasicThrowingAxe = 22,

        HeavyVibrobladeGA1 = 23,
        VibrobladeBA1 = 24,
        VibrobladeBS1 = 25,
        FinesseVibrobladeD1 = 26,
        HeavyVibrobladeGS1 = 27,
        VibrobladeLS1 = 28,
        FinesseVibrobladeR1 = 29,
        VibrobladeK1 = 30,
        FinesseVibrobladeSS1 = 31,
        BatonC1 = 32,
        BatonM1 = 33,
        BatonMS1 = 34,
        Quarterstaff1 = 35,
        FinesseVibrobladeK1 = 36,
        Knuckles1 = 37,
        PolearmH1 = 38,
        PolearmS1 = 39,
        BlasterPistol1 = 40,
        BlasterRifle1 = 41,
        Dart1 = 42,
        Shuriken1 = 43,
        ThrowingAxe1 = 44,

        HeavyVibrobladeGA2 = 45,
        VibrobladeBA2 = 46,
        VibrobladeBS2 = 47,
        FinesseVibrobladeD2 = 48,
        HeavyVibrobladeGS2 = 49,
        VibrobladeLS2 = 50,
        FinesseVibrobladeR2 = 51,
        VibrobladeK2 = 52,
        FinesseVibrobladeSS2 = 53,
        BatonC2 = 54,
        BatonM2 = 55,
        BatonMS2 = 56,
        Quarterstaff2 = 57,
        FinesseVibrobladeK2 = 58,
        Knuckles2 = 59,
        PolearmH2 = 60,
        PolearmS2 = 61,
        BlasterPistol2 = 62,
        BlasterRifle2 = 63,
        Dart2 = 64,
        Shuriken2 = 65,
        ThrowingAxe2 = 66,

        HeavyVibrobladeGA3 = 67,
        VibrobladeBA3 = 68,
        VibrobladeBS3 = 69,
        FinesseVibrobladeD3 = 70,
        HeavyVibrobladeGS3 = 71,
        VibrobladeLS3 = 72,
        FinesseVibrobladeR3 = 73,
        VibrobladeK3 = 74,
        FinesseVibrobladeSS3 = 75,
        BatonC3 = 76,
        BatonM3 = 77,
        BatonMS3 = 78,
        Quarterstaff3 = 79,
        FinesseVibrobladeK3 = 80,
        Knuckles3 = 81,
        PolearmH3 = 82,
        PolearmS3 = 83,
        BlasterPistol3 = 84,
        BlasterRifle3 = 85,
        Dart3 = 86,
        Shuriken3 = 87,
        ThrowingAxe3 = 88,

        HeavyVibrobladeGA4 = 89,
        VibrobladeBA4 = 90,
        VibrobladeBS4 = 91,
        FinesseVibrobladeD4 = 92,
        HeavyVibrobladeGS4 = 93,
        VibrobladeLS4 = 94,
        FinesseVibrobladeR4 = 95,
        VibrobladeK4 = 96,
        FinesseVibrobladeSS4 = 97,
        BatonC4 = 98,
        BatonM4 = 99,
        BatonMS4 = 100,
        Quarterstaff4 = 101,
        FinesseVibrobladeK4 = 102,
        Knuckles4 = 103,
        PolearmH4 = 104,
        PolearmS4 = 105,
        BlasterPistol4 = 106,
        BlasterRifle4 = 107,
        Dart4 = 108,
        Shuriken4 = 109,
        ThrowingAxe4 = 110,
        
        // Cybertech:  1001-2000

        // Fabrication:     2001-3000

    }
}
