namespace SWLOR.Game.Server.Enumeration
{
    public enum SkillType
    {
        Unknown = 0,
        OneHanded = 1,
        TwoHanded = 2,
        TwinBlades = 3,
        MartialArts = 4,
        Firearms = 5,
        Throwing = 6,
        LightArmor = 7,
        HeavyArmor = 8,
        Shields = 9,
        Harvesting = 10,
        ForceArmor = 11,
        Weaponsmith = 12,
        Armorsmith = 13,
        Lightsaber = 14,
        Fabrication = 15,
        Cooking = 16,
        Medicine = 17,
        Mirialan = 18,
        ForceAlter = 19,
        ForceControl = 20,
        ForceSense = 21,
        Engineering = 22,
        Farming = 23,
        Scavenging = 24,
        Bothese = 25,
        Cheunh = 26,
        Zabraki = 27,
        Twileki = 28,
        Catharese = 29,
        Dosh = 30,
        Shyriiwook = 31,
        Droidspeak = 32,
        Basic = 33,
        Mandoa = 34,
        Huttese = 35,
        Piloting = 36,
        MonCalamarian = 37,
        Ugnaught = 38
    }
}
