namespace SWLOR.Game.Server.Enumeration
{
    public enum StatusEffectType
    {
        Invalid = 0,
        ForceAttunement = 1,
        ComprehendSpeech1 = 2,
        ComprehendSpeech2 = 3,
        ComprehendSpeech3 = 4,
        ComprehendSpeech4 = 5,
        ForcePack1 = 6,
        ForcePack2 = 7,
        ForcePack3 = 8,
        ForcePack4 = 9,
        ForcePack5 = 10,
        StaminaPack1 = 11,
        StaminaPack2 = 12,
        StaminaPack3 = 13,
        StaminaPack4 = 14,
        StaminaPack5 = 15,
        Poison = 16,
        Bleed = 17,
        BurstOfSpeed1 = 18,
        BurstOfSpeed2 = 19,
        BurstOfSpeed3 = 20,
        BurstOfSpeed4 = 21,
        BurstOfSpeed5 = 22,
        ForceHeal1 = 23,
        ForceHeal2 = 24,
        ForceHeal3 = 25,
        ForceHeal4 = 26,
        ForceHeal5 = 27,
        ForceStun1 = 28,
        ForceStun2 = 29,
        ForceStun3 = 30,
        BattleInsight1 = 31,
        BattleInsight2 = 32,
        MindTrick1 = 33,
        MindTrick2 = 34,
        ForceDrain1 = 35,
        ForceDrain2 = 36,
        ForceDrain3 = 37,
        ForceDrain4 = 38,
        ForceDrain5 = 39,
        Shock = 40,
        Tranquilize = 41,
        Burn = 42,
        Rest = 43,
        ImplantInstallation1,
        ImplantInstallation2,
        ImplantInstallation3,
        ImplantInstallation4,
        ImplantInstallation5,
    }
}
