namespace SWLOR.Game.Server.Enumeration
{
    public enum StatusEffectType
    {
        Invincible = 1,
        Burn = 2,
        ElementalSeal = 3,
        ElementalSpread = 4,
        Sleep = 5,
        SubtleBlow1 = 6,
        SubtleBlow2 = 7,
        Poison1 = 8,
        Poison2 = 9,
        Static = 10,
        Defender1 = 11,
        Defender2 = 12,
        Defender3 = 13,
        Ironclad1 = 14,
        Ironclad2 = 15,
        Ironclad3 = 16,
        Blind1 = 17,
        Blind2 = 18,
        Cover1 = 19,
        Cover2 = 20,
        Cover3 = 21,
        Cover4 = 22,
        Poison3 = 23,
        Dia1 = 24,
        Dia2 = 25,
        Dia3 = 26,
        Manafont = 27,
        Bleed1 = 28,
        Bleed2 = 29,
        Bleed3 = 30,
        Refresh = 31,
        DeliberateStab = 32,
    }
}
