//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWLOR.Game.Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatLog
    {
        public long ChatLogID { get; set; }
        public int ChatChannelID { get; set; }
        public string SenderPlayerID { get; set; }
        public string SenderAccountName { get; set; }
        public string SenderCDKey { get; set; }
        public string ReceiverPlayerID { get; set; }
        public string ReceiverAccountName { get; set; }
        public string ReceiverCDKey { get; set; }
        public string Message { get; set; }
        public System.DateTime DateSent { get; set; }
        public string SenderDMName { get; set; }
        public string ReceiverDMName { get; set; }
    
        public virtual ChatChannelsDomain ChatChannelsDomain { get; set; }
        public virtual PlayerCharacter PlayerCharacter { get; set; }
        public virtual PlayerCharacter PlayerCharacter1 { get; set; }
    }
}
