using System.Linq;
using SWLOR.Game.Server.Feature.AppearanceDefinition.TintMap;
using SWLOR.Game.Server.Service.GuiService.Component;
using SWLOR.NWN.API.NWScript.Enum.Item;

namespace SWLOR.Game.Server.Feature.GuiDefinition.ViewModel
{
    public partial class AppearanceEditorViewModel
    {
        private void UpdateColorSwatch(ColorTarget target, AppearanceArmorColor channel, string regionName)
        {
            var name = regionName[..^"Region".Length];
            var item = GetItem();
            TryGetArmorTintLayer(channel, out var layer);
            var colorId = target == ColorTarget.Global
                ? GetItemAppearance(item, ItemAppearanceType.ArmorColor, (int)channel)
                : GetArmorSwatchColor(item, GetArmorModelType(target), channel);
            var custom = default(TintMapColor);
            var hasCustom = target == ColorTarget.Global
                ? TintMapColor.TryFromStoredValue(GetLocalInt(item,
                    TintMapVariable.GetItemGlobalColorStateName(layer)), out custom)
                : colorId != 255 && _tintMapSelections.Any(selection =>
                    selection.ArmorPart == GetArmorModelType(target) &&
                    selection.GetPaletteSource(layer) == item && selection.Material.Layers.Contains(layer) &&
                    TintMapService.TryGetCustomColor(selection, layer, out custom));
            var color = hasCustom ? custom : colorId == 255 ? default
                : TintMapPaletteColors.GetColor(layer, colorId);
            var previous = Get<GuiColor>(name + "Tint");
            if (previous == null || previous.R != color.Red || previous.G != color.Green || previous.B != color.Blue)
                Set(new GuiColor(color.Red, color.Green, color.Blue), name + "Tint");
            if (previous == null || Get<bool>(name + "Custom") != hasCustom)
                Set(hasCustom, name + "Custom");
        }

        public GuiColor GlobalLeather1Tint => Get<GuiColor>();
        public bool GlobalLeather1Custom => Get<bool>();
        public GuiColor GlobalLeather2Tint => Get<GuiColor>();
        public bool GlobalLeather2Custom => Get<bool>();
        public GuiColor GlobalCloth1Tint => Get<GuiColor>();
        public bool GlobalCloth1Custom => Get<bool>();
        public GuiColor GlobalCloth2Tint => Get<GuiColor>();
        public bool GlobalCloth2Custom => Get<bool>();
        public GuiColor GlobalMetal1Tint => Get<GuiColor>();
        public bool GlobalMetal1Custom => Get<bool>();
        public GuiColor GlobalMetal2Tint => Get<GuiColor>();
        public bool GlobalMetal2Custom => Get<bool>();
        public GuiColor LeftShoulderLeather1Tint => Get<GuiColor>();
        public bool LeftShoulderLeather1Custom => Get<bool>();
        public GuiColor LeftShoulderLeather2Tint => Get<GuiColor>();
        public bool LeftShoulderLeather2Custom => Get<bool>();
        public GuiColor LeftShoulderCloth1Tint => Get<GuiColor>();
        public bool LeftShoulderCloth1Custom => Get<bool>();
        public GuiColor LeftShoulderCloth2Tint => Get<GuiColor>();
        public bool LeftShoulderCloth2Custom => Get<bool>();
        public GuiColor LeftShoulderMetal1Tint => Get<GuiColor>();
        public bool LeftShoulderMetal1Custom => Get<bool>();
        public GuiColor LeftShoulderMetal2Tint => Get<GuiColor>();
        public bool LeftShoulderMetal2Custom => Get<bool>();
        public GuiColor LeftBicepLeather1Tint => Get<GuiColor>();
        public bool LeftBicepLeather1Custom => Get<bool>();
        public GuiColor LeftBicepLeather2Tint => Get<GuiColor>();
        public bool LeftBicepLeather2Custom => Get<bool>();
        public GuiColor LeftBicepCloth1Tint => Get<GuiColor>();
        public bool LeftBicepCloth1Custom => Get<bool>();
        public GuiColor LeftBicepCloth2Tint => Get<GuiColor>();
        public bool LeftBicepCloth2Custom => Get<bool>();
        public GuiColor LeftBicepMetal1Tint => Get<GuiColor>();
        public bool LeftBicepMetal1Custom => Get<bool>();
        public GuiColor LeftBicepMetal2Tint => Get<GuiColor>();
        public bool LeftBicepMetal2Custom => Get<bool>();
        public GuiColor LeftForearmLeather1Tint => Get<GuiColor>();
        public bool LeftForearmLeather1Custom => Get<bool>();
        public GuiColor LeftForearmLeather2Tint => Get<GuiColor>();
        public bool LeftForearmLeather2Custom => Get<bool>();
        public GuiColor LeftForearmCloth1Tint => Get<GuiColor>();
        public bool LeftForearmCloth1Custom => Get<bool>();
        public GuiColor LeftForearmCloth2Tint => Get<GuiColor>();
        public bool LeftForearmCloth2Custom => Get<bool>();
        public GuiColor LeftForearmMetal1Tint => Get<GuiColor>();
        public bool LeftForearmMetal1Custom => Get<bool>();
        public GuiColor LeftForearmMetal2Tint => Get<GuiColor>();
        public bool LeftForearmMetal2Custom => Get<bool>();
        public GuiColor LeftHandLeather1Tint => Get<GuiColor>();
        public bool LeftHandLeather1Custom => Get<bool>();
        public GuiColor LeftHandLeather2Tint => Get<GuiColor>();
        public bool LeftHandLeather2Custom => Get<bool>();
        public GuiColor LeftHandCloth1Tint => Get<GuiColor>();
        public bool LeftHandCloth1Custom => Get<bool>();
        public GuiColor LeftHandCloth2Tint => Get<GuiColor>();
        public bool LeftHandCloth2Custom => Get<bool>();
        public GuiColor LeftHandMetal1Tint => Get<GuiColor>();
        public bool LeftHandMetal1Custom => Get<bool>();
        public GuiColor LeftHandMetal2Tint => Get<GuiColor>();
        public bool LeftHandMetal2Custom => Get<bool>();
        public GuiColor LeftThighLeather1Tint => Get<GuiColor>();
        public bool LeftThighLeather1Custom => Get<bool>();
        public GuiColor LeftThighLeather2Tint => Get<GuiColor>();
        public bool LeftThighLeather2Custom => Get<bool>();
        public GuiColor LeftThighCloth1Tint => Get<GuiColor>();
        public bool LeftThighCloth1Custom => Get<bool>();
        public GuiColor LeftThighCloth2Tint => Get<GuiColor>();
        public bool LeftThighCloth2Custom => Get<bool>();
        public GuiColor LeftThighMetal1Tint => Get<GuiColor>();
        public bool LeftThighMetal1Custom => Get<bool>();
        public GuiColor LeftThighMetal2Tint => Get<GuiColor>();
        public bool LeftThighMetal2Custom => Get<bool>();
        public GuiColor LeftShinLeather1Tint => Get<GuiColor>();
        public bool LeftShinLeather1Custom => Get<bool>();
        public GuiColor LeftShinLeather2Tint => Get<GuiColor>();
        public bool LeftShinLeather2Custom => Get<bool>();
        public GuiColor LeftShinCloth1Tint => Get<GuiColor>();
        public bool LeftShinCloth1Custom => Get<bool>();
        public GuiColor LeftShinCloth2Tint => Get<GuiColor>();
        public bool LeftShinCloth2Custom => Get<bool>();
        public GuiColor LeftShinMetal1Tint => Get<GuiColor>();
        public bool LeftShinMetal1Custom => Get<bool>();
        public GuiColor LeftShinMetal2Tint => Get<GuiColor>();
        public bool LeftShinMetal2Custom => Get<bool>();
        public GuiColor LeftFootLeather1Tint => Get<GuiColor>();
        public bool LeftFootLeather1Custom => Get<bool>();
        public GuiColor LeftFootLeather2Tint => Get<GuiColor>();
        public bool LeftFootLeather2Custom => Get<bool>();
        public GuiColor LeftFootCloth1Tint => Get<GuiColor>();
        public bool LeftFootCloth1Custom => Get<bool>();
        public GuiColor LeftFootCloth2Tint => Get<GuiColor>();
        public bool LeftFootCloth2Custom => Get<bool>();
        public GuiColor LeftFootMetal1Tint => Get<GuiColor>();
        public bool LeftFootMetal1Custom => Get<bool>();
        public GuiColor LeftFootMetal2Tint => Get<GuiColor>();
        public bool LeftFootMetal2Custom => Get<bool>();
        public GuiColor RightShoulderLeather1Tint => Get<GuiColor>();
        public bool RightShoulderLeather1Custom => Get<bool>();
        public GuiColor RightShoulderLeather2Tint => Get<GuiColor>();
        public bool RightShoulderLeather2Custom => Get<bool>();
        public GuiColor RightShoulderCloth1Tint => Get<GuiColor>();
        public bool RightShoulderCloth1Custom => Get<bool>();
        public GuiColor RightShoulderCloth2Tint => Get<GuiColor>();
        public bool RightShoulderCloth2Custom => Get<bool>();
        public GuiColor RightShoulderMetal1Tint => Get<GuiColor>();
        public bool RightShoulderMetal1Custom => Get<bool>();
        public GuiColor RightShoulderMetal2Tint => Get<GuiColor>();
        public bool RightShoulderMetal2Custom => Get<bool>();
        public GuiColor RightBicepLeather1Tint => Get<GuiColor>();
        public bool RightBicepLeather1Custom => Get<bool>();
        public GuiColor RightBicepLeather2Tint => Get<GuiColor>();
        public bool RightBicepLeather2Custom => Get<bool>();
        public GuiColor RightBicepCloth1Tint => Get<GuiColor>();
        public bool RightBicepCloth1Custom => Get<bool>();
        public GuiColor RightBicepCloth2Tint => Get<GuiColor>();
        public bool RightBicepCloth2Custom => Get<bool>();
        public GuiColor RightBicepMetal1Tint => Get<GuiColor>();
        public bool RightBicepMetal1Custom => Get<bool>();
        public GuiColor RightBicepMetal2Tint => Get<GuiColor>();
        public bool RightBicepMetal2Custom => Get<bool>();
        public GuiColor RightForearmLeather1Tint => Get<GuiColor>();
        public bool RightForearmLeather1Custom => Get<bool>();
        public GuiColor RightForearmLeather2Tint => Get<GuiColor>();
        public bool RightForearmLeather2Custom => Get<bool>();
        public GuiColor RightForearmCloth1Tint => Get<GuiColor>();
        public bool RightForearmCloth1Custom => Get<bool>();
        public GuiColor RightForearmCloth2Tint => Get<GuiColor>();
        public bool RightForearmCloth2Custom => Get<bool>();
        public GuiColor RightForearmMetal1Tint => Get<GuiColor>();
        public bool RightForearmMetal1Custom => Get<bool>();
        public GuiColor RightForearmMetal2Tint => Get<GuiColor>();
        public bool RightForearmMetal2Custom => Get<bool>();
        public GuiColor RightHandLeather1Tint => Get<GuiColor>();
        public bool RightHandLeather1Custom => Get<bool>();
        public GuiColor RightHandLeather2Tint => Get<GuiColor>();
        public bool RightHandLeather2Custom => Get<bool>();
        public GuiColor RightHandCloth1Tint => Get<GuiColor>();
        public bool RightHandCloth1Custom => Get<bool>();
        public GuiColor RightHandCloth2Tint => Get<GuiColor>();
        public bool RightHandCloth2Custom => Get<bool>();
        public GuiColor RightHandMetal1Tint => Get<GuiColor>();
        public bool RightHandMetal1Custom => Get<bool>();
        public GuiColor RightHandMetal2Tint => Get<GuiColor>();
        public bool RightHandMetal2Custom => Get<bool>();
        public GuiColor RightThighLeather1Tint => Get<GuiColor>();
        public bool RightThighLeather1Custom => Get<bool>();
        public GuiColor RightThighLeather2Tint => Get<GuiColor>();
        public bool RightThighLeather2Custom => Get<bool>();
        public GuiColor RightThighCloth1Tint => Get<GuiColor>();
        public bool RightThighCloth1Custom => Get<bool>();
        public GuiColor RightThighCloth2Tint => Get<GuiColor>();
        public bool RightThighCloth2Custom => Get<bool>();
        public GuiColor RightThighMetal1Tint => Get<GuiColor>();
        public bool RightThighMetal1Custom => Get<bool>();
        public GuiColor RightThighMetal2Tint => Get<GuiColor>();
        public bool RightThighMetal2Custom => Get<bool>();
        public GuiColor RightShinLeather1Tint => Get<GuiColor>();
        public bool RightShinLeather1Custom => Get<bool>();
        public GuiColor RightShinLeather2Tint => Get<GuiColor>();
        public bool RightShinLeather2Custom => Get<bool>();
        public GuiColor RightShinCloth1Tint => Get<GuiColor>();
        public bool RightShinCloth1Custom => Get<bool>();
        public GuiColor RightShinCloth2Tint => Get<GuiColor>();
        public bool RightShinCloth2Custom => Get<bool>();
        public GuiColor RightShinMetal1Tint => Get<GuiColor>();
        public bool RightShinMetal1Custom => Get<bool>();
        public GuiColor RightShinMetal2Tint => Get<GuiColor>();
        public bool RightShinMetal2Custom => Get<bool>();
        public GuiColor RightFootLeather1Tint => Get<GuiColor>();
        public bool RightFootLeather1Custom => Get<bool>();
        public GuiColor RightFootLeather2Tint => Get<GuiColor>();
        public bool RightFootLeather2Custom => Get<bool>();
        public GuiColor RightFootCloth1Tint => Get<GuiColor>();
        public bool RightFootCloth1Custom => Get<bool>();
        public GuiColor RightFootCloth2Tint => Get<GuiColor>();
        public bool RightFootCloth2Custom => Get<bool>();
        public GuiColor RightFootMetal1Tint => Get<GuiColor>();
        public bool RightFootMetal1Custom => Get<bool>();
        public GuiColor RightFootMetal2Tint => Get<GuiColor>();
        public bool RightFootMetal2Custom => Get<bool>();
        public GuiColor NeckLeather1Tint => Get<GuiColor>();
        public bool NeckLeather1Custom => Get<bool>();
        public GuiColor NeckLeather2Tint => Get<GuiColor>();
        public bool NeckLeather2Custom => Get<bool>();
        public GuiColor NeckCloth1Tint => Get<GuiColor>();
        public bool NeckCloth1Custom => Get<bool>();
        public GuiColor NeckCloth2Tint => Get<GuiColor>();
        public bool NeckCloth2Custom => Get<bool>();
        public GuiColor NeckMetal1Tint => Get<GuiColor>();
        public bool NeckMetal1Custom => Get<bool>();
        public GuiColor NeckMetal2Tint => Get<GuiColor>();
        public bool NeckMetal2Custom => Get<bool>();
        public GuiColor ChestLeather1Tint => Get<GuiColor>();
        public bool ChestLeather1Custom => Get<bool>();
        public GuiColor ChestLeather2Tint => Get<GuiColor>();
        public bool ChestLeather2Custom => Get<bool>();
        public GuiColor ChestCloth1Tint => Get<GuiColor>();
        public bool ChestCloth1Custom => Get<bool>();
        public GuiColor ChestCloth2Tint => Get<GuiColor>();
        public bool ChestCloth2Custom => Get<bool>();
        public GuiColor ChestMetal1Tint => Get<GuiColor>();
        public bool ChestMetal1Custom => Get<bool>();
        public GuiColor ChestMetal2Tint => Get<GuiColor>();
        public bool ChestMetal2Custom => Get<bool>();
        public GuiColor BeltLeather1Tint => Get<GuiColor>();
        public bool BeltLeather1Custom => Get<bool>();
        public GuiColor BeltLeather2Tint => Get<GuiColor>();
        public bool BeltLeather2Custom => Get<bool>();
        public GuiColor BeltCloth1Tint => Get<GuiColor>();
        public bool BeltCloth1Custom => Get<bool>();
        public GuiColor BeltCloth2Tint => Get<GuiColor>();
        public bool BeltCloth2Custom => Get<bool>();
        public GuiColor BeltMetal1Tint => Get<GuiColor>();
        public bool BeltMetal1Custom => Get<bool>();
        public GuiColor BeltMetal2Tint => Get<GuiColor>();
        public bool BeltMetal2Custom => Get<bool>();
        public GuiColor PelvisLeather1Tint => Get<GuiColor>();
        public bool PelvisLeather1Custom => Get<bool>();
        public GuiColor PelvisLeather2Tint => Get<GuiColor>();
        public bool PelvisLeather2Custom => Get<bool>();
        public GuiColor PelvisCloth1Tint => Get<GuiColor>();
        public bool PelvisCloth1Custom => Get<bool>();
        public GuiColor PelvisCloth2Tint => Get<GuiColor>();
        public bool PelvisCloth2Custom => Get<bool>();
        public GuiColor PelvisMetal1Tint => Get<GuiColor>();
        public bool PelvisMetal1Custom => Get<bool>();
        public GuiColor PelvisMetal2Tint => Get<GuiColor>();
        public bool PelvisMetal2Custom => Get<bool>();
        public GuiColor RobeLeather1Tint => Get<GuiColor>();
        public bool RobeLeather1Custom => Get<bool>();
        public GuiColor RobeLeather2Tint => Get<GuiColor>();
        public bool RobeLeather2Custom => Get<bool>();
        public GuiColor RobeCloth1Tint => Get<GuiColor>();
        public bool RobeCloth1Custom => Get<bool>();
        public GuiColor RobeCloth2Tint => Get<GuiColor>();
        public bool RobeCloth2Custom => Get<bool>();
        public GuiColor RobeMetal1Tint => Get<GuiColor>();
        public bool RobeMetal1Custom => Get<bool>();
        public GuiColor RobeMetal2Tint => Get<GuiColor>();
        public bool RobeMetal2Custom => Get<bool>();
    }
}
