// Generated from design/animations/active-abilities.json and saved animation projects.
using System.Collections.Generic;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Service.AnimationService;

public static class ActiveAbilityAnimationCatalog
{
    public static IReadOnlyList<AbilityAnimationEntry> Entries { get; } = new AbilityAnimationEntry[]
    {
        new("CallBeast", "Call Beast", "Beast Mastery", AuthoredAnimation.CallBeast, new FeatType[] { FeatType.CallBeast }),
        new("GuardingBond", "Guarding Bond", "Beast Mastery", AuthoredAnimation.GuardingBond, new FeatType[] { FeatType.GuardingBond }),
        new("PredatoryBond", "Predatory Bond", "Beast Mastery", AuthoredAnimation.PredatoryBond, new FeatType[] { FeatType.PredatoryBond }),
        new("ReviveBeast", "Revive Beast", "Beast Mastery", AuthoredAnimation.ReviveBeast, new FeatType[] { FeatType.ReviveBeast1, FeatType.ReviveBeast2, FeatType.ReviveBeast3 }),
        new("Reward", "Reward", "Beast Mastery", AuthoredAnimation.Reward, new FeatType[] { FeatType.Reward1, FeatType.Reward2, FeatType.Reward3 }),
        new("SoothePet", "Soothe Pet", "Beast Mastery", AuthoredAnimation.SoothePet, new FeatType[] { FeatType.SoothePet }),
        new("Tame", "Tame", "Beast Mastery", AuthoredAnimation.Tame, new FeatType[] { FeatType.Tame }),
        new("AdhesiveGrenade", "Adhesive Grenade", "Devices", AuthoredAnimation.AdhesiveGrenade, new FeatType[] { FeatType.AdhesiveGrenade1, FeatType.AdhesiveGrenade2 }),
        new("ArcProjector", "Arc Projector", "Devices", AuthoredAnimation.ArcProjector, new FeatType[] { FeatType.ArcProjector1, FeatType.ArcProjector2, FeatType.ArcProjector3 }),
        new("BlasterBeacon", "Blaster Beacon", "Devices", AuthoredAnimation.BlasterBeacon, new FeatType[] { FeatType.BlasterBeacon1, FeatType.BlasterBeacon2, FeatType.BlasterBeacon3 }),
        new("ClusterGrenade", "Cluster Grenade", "Devices", AuthoredAnimation.ClusterGrenade, new FeatType[] { FeatType.ClusterGrenade1 }),
        new("ConcussionGrenade", "Concussion Grenade", "Devices", AuthoredAnimation.ConcussionGrenade, new FeatType[] { FeatType.ConcussionGrenade1, FeatType.ConcussionGrenade2 }),
        new("CryoSprayer", "Cryo Sprayer", "Devices", AuthoredAnimation.CryoSprayer, new FeatType[] { FeatType.CryoSprayer1 }),
        new("DeflectorShield", "Deflector Shield", "Devices", AuthoredAnimation.DeflectorShield, new FeatType[] { FeatType.DeflectorShield1, FeatType.DeflectorShield2, FeatType.DeflectorShield3 }),
        new("DisruptionPulse", "Disruption Pulse", "Devices", AuthoredAnimation.DisruptionPulse, new FeatType[] { FeatType.DisruptionPulse1 }),
        new("EmergencyBunker", "Emergency Bunker", "Devices", AuthoredAnimation.EmergencyBunker, new FeatType[] { FeatType.EmergencyBunker1 }),
        new("Flamethrower", "Flamethrower", "Devices", AuthoredAnimation.Flamethrower, new FeatType[] { FeatType.Flamethrower1, FeatType.Flamethrower2, FeatType.Flamethrower3 }),
        new("FlashGrenade", "Flash Grenade", "Devices", AuthoredAnimation.FlashGrenade, new FeatType[] { FeatType.FlashGrenade1 }),
        new("FragGrenade", "Frag Grenade", "Devices", AuthoredAnimation.FragGrenade, new FeatType[] { FeatType.FragGrenade1, FeatType.FragGrenade2, FeatType.FragGrenade3 }),
        new("GroupDeflector", "Group Deflector", "Devices", AuthoredAnimation.GroupDeflector, new FeatType[] { FeatType.GroupDeflector1 }),
        new("IncendiaryField", "Incendiary Field", "Devices", AuthoredAnimation.IncendiaryField, new FeatType[] { FeatType.IncendiaryField1, FeatType.IncendiaryField2, FeatType.IncendiaryField3 }),
        new("IonGrenade", "Ion Grenade", "Devices", AuthoredAnimation.IonGrenade, new FeatType[] { FeatType.IonGrenade1, FeatType.IonGrenade2 }),
        new("IonLance", "Ion Lance", "Devices", AuthoredAnimation.IonLance, new FeatType[] { FeatType.IonLance1, FeatType.IonLance2, FeatType.IonLance3 }),
        new("KillzoneBeacon", "Killzone Beacon", "Devices", AuthoredAnimation.KillzoneBeacon, new FeatType[] { FeatType.KillzoneBeacon1 }),
        new("OverloadBarrage", "Overload Barrage", "Devices", AuthoredAnimation.OverloadBarrage, new FeatType[] { FeatType.OverloadBarrage1 }),
        new("PowerCell", "Power Cell", "Devices", AuthoredAnimation.PowerCell, new FeatType[] { FeatType.PowerCell1, FeatType.PowerCell2, FeatType.PowerCell3 }),
        new("RailDart", "Rail Dart", "Devices", AuthoredAnimation.RailDart, new FeatType[] { FeatType.RailDart1, FeatType.RailDart2, FeatType.RailDart3 }),
        new("RemoteCharge", "Remote Charge", "Devices", AuthoredAnimation.RemoteCharge, new FeatType[] { FeatType.RemoteCharge1, FeatType.RemoteCharge2 }),
        new("ShockBeacon", "Shock Beacon", "Devices", AuthoredAnimation.ShockBeacon, new FeatType[] { FeatType.ShockBeacon1, FeatType.ShockBeacon2 }),
        new("SignalJammer", "Signal Jammer", "Devices", AuthoredAnimation.SignalJammer, new FeatType[] { FeatType.SignalJammer1 }),
        new("SonicBurst", "Sonic Burst", "Devices", AuthoredAnimation.SonicBurst, new FeatType[] { FeatType.SonicBurst1, FeatType.SonicBurst2, FeatType.SonicBurst3 }),
        new("ThermalDetonator", "Thermal Detonator", "Devices", AuthoredAnimation.ThermalDetonator, new FeatType[] { FeatType.ThermalDetonator1 }),
        new("WeaponJam", "Weapon Jam", "Devices", AuthoredAnimation.WeaponJam, new FeatType[] { FeatType.WeaponJam1 }),
        new("WristRocket", "Wrist Rocket", "Devices", AuthoredAnimation.WristRocket, new FeatType[] { FeatType.WristRocket1, FeatType.WristRocket2, FeatType.WristRocket3 }),
        new("GhostProtocol", "Ghost Protocol", "Espionage", AuthoredAnimation.GhostProtocol, new FeatType[] { FeatType.GhostProtocol }),
        new("RazorTrap", "Razor Trap", "Espionage", AuthoredAnimation.RazorTrap, new FeatType[] { FeatType.RazorTrap1, FeatType.RazorTrap2 }),
        new("ShadowStep", "Shadow Step", "Espionage", AuthoredAnimation.ShadowStep, new FeatType[] { FeatType.ShadowStep1, FeatType.ShadowStep2 }),
        new("ShockTrap", "Shock Trap", "Espionage", AuthoredAnimation.ShockTrap, new FeatType[] { FeatType.ShockTrap }),
        new("Stealth", "Stealth", "Espionage", AuthoredAnimation.Stealth, new FeatType[] {  }),
        new("TacticalEscape", "Tactical Escape", "Espionage", AuthoredAnimation.TacticalEscape, new FeatType[] { FeatType.TacticalEscape1, FeatType.TacticalEscape2 }),
        new("AdrenalStim", "Adrenal Stim", "First Aid", AuthoredAnimation.AdrenalStim, new FeatType[] { FeatType.AdrenalStim1, FeatType.AdrenalStim2, FeatType.AdrenalStim3 }),
        new("Antitoxin", "Antitoxin", "First Aid", AuthoredAnimation.Antitoxin, new FeatType[] { FeatType.Antitoxin1 }),
        new("EmergencyCocktail", "Emergency Cocktail", "First Aid", AuthoredAnimation.EmergencyCocktail, new FeatType[] { FeatType.EmergencyCocktail1 }),
        new("EmergencyTriage", "Emergency Triage", "First Aid", AuthoredAnimation.EmergencyTriage, new FeatType[] { FeatType.EmergencyTriage1 }),
        new("FocusStim", "Focus Stim", "First Aid", AuthoredAnimation.FocusStim, new FeatType[] { FeatType.FocusStim1, FeatType.FocusStim2 }),
        new("Infusion", "Infusion", "First Aid", AuthoredAnimation.Infusion, new FeatType[] { FeatType.Infusion1, FeatType.Infusion2 }),
        new("KoltoMist", "Kolto Mist", "First Aid", AuthoredAnimation.KoltoMist, new FeatType[] { FeatType.KoltoMist1, FeatType.KoltoMist2 }),
        new("MedKit", "Med Kit", "First Aid", AuthoredAnimation.MedKit, new FeatType[] { FeatType.MedKit1, FeatType.MedKit2, FeatType.MedKit3, FeatType.MedKit4 }),
        new("PainSuppressant", "Pain Suppressant", "First Aid", AuthoredAnimation.PainSuppressant, new FeatType[] { FeatType.PainSuppressant1, FeatType.PainSuppressant2 }),
        new("Resuscitation", "Resuscitation", "First Aid", AuthoredAnimation.Resuscitation, new FeatType[] { FeatType.Resuscitation1, FeatType.Resuscitation2 }),
        new("Shielding", "Shielding", "First Aid", AuthoredAnimation.Shielding, new FeatType[] { FeatType.Shielding1, FeatType.Shielding2, FeatType.Shielding3 }),
        new("TreatmentKit", "Treatment Kit", "First Aid", AuthoredAnimation.TreatmentKit, new FeatType[] { FeatType.TreatmentKit1, FeatType.TreatmentKit2, FeatType.TreatmentKit3 }),
        new("Benevolence", "Benevolence", "Force", AuthoredAnimation.Benevolence, new FeatType[] { FeatType.Benevolence1, FeatType.Benevolence2, FeatType.Benevolence3 }),
        new("CreepingTerror", "Creeping Terror", "Force", AuthoredAnimation.CreepingTerror, new FeatType[] { FeatType.CreepingTerror1, FeatType.CreepingTerror2, FeatType.CreepingTerror3 }),
        new("EclipseOfResolve", "Eclipse of Resolve", "Force", AuthoredAnimation.EclipseOfResolve, new FeatType[] { FeatType.EclipseOfResolve1 }),
        new("ForceBurst", "Force Burst", "Force", AuthoredAnimation.ForceBurst, new FeatType[] { FeatType.ForceBurst1 }),
        new("ForceChoke", "Force Choke", "Force", AuthoredAnimation.ForceChoke, new FeatType[] { FeatType.ForceChoke1, FeatType.ForceChoke2, FeatType.ForceChoke3, FeatType.ForceChoke4 }),
        new("ForceDrain", "Force Drain", "Force", AuthoredAnimation.ForceDrain, new FeatType[] { FeatType.ForceDrain1, FeatType.ForceDrain2, FeatType.ForceDrain3 }),
        new("ForceIntercept", "Force Intercept", "Force", AuthoredAnimation.ForceIntercept, new FeatType[] { FeatType.ForceIntercept1 }),
        new("ForceJudgment", "Force Judgment", "Force", AuthoredAnimation.ForceJudgment, new FeatType[] { FeatType.ForceJudgment1, FeatType.ForceJudgment2, FeatType.ForceJudgment3 }),
        new("ForceLeap", "Force Leap", "Force", AuthoredAnimation.ForceLeap, new FeatType[] { FeatType.ForceLeap1, FeatType.ForceLeap2 }),
        new("ForceLightning", "Force Lightning", "Force", AuthoredAnimation.ForceLightning, new FeatType[] { FeatType.ForceLightning1, FeatType.ForceLightning2, FeatType.ForceLightning3 }),
        new("ForcePush", "Force Push", "Force", AuthoredAnimation.ForcePush, new FeatType[] { FeatType.ForcePush1, FeatType.ForcePush2, FeatType.ForcePush3 }),
        new("ForceSanctuary", "Force Sanctuary", "Force", AuthoredAnimation.ForceSanctuary, new FeatType[] { FeatType.ForceSanctuary1 }),
        new("ForceSpark", "Force Spark", "Force", AuthoredAnimation.ForceSpark, new FeatType[] { FeatType.ForceSpark1, FeatType.ForceSpark2 }),
        new("FuryStance", "Fury Stance", "Force", AuthoredAnimation.FuryStance, new FeatType[] { FeatType.FuryStance1, FeatType.FuryStance2 }),
        new("GuardianWard", "Guardian Ward", "Force", AuthoredAnimation.GuardianWard, new FeatType[] { FeatType.GuardianWard1, FeatType.GuardianWard2, FeatType.GuardianWard3, FeatType.GuardianWard4 }),
        new("HungerOfTheDark", "Hunger of the Dark", "Force", AuthoredAnimation.HungerOfTheDark, new FeatType[] { FeatType.HungerOfTheDark1 }),
        new("LastStandOfTheLight", "Last Stand of the Light", "Force", AuthoredAnimation.LastStandOfTheLight, new FeatType[] { FeatType.LastStandOfTheLight1 }),
        new("MindTrick", "Mind Trick", "Force", AuthoredAnimation.MindTrick, new FeatType[] { FeatType.MindTrick1, FeatType.MindTrick2 }),
        new("NightmareField", "Nightmare Field", "Force", AuthoredAnimation.NightmareField, new FeatType[] { FeatType.NightmareField1 }),
        new("PurifyingWave", "Purifying Wave", "Force", AuthoredAnimation.PurifyingWave, new FeatType[] { FeatType.PurifyingWave1 }),
        new("RadiantLance", "Radiant Lance", "Force", AuthoredAnimation.RadiantLance, new FeatType[] { FeatType.RadiantLance1, FeatType.RadiantLance2, FeatType.RadiantLance3 }),
        new("Renewal", "Renewal", "Force", AuthoredAnimation.Renewal, new FeatType[] { FeatType.Renewal1, FeatType.Renewal2, FeatType.Renewal3 }),
        new("ThrowLightsaber", "Throw Lightsaber", "Force", AuthoredAnimation.ThrowLightsaber, new FeatType[] { FeatType.ThrowLightsaber1, FeatType.ThrowLightsaber2, FeatType.ThrowLightsaber3 }),
        new("ThrowRock", "Throw Rock", "Force", AuthoredAnimation.ThrowRock, new FeatType[] { FeatType.ThrowRock1, FeatType.ThrowRock2, FeatType.ThrowRock3 }),
        new("WeakenResolve", "Weaken Resolve", "Force", AuthoredAnimation.WeakenResolve, new FeatType[] { FeatType.WeakenResolve1, FeatType.WeakenResolve2 }),
        new("Provoke", "Provoke", "General", AuthoredAnimation.Provoke, new FeatType[] { FeatType.Provoke1, FeatType.Provoke2 }),
        new("AbsoluteDefense", "Absolute Defense", "Heavy Vibroblade", AuthoredAnimation.AbsoluteDefense, new FeatType[] { FeatType.AbsoluteDefense1 }),
        new("BastionStance", "Bastion Stance", "Heavy Vibroblade", AuthoredAnimation.BastionStance, new FeatType[] { FeatType.BastionStance1 }),
        new("BlazingSpikes", "Blazing Spikes", "Heavy Vibroblade", AuthoredAnimation.BlazingSpikes, new FeatType[] { FeatType.BlazingSpikes1 }),
        new("Earthshatter", "Earthshatter", "Heavy Vibroblade", AuthoredAnimation.Earthshatter, new FeatType[] { FeatType.Earthshatter1, FeatType.Earthshatter2 }),
        new("Flash", "Flash", "Heavy Vibroblade", AuthoredAnimation.Flash, new FeatType[] { FeatType.Flash1 }),
        new("FortressStrike", "Fortress Strike", "Heavy Vibroblade", AuthoredAnimation.FortressStrike, new FeatType[] { FeatType.FortressStrike1, FeatType.FortressStrike2, FeatType.FortressStrike3 }),
        new("Rampart", "Rampart", "Heavy Vibroblade", AuthoredAnimation.Rampart, new FeatType[] { FeatType.Rampart1 }),
        new("SacrificialBlade", "Sacrificial Blade", "Heavy Vibroblade", AuthoredAnimation.SacrificialBlade, new FeatType[] { FeatType.SacrificialBlade1 }),
        new("SoulBurst", "Soul Burst", "Heavy Vibroblade", AuthoredAnimation.SoulBurst, new FeatType[] { FeatType.SoulBurst1 }),
        new("SoulDevourer", "Soul Devourer", "Heavy Vibroblade", AuthoredAnimation.SoulDevourer, new FeatType[] { FeatType.SoulDevourer1 }),
        new("SoulStorm", "Soul Storm", "Heavy Vibroblade", AuthoredAnimation.SoulStorm, new FeatType[] { FeatType.SoulStorm1 }),
        new("SoulStrike", "Soul Strike", "Heavy Vibroblade", AuthoredAnimation.SoulStrike, new FeatType[] { FeatType.SoulStrike1, FeatType.SoulStrike2, FeatType.SoulStrike3 }),
        new("AdamantineGuard", "Adamantine Guard", "Katar", AuthoredAnimation.AdamantineGuard, new FeatType[] { FeatType.AdamantineGuard1 }),
        new("GuardCounter", "Guard Counter", "Katar", AuthoredAnimation.GuardCounter, new FeatType[] { FeatType.GuardCounter1, FeatType.GuardCounter2, FeatType.GuardCounter3 }),
        new("HookingStrike", "Hooking Strike", "Katar", AuthoredAnimation.HookingStrike, new FeatType[] { FeatType.HookingStrike1, FeatType.HookingStrike2, FeatType.HookingStrike3, FeatType.HookingStrike4 }),
        new("InterruptingSweep", "Interrupting Sweep", "Katar", AuthoredAnimation.InterruptingSweep, new FeatType[] { FeatType.InterruptingSweep1, FeatType.InterruptingSweep2 }),
        new("IronWallStance", "Iron Wall Stance", "Katar", AuthoredAnimation.IronWallStance, new FeatType[] { FeatType.IronWallStance1 }),
        new("JointLock", "Joint Lock", "Katar", AuthoredAnimation.JointLock, new FeatType[] { FeatType.JointLock1, FeatType.JointLock2, FeatType.JointLock3 }),
        new("ScrapheapLockdown", "Scrapheap Lockdown", "Katar", AuthoredAnimation.ScrapheapLockdown, new FeatType[] { FeatType.ScrapheapLockdown1 }),
        new("ScrapperStance", "Scrapper Stance", "Katar", AuthoredAnimation.ScrapperStance, new FeatType[] { FeatType.ScrapperStance1 }),
        new("TwinGuardStance", "Steel Shoulder", "Katar", AuthoredAnimation.TwinGuardStance, new FeatType[] { FeatType.TwinGuardStance1 }),
        new("TwinIntercept", "Tag In", "Katar", AuthoredAnimation.TwinIntercept, new FeatType[] { FeatType.TwinIntercept1 }),
        new("WhirlingGuard", "Whirling Guard", "Katar", AuthoredAnimation.WhirlingGuard, new FeatType[] { FeatType.WhirlingGuard1 }),
        new("BreakMorale", "Break Morale", "Leadership", AuthoredAnimation.BreakMorale, new FeatType[] { FeatType.BreakMorale1, FeatType.BreakMorale2 }),
        new("ChargeOrder", "Charge Order", "Leadership", AuthoredAnimation.ChargeOrder, new FeatType[] { FeatType.ChargeOrder1, FeatType.ChargeOrder2 }),
        new("CleanseOrder", "Cleanse Order", "Leadership", AuthoredAnimation.CleanseOrder, new FeatType[] { FeatType.CleanseOrder1, FeatType.CleanseOrder2 }),
        new("CoordinatedFocus", "Coordinated Focus", "Leadership", AuthoredAnimation.CoordinatedFocus, new FeatType[] { FeatType.CoordinatedFocus1, FeatType.CoordinatedFocus2, FeatType.CoordinatedFocus3 }),
        new("DecisiveCommand", "Decisive Command", "Leadership", AuthoredAnimation.DecisiveCommand, new FeatType[] { FeatType.DecisiveCommand1 }),
        new("FieldRecovery", "Field Recovery", "Leadership", AuthoredAnimation.FieldRecovery, new FeatType[] { FeatType.FieldRecovery1, FeatType.FieldRecovery2 }),
        new("HoldTheLine", "Hold the Line", "Leadership", AuthoredAnimation.HoldTheLine, new FeatType[] { FeatType.HoldTheLine1 }),
        new("PressTheAttack", "Press the Attack", "Leadership", AuthoredAnimation.PressTheAttack, new FeatType[] { FeatType.PressTheAttack1, FeatType.PressTheAttack2, FeatType.PressTheAttack3 }),
        new("RallyingStandard", "Rallying Standard", "Leadership", AuthoredAnimation.RallyingStandard, new FeatType[] { FeatType.RallyingStandard1, FeatType.RallyingStandard2 }),
        new("RousingShout", "Rousing Shout", "Leadership", AuthoredAnimation.RousingShout, new FeatType[] { FeatType.RousingShout1, FeatType.RousingShout2, FeatType.RousingShout3 }),
        new("SteadyFormation", "Steady Formation", "Leadership", AuthoredAnimation.SteadyFormation, new FeatType[] { FeatType.SteadyFormation1, FeatType.SteadyFormation2 }),
        new("WatchfulPresence", "Watchful Presence", "Leadership", AuthoredAnimation.WatchfulPresence, new FeatType[] { FeatType.WatchfulPresence1, FeatType.WatchfulPresence2, FeatType.WatchfulPresence3 }),
        new("AegisEternal", "Aegis Eternal", "Lightsaber", AuthoredAnimation.AegisEternal, new FeatType[] { FeatType.AegisEternal1 }),
        new("Epicenter", "Epicenter", "Lightsaber", AuthoredAnimation.Epicenter, new FeatType[] { FeatType.Epicenter1 }),
        new("SaberForceLink", "Force Link", "Lightsaber", AuthoredAnimation.SaberForceLink, new FeatType[] { FeatType.ForceLink1 }),
        new("ForceSheath", "Force Sheath", "Lightsaber", AuthoredAnimation.ForceSheath, new FeatType[] { FeatType.ForceSheath1, FeatType.ForceSheath2, FeatType.ForceSheath3, FeatType.ForceSheath4 }),
        new("GuardiansChallenge", "Guardian's Challenge", "Lightsaber", AuthoredAnimation.GuardiansChallenge, new FeatType[] { FeatType.GuardiansChallenge1, FeatType.GuardiansChallenge2 }),
        new("ImbuementStance", "Imbuement Stance", "Lightsaber", AuthoredAnimation.ImbuementStance, new FeatType[] { FeatType.ImbuementStance1 }),
        new("ImmovableStance", "Immovable Stance", "Lightsaber", AuthoredAnimation.ImmovableStance, new FeatType[] { FeatType.ImmovableStance1 }),
        new("Reprisal", "Reprisal", "Lightsaber", AuthoredAnimation.Reprisal, new FeatType[] { FeatType.Reprisal1, FeatType.Reprisal2 }),
        new("SaberWard", "Saber Ward", "Lightsaber", AuthoredAnimation.SaberWard, new FeatType[] { FeatType.SaberWard1, FeatType.SaberWard2, FeatType.SaberWard3, FeatType.SaberWard4 }),
        new("ShatteringStrike", "Shattering Strike", "Lightsaber", AuthoredAnimation.ShatteringStrike, new FeatType[] { FeatType.ShatteringStrike1, FeatType.ShatteringStrike2 }),
        new("SunderingSweep", "Sundering Sweep", "Lightsaber", AuthoredAnimation.SunderingSweep, new FeatType[] { FeatType.SunderingSweep1, FeatType.SunderingSweep2, FeatType.SunderingSweep3 }),
        new("ApexCollapseTechnique", "Apex Collapse", "Mimicry", AuthoredAnimation.ApexCollapseTechnique, new FeatType[] { FeatType.ApexCollapseTechnique }),
        new("ArcPulseTechnique", "Arc Pulse", "Mimicry", AuthoredAnimation.ArcPulseTechnique, new FeatType[] { FeatType.ArcPulseTechnique }),
        new("BarbedVolleyTechnique", "Barbed Volley", "Mimicry", AuthoredAnimation.BarbedVolleyTechnique, new FeatType[] { FeatType.BarbedVolleyTechnique }),
        new("BloodFrenzyFlurryTechnique", "Blood Frenzy Flurry", "Mimicry", AuthoredAnimation.BloodFrenzyFlurryTechnique, new FeatType[] { FeatType.BloodFrenzyFlurryTechnique }),
        new("BraceBreakerTechnique", "Brace Breaker", "Mimicry", AuthoredAnimation.BraceBreakerTechnique, new FeatType[] { FeatType.BraceBreakerTechnique }),
        new("BrutalBashTechnique", "Brutal Bash", "Mimicry", AuthoredAnimation.BrutalBashTechnique, new FeatType[] { FeatType.BrutalBashTechnique }),
        new("CapacitorSurgeTechnique", "Capacitor Surge", "Mimicry", AuthoredAnimation.CapacitorSurgeTechnique, new FeatType[] { FeatType.CapacitorSurgeTechnique }),
        new("ConcussiveChallengeTechnique", "Concussive Challenge", "Mimicry", AuthoredAnimation.ConcussiveChallengeTechnique, new FeatType[] { FeatType.ConcussiveChallengeTechnique }),
        new("CrossfireDrillTechnique", "Crossfire Drill", "Mimicry", AuthoredAnimation.CrossfireDrillTechnique, new FeatType[] { FeatType.CrossfireDrillTechnique }),
        new("CryoBileTechnique", "Cryo Bile", "Mimicry", AuthoredAnimation.CryoBileTechnique, new FeatType[] { FeatType.CryoBileTechnique }),
        new("DarkShockTechnique", "Dark Shock", "Mimicry", AuthoredAnimation.DarkShockTechnique, new FeatType[] { FeatType.DarkShockTechnique }),
        new("DisorientingScreechTechnique", "Disorienting Screech", "Mimicry", AuthoredAnimation.DisorientingScreechTechnique, new FeatType[] { FeatType.DisorientingScreechTechnique }),
        new("DreadWaveTechnique", "Dread Wave", "Mimicry", AuthoredAnimation.DreadWaveTechnique, new FeatType[] { FeatType.DreadWaveTechnique }),
        new("FinalEclipseTechnique", "Final Eclipse", "Mimicry", AuthoredAnimation.FinalEclipseTechnique, new FeatType[] { FeatType.FinalEclipseTechnique }),
        new("FinalLineTechnique", "Final Line", "Mimicry", AuthoredAnimation.FinalLineTechnique, new FeatType[] { FeatType.FinalLineTechnique }),
        new("FinalMandateTechnique", "Final Mandate", "Mimicry", AuthoredAnimation.FinalMandateTechnique, new FeatType[] { FeatType.FinalMandateTechnique }),
        new("FinalSuppressionTechnique", "Final Suppression", "Mimicry", AuthoredAnimation.FinalSuppressionTechnique, new FeatType[] { FeatType.FinalSuppressionTechnique }),
        new("FinishingDriveTechnique", "Finishing Drive", "Mimicry", AuthoredAnimation.FinishingDriveTechnique, new FeatType[] { FeatType.FinishingDriveTechnique }),
        new("FrostSpitTechnique", "Frost Spit", "Mimicry", AuthoredAnimation.FrostSpitTechnique, new FeatType[] { FeatType.FrostSpitTechnique }),
        new("GoringChargeTechnique", "Goring Charge", "Mimicry", AuthoredAnimation.GoringChargeTechnique, new FeatType[] { FeatType.GoringChargeTechnique }),
        new("GrenadeBurstTechnique", "Grenade Burst", "Mimicry", AuthoredAnimation.GrenadeBurstTechnique, new FeatType[] { FeatType.GrenadeBurstTechnique }),
        new("HoldfastSlamTechnique", "Holdfast Slam", "Mimicry", AuthoredAnimation.HoldfastSlamTechnique, new FeatType[] { FeatType.HoldfastSlamTechnique }),
        new("InfernoBlastTechnique", "Inferno Blast", "Mimicry", AuthoredAnimation.InfernoBlastTechnique, new FeatType[] { FeatType.InfernoBlastTechnique }),
        new("InnerCircleBindTechnique", "Inner Circle Bind", "Mimicry", AuthoredAnimation.InnerCircleBindTechnique, new FeatType[] { FeatType.InnerCircleBindTechnique }),
        new("InnerCirclePounceTechnique", "Inner Circle Pounce", "Mimicry", AuthoredAnimation.InnerCirclePounceTechnique, new FeatType[] { FeatType.InnerCirclePounceTechnique }),
        new("InnerCircleSurgeTechnique", "Inner Circle Surge", "Mimicry", AuthoredAnimation.InnerCircleSurgeTechnique, new FeatType[] { FeatType.InnerCircleSurgeTechnique }),
        new("InnerCircleVolleyTechnique", "Inner Circle Volley", "Mimicry", AuthoredAnimation.InnerCircleVolleyTechnique, new FeatType[] { FeatType.InnerCircleVolleyTechnique }),
        new("InnerRingFlurryTechnique", "Inner Ring Flurry", "Mimicry", AuthoredAnimation.InnerRingFlurryTechnique, new FeatType[] { FeatType.InnerRingFlurryTechnique }),
        new("InnerVoidTechnique", "Inner Void", "Mimicry", AuthoredAnimation.InnerVoidTechnique, new FeatType[] { FeatType.InnerVoidTechnique }),
        new("IonBurstTechnique", "Ion Burst", "Mimicry", AuthoredAnimation.IonBurstTechnique, new FeatType[] { FeatType.IonBurstTechnique }),
        new("LastBastionTechnique", "Last Bastion", "Mimicry", AuthoredAnimation.LastBastionTechnique, new FeatType[] { FeatType.LastBastionTechnique }),
        new("LockstepCrushTechnique", "Lockstep Crush", "Mimicry", AuthoredAnimation.LockstepCrushTechnique, new FeatType[] { FeatType.LockstepCrushTechnique }),
        new("MercilessAngleTechnique", "Merciless Angle", "Mimicry", AuthoredAnimation.MercilessAngleTechnique, new FeatType[] { FeatType.MercilessAngleTechnique }),
        new("NullShockTechnique", "Null Shock", "Mimicry", AuthoredAnimation.NullShockTechnique, new FeatType[] { FeatType.NullShockTechnique }),
        new("OverclockedAnalyzer", "Overclocked Analyzer", "Mimicry", AuthoredAnimation.OverclockedAnalyzer, new FeatType[] { FeatType.Overload }),
        new("PackHarrierTechnique", "Pack Harrier", "Mimicry", AuthoredAnimation.PackHarrierTechnique, new FeatType[] { FeatType.PackHarrierTechnique }),
        new("PermafrostRuptureTechnique", "Permafrost Rupture", "Mimicry", AuthoredAnimation.PermafrostRuptureTechnique, new FeatType[] { FeatType.PermafrostRuptureTechnique }),
        new("PiercingQuillsTechnique", "Piercing Quills", "Mimicry", AuthoredAnimation.PiercingQuillsTechnique, new FeatType[] { FeatType.PiercingQuillsTechnique }),
        new("PouncingStrikeTechnique", "Pouncing Strike", "Mimicry", AuthoredAnimation.PouncingStrikeTechnique, new FeatType[] { FeatType.PouncingStrikeTechnique }),
        new("PressureLockTechnique", "Pressure Lock", "Mimicry", AuthoredAnimation.PressureLockTechnique, new FeatType[] { FeatType.PressureLockTechnique }),
        new("RakingClawsTechnique", "Raking Claws", "Mimicry", AuthoredAnimation.RakingClawsTechnique, new FeatType[] { FeatType.RakingClawsTechnique }),
        new("RallyBreakerTechnique", "Rally Breaker", "Mimicry", AuthoredAnimation.RallyBreakerTechnique, new FeatType[] { FeatType.RallyBreakerTechnique }),
        new("RupturingQuakeTechnique", "Rupturing Quake", "Mimicry", AuthoredAnimation.RupturingQuakeTechnique, new FeatType[] { FeatType.RupturingQuakeTechnique }),
        new("SavageRoarTechnique", "Savage Roar", "Mimicry", AuthoredAnimation.SavageRoarTechnique, new FeatType[] { FeatType.SavageRoarTechnique }),
        new("ScorchingBreathTechnique", "Scorching Breath", "Mimicry", AuthoredAnimation.ScorchingBreathTechnique, new FeatType[] { FeatType.ScorchingBreathTechnique }),
        new("SeismicSlamTechnique", "Seismic Slam", "Mimicry", AuthoredAnimation.SeismicSlamTechnique, new FeatType[] { FeatType.SeismicSlamTechnique }),
        new("ShrapnelBurstTechnique", "Shrapnel Burst", "Mimicry", AuthoredAnimation.ShrapnelBurstTechnique, new FeatType[] { FeatType.ShrapnelBurstTechnique }),
        new("SignalSnareTechnique", "Signal Snare", "Mimicry", AuthoredAnimation.SignalSnareTechnique, new FeatType[] { FeatType.SignalSnareTechnique }),
        new("SnapRushTechnique", "Snap Rush", "Mimicry", AuthoredAnimation.SnapRushTechnique, new FeatType[] { FeatType.SnapRushTechnique }),
        new("SonicShriekTechnique", "Sonic Shriek", "Mimicry", AuthoredAnimation.SonicShriekTechnique, new FeatType[] { FeatType.SonicShriekTechnique }),
        new("StaticBurstTechnique", "Static Burst", "Mimicry", AuthoredAnimation.StaticBurstTechnique, new FeatType[] { FeatType.StaticBurstTechnique }),
        new("StaticWebTechnique", "Static Web", "Mimicry", AuthoredAnimation.StaticWebTechnique, new FeatType[] { FeatType.StaticWebTechnique }),
        new("StimCanisterTechnique", "Stim Canister", "Mimicry", AuthoredAnimation.StimCanisterTechnique, new FeatType[] { FeatType.StimCanisterTechnique }),
        new("SuppressingShotTechnique", "Suppressing Shot", "Mimicry", AuthoredAnimation.SuppressingShotTechnique, new FeatType[] { FeatType.SuppressingShotTechnique }),
        new("SustainBurnTechnique", "Sustain Burn", "Mimicry", AuthoredAnimation.SustainBurnTechnique, new FeatType[] { FeatType.SustainBurnTechnique }),
        new("TailSweepTechnique", "Tail Sweep", "Mimicry", AuthoredAnimation.TailSweepTechnique, new FeatType[] { FeatType.TailSweepTechnique }),
        new("TerrifyingBellowTechnique", "Terrifying Bellow", "Mimicry", AuthoredAnimation.TerrifyingBellowTechnique, new FeatType[] { FeatType.TerrifyingBellowTechnique }),
        new("ToxicCloudTechnique", "Toxic Cloud", "Mimicry", AuthoredAnimation.ToxicCloudTechnique, new FeatType[] { FeatType.ToxicCloudTechnique }),
        new("ToxicSpitTechnique", "Toxic Spit", "Mimicry", AuthoredAnimation.ToxicSpitTechnique, new FeatType[] { FeatType.ToxicSpitTechnique }),
        new("VenomSprayTechnique", "Venom Spray", "Mimicry", AuthoredAnimation.VenomSprayTechnique, new FeatType[] { FeatType.VenomSprayTechnique }),
        new("WardenClampTechnique", "Warden Clamp", "Mimicry", AuthoredAnimation.WardenClampTechnique, new FeatType[] { FeatType.WardenClampTechnique }),
        new("WardenMarkTechnique", "Warden Mark", "Mimicry", AuthoredAnimation.WardenMarkTechnique, new FeatType[] { FeatType.WardenMarkTechnique }),
        new("WardenMaulTechnique", "Warden Maul", "Mimicry", AuthoredAnimation.WardenMaulTechnique, new FeatType[] { FeatType.WardenMaulTechnique }),
        new("WardenOrderTechnique", "Warden Order", "Mimicry", AuthoredAnimation.WardenOrderTechnique, new FeatType[] { FeatType.WardenOrderTechnique }),
        new("WardenRendTechnique", "Warden Rend", "Mimicry", AuthoredAnimation.WardenRendTechnique, new FeatType[] { FeatType.WardenRendTechnique }),
        new("WardenSweepTechnique", "Warden Sweep", "Mimicry", AuthoredAnimation.WardenSweepTechnique, new FeatType[] { FeatType.WardenSweepTechnique }),
        new("WardenWallTechnique", "Warden Wall", "Mimicry", AuthoredAnimation.WardenWallTechnique, new FeatType[] { FeatType.WardenWallTechnique }),
        new("WillFractureTechnique", "Will Fracture", "Mimicry", AuthoredAnimation.WillFractureTechnique, new FeatType[] { FeatType.WillFractureTechnique }),
        new("DeadMansHand", "Dead Man's Hand", "Pistol", AuthoredAnimation.DeadMansHand, new FeatType[] { FeatType.DeadMansHand1 }),
        new("DisarmingShot", "Disarming Shot", "Pistol", AuthoredAnimation.DisarmingShot, new FeatType[] { FeatType.DisarmingShot1, FeatType.DisarmingShot2, FeatType.DisarmingShot3, FeatType.DisarmingShot4 }),
        new("DoubleShot", "Double Shot", "Pistol", AuthoredAnimation.DoubleShot, new FeatType[] { FeatType.DoubleShot1, FeatType.DoubleShot2, FeatType.DoubleShot3 }),
        new("FanTheHammer", "Fan the Hammer", "Pistol", AuthoredAnimation.FanTheHammer, new FeatType[] { FeatType.FanTheHammer1, FeatType.FanTheHammer2 }),
        new("GamblerStance", "Gambler Stance", "Pistol", AuthoredAnimation.GamblerStance, new FeatType[] { FeatType.GamblerStance1 }),
        new("InterruptingShot", "Interrupting Shot", "Pistol", AuthoredAnimation.InterruptingShot, new FeatType[] { FeatType.InterruptingShot1, FeatType.InterruptingShot2, FeatType.InterruptingShot3 }),
        new("LastWord", "Last Word", "Pistol", AuthoredAnimation.LastWord, new FeatType[] { FeatType.LastWord1 }),
        new("PointBlankBurst", "Point Blank Burst", "Pistol", AuthoredAnimation.PointBlankBurst, new FeatType[] { FeatType.PointBlankBurst1, FeatType.PointBlankBurst2 }),
        new("QuickDraw", "Quick Draw", "Pistol", AuthoredAnimation.QuickDraw, new FeatType[] { FeatType.QuickDraw1, FeatType.QuickDraw2, FeatType.QuickDraw3, FeatType.QuickDraw4 }),
        new("SkirmisherStance", "Skirmisher Stance", "Pistol", AuthoredAnimation.SkirmisherStance, new FeatType[] { FeatType.SkirmisherStance1 }),
        new("AimedShot", "Aimed Shot", "Rifle", AuthoredAnimation.AimedShot, new FeatType[] { FeatType.AimedShot1, FeatType.AimedShot2, FeatType.AimedShot3, FeatType.AimedShot4 }),
        new("CripplingShot", "Crippling Shot", "Rifle", AuthoredAnimation.CripplingShot, new FeatType[] { FeatType.CripplingShot1, FeatType.CripplingShot2, FeatType.CripplingShot3 }),
        new("Headshot", "Headshot", "Rifle", AuthoredAnimation.Headshot, new FeatType[] { FeatType.Headshot1, FeatType.Headshot2 }),
        new("KillBox", "Kill Box", "Rifle", AuthoredAnimation.KillBox, new FeatType[] { FeatType.KillBox1 }),
        new("OneShot", "One Shot", "Rifle", AuthoredAnimation.OneShot, new FeatType[] { FeatType.OneShot1 }),
        new("PiercingRound", "Piercing Round", "Rifle", AuthoredAnimation.PiercingRound, new FeatType[] { FeatType.PiercingRound1, FeatType.PiercingRound2, FeatType.PiercingRound3 }),
        new("SniperStance", "Sniper Stance", "Rifle", AuthoredAnimation.SniperStance, new FeatType[] { FeatType.SniperStance1 }),
        new("SuppressingShot", "Suppressing Shot", "Rifle", AuthoredAnimation.SuppressingShot, new FeatType[] { FeatType.SuppressingShot1, FeatType.SuppressingShot2, FeatType.SuppressingShot3, FeatType.SuppressingShot4 }),
        new("SuppressionStance", "Suppression Stance", "Rifle", AuthoredAnimation.SuppressionStance, new FeatType[] { FeatType.SuppressionStance1 }),
        new("SuppressiveLine", "Suppressive Line", "Rifle", AuthoredAnimation.SuppressiveLine, new FeatType[] { FeatType.SuppressiveLine1, FeatType.SuppressiveLine2 }),
        new("CircleSlash", "Circle Slash", "Saberstaff", AuthoredAnimation.CircleSlash, new FeatType[] { FeatType.CircleSlash1, FeatType.CircleSlash2, FeatType.CircleSlash3 }),
        new("ConduitStance", "Conduit Stance", "Saberstaff", AuthoredAnimation.ConduitStance, new FeatType[] { FeatType.ConduitStance1 }),
        new("DoubleStrike", "Double Strike", "Saberstaff", AuthoredAnimation.DoubleStrike, new FeatType[] { FeatType.DoubleStrike1, FeatType.DoubleStrike2, FeatType.DoubleStrike3, FeatType.DoubleStrike4 }),
        new("FocusedArc", "Focused Arc", "Saberstaff", AuthoredAnimation.FocusedArc, new FeatType[] { FeatType.FocusedArc1, FeatType.FocusedArc2, FeatType.FocusedArc3, FeatType.FocusedArc4 }),
        new("GuardedChannel", "Guarded Channel", "Saberstaff", AuthoredAnimation.GuardedChannel, new FeatType[] { FeatType.GuardedChannel1, FeatType.GuardedChannel2, FeatType.GuardedChannel3 }),
        new("InfiniteConduit", "Infinite Conduit", "Saberstaff", AuthoredAnimation.InfiniteConduit, new FeatType[] { FeatType.InfiniteConduit1 }),
        new("MaelstromArc", "Maelstrom Arc", "Saberstaff", AuthoredAnimation.MaelstromArc, new FeatType[] { FeatType.MaelstromArc1, FeatType.MaelstromArc2 }),
        new("SaberCyclone", "Saber Cyclone", "Saberstaff", AuthoredAnimation.SaberCyclone, new FeatType[] { FeatType.SaberCyclone1 }),
        new("SeverFocus", "Sever Focus", "Saberstaff", AuthoredAnimation.SeverFocus, new FeatType[] { FeatType.SeverFocus1, FeatType.SeverFocus2 }),
        new("TempestStance", "Tempest Stance", "Saberstaff", AuthoredAnimation.TempestStance, new FeatType[] { FeatType.TempestStance1 }),
        new("CripplingDefense", "Crippling Defense", "Spear", AuthoredAnimation.CripplingDefense, new FeatType[] { FeatType.CripplingDefense1 }),
        new("DisablingStrike", "Disabling Strike", "Spear", AuthoredAnimation.DisablingStrike, new FeatType[] { FeatType.DisablingStrike1, FeatType.DisablingStrike2, FeatType.DisablingStrike3, FeatType.DisablingStrike4 }),
        new("DisruptionField", "Disruption Field", "Spear", AuthoredAnimation.DisruptionField, new FeatType[] { FeatType.DisruptionField1, FeatType.DisruptionField2 }),
        new("Forcebane", "Forcebane", "Spear", AuthoredAnimation.Forcebane, new FeatType[] { FeatType.Forcebane1 }),
        new("HamperingBarrage", "Hampering Barrage", "Spear", AuthoredAnimation.HamperingBarrage, new FeatType[] { FeatType.HamperingBarrage1, FeatType.HamperingBarrage2 }),
        new("InterruptionStrike", "Interruption Strike", "Spear", AuthoredAnimation.InterruptionStrike, new FeatType[] { FeatType.InterruptionStrike1, FeatType.InterruptionStrike2, FeatType.InterruptionStrike3 }),
        new("PerceptiveStance", "Perceptive Stance", "Spear", AuthoredAnimation.PerceptiveStance, new FeatType[] { FeatType.PerceptiveStance1 }),
        new("SweepingFlank", "Sweeping Flank", "Spear", AuthoredAnimation.SweepingFlank, new FeatType[] { FeatType.SweepingFlank1, FeatType.SweepingFlank2, FeatType.SweepingFlank3 }),
        new("VigorStance", "Vigor Stance", "Spear", AuthoredAnimation.VigorStance, new FeatType[] { FeatType.VigorStance1 }),
        new("VigorThrust", "Vigor Thrust", "Spear", AuthoredAnimation.VigorThrust, new FeatType[] { FeatType.VigorThrust1, FeatType.VigorThrust2, FeatType.VigorThrust3, FeatType.VigorThrust4 }),
        new("CrusherStance", "Crusher Stance", "Staff", AuthoredAnimation.CrusherStance, new FeatType[] { FeatType.CrusherStance1 }),
        new("GroundQuake", "Ground Quake", "Staff", AuthoredAnimation.GroundQuake, new FeatType[] { FeatType.GroundQuake1, FeatType.GroundQuake2 }),
        new("LegSweep", "Leg Sweep", "Staff", AuthoredAnimation.LegSweep, new FeatType[] { FeatType.LegSweep1, FeatType.LegSweep2, FeatType.LegSweep3 }),
        new("LineBreaker", "Line Breaker", "Staff", AuthoredAnimation.LineBreaker, new FeatType[] { FeatType.LineBreaker1, FeatType.LineBreaker2, FeatType.LineBreaker3, FeatType.LineBreaker4 }),
        new("RibBreaker", "Rib Breaker", "Staff", AuthoredAnimation.RibBreaker, new FeatType[] { FeatType.RibBreaker1, FeatType.RibBreaker2, FeatType.RibBreaker3 }),
        new("SentinelStance", "Sentinel Stance", "Staff", AuthoredAnimation.SentinelStance, new FeatType[] { FeatType.SentinelStance1 }),
        new("ShelterCircle", "Shelter Circle", "Staff", AuthoredAnimation.ShelterCircle, new FeatType[] { FeatType.ShelterCircle1 }),
        new("Slam", "Slam", "Staff", AuthoredAnimation.Slam, new FeatType[] { FeatType.Slam1, FeatType.Slam2, FeatType.Slam3, FeatType.Slam4 }),
        new("SweepingGuard", "Sweeping Guard", "Staff", AuthoredAnimation.SweepingGuard, new FeatType[] { FeatType.SweepingGuard1 }),
        new("UnmovingCenter", "Unmoving Center", "Staff", AuthoredAnimation.UnmovingCenter, new FeatType[] { FeatType.UnmovingCenter1 }),
        new("Worldbreaker", "Worldbreaker", "Staff", AuthoredAnimation.Worldbreaker, new FeatType[] { FeatType.Worldbreaker1 }),
        new("ConcussiveToss", "Concussive Toss", "Throwing", AuthoredAnimation.ConcussiveToss, new FeatType[] { FeatType.ConcussiveToss1, FeatType.ConcussiveToss2 }),
        new("ExplosiveToss", "Explosive Toss", "Throwing", AuthoredAnimation.ExplosiveToss, new FeatType[] { FeatType.ExplosiveToss1, FeatType.ExplosiveToss2, FeatType.ExplosiveToss3, FeatType.ExplosiveToss4 }),
        new("FlashToss", "Flash Toss", "Throwing", AuthoredAnimation.FlashToss, new FeatType[] { FeatType.FlashToss1, FeatType.FlashToss2, FeatType.FlashToss3 }),
        new("FlurryStance", "Flurry Stance", "Throwing", AuthoredAnimation.FlurryStance, new FeatType[] { FeatType.FlurryStance1 }),
        new("OrdnanceStance", "Ordnance Stance", "Throwing", AuthoredAnimation.OrdnanceStance, new FeatType[] { FeatType.OrdnanceStance1 }),
        new("PerfectFlurry", "Perfect Flurry", "Throwing", AuthoredAnimation.PerfectFlurry, new FeatType[] { FeatType.PerfectFlurry1 }),
        new("PiercingToss", "Piercing Toss", "Throwing", AuthoredAnimation.PiercingToss, new FeatType[] { FeatType.PiercingToss1, FeatType.PiercingToss2, FeatType.PiercingToss3, FeatType.PiercingToss4 }),
        new("PinningToss", "Pinning Toss", "Throwing", AuthoredAnimation.PinningToss, new FeatType[] { FeatType.PinningToss1, FeatType.PinningToss2, FeatType.PinningToss3 }),
        new("RainOfSteel", "Rain of Steel", "Throwing", AuthoredAnimation.RainOfSteel, new FeatType[] { FeatType.RainOfSteel1 }),
        new("SeveringToss", "Severing Toss", "Throwing", AuthoredAnimation.SeveringToss, new FeatType[] { FeatType.SeveringToss1, FeatType.SeveringToss2 }),
        new("BladeVortex", "Blade Vortex", "Twin Blade", AuthoredAnimation.BladeVortex, new FeatType[] { FeatType.BladeVortex1, FeatType.BladeVortex2 }),
        new("CrossCut", "Cross Cut", "Twin Blade", AuthoredAnimation.CrossCut, new FeatType[] { FeatType.CrossCut1, FeatType.CrossCut2, FeatType.CrossCut3, FeatType.CrossCut4 }),
        new("CycloneStance", "Cyclone Stance", "Twin Blade", AuthoredAnimation.CycloneStance, new FeatType[] { FeatType.CycloneStance1 }),
        new("LaceratingTwinCut", "Lacerating Twin Cut", "Twin Blade", AuthoredAnimation.LaceratingTwinCut, new FeatType[] { FeatType.LaceratingTwinCut1, FeatType.LaceratingTwinCut2, FeatType.LaceratingTwinCut3, FeatType.LaceratingTwinCut4 }),
        new("LaceratorStance", "Lacerator Stance", "Twin Blade", AuthoredAnimation.LaceratorStance, new FeatType[] { FeatType.LaceratorStance1 }),
        new("RedBloom", "Red Bloom", "Twin Blade", AuthoredAnimation.RedBloom, new FeatType[] { FeatType.RedBloom1 }),
        new("SerratedArc", "Serrated Arc", "Twin Blade", AuthoredAnimation.SerratedArc, new FeatType[] { FeatType.SerratedArc1, FeatType.SerratedArc2, FeatType.SerratedArc3 }),
        new("SpinningWhirl", "Spinning Whirl", "Twin Blade", AuthoredAnimation.SpinningWhirl, new FeatType[] { FeatType.SpinningWhirl1, FeatType.SpinningWhirl2, FeatType.SpinningWhirl3 }),
        new("TempestBloom", "Tempest Bloom", "Twin Blade", AuthoredAnimation.TempestBloom, new FeatType[] { FeatType.TempestBloom1 }),
        new("TwinRupture", "Twin Rupture", "Twin Blade", AuthoredAnimation.TwinRupture, new FeatType[] { FeatType.TwinRupture1, FeatType.TwinRupture2 }),
        new("BerserkerStance", "Berserker Stance", "Vibroblade", AuthoredAnimation.BerserkerStance, new FeatType[] { FeatType.BerserkerStance1 }),
        new("CoveringStrike", "Covering Strike", "Vibroblade", AuthoredAnimation.CoveringStrike, new FeatType[] { FeatType.CoveringStrike1, FeatType.CoveringStrike2, FeatType.CoveringStrike3 }),
        new("DefensiveStance", "Defensive Stance", "Vibroblade", AuthoredAnimation.DefensiveStance, new FeatType[] { FeatType.DefensiveStance1 }),
        new("Invincible", "Invincible", "Vibroblade", AuthoredAnimation.Invincible, new FeatType[] { FeatType.Invincible1 }),
        new("RendingStrike", "Rending Strike", "Vibroblade", AuthoredAnimation.RendingStrike, new FeatType[] { FeatType.RendingStrike1, FeatType.RendingStrike2 }),
        new("RiotBlade", "Riot Blade", "Vibroblade", AuthoredAnimation.RiotBlade, new FeatType[] { FeatType.RiotBlade1, FeatType.RiotBlade2, FeatType.RiotBlade3, FeatType.RiotBlade4 }),
        new("SavageCleave", "Savage Cleave", "Vibroblade", AuthoredAnimation.SavageCleave, new FeatType[] { FeatType.SavageCleave1, FeatType.SavageCleave2, FeatType.SavageCleave3 }),
        new("ShieldBash", "Shield Bash", "Vibroblade", AuthoredAnimation.ShieldBash, new FeatType[] { FeatType.ShieldBash1, FeatType.ShieldBash2, FeatType.ShieldBash3, FeatType.ShieldBash4 }),
        new("ShieldWall", "Shield Wall", "Vibroblade", AuthoredAnimation.ShieldWall, new FeatType[] { FeatType.ShieldWall1, FeatType.ShieldWall2 }),
        new("AssassinsStance", "Assassin's Stance", "Vibroknife", AuthoredAnimation.AssassinsStance, new FeatType[] { FeatType.AssassinsStance1 }),
        new("Backstab", "Backstab", "Vibroknife", AuthoredAnimation.Backstab, new FeatType[] { FeatType.Backstab1, FeatType.Backstab2 }),
        new("CripplingSlice", "Crippling Slice", "Vibroknife", AuthoredAnimation.CripplingSlice, new FeatType[] { FeatType.CripplingSlice1, FeatType.CripplingSlice2, FeatType.CripplingSlice3 }),
        new("EscapeArtist", "Escape Artist", "Vibroknife", AuthoredAnimation.EscapeArtist, new FeatType[] { FeatType.EscapeArtist1 }),
        new("PathogenStrike", "Pathogen Strike", "Vibroknife", AuthoredAnimation.PathogenStrike, new FeatType[] { FeatType.PathogenStrike1, FeatType.PathogenStrike2, FeatType.PathogenStrike3, FeatType.PathogenStrike4 }),
        new("ShadowflowStance", "Shadowflow Stance", "Vibroknife", AuthoredAnimation.ShadowflowStance, new FeatType[] { FeatType.ShadowflowStance1 }),
        new("VeiledStrike", "Veiled Strike", "Vibroknife", AuthoredAnimation.VeiledStrike, new FeatType[] { FeatType.VeiledStrike1, FeatType.VeiledStrike2, FeatType.VeiledStrike3, FeatType.VeiledStrike4 }),
        new("ViralCascade", "Viral Cascade", "Vibroknife", AuthoredAnimation.ViralCascade, new FeatType[] { FeatType.ViralCascade1 }),
        new("VirulentBlade", "Virulent Blade", "Vibroknife", AuthoredAnimation.VirulentBlade, new FeatType[] { FeatType.VirulentBlade1, FeatType.VirulentBlade2, FeatType.VirulentBlade3 }),
        new("VolatileCompound", "Volatile Compound", "Vibroknife", AuthoredAnimation.VolatileCompound, new FeatType[] { FeatType.VolatileCompound1, FeatType.VolatileCompound2 }),
    };
}
