// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Pistol
{
    public class DisarmingShotAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.DisarmingShot1, PerkType.DisarmingShot)
                    .Name("Disarming Shot I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.DisarmingShot, 18.0f),
                SkillType.Pistol,
                8,
                30,
                null,
                null,
                3,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.PointPistol,
                25.0f,
                AbilityType.Perception,
                new WeaponAbilityProfile
                {
                    StatusEffectFactory = () => new DisarmingShotStatusEffect(10)
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.DisarmingShot2, PerkType.DisarmingShot)
                    .Name("Disarming Shot II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.DisarmingShot, 18.0f),
                SkillType.Pistol,
                18,
                30,
                null,
                null,
                5,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.PointPistol,
                25.0f,
                AbilityType.Perception,
                new WeaponAbilityProfile
                {
                    StatusEffectFactory = () => new DisarmingShotStatusEffect(12)
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.DisarmingShot3, PerkType.DisarmingShot)
                    .Name("Disarming Shot III")
                    .Level(3)
                    .HasRecastDelay(RecastGroup.DisarmingShot, 18.0f),
                SkillType.Pistol,
                28,
                30,
                null,
                null,
                8,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.PointPistol,
                25.0f,
                AbilityType.Perception,
                new WeaponAbilityProfile
                {
                    StatusEffectFactory = () => new DisarmingShotStatusEffect(15)
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.DisarmingShot4, PerkType.DisarmingShot)
                    .Name("Disarming Shot IV")
                    .Level(4)
                    .HasRecastDelay(RecastGroup.DisarmingShot, 18.0f),
                SkillType.Pistol,
                38,
                30,
                null,
                null,
                12,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.PointPistol,
                25.0f,
                AbilityType.Perception,
                new WeaponAbilityProfile
                {
                    StatusEffectFactory = () => new DisarmingShotStatusEffect(18)
                });

            return builder.Build();
        }
    }
}
