// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Pistol
{
    public class PointBlankBurstAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.PointBlankBurst1, PerkType.PointBlankBurst)
                    .Name("Point Blank Burst I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.PointBlankBurst, 30.0f),
                SkillType.Pistol,
                16,
                30,
                null,
                null,
                6,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.PointBlankBurst1,
                AbilityTargetingShapeType.Sphere,
                5.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.PointPistol,
                25.0f,
                AbilityType.Perception,
                new GeneratedWeaponAbilityProfile
                {
                    SelfStatusEffectFactory = () => new PointBlankBurstStatusEffect(10),
                    SelfStatDurationSeconds = 30,
                    ApplySelfModifiersOnHostileActivation = true
                });

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.PointBlankBurst2, PerkType.PointBlankBurst)
                    .Name("Point Blank Burst II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.PointBlankBurst, 30.0f),
                SkillType.Pistol,
                30,
                30,
                null,
                null,
                9,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.PointBlankBurst2,
                AbilityTargetingShapeType.Sphere,
                5.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.PointPistol,
                25.0f,
                AbilityType.Perception,
                new GeneratedWeaponAbilityProfile
                {
                    SelfStatusEffectFactory = () => new PointBlankBurstStatusEffect(15),
                    SelfStatDurationSeconds = 30,
                    ApplySelfModifiersOnHostileActivation = true
                });

            return builder.Build();
        }
    }
}
