using System.Collections.Generic;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.CombatService;
using SWLOR.NWN.API.NWScript.Enum;
using SWLOR.NWN.API.NWScript.Enum.VisualEffect;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.NPC
{
// <auto-generated by UpdateCapstoneEnemyIdentity.ps1>

    public class HoldfastSlamAbilityDefinition : IAbilityListDefinition
    {
        private readonly AbilityBuilder _builder = new AbilityBuilder();

        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            NPCSignatureAbility.BuildSingleTarget(
                _builder,
                FeatType.HoldfastSlam,
                "Holdfast Slam",
                Animation.DoubleThrust,
                InnateAbilityProfile.CreaturePhysical,
                1.3f,
                34.0f,
                8,
                23,
                12,
                typeof(SunderStatusEffect),
                CombatDamageType.Physical,
                ResistanceType.Trauma,
                VisualEffect.Vfx_Com_Chunk_Red_Medium,
                maxRange: 3.0f);

            return _builder.Build();
        }
    }
}
