using System.Collections.Generic;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.CombatService;
using SWLOR.NWN.API.NWScript.Enum;
using SWLOR.NWN.API.NWScript.Enum.VisualEffect;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.NPC
{
// <auto-generated by UpdateCapstoneEnemyIdentity.ps1>

    public class InnerCircleBindAbilityDefinition : IAbilityListDefinition
    {
        private readonly AbilityBuilder _builder = new AbilityBuilder();

        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            NPCSignatureAbility.BuildSingleTarget(
                _builder,
                FeatType.InnerCircleBind,
                "Inner Circle Bind",
                Animation.CastOutAnimation,
                InnateAbilityProfile.CreaturePhysical,
                1.3f,
                34.0f,
                8,
                21,
                12,
                typeof(WeaponJam1StatusEffect),
                CombatDamageType.Electrical,
                ResistanceType.Disruption,
                VisualEffect.Vfx_Imp_Lightning_M,
                maxRange: 12.0f);

            return _builder.Build();
        }
    }
}
