using System.Collections.Generic;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.CombatService;
using SWLOR.NWN.API.NWScript.Enum;
using SWLOR.NWN.API.NWScript.Enum.VisualEffect;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.NPC
{
// <auto-generated by UpdateCapstoneEnemyIdentity.ps1>

    public class LastBastionAbilityDefinition : IAbilityListDefinition
    {
        private readonly AbilityBuilder _builder = new AbilityBuilder();

        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            NPCSignatureAbility.BuildArea(
                _builder,
                FeatType.LastBastion,
                "Last Bastion",
                Animation.ShieldWall,
                InnateAbilityProfile.CreaturePhysical,
                1.4f,
                38.0f,
                9,
                29,
                6,
                typeof(KnockdownStatusEffect),
                CombatImpactAreaShape.Line,
                8.0f,
                2.5f,
                CombatDamageType.Physical,
                ResistanceType.Mobility,
                VisualEffect.Vfx_Fnf_Screen_Bump,
                VisualEffect.Vfx_Fnf_Screen_Shake,
                maxRange: 8.0f,
                centerOnActivator: false);

            return _builder.Build();
        }
    }
}
