using System.Collections.Generic;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.CombatService;
using SWLOR.NWN.API.NWScript.Enum;
using SWLOR.NWN.API.NWScript.Enum.VisualEffect;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.NPC
{
// <auto-generated by UpdateCapstoneEnemyIdentity.ps1>

    public class PackHarrierAbilityDefinition : IAbilityListDefinition
    {
        private readonly AbilityBuilder _builder = new AbilityBuilder();

        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            NPCSignatureAbility.BuildSingleTarget(
                _builder,
                FeatType.PackHarrier,
                "Pack Harrier",
                Animation.DoubleThrust,
                InnateAbilityProfile.CreaturePhysical,
                0.8f,
                22.0f,
                5,
                19,
                6,
                typeof(HobbleStatusEffect),
                CombatDamageType.Physical,
                ResistanceType.Mobility,
                VisualEffect.Vfx_Com_Chunk_Red_Small,
                maxRange: 3.0f);

            return _builder.Build();
        }
    }
}
