using System.Collections.Generic;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.CombatService;
using SWLOR.NWN.API.NWScript.Enum;
using SWLOR.NWN.API.NWScript.Enum.VisualEffect;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.NPC
{
// <auto-generated by UpdateCapstoneEnemyIdentity.ps1>

    public class PressureLockAbilityDefinition : IAbilityListDefinition
    {
        private readonly AbilityBuilder _builder = new AbilityBuilder();

        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            NPCSignatureAbility.BuildArea(
                _builder,
                FeatType.PressureLock,
                "Pressure Lock",
                Animation.CastOutAnimation,
                InnateAbilityProfile.CreaturePhysical,
                1.0f,
                26.0f,
                6,
                19,
                8,
                typeof(ImmobilizedStatusEffect),
                CombatImpactAreaShape.Cone,
                5.0f,
                5.0f,
                CombatDamageType.Electrical,
                ResistanceType.Mobility,
                VisualEffect.Vfx_Imp_Head_Electricity,
                VisualEffect.Dur_Web,
                maxRange: 5.0f,
                centerOnActivator: false);

            return _builder.Build();
        }
    }
}
