using System.Collections.Generic;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.CombatService;
using SWLOR.NWN.API.NWScript.Enum;
using SWLOR.NWN.API.NWScript.Enum.VisualEffect;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.NPC
{
// <auto-generated by UpdateCapstoneEnemyIdentity.ps1>

    public class SnapRushAbilityDefinition : IAbilityListDefinition
    {
        private readonly AbilityBuilder _builder = new AbilityBuilder();

        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            NPCSignatureAbility.BuildArea(
                _builder,
                FeatType.SnapRush,
                "Snap Rush",
                Animation.DoubleThrust,
                InnateAbilityProfile.CreaturePhysical,
                1.0f,
                26.0f,
                6,
                23,
                8,
                typeof(BleedStatusEffect),
                CombatImpactAreaShape.Cone,
                5.0f,
                5.0f,
                CombatDamageType.Physical,
                ResistanceType.Trauma,
                VisualEffect.Vfx_Com_Blood_Spark_Medium,
                VisualEffect.Vfx_Fnf_Screen_Bump,
                maxRange: 5.0f,
                centerOnActivator: false);

            return _builder.Build();
        }
    }
}
