using System.Collections.Generic;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.CombatService;
using SWLOR.NWN.API.NWScript.Enum;
using SWLOR.NWN.API.NWScript.Enum.VisualEffect;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.NPC
{
// <auto-generated by UpdateCapstoneEnemyIdentity.ps1>

    public class WardenOrderAbilityDefinition : IAbilityListDefinition
    {
        private readonly AbilityBuilder _builder = new AbilityBuilder();

        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            NPCSignatureAbility.BuildArea(
                _builder,
                FeatType.WardenOrder,
                "Warden Order",
                Animation.FireForgetTaunt,
                InnateAbilityProfile.CreaturePhysical,
                1.1f,
                30.0f,
                7,
                24,
                10,
                typeof(DisorientedStatusEffect),
                CombatImpactAreaShape.Sphere,
                5.5f,
                0.0f,
                CombatDamageType.Sonic,
                ResistanceType.Mind,
                VisualEffect.Vfx_Imp_Dazed_S,
                VisualEffect.Vfx_Fnf_Sound_Burst,
                maxRange: 0.0f,
                centerOnActivator: true);

            return _builder.Build();
        }
    }
}
