using System.Collections.Generic;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.CombatService;
using SWLOR.NWN.API.NWScript.Enum;
using SWLOR.NWN.API.NWScript.Enum.VisualEffect;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.NPC
{
// <auto-generated by UpdateCapstoneEnemyIdentity.ps1>

    public class WardenSweepAbilityDefinition : IAbilityListDefinition
    {
        private readonly AbilityBuilder _builder = new AbilityBuilder();

        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            NPCSignatureAbility.BuildArea(
                _builder,
                FeatType.WardenSweep,
                "Warden Sweep",
                Animation.Whirlwind,
                InnateAbilityProfile.CreaturePhysical,
                1.1f,
                30.0f,
                7,
                28,
                10,
                typeof(SunderStatusEffect),
                CombatImpactAreaShape.Sphere,
                5.5f,
                0.0f,
                CombatDamageType.Physical,
                ResistanceType.Trauma,
                VisualEffect.Vfx_Com_Chunk_Red_Small,
                VisualEffect.Vfx_Fnf_Screen_Shake,
                maxRange: 0.0f,
                centerOnActivator: true);

            return _builder.Build();
        }
    }
}
