using System.Collections.Generic;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.CombatService;
using SWLOR.NWN.API.NWScript.Enum;
using SWLOR.NWN.API.NWScript.Enum.VisualEffect;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.NPC
{
// <auto-generated by UpdateCapstoneEnemyIdentity.ps1>

    public class WardenMarkAbilityDefinition : IAbilityListDefinition
    {
        private readonly AbilityBuilder _builder = new AbilityBuilder();

        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            NPCSignatureAbility.BuildArea(
                _builder,
                FeatType.WardenMark,
                "Warden Mark",
                Animation.FireForgetDodgeSide,
                InnateAbilityProfile.CreaturePhysical,
                1.1f,
                30.0f,
                7,
                26,
                10,
                typeof(MarkedStatusEffect),
                CombatImpactAreaShape.Sphere,
                5.5f,
                0.0f,
                CombatDamageType.Electrical,
                ResistanceType.Electrical,
                VisualEffect.Vfx_Imp_Magical_Vision,
                VisualEffect.Vfx_Fnf_Storm,
                maxRange: 0.0f,
                centerOnActivator: true);

            return _builder.Build();
        }
    }
}
