using System.Collections.Generic;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.CombatService;
using SWLOR.NWN.API.NWScript.Enum;
using SWLOR.NWN.API.NWScript.Enum.VisualEffect;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.NPC
{
// <auto-generated by UpdateCapstoneEnemyIdentity.ps1>

    public class WillFractureAbilityDefinition : IAbilityListDefinition
    {
        private readonly AbilityBuilder _builder = new AbilityBuilder();

        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            NPCSignatureAbility.BuildArea(
                _builder,
                FeatType.WillFracture,
                "Will Fracture",
                Animation.CastOutAnimation,
                InnateAbilityProfile.CreaturePhysical,
                1.0f,
                26.0f,
                6,
                22,
                8,
                typeof(FoggyMindStatusEffect),
                CombatImpactAreaShape.Cone,
                5.0f,
                5.0f,
                CombatDamageType.Force,
                ResistanceType.Mind,
                VisualEffect.Vfx_Imp_Fear_S,
                VisualEffect.Vfx_Fnf_Gas_Explosion_Mind,
                maxRange: 5.0f,
                centerOnActivator: false);

            return _builder.Build();
        }
    }
}
