namespace SWLOR.NWN.API.NWScript.Enum.Item.Property
{
    public enum ItemPropertyFeat
    {
        Alertness = 0,
        Ambidextrous = 1,
        Cleave = 2,
        CombatCasting = 3,
        Dodge = 4,
        ExtraTurning = 5,
        Knockdown = 6,
        Pointblank = 7,
        SpellFocusAdjudication = 8,
        SpellFocusConjuration = 9,
        SpellFocusDivination = 10,
        SpellFocusEnchantment = 11,
        SpellFocusEvocation = 12,
        SpellFocusIllusion = 13,
        SpellFocusNecromancy = 14,
        SpellPenetration = 15,
        PowerAttack = 16,
        TwoWeaponFighting = 17,
        WeaponSpellUnarmed = 18,
        WeaponFinesse = 19,
        ImprovedCriticalUnarmed = 20,
        WeaponProficiencyExotic = 21,
        WeaponProficiencyMartial = 22,
        WeaponProficiencySimple = 23,
        ArmorProficiencyHeavy = 24,
        ArmorProficiencyLight = 25,
        ArmorProficiencyMedium = 26,
        Mobility = 27,
        Disarm = 28,
        Whirlwind = 29,
        RapidShot = 30,
        HideInPlainSight = 31,
        SneakAttack1D6 = 32,
        SneakAttack2D6 = 33,
        SneakAttack3D6 = 34,
        ShieldProficiency = 35,
        UsePoison = 36,
        DisarmWhip = 37,
        WeaponProficiencyCreature = 38,
        SneakAttack5D6 = 39,
        PlayerTool01 = 53,
        PlayerTool02 = 54,
        PlayerTool03 = 55,
        PlayerTool04 = 56,
        PlayerTool05 = 57,
        PlayerTool06 = 58,
        PlayerTool07 = 59,
        PlayerTool08 = 60,
        PlayerTool09 = 61,
        PlayerTool10 = 62
    }
}