namespace SWLOR.NWN.API.NWScript.Enum.Item.Property
{
    // Corresponds to iprp_foodtype.2da
    public enum FoodItemPropertySubType
    {
        Invalid = 0,
        HP = 1,
        FP = 2,
        STM = 3,
        HPRegen = 4,
        FPRegen = 5,
        STMRegen = 6,
        RestRegen = 7,
        XPBonus = 8,
        CombatReadiness = 9,
        Duration = 10,
        Might = 11,
        Vitality = 12,
        Perception = 13,
        Willpower = 14,
        Agility = 15,
        Social = 16,
        DefensePhysical = 17,
        DefenseForce = 18,
        ResistanceFire = 19,
        ResistancePoison = 20,
        ResistanceElectrical = 21,
        ResistanceIce = 22,
        Evasion = 23,
        ControlSmithery = 24,
        CraftsmanshipSmithery = 25,
        ControlEngineering = 26,
        CraftsmanshipEngineering = 27,
        ControlFabrication = 28,
        CraftsmanshipFabrication = 29,
        ControlAgriculture = 30,
        CraftsmanshipAgriculture = 31,
        Accuracy = 32,
        Attack = 33,
        ResistanceMind = 34,
        ResistanceMobility = 35,
        ResistanceTrauma = 36,
        ResistanceDisruption = 37,
    }
}
