namespace SWLOR.Game.Server.Service.BeastMasteryService
{
    public enum BeastType
    {
        Invalid = 0,
        Aradile = 1,
        CrystalSpider = 2,
        Gimpassa = 3,
        JungleBug = 4,
        KathHound = 5,
        Klorslug = 6,
        Microtench = 7,
        MorabandSerpent = 8,
        Octotench = 9,
        Purbole = 10,
        QionSlug = 11,
        QionTiger = 12,
        Raivor = 13,
        SandBeetle = 14,
        SandDemon = 15,
        Sandswimmer = 16,
        Scorchellus = 17,
        ShearMite = 18,
        Shyrack = 19,
        Sprantal = 20,
        Squellbug = 21,
        Ssurian = 22,
        ValleyCairnmog = 23,
        ValleyCairnmogAlpha = 24,
        ValleyNashtah = 25,
        Viper = 26,
        Warocas = 27,
        WildwoodsKinrath = 28,
        Womprat = 29,
    }
}
