using System.Collections.Generic;

namespace SWLOR.Game.Server.ValueObject
{
    public class ColorNames
    {
        public Dictionary<int, string> ClothLeatherNames { get; set; }
        public Dictionary<int, string> MetalNames { get; set; }

        public ColorNames()
        {
            ClothLeatherNames = new Dictionary<int, string>
            {
                { 0, "Bleach" },
                { 1, "Light Brown" },
                { 2, "Brown" },
                { 3, "Dark Brown" },
                { 4, "Bright Ruddy Brown" },
                { 5, "Light Ruddy Brown" },
                { 6, "Ruddy Brown" },
                { 7, "Dark Ruddy Brown" },
                { 8, "Bright Tan" },
                { 9, "Light Tan" },
                { 10, "Tan" },
                { 11, "Dark Tan" },
                { 12, "Bright Chocolate Brown" },
                { 13, "Light Choclate Brown" },
                { 14, "Chocolate Brown" },
                { 15, "Dark Chocolate Brown" },
                { 16, "Bright Olive Green" },
                { 17, "Light Olive Green" },
                { 18, "Olive Green" },
                { 19, "Dark Olive Green" },
                { 20, "Light Grey" },
                { 21, "Grey" },
                { 22, "Dark Grey" },
                { 23, "Black" },
                { 24, "Bright Navy Blue" },
                { 25, "Navy Blue" },
                { 26, "Bright Blue" },
                { 27, "Blue" },
                { 28, "Bright Turquoise" },
                { 29, "Turquoise" },
                { 30, "Bright Green" },
                { 31, "Green" },
                { 32, "Yellow" },
                { 33, "Gold" },
                { 34, "Bright Orange" },
                { 35, "Orange" },
                { 36, "Bright Red" },
                { 37, "Red" },
                { 38, "Bright Pink" },
                { 39, "Pink" },
                { 40, "Bright Purple" },
                { 41, "Purple" },
                { 42, "Bright Violet" },
                { 43, "Violet" },
                { 44, "Grey Silk" },
                { 45, "Black Silk" },
                { 46, "Navy Blue Silk" },
                { 47, "Blue Silk" },
                { 48, "Turquoise Silk" },
                { 49, "Green Silk" },
                { 50, "Gold Silk" },
                { 51, "Orange Silk" },
                { 52, "Red Silk" },
                { 53, "Pink Silk" },
                { 54, "Purple Silk" },
                { 55, "Violet Silk" },
                { 56, "Light Grey Silk" },
                { 57, "Metallic Black" },
                { 58, "Metallic Gold" },
                { 59, "Metallic Copper" },
                { 60, "Metallic Steel" },
                { 61, "Metallic Platinum" },
                { 62, "Stark White" },
                { 63, "Midnight Black" },
                { 64, "Wet Brick" },
                { 65, "Riverbank Brown" },
                { 66, "Mustard" },
                { 67, "Dark Moss" },
                { 68, "Forest Green" },
                { 69, "Forest Drab" },
                { 70, "Indigo Purple" },
                { 71, "Violet Shadow" },
                { 72, "Dark Orchid" },
                { 73, "Orchid Shadow" },
                { 74, "Acorn Brown" },
                { 75, "Pale Brown" },
                { 76, "Sea Green" },
                { 77, "Aqua Shadow" },
                { 78, "Storm Blue" },
                { 79, "Charcoal" },
                { 80, "T'Nanshi Green" },
                { 81, "Dark Pine" },
                { 82, "Azure" },
                { 83, "Azure Shadow" },
                { 84, "Raw Umber" },
                { 85, "Umber Shadow" },
                { 86, "Mud Brown" },
                { 87, "Walnut" },
                { 88, "Scarlet" },
                { 89, "Crimson" },
                { 90, "Blood Red" },
                { 91, "Burgundy" },
                { 92, "Goldenrod" },
                { 93, "Dark Goldenrod" },
                { 94, "Rich Ochre" },
                { 95, "Old Leather" },
                { 96, "Mauve" },
                { 97, "Dark Mauve" },
                { 98, "Maroon" },
                { 99, "Wine Red" },
                { 100, "Dark Coral" },
                { 101, "Firebrick Red" },
                { 102, "Dark Firebrick" },
                { 103, "Dark Red" },
                { 104, "Dark Ferrell Green" },
                { 105, "Dark Green" },
                { 106, "Oak Green" },
                { 107, "Pine Green" },
                { 108, "Light Swamp Green" },
                { 109, "Swamp Green" },
                { 110, "M'Chekian Olive" },
                { 111, "M'Chekian Dark Olive" },
                { 112, "Deglossian Ash Green" },
                { 113, "Deglossian Dark Ash Green" },
                { 114, "Faded Sepia" },
                { 115, "Deep Earth" },
                { 116, "Khaki" },
                { 117, "Sienna" },
                { 118, "Dark Sienna" },
                { 119, "Mahogany" },
                { 120, "Sand" },
                { 121, "Driftwood" },
                { 122, "Bark" },
                { 123, "Dark Bark" },
                { 124, "Ash" },
                { 125, "Smoke" },
                { 126, "Light Bistre" },
                { 127, "Bistre" },
                { 128, "Wheat" },
                { 129, "Buckskin" },
                { 130, "Saddle Brown" },
                { 131, "Autumn Brown" },
                { 132, "Slate" },
                { 133, "Dark Slate" },
                { 134, "Midnight Ash" },
                { 135, "Midnight Smoke" },
                { 136, "Royal Blue" },
                { 137, "Cobalt" },
                { 138, "Ingoren Blue" },
                { 139, "Indigo Blue" },
                { 140, "Cyan Shadow" },
                { 141, "Light Teal" },
                { 142, "Teal" },
                { 143, "Teal Shadow" },
                { 144, "Magenta" },
                { 145, "Dark Magenta" },
                { 146, "Grape" },
                { 147, "Imperial Purple" },
                { 148, "Cornflower Blue" },
                { 149, "Steele Blue" },
                { 150, "Pale Turquoise" },
                { 151, "Dark Aquamarine" },
                { 152, "Sapling Green" },
                { 153, "Emerald" },
                { 154, "Honey" },
                { 155, "Dark Honey" },
                { 156, "Desert Brown" },
                { 157, "Ash Brown" },
                { 158, "Pale Rust" },
                { 159, "Rust" },
                { 160, "Dark Lilac" },
                { 161, "Mauve Shadow" },
                { 162, "Burnt Sienna" },
                { 163, "Dark Violet" },
                { 164, "Silver Gray" },
                { 165, "Kurathene Steel Blue" },
                { 166, "Snow" },
                { 167, "Midnight Camouflage" },
                { 168, "Drotid Tan" },
                { 169, "Viridian Shadow" },
                { 170, "Corsair Purple" },
                { 171, "Shadow" },
                { 172, "Lizard Belly Olive" },
                { 173, "Russet Shadow" },
                { 174, "Cinnamon" },
                { 175, "Forian's Gold" }
            };
            MetalNames = new Dictionary<int, string>
            {
                { 0, "Bleach" },
                { 1, "Light Iron" },
                { 2, "Dark Iron" },
                { 3, "Black" },
                { 4, "Bright Steel" },
                { 5, "Light Steel" },
                { 6, "Steel" },
                { 7, "Dark Steel" },
                { 8, "Bright Gold" },
                { 9, "Light Gold" },
                { 10, "Gold" },
                { 11, "Dark Gold" },
                { 12, "Bright Brass" },
                { 13, "Light Brass" },
                { 14, "Brass" },
                { 15, "Dark Brass" },
                { 16, "Bright Copper" },
                { 17, "Light Copper" },
                { 18, "Copper" },
                { 19, "Dark Copper" },
                { 20, "Bright Bronze" },
                { 21, "Light Bronze" },
                { 22, "Bronze" },
                { 23, "Dark Bronze" },
                { 24, "Bright Red" },
                { 25, "Red" },
                { 26, "Light Red" },
                { 27, "Dark Red" },
                { 28, "Bright Purple" },
                { 29, "Purple" },
                { 30, "Light Purple" },
                { 31, "Dark Purple" },
                { 32, "Bright Navy Blue" },
                { 33, "Navy Blue" },
                { 34, "Light Navy Blue" },
                { 35, "Dark Navy Blue" },
                { 36, "Bright Turquoise" },
                { 37, "Turquoise" },
                { 38, "Light Turquoise" },
                { 39, "Dark Turquoise" },
                { 40, "Bright Green" },
                { 41, "Green" },
                { 42, "Light Green" },
                { 43, "Dark Green" },
                { 44, "Bright Olive Green" },
                { 45, "Olive Green" },
                { 46, "Bright Sage" },
                { 47, "Dark Sage" },
                { 48, "Rainbow" },
                { 49, "Dark Rainbow" },
                { 50, "Rusted Light Iron" },
                { 51, "Heavily Rusted Light Iron" },
                { 52, "Rusted Dark Iron" },
                { 53, "Heavily Rusted Dark Iron" },
                { 54, "Worn Light Steel" },
                { 55, "Worn Steel" },
                { 56, "Polished Silver" },
                { 57, "Polished Black Steel" },
                { 58, "Polished Gold" },
                { 59, "Polished Copper" },
                { 60, "Polished Steel" },
                { 61, "Polished Platinum" },
                { 62, "Stark White" },
                { 63, "Midnight Black" },
                { 64, "Sanguine Red" },
                { 65, "Chocolate Steel" },
                { 66, "Amber Gold" },
                { 67, "Smoky Sage" },
                { 68, "Emerald Steel" },
                { 69, "Moonlight Moss" },
                { 70, "Elysian Violet" },
                { 71, "Stormreaver Gray" },
                { 72, "Jechran Purple" },
                { 73, "Legionnaire Steel" },
                { 74, "Burnished Bronze" },
                { 75, "Cold Iron" },
                { 76, "Bug Green" },
                { 77, "Drotid Steel" },
                { 78, "Kurathene Blue" },
                { 79, "Granite" },
                { 80, "Fern Steel" },
                { 81, "Dull Steel" },
                { 82, "Skymetal" },
                { 83, "Iron" },
                { 84, "Tarnished Silver" },
                { 85, "Gnomish Steel" },
                { 86, "Deglosian Silver" },
                { 87, "Tarnished Bronze" },
                { 88, "Ember Red" },
                { 89, "Demon Red" },
                { 90, "Blood Red" },
                { 91, "Crimson" },
                { 92, "Glorious Gold" },
                { 93, "Mustard Gold" },
                { 94, "Bandit Bronze" },
                { 95, "Woodsman Bronze" },
                { 96, "Lizard Scale Pink" },
                { 97, "Eggplant" },
                { 98, "Merlot" },
                { 99, "Swamp Purple" },
                { 100, "Brick Red" },
                { 101, "Fire Brick Red" },
                { 102, "Steak" },
                { 103, "Old Crimson Steel" },
                { 104, "Slime Green" },
                { 105, "Dark Slime Green" },
                { 106, "Forest Steel" },
                { 107, "Deep Forest Steel" },
                { 108, "Verdigris Silver" },
                { 109, "Dark Verdigris Silver" },
                { 110, "Olive Drab" },
                { 111, "Dark Olive Drab" },
                { 112, "Derrington Steel" },
                { 113, "Bazgamph Iron" },
                { 114, "Smoky Steel" },
                { 115, "Underdark Iron" },
                { 116, "Burnished Copper" },
                { 117, "Earthmetal" },
                { 118, "Russet" },
                { 119, "Deep Brown" },
                { 120, "Ancient Silver" },
                { 121, "Smoky Silver" },
                { 122, "Journeyman's Steel" },
                { 123, "Coldforged Iron" },
                { 124, "Stormmetal" },
                { 125, "Infantry Steel" },
                { 126, "Shadow Steel" },
                { 127, "Midnight Steel" },
                { 128, "Champagne Silver" },
                { 129, "Harvest Bronze" },
                { 130, "Chocolate Bronze" },
                { 131, "Deep Chocolate Bronze" },
                { 132, "Slate Steel" },
                { 133, "Smoky Slate Steel" },
                { 134, "Shadow Slate" },
                { 135, "Navy Steel" },
                { 136, "Bright Cobalt" },
                { 137, "Cobalt" },
                { 138, "Visimontium Blue" },
                { 139, "Twilight Steel" },
                { 140, "Aqua" },
                { 141, "Dark Aqua" },
                { 142, "Teal Steel" },
                { 143, "Dark Teal Steel" },
                { 144, "Heliotrope Pink" },
                { 145, "Grape" },
                { 146, "Imperial Purple" },
                { 147, "Deep Purple" },
                { 148, "Cornflower Steel" },
                { 149, "Royal Blue" },
                { 150, "Aquamarine" },
                { 151, "Deep Turquoise" },
                { 152, "Light Ferrell Green" },
                { 153, "Dark Ferrell Green" },
                { 154, "Old Bronze" },
                { 155, "Rich Bronze" },
                { 156, "Galdosian Copper" },
                { 157, "Rich Copper" },
                { 158, "Chestnut Copper" },
                { 159, "Rust" },
                { 160, "Lilac" },
                { 161, "Mauve" },
                { 162, "Puce" },
                { 163, "Violet-Eggplant" },
                { 164, "Mithril" },
                { 165, "Sunset Steel" },
                { 166, "Ice" },
                { 167, "Hunter Green" },
                { 168, "Cheap Silver" },
                { 169, "Summerleaf Slate" },
                { 170, "Indigo Smoke" },
                { 171, "Dark Slate Grey" },
                { 172, "Fish Belly Green" },
                { 173, "Indigo Shadow" },
                { 174, "Brown" },
                { 175, "Forian's Gold" }
            };



        }

    }
}
