// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Spear
{
    public class DisablingStrikeAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.DisablingStrike1, PerkType.DisablingStrike)
                    .Name("Disabling Strike I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.DisablingStrike, 18.0f),
                SkillType.Spear,
                8,
                30,
                typeof(FoggyMindStatusEffect),
                null,
                3,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                null);

            ConfigureWeaponAbility(
                builder.Create(FeatType.DisablingStrike2, PerkType.DisablingStrike)
                    .Name("Disabling Strike II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.DisablingStrike, 18.0f),
                SkillType.Spear,
                18,
                30,
                typeof(FoggyMindStatusEffect),
                null,
                5,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                null);

            ConfigureWeaponAbility(
                builder.Create(FeatType.DisablingStrike3, PerkType.DisablingStrike)
                    .Name("Disabling Strike III")
                    .Level(3)
                    .HasRecastDelay(RecastGroup.DisablingStrike, 18.0f),
                SkillType.Spear,
                28,
                30,
                typeof(FoggyMindStatusEffect),
                null,
                8,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                null);

            ConfigureWeaponAbility(
                builder.Create(FeatType.DisablingStrike4, PerkType.DisablingStrike)
                    .Name("Disabling Strike IV")
                    .Level(4)
                    .HasRecastDelay(RecastGroup.DisablingStrike, 18.0f),
                SkillType.Spear,
                38,
                30,
                typeof(FoggyMindStatusEffect),
                null,
                12,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                null);

            return builder.Build();
        }
    }
}
