// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Spear
{
    public class DisruptionFieldAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.DisruptionField1, PerkType.DisruptionField)
                    .Name("Disruption Field I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.DisruptionField, 30.0f),
                SkillType.Spear,
                16,
                30,
                typeof(ForceDisruptionStatusEffect),
                null,
                6,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.DisruptionField1,
                AbilityTargetingShapeType.Sphere,
                5.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                null);

            ConfigureWeaponAbility(
                builder.Create(FeatType.DisruptionField2, PerkType.DisruptionField)
                    .Name("Disruption Field II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.DisruptionField, 30.0f),
                SkillType.Spear,
                30,
                30,
                typeof(ForceDisruptionStatusEffect),
                null,
                9,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.DisruptionField2,
                AbilityTargetingShapeType.Sphere,
                5.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                null);

            return builder.Build();
        }
    }
}
