// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Spear
{
    public class HamperingBarrageAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.HamperingBarrage1, PerkType.HamperingBarrage)
                    .Name("Hampering Barrage I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.HamperingBarrage, 30.0f),
                SkillType.Spear,
                16,
                30,
                typeof(HamstringStatusEffect),
                null,
                6,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.HamperingBarrage1,
                AbilityTargetingShapeType.Cone,
                5.0f,
                5.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                null);

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.HamperingBarrage2, PerkType.HamperingBarrage)
                    .Name("Hampering Barrage II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.HamperingBarrage, 30.0f),
                SkillType.Spear,
                30,
                30,
                typeof(HamstringStatusEffect),
                null,
                9,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.HamperingBarrage2,
                AbilityTargetingShapeType.Cone,
                5.0f,
                5.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                null);

            return builder.Build();
        }
    }
}
