// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Spear
{
    public class InterruptionStrikeAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.InterruptionStrike1, PerkType.InterruptionStrike)
                    .Name("Interruption Strike I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.InterruptionStrike, 24.0f),
                SkillType.Spear,
                12,
                0,
                null,
                null,
                4,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    TargetUsingAbilityDrainFP = 4,
                    TargetUsingAbilityDrainStamina = 4
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.InterruptionStrike2, PerkType.InterruptionStrike)
                    .Name("Interruption Strike II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.InterruptionStrike, 24.0f),
                SkillType.Spear,
                24,
                0,
                null,
                null,
                8,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    TargetUsingAbilityDrainFP = 7,
                    TargetUsingAbilityDrainStamina = 7
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.InterruptionStrike3, PerkType.InterruptionStrike)
                    .Name("Interruption Strike III")
                    .Level(3)
                    .HasRecastDelay(RecastGroup.InterruptionStrike, 24.0f),
                SkillType.Spear,
                36,
                0,
                null,
                null,
                10,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    TargetUsingAbilityDrainFP = 10,
                    TargetUsingAbilityDrainStamina = 10
                });

            return builder.Build();
        }
    }
}
