// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.TwinBlade
{
    public class BladeVortexAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.BladeVortex1, PerkType.BladeVortex)
                    .Name("Blade Vortex I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.BladeVortex, 30.0f),
                SkillType.TwinBlade,
                18,
                0,
                null,
                null,
                6,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.BladeVortex1,
                AbilityTargetingShapeType.Sphere,
                5.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    RestoreStaminaIfMinimumTargetsHit = 4,
                    StaminaRestoreMinimumTargets = 3
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.BladeVortex2, PerkType.BladeVortex)
                    .Name("Blade Vortex II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.BladeVortex, 30.0f),
                SkillType.TwinBlade,
                30,
                0,
                null,
                null,
                9,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.BladeVortex2,
                AbilityTargetingShapeType.Sphere,
                5.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    RestoreStaminaIfMinimumTargetsHit = 6,
                    StaminaRestoreMinimumTargets = 3
                });

            return builder.Build();
        }
    }
}
