// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.TwinBlade
{
    public class CrossCutAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.CrossCut1, PerkType.CrossCut)
                    .Name("Cross Cut I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.CrossCut, 18.0f),
                SkillType.TwinBlade,
                6,
                30,
                null,
                null,
                3,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    HitCount = 2,
                    SelfHastePercentIfAllHitsLand = 5,
                    SelfHasteMaximumPercentIfAllHitsLand = 15,
                    SelfHasteDurationSecondsIfAllHitsLand = 30
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.CrossCut2, PerkType.CrossCut)
                    .Name("Cross Cut II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.CrossCut, 18.0f),
                SkillType.TwinBlade,
                13,
                30,
                null,
                null,
                5,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    HitCount = 2,
                    SelfHastePercentIfAllHitsLand = 5,
                    SelfHasteMaximumPercentIfAllHitsLand = 15,
                    SelfHasteDurationSecondsIfAllHitsLand = 30
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.CrossCut3, PerkType.CrossCut)
                    .Name("Cross Cut III")
                    .Level(3)
                    .HasRecastDelay(RecastGroup.CrossCut, 18.0f),
                SkillType.TwinBlade,
                20,
                30,
                null,
                null,
                8,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    HitCount = 2,
                    SelfHastePercentIfAllHitsLand = 5,
                    SelfHasteMaximumPercentIfAllHitsLand = 15,
                    SelfHasteDurationSecondsIfAllHitsLand = 30
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.CrossCut4, PerkType.CrossCut)
                    .Name("Cross Cut IV")
                    .Level(4)
                    .HasRecastDelay(RecastGroup.CrossCut, 18.0f),
                SkillType.TwinBlade,
                27,
                30,
                null,
                null,
                12,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    HitCount = 2,
                    SelfHastePercentIfAllHitsLand = 5,
                    SelfHasteMaximumPercentIfAllHitsLand = 15,
                    SelfHasteDurationSecondsIfAllHitsLand = 30
                });

            return builder.Build();
        }
    }
}
