// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.TwinBlade
{
    public class SerratedArcAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.SerratedArc1, PerkType.SerratedArc)
                    .Name("Serrated Arc I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.SerratedArc, 24.0f),
                SkillType.TwinBlade,
                10,
                0,
                null,
                null,
                4,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.SerratedArc1,
                AbilityTargetingShapeType.Sphere,
                5.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new GeneratedWeaponAbilityProfile
                {
                    SpreadBleedFromTarget = true,
                    SpreadBleedDurationSeconds = 30
                });

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.SerratedArc2, PerkType.SerratedArc)
                    .Name("Serrated Arc II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.SerratedArc, 24.0f),
                SkillType.TwinBlade,
                20,
                0,
                null,
                null,
                8,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.SerratedArc2,
                AbilityTargetingShapeType.Sphere,
                5.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new GeneratedWeaponAbilityProfile
                {
                    SpreadBleedFromTarget = true,
                    SpreadBleedDurationSeconds = 30
                });

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.SerratedArc3, PerkType.SerratedArc)
                    .Name("Serrated Arc III")
                    .Level(3)
                    .HasRecastDelay(RecastGroup.SerratedArc, 24.0f),
                SkillType.TwinBlade,
                30,
                0,
                null,
                null,
                10,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.SerratedArc3,
                AbilityTargetingShapeType.Sphere,
                5.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new GeneratedWeaponAbilityProfile
                {
                    SpreadBleedFromTarget = true,
                    SpreadBleedDurationSeconds = 30
                });

            return builder.Build();
        }
    }
}
