// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.TwinBlade
{
    public class TempestBloomAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.TempestBloom1, PerkType.TempestBloom)
                    .Name("Tempest Bloom")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.Capstone, 90.0f),
                SkillType.TwinBlade,
                25,
                45,
                null,
                null,
                15,
                0,
                2.0f,
                true,
                true,
                false,
                Spell.TempestBloom1,
                AbilityTargetingShapeType.Sphere,
                5.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    TemporaryAreaAbilityFragmentationDamage = 8,
                    TemporaryAreaAbilityFragmentationDurationSeconds = 30,
                    TemporaryAreaAbilityFragmentationPulseSeconds = 3,
                    TemporaryDefeatedEnemyEffectDurationSeconds = 45
                });

            return builder.Build();
        }
    }
}
