using System.Collections.Generic;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.NWN.API.NWScript.Enum;
namespace SWLOR.Game.Server.EngineTests.Definitions.PerkCoverage
{
    public sealed class ShipOperatingPerkCoverage : IPerkCoverageSource
    {
        public List<PerkCoverageCase> BuildCases() => new()
        {
                new() { Perk = PerkType.ShipIntercept, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipIntercept1, FeatType.ShipIntercept2, FeatType.ShipIntercept3 } },
                new() { Perk = PerkType.ShipBreakAway, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipBreakAway1, FeatType.ShipBreakAway2, FeatType.ShipBreakAway3 } },
                new() { Perk = PerkType.ShipEvasiveManeuver, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipEvasiveManeuver1, FeatType.ShipEvasiveManeuver2, FeatType.ShipEvasiveManeuver3 } },
                new() { Perk = PerkType.ShipManeuverHandling, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipManeuverHandlingTrait } },
                new() { Perk = PerkType.ShipPursuitEfficiency, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipPursuitEfficiencyTrait } },
                new() { Perk = PerkType.ShipPursuit, MaxLevel = 1, Prices = new[] { 3 }, GrantedFeats = new[] { FeatType.ShipPursuit1 } },
                new() { Perk = PerkType.ShipAceManeuver, MaxLevel = 1, Prices = new[] { 7 }, GrantedFeats = new[] { FeatType.ShipAceManeuver1 } },
                new() { Perk = PerkType.ShipEfficientTransit, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipEfficientTransit1, FeatType.ShipEfficientTransit2, FeatType.ShipEfficientTransit3 } },
                new() { Perk = PerkType.ShipHazardRun, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipHazardRun1, FeatType.ShipHazardRun2, FeatType.ShipHazardRun3 } },
                new() { Perk = PerkType.ShipEmergencyEscape, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipEmergencyEscape1, FeatType.ShipEmergencyEscape2, FeatType.ShipEmergencyEscape3 } },
                new() { Perk = PerkType.ShipNavigationEconomy, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipNavigationEconomyTrait } },
                new() { Perk = PerkType.ShipHazardHandling, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipHazardHandlingTrait } },
                new() { Perk = PerkType.ShipCruise, MaxLevel = 1, Prices = new[] { 3 }, GrantedFeats = new[] { FeatType.ShipCruise1 } },
                new() { Perk = PerkType.ShipSafePassage, MaxLevel = 1, Prices = new[] { 7 }, GrantedFeats = new[] { FeatType.ShipSafePassage1 } },
                new() { Perk = PerkType.ShipControlledBurst, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipControlledBurst1, FeatType.ShipControlledBurst2, FeatType.ShipControlledBurst3 } },
                new() { Perk = PerkType.ShipTrackingSolution, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipTrackingSolution1, FeatType.ShipTrackingSolution2, FeatType.ShipTrackingSolution3 } },
                new() { Perk = PerkType.ShipExploitOpening, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipExploitOpening1, FeatType.ShipExploitOpening2, FeatType.ShipExploitOpening3 } },
                new() { Perk = PerkType.ShipWeaponHandling, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipWeaponHandlingTrait } },
                new() { Perk = PerkType.ShipFiringEfficiency, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipFiringEfficiencyTrait } },
                new() { Perk = PerkType.ShipPrecision, MaxLevel = 1, Prices = new[] { 3 }, GrantedFeats = new[] { FeatType.ShipPrecision1 } },
                new() { Perk = PerkType.ShipPerfectSolution, MaxLevel = 1, Prices = new[] { 7 }, GrantedFeats = new[] { FeatType.ShipPerfectSolution1 } },
                new() { Perk = PerkType.ShipPreparedVolley, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipPreparedVolley1, FeatType.ShipPreparedVolley2, FeatType.ShipPreparedVolley3 } },
                new() { Perk = PerkType.ShipTorpedoRun, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipTorpedoRun1, FeatType.ShipTorpedoRun2, FeatType.ShipTorpedoRun3 } },
                new() { Perk = PerkType.ShipBombardment, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipBombardment1, FeatType.ShipBombardment2, FeatType.ShipBombardment3 } },
                new() { Perk = PerkType.ShipOrdnanceHandling, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipOrdnanceHandlingTrait } },
                new() { Perk = PerkType.ShipAmmunitionEconomy, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipAmmunitionEconomyTrait } },
                new() { Perk = PerkType.ShipSiege, MaxLevel = 1, Prices = new[] { 3 }, GrantedFeats = new[] { FeatType.ShipSiege1 } },
                new() { Perk = PerkType.ShipCoordinatedSalvo, MaxLevel = 1, Prices = new[] { 7 }, GrantedFeats = new[] { FeatType.ShipCoordinatedSalvo1 } },
                new() { Perk = PerkType.ShipEmergencyRepair, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipEmergencyRepair1, FeatType.ShipEmergencyRepair2, FeatType.ShipEmergencyRepair3 } },
                new() { Perk = PerkType.ShipPowerRouting, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipPowerRouting1, FeatType.ShipPowerRouting2, FeatType.ShipPowerRouting3 } },
                new() { Perk = PerkType.ShipShieldRecovery, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipShieldRecovery1, FeatType.ShipShieldRecovery2, FeatType.ShipShieldRecovery3 } },
                new() { Perk = PerkType.ShipRecoveryEfficiency, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipRecoveryEfficiencyTrait } },
                new() { Perk = PerkType.ShipPowerDiscipline, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipPowerDisciplineTrait } },
                new() { Perk = PerkType.ShipDefensiveRouting, MaxLevel = 1, Prices = new[] { 3 }, GrantedFeats = new[] { FeatType.ShipDefensiveRouting1 } },
                new() { Perk = PerkType.ShipDamageControl, MaxLevel = 1, Prices = new[] { 7 }, GrantedFeats = new[] { FeatType.ShipDamageControl1 } },
                new() { Perk = PerkType.ShipRepairLink, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipRepairLink1, FeatType.ShipRepairLink2, FeatType.ShipRepairLink3 } },
                new() { Perk = PerkType.ShipCapacitorTransfer, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipCapacitorTransfer1, FeatType.ShipCapacitorTransfer2, FeatType.ShipCapacitorTransfer3 } },
                new() { Perk = PerkType.ShipSupportSurge, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipSupportSurge1, FeatType.ShipSupportSurge2, FeatType.ShipSupportSurge3 } },
                new() { Perk = PerkType.ShipProjectorHandling, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipProjectorHandlingTrait } },
                new() { Perk = PerkType.ShipTransferEfficiency, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipTransferEfficiencyTrait } },
                new() { Perk = PerkType.ShipSupportRouting, MaxLevel = 1, Prices = new[] { 3 }, GrantedFeats = new[] { FeatType.ShipSupportRouting1 } },
                new() { Perk = PerkType.ShipFleetStabilization, MaxLevel = 1, Prices = new[] { 7 }, GrantedFeats = new[] { FeatType.ShipFleetStabilization1 } },
                new() { Perk = PerkType.ShipDepositAnalysis, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipDepositAnalysis1, FeatType.ShipDepositAnalysis2, FeatType.ShipDepositAnalysis3 } },
                new() { Perk = PerkType.ShipAnomalyScan, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipAnomalyScan1, FeatType.ShipAnomalyScan2, FeatType.ShipAnomalyScan3 } },
                new() { Perk = PerkType.ShipRouteSurvey, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipRouteSurvey1, FeatType.ShipRouteSurvey2, FeatType.ShipRouteSurvey3 } },
                new() { Perk = PerkType.ShipSurveyResolution, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipSurveyResolutionTrait } },
                new() { Perk = PerkType.ShipScanEconomy, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipScanEconomyTrait } },
                new() { Perk = PerkType.ShipDetailedSurvey, MaxLevel = 1, Prices = new[] { 3 }, GrantedFeats = new[] { FeatType.ShipDetailedSurvey1 } },
                new() { Perk = PerkType.ShipDeepSurvey, MaxLevel = 1, Prices = new[] { 7 }, GrantedFeats = new[] { FeatType.ShipDeepSurvey1 } },
                new() { Perk = PerkType.ShipTargetAnalysis, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipTargetAnalysis1, FeatType.ShipTargetAnalysis2, FeatType.ShipTargetAnalysis3 } },
                new() { Perk = PerkType.ShipSensorDisruption, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipSensorDisruption1, FeatType.ShipSensorDisruption2, FeatType.ShipSensorDisruption3 } },
                new() { Perk = PerkType.ShipCountermeasureTiming, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipCountermeasureTiming1, FeatType.ShipCountermeasureTiming2, FeatType.ShipCountermeasureTiming3 } },
                new() { Perk = PerkType.ShipSensorHandling, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipSensorHandlingTrait } },
                new() { Perk = PerkType.ShipInterferenceEfficiency, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipInterferenceEfficiencyTrait } },
                new() { Perk = PerkType.ShipInterference, MaxLevel = 1, Prices = new[] { 3 }, GrantedFeats = new[] { FeatType.ShipInterference1 } },
                new() { Perk = PerkType.ShipSignalBreak, MaxLevel = 1, Prices = new[] { 7 }, GrantedFeats = new[] { FeatType.ShipSignalBreak1 } },
                new() { Perk = PerkType.ShipPrecisionExtraction, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipPrecisionExtraction1, FeatType.ShipPrecisionExtraction2, FeatType.ShipPrecisionExtraction3 } },
                new() { Perk = PerkType.ShipExtractionSurge, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipExtractionSurge1, FeatType.ShipExtractionSurge2, FeatType.ShipExtractionSurge3 } },
                new() { Perk = PerkType.ShipSelectiveRecovery, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipSelectiveRecovery1, FeatType.ShipSelectiveRecovery2, FeatType.ShipSelectiveRecovery3 } },
                new() { Perk = PerkType.ShipBeamHandling, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipBeamHandlingTrait } },
                new() { Perk = PerkType.ShipIndustrialEfficiency, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipIndustrialEfficiencyTrait } },
                new() { Perk = PerkType.ShipCarefulExtraction, MaxLevel = 1, Prices = new[] { 3 }, GrantedFeats = new[] { FeatType.ShipCarefulExtraction1 } },
                new() { Perk = PerkType.ShipDeepCoreExtraction, MaxLevel = 1, Prices = new[] { 7 }, GrantedFeats = new[] { FeatType.ShipDeepCoreExtraction1 } },
                new() { Perk = PerkType.ShipCarefulDismantling, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipCarefulDismantling1, FeatType.ShipCarefulDismantling2, FeatType.ShipCarefulDismantling3 } },
                new() { Perk = PerkType.ShipRecoverySweep, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipRecoverySweep1, FeatType.ShipRecoverySweep2, FeatType.ShipRecoverySweep3 } },
                new() { Perk = PerkType.ShipCargoHandling, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipCargoHandling1, FeatType.ShipCargoHandling2, FeatType.ShipCargoHandling3 } },
                new() { Perk = PerkType.ShipComponentRecovery, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipComponentRecoveryTrait } },
                new() { Perk = PerkType.ShipFreightEfficiency, MaxLevel = 3, Prices = new[] { 1, 2, 3 }, GrantedFeats = new[] { FeatType.ShipFreightEfficiencyTrait } },
                new() { Perk = PerkType.ShipRecoveryOperations, MaxLevel = 1, Prices = new[] { 3 }, GrantedFeats = new[] { FeatType.ShipRecoveryOperations1 } },
                new() { Perk = PerkType.ShipSpecialistRecovery, MaxLevel = 1, Prices = new[] { 7 }, GrantedFeats = new[] { FeatType.ShipSpecialistRecovery1 } },
                new() { Perk = PerkType.ShipManufacturing, MaxLevel = 5, Prices = new[] { 1, 2, 3, 4, 5 }, GrantedFeats = new[] { FeatType.ShipManufacturingTrait } },
        };
    }
}
