namespace SWLOR.Game.Server.Core.NWScript.Enum
{
    public enum EffectTypeScript
    {
        Invalideffect = 0,
        DamageResistance = 1,

        //      AbilityBonus                = 2,
        Regenerate = 3,

        //      SavingThrowBonus            = 4,
        //      ModifyAc                    = 5,
        //      AttackBonus                 = 6,
        DamageReduction = 7,

        //      DamageBonus                 = 8,
        TemporaryHitpoints = 9,

        //      DamageImmunity              = 10,
        Entangle = 11,
        Invulnerable = 12,
        Deaf = 13,
        Resurrection = 14,
        Immunity = 15,

        //      Blind                       = 16,
        EnemyAttackBonus = 17,
        ArcaneSpellFailure = 18,

        //      MovementSpeed               = 19,
        AreaOfEffect = 20,
        Beam = 21,

        //      SpellResistance             = 22,
        Charmed = 23,
        Confused = 24,
        Frightened = 25,
        Dominated = 26,
        Paralyze = 27,
        Dazed = 28,
        Stunned = 29,
        Sleep = 30,
        Poison = 31,
        Disease = 32,
        Curse = 33,
        Silence = 34,
        Turned = 35,
        Haste = 36,
        Slow = 37,
        AbilityIncrease = 38,
        AbilityDecrease = 39,
        AttackIncrease = 40,
        AttackDecrease = 41,
        DamageIncrease = 42,
        DamageDecrease = 43,
        DamageImmunityIncrease = 44,
        DamageImmunityDecrease = 45,
        ACIncrease = 46,
        ACDecrease = 47,
        MovementSpeedIncrease = 48,
        MovementSpeedDecrease = 49,
        SavingThrowIncrease = 50,
        SavingThrowDecrease = 51,
        SpellResistanceIncrease = 52,
        SpellResistanceDecrease = 53,
        SkillIncrease = 54,
        SkillDecrease = 55,
        Invisibility = 56,
        ImprovedInvisibility = 57,
        Darkness = 58,
        DispelMagicAll = 59,
        ElementalShield = 60,
        NegativeLevel = 61,
        Polymorph = 62,
        Sanctuary = 63,
        TrueSeeing = 64,
        SeeInvisible = 65,
        Timestop = 66,
        Blindness = 67,
        SpellLevelAbsorption = 68,
        DispelMagicBest = 69,
        Ultravision = 70,
        MissChance = 71,
        Concealment = 72,
        SpellImmunity = 73,
        Visualeffect = 74,
        DisappearAppear = 75,
        Swarm = 76,
        TurnResistanceDecrease = 77,
        TurnResistanceIncrease = 78,
        Petrify = 79,
        CutsceneParalyze = 80,
        Ethereal = 81,
        SpellFailure = 82,
        CutsceneGhost = 83,
        CutsceneImmobilize = 84,
        RunScript = 85,
        Icon = 86,
    }
}