namespace SWLOR.NWN.API.NWScript.Enum
{
    public enum Poison
    {
        // these constants must match those in poison.2da
        Nightshade = 0,
        Small_Centipede_Poison = 1,
        Blade_Bane = 2,
        Greenblood_Oil = 3,
        Bloodroot = 4,
        Purple_Worm_Poison = 5,
        Large_Scorpion_Venom = 6,
        Wyvern_Poison = 7,
        Blue_Whinnis = 8,
        Giant_Wasp_Poison = 9,
        Shadow_Essence = 10,
        Black_Adder_Venom = 11,
        Deathblade = 12,
        Malyss_Root_Paste = 13,
        Nitharit = 14,
        Dragon_Bile = 15,
        Sassone_Leaf_Residue = 16,
        Terinav_Root = 17,
        Carrion_Crawler_Brain_Juice = 18,
        Black_Lotus_Extract = 19,
        Oil_Of_Taggit = 20,
        Id_Moss = 21,
        Striped_Toadstool = 22,
        Arsenic = 23,
        Lich_Dust = 24,
        Dark_Reaver_Powder = 25,
        Ungol_Dust = 26,
        Burnt_Othur_Fumes = 27,
        Chaos_Mist = 28,
        Bebilith_Venom = 29,
        Quasit_Venom = 30,
        Pit_Fiend_Ichor = 31,
        Ettercap_Venom = 32,
        Aranea_Venom = 33,
        Tiny_Spider_Venom = 34,
        Small_Spider_Venom = 35,
        Medium_Spider_Venom = 36,
        Large_Spider_Venom = 37,
        Huge_Spider_Venom = 38,
        Gargantuan_Spider_Venom = 39,
        Colossal_Spider_Venom = 40,
        Phase_Spider_Venom = 41,
        Wraith_Spider_Venom = 42,
        Iron_Golem = 43
    }
}