namespace SWLOR.NWN.API.NWScript.Enum
{
    public enum TrapBaseType
    {
        MinorSpike = 0,
        AverageSpike = 1,
        StrongSpike = 2,
        DeadlySpike = 3,
        MinorHoly = 4,
        AverageHoly = 5,
        StrongHoly = 6,
        DeadlyHoly = 7,
        MinorTangle = 8,
        AverageTangle = 9,
        StrongTangle = 10,
        DeadlyTangle = 11,
        MinorAcid = 12,
        AverageAcid = 13,
        StrongAcid = 14,
        DeadlyAcid = 15,
        MinorFire = 16,
        AverageFire = 17,
        StrongFire = 18,
        DeadlyFire = 19,
        MinorElectrical = 20,
        AverageElectrical = 21,
        StrongElectrical = 22,
        DeadlyElectrical = 23,
        MinorGas = 24,
        AverageGas = 25,
        StrongGas = 26,
        DeadlyGas = 27,
        MinorFrost = 28,
        AverageFrost = 29,
        StrongFrost = 30,
        DeadlyFrost = 31,
        MinorNegative = 32,
        AverageNegative = 33,
        StrongNegative = 34,
        DeadlyNegative = 35,
        MinorSonic = 36,
        AverageSonic = 37,
        StrongSonic = 38,
        DeadlySonic = 39,
        MinorAcidSplash = 40,
        AverageAcidSplash = 41,
        StrongAcidSplash = 42,
        DeadlyAcidSplash = 43,
        EpicElectrical = 44,
        EpicFire = 45,
        EpicFrost = 46,
        EpicSonic = 47
    }
}