namespace SWLOR.Game.Server.Core.NWScript.Enum
{
    public enum VoiceChat
    {
        Attack = 0,
        BadIdea = 47,
        Battlecry1 = 1,
        Battlecry2 = 2,
        Battlecry3 = 3,
        Bored = 39,
        CanDo = 29,
        CantDo = 30,
        Cheer = 44,
        Cuss = 43,
        Death = 18,
        Encumbered = 32,
        Enemies = 6,
        Flee = 7,
        FollowMe = 22,
        GAttack = 11,
        GAttack2 = 12,
        GAttack3 = 13,
        Goodbye = 40,
        GoodIdea = 46,
        Group = 24,
        GuardMe = 9,
        HealMe = 4,
        Hello = 34,
        Help = 5,
        Hide = 28,
        Hold = 10,
        Laugh = 42,
        LookHere = 23,
        MoveOver = 25,
        NearDeath = 17,
        No = 36,
        Pain1 = 14,
        Pain2 = 15,
        Pain3 = 16,
        Picklock = 26,
        Poisoned = 19,
        Rest = 38,
        Search = 27,
        Selected = 33,
        SpellFailed = 20,
        Stop = 37,
        TalkToMe = 45,
        TaskComplete = 31,
        Taunt = 8,
        Thanks = 41,
        Threaten = 48,
        WeaponSucks = 21,
        Yes = 35
    }
}
