// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Lightsaber
{
    public class GuardianMasterAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.GuardianMaster1, PerkType.GuardianMaster)
                    .Name("Guardian Master")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.Capstone, 345.0f),
                SkillType.Lightsaber,
                8,
                45,
                null,
                null,
                15,
                8,
                2.0f,
                false,
                false,
                true,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                8.0f,
                AbilityType.Invalid,
                () => new GeneratedWeaponAbilityProfile
                {
                    FriendlyTargetStatusEffectFactory = () => new WardBondStatusEffect(50, 15, 15, 15, 8.0f),
                    SelfDefensePercent = 15,
                    SelfStatDurationSeconds = 45
                });

            return builder.Build();
        }
    }
}
