// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Lightsaber
{
    public class SaberStormAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.SaberStorm1, PerkType.SaberStorm)
                    .Name("Saber Storm")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.Capstone, 345.0f),
                SkillType.Lightsaber,
                45,
                45,
                null,
                null,
                15,
                8,
                2.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                () => new GeneratedWeaponAbilityProfile
                {
                    ExtraDamageTargetStatusEffect = typeof(SunderStatusEffect),
                    ExtraDamageIfTargetStatusEffect = 30,
                    RequiredTargetStatusEffectForConditionalStatus = typeof(SunderStatusEffect),
                    ConditionalTargetStatusEffect = typeof(SunderStatusEffect),
                    ConditionalTargetStatusDurationSeconds = 45
                });

            return builder.Build();
        }
    }
}
