// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Lightsaber
{
    public class SurgeStrikeAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.SurgeStrike1, PerkType.SurgeStrike)
                    .Name("Surge Strike I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.SurgeStrike, 30.0f),
                SkillType.Lightsaber,
                16,
                30,
                null,
                null,
                6,
                2,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new GeneratedWeaponAbilityProfile
                {
                    ConditionalStatusEffect = typeof(ForceDisruptionStatusEffect),
                    ConditionalStatusDurationSeconds = 30,
                    ConditionalStatusAfterDeflectionWindowSeconds = 30
                });

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.SurgeStrike2, PerkType.SurgeStrike)
                    .Name("Surge Strike II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.SurgeStrike, 30.0f),
                SkillType.Lightsaber,
                30,
                30,
                null,
                null,
                9,
                3,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new GeneratedWeaponAbilityProfile
                {
                    ConditionalStatusEffect = typeof(ForceDisruptionStatusEffect),
                    ConditionalStatusDurationSeconds = 30,
                    ConditionalStatusAfterDeflectionWindowSeconds = 30
                });

            return builder.Build();
        }
    }
}
