// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Lightsaber
{
    public class WardBondAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.WardBond1, PerkType.WardBond)
                    .Name("Ward Bond I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.WardBond, 30.0f),
                SkillType.Lightsaber,
                8,
                45,
                null,
                null,
                3,
                2,
                0.0f,
                false,
                false,
                true,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                8.0f,
                AbilityType.Invalid,
                () => new GeneratedWeaponAbilityProfile
                {
                    FriendlyTargetStatusEffectFactory = () => new WardBondStatusEffect(30, 6, 6, 0, 8.0f),
                    SelfDefensePercent = 6,
                    SelfStatDurationSeconds = 45
                });

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.WardBond2, PerkType.WardBond)
                    .Name("Ward Bond II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.WardBond, 30.0f),
                SkillType.Lightsaber,
                18,
                45,
                null,
                null,
                5,
                3,
                0.0f,
                false,
                false,
                true,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                8.0f,
                AbilityType.Invalid,
                () => new GeneratedWeaponAbilityProfile
                {
                    FriendlyTargetStatusEffectFactory = () => new WardBondStatusEffect(35, 8, 8, 0, 8.0f),
                    SelfDefensePercent = 8,
                    SelfStatDurationSeconds = 45
                });

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.WardBond3, PerkType.WardBond)
                    .Name("Ward Bond III")
                    .Level(3)
                    .HasRecastDelay(RecastGroup.WardBond, 30.0f),
                SkillType.Lightsaber,
                28,
                45,
                null,
                null,
                8,
                4,
                0.0f,
                false,
                false,
                true,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                8.0f,
                AbilityType.Invalid,
                () => new GeneratedWeaponAbilityProfile
                {
                    FriendlyTargetStatusEffectFactory = () => new WardBondStatusEffect(40, 10, 10, 0, 8.0f),
                    SelfDefensePercent = 10,
                    SelfStatDurationSeconds = 45
                });

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.WardBond4, PerkType.WardBond)
                    .Name("Ward Bond IV")
                    .Level(4)
                    .HasRecastDelay(RecastGroup.WardBond, 30.0f),
                SkillType.Lightsaber,
                38,
                45,
                null,
                null,
                12,
                5,
                0.0f,
                false,
                false,
                true,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                8.0f,
                AbilityType.Invalid,
                () => new GeneratedWeaponAbilityProfile
                {
                    FriendlyTargetStatusEffectFactory = () => new WardBondStatusEffect(45, 12, 12, 0, 8.0f),
                    SelfDefensePercent = 12,
                    SelfStatDurationSeconds = 45
                });

            return builder.Build();
        }
    }
}
