namespace SWLOR.Game.Server.Core.NWScript.Enum
{
    public enum Animation
    {
        Invalid = -1,
        // Looping animation constants.
        LoopingPause,
        LoopingPause2,
        LoopingListen,
        LoopingMeditate,
        LoopingWorship,
        LoopingLookFar,
        LoopingSitChair,
        LoopingSitCross,
        LoopingTalkNormal,
        LoopingTalkPleading,
        LoopingTalkForceful,
        LoopingTalkLaughing,
        LoopingGetLow,
        LoopingGetMid,
        LoopingPauseTired,
        LoopingPauseDrunk,
        LoopingDeadFront,
        LoopingDeadBack,
        LoopingConjure1,
        LoopingConjure2,
        LoopingSpasm,
        LoopingCustom1,
        LoopingCustom2,
        LoopingCustom3,
        LoopingCustom4,
        LoopingCustom5,
        LoopingCustom6,
        LoopingCustom7,
        LoopingCustom8,
        LoopingCustom9,
        LoopingCustom10,
        LoopingCustom11,
        LoopingCustom12,
        LoopingCustom13,
        LoopingCustom14,
        LoopingCustom15,
        LoopingCustom16,
        LoopingCustom17,
        LoopingCustom18,
        LoopingCustom19,
        LoopingCustom20,
        Mount1,
        Dismount1,

        // Fire and forget animation constants.
        FireForgetHeadTurnLeft = 100,
        FireForgetHeadTurnRight,
        FireForgetPauseScratchHead,
        FireForgetPauseBored,
        FireForgetSalute,
        FireForgetBow,
        FireForgetSteal,
        FireForgetGreeting,
        FireForgetTaunt,
        FireForgetVictory1,
        FireForgetVictory2,
        FireForgetVictory3,
        FireForgetRead,
        FireForgetDrink,
        FireForgetDodgeSide,
        FireForgetDodgeDuck,
        FireForgetSpasm,

        // Placeable animation constants
        PlaceableActivate = 200,
        PlaceableDeactivate,
        PlaceableOpen,
        PlaceableClose,

        // Door animation constants
        DoorClose,
        DoorOpen1,
        DoorOpen2,
        DoorDestro7
    }
}