namespace SWLOR.Game.Server.Core.NWScript.Enum
{
    public enum ClassType
    {
        Barbarian = 0,
        Bard = 1,
        Cleric = 2,
        Druid = 3,
        Fighter = 4,
        Monk = 5,
        Paladin = 6,
        Ranger = 7,
        Rogue = 8,
        Sorcerer = 9,
        Wizard = 10,
        Aberration = 11,
        Animal = 12,
        Construct = 13,
        Humanoid = 14,
        Monstrous = 15,
        Elemental = 16,
        Fey = 17,
        Dragon = 18,
        Undead = 19,
        Commoner = 20,
        Beast = 21,
        Giant = 22,
        MagicalBeast = 23,
        Outsider = 24,
        Shapechanger = 25,
        Vermin = 26,
        Shadowdancer = 27,
        Harper = 28,
        ArcaneArcher = 29,
        Assassin = 30,
        Blackguard = 31,
        DivineChampion = 32,
        WeaponMaster = 33,
        Palemaster = 34,
        Shifter = 35,
        DwarvenDefender = 36,
        DragonDisciple = 37,
        Ooze = 38,
        EyeOfGruumsh = 39,
        ShouDisciple = 40,
        PDK = 41,

        Standard = 66,
        ForceSensitive = 67,

        Invalid = 255
    }
}