namespace SWLOR.Game.Server.Core.NWScript.Enum
{
    public enum PhenoType
    {
        Normal,
        Large,
        Big,
        Custom1,
        Custom2,
        Custom3,
        Custom4,
        Custom5,
        Custom6,
        Custom7,
        Custom8,
        Custom9,
        Custom10,
        Custom11,
        Custom12,
        Custom13,
        Custom14,
        Custom15,
        Custom16,
        Custom17,
        Custom18,
        Custom19,
        SpeederBike,
        Custom21,
        Custom22,
    }
}