namespace SWLOR.Game.Server.Core.NWScript.Enum
{
    public enum RacialType
    {
        Dwarf = 0,
        Elf = 1,
        Gnome = 2,
        Halfling = 3,
        Halfelf = 4,
        Halforc = 5,
        Human = 6,
        Aberration = 7,
        Animal = 8,
        Beast = 9,
        Construct = 10,
        Dragon = 11,
        HumanoidGoblinoid = 12,
        HumanoidMonstrous = 13,
        HumanoidOrc = 14,
        HumanoidReptilian = 15,
        Elemental = 16,
        Fey = 17,
        Giant = 18,
        MagicalBeast = 19,
        Outsider = 20,
        Shapechanger = 23,
        Undead = 24,
        Vermin = 25,
        All = 28, 
        Invalid = 28, 
        Ooze = 29, 
        Plant = 52,

        Robot = 150,
        Alien = 151,
        Bothan = 152,
        Chiss = 153,
        Zabrak = 154,
        Wookiee = 155,
        Twilek = 156,
        Cyborg = 157,
        Cathar = 158,
        Trandoshan = 159,
        Mirialan = 160,
        Echani = 161,
        MonCalamari = 162,
        Ugnaught = 163,
        Togruta = 164,
        Rodian = 165,
        KelDor = 166,
        Droid = 167,
        Nautolan = 168

    }
}
