// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.Game.Server.Service.StatService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.StatusEffectDefinition
{
    public sealed class DebilitatingStanceStatusEffect : StatusEffectBase
    {
        public override string Name => "Debilitating Stance";
        public override EffectIconType Icon => EffectIconType.DebilitatingStanceStatusEffect;
        public override StatusEffectSourceType SourceType => StatusEffectSourceType.Stance;

        public DebilitatingStanceStatusEffect()
        {
            StatGroup.Stats[StatType.DamageDealtHamstringSkillType] = (int)SkillType.Vibroknife;
            StatGroup.Stats[StatType.DamageDealtHamstringChance] = 100;
            StatGroup.Stats[StatType.DamageDealtHamstringDurationSeconds] = 30;
            StatGroup.Stats[StatType.AttackPercentAdjustment] = -10;
        }
    }
}
