// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.Game.Server.Service.StatService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.StatusEffectDefinition
{
    public sealed class IronWallStanceStatusEffect : StatusEffectBase
    {
        public override string Name => "Iron Wall Stance";
        public override EffectIconType Icon => EffectIconType.IronWallStanceStatusEffect;
        public override StatusEffectSourceType SourceType => StatusEffectSourceType.Stance;

        public IronWallStanceStatusEffect()
        {
            StatGroup.Stats[StatType.DefensePercentAdjustment] = 25;
            StatGroup.Stats[StatType.ForceDefensePercentAdjustment] = 20;
            StatGroup.Stats[StatType.EnmityPercentAdjustment] = 30;
            StatGroup.Stats[StatType.AttackPercentAdjustment] = -25;
        }
    }
}
