// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.Game.Server.Service.StatService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.StatusEffectDefinition
{
    public sealed class LaceratorStanceStatusEffect : StatusEffectBase
    {
        public override string Name => "Lacerator Stance";
        public override EffectIconType Icon => EffectIconType.LaceratorStanceStatusEffect;
        public override StatusEffectSourceType SourceType => StatusEffectSourceType.Stance;

        public LaceratorStanceStatusEffect()
        {
            StatGroup.Stats[StatType.DamageToBleedingTargetPercentAdjustment] = 10;
            StatGroup.Stats[StatType.EvasionPercentAdjustment] = -10;
        }
    }
}
