// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.Game.Server.Service.StatService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.StatusEffectDefinition
{
    public sealed class OpportunistStanceStatusEffect : StatusEffectBase
    {
        public override string Name => "Opportunist Stance";
        public override EffectIconType Icon => EffectIconType.OpportunistStanceStatusEffect;
        public override StatusEffectSourceType SourceType => StatusEffectSourceType.Stance;

        public OpportunistStanceStatusEffect()
        {
            StatGroup.Stats[StatType.CriticalRatePercentAdjustment] = 12;
            StatGroup.Stats[StatType.DefensePercentAdjustment] = -10;
        }
    }
}
