// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.Game.Server.Service.StatService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.StatusEffectDefinition
{
    public sealed class OrdnanceStanceStatusEffect : StatusEffectBase
    {
        public override string Name => "Ordnance Stance";
        public override EffectIconType Icon => EffectIconType.OrdnanceStanceStatusEffect;
        public override StatusEffectSourceType SourceType => StatusEffectSourceType.Stance;

        public OrdnanceStanceStatusEffect()
        {
            StatGroup.Stats[StatType.ThrowingAreaAbilityDamagePercentAdjustment] = 10;
        }
    }
}
