// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.Game.Server.Service.StatService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.StatusEffectDefinition
{
    public sealed class PerceptiveStanceStatusEffect : StatusEffectBase
    {
        public override string Name => "Perceptive Stance";
        public override EffectIconType Icon => EffectIconType.PerceptiveStanceStatusEffect;
        public override StatusEffectSourceType SourceType => StatusEffectSourceType.Stance;

        public PerceptiveStanceStatusEffect()
        {
            StatGroup.Stats[StatType.DefensePercentAdjustment] = -10;
        }
    }
}
