// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.Game.Server.Service.StatService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.StatusEffectDefinition
{
    public sealed class ScrapperStanceStatusEffect : StatusEffectBase
    {
        public override string Name => "Scrapper Stance";
        public override EffectIconType Icon => EffectIconType.ScrapperStanceStatusEffect;
        public override StatusEffectSourceType SourceType => StatusEffectSourceType.Stance;

        public ScrapperStanceStatusEffect()
        {
        }
    }
}
