// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.Game.Server.Service.StatService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.StatusEffectDefinition
{
    public sealed class SniperStanceStatusEffect : StatusEffectBase
    {
        public override string Name => "Sniper Stance";
        public override EffectIconType Icon => EffectIconType.SniperStanceStatusEffect;
        public override StatusEffectSourceType SourceType => StatusEffectSourceType.Stance;

        public SniperStanceStatusEffect()
        {
            StatGroup.Stats[StatType.AttackDelayReductionPercent] = -15;
        }
    }
}
