// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.Game.Server.Service.StatService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.StatusEffectDefinition
{
    public sealed class SuppressionStanceStatusEffect : StatusEffectBase
    {
        public override string Name => "Suppression Stance";
        public override EffectIconType Icon => EffectIconType.SuppressionStanceStatusEffect;
        public override StatusEffectSourceType SourceType => StatusEffectSourceType.Stance;

        public SuppressionStanceStatusEffect()
        {
            StatGroup.Stats[StatType.AttackDelayReductionPercent] = 10;
            StatGroup.Stats[StatType.RangedHitSuppressionStackDurationSeconds] = 30;
            StatGroup.Stats[StatType.RangedCriticalDamagePercentAdjustment] = -10;
        }
    }
}
