// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.Game.Server.Service.StatService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.StatusEffectDefinition
{
    public sealed class TwinGuardStanceStatusEffect : StatusEffectBase
    {
        public override string Name => "Twin Guard Stance";
        public override EffectIconType Icon => EffectIconType.TwinGuardStanceStatusEffect;
        public override StatusEffectSourceType SourceType => StatusEffectSourceType.Stance;

        public TwinGuardStanceStatusEffect()
        {
            StatGroup.Stats[StatType.DefensePercentAdjustment] = 15;
            StatGroup.Stats[StatType.EnmityPercentAdjustment] = 20;
            StatGroup.Stats[StatType.AttackPercentAdjustment] = -15;
        }
    }
}
