// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.Game.Server.Service.StatService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.StatusEffectDefinition
{
    public sealed class VigorStanceStatusEffect : StatusEffectBase
    {
        public override string Name => "Vigor Stance";
        public override EffectIconType Icon => EffectIconType.VigorStanceStatusEffect;
        public override StatusEffectSourceType SourceType => StatusEffectSourceType.Stance;

        public VigorStanceStatusEffect()
        {
            StatGroup.Stats[StatType.HostileAbilityStaminaCostFlatAdjustment] = 2;
            StatGroup.Stats[StatType.DamageDealtPercentAdjustment] = 10;
            StatGroup.Stats[StatType.HostileAbilityUsedEvasionPercentAdjustment] = 8;
            StatGroup.Stats[StatType.HostileAbilityUsedEvasionDurationSeconds] = 30;
        }
    }
}
