// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Staff
{
    public class LineBreakerAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.LineBreaker1, PerkType.LineBreaker)
                    .Name("Line Breaker I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.LineBreaker, 18.0f),
                SkillType.Staff,
                8,
                30,
                typeof(DisorientedStatusEffect),
                null,
                3,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.LineBreaker1,
                AbilityTargetingShapeType.Rect,
                8.0f,
                2.5f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                null);

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.LineBreaker2, PerkType.LineBreaker)
                    .Name("Line Breaker II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.LineBreaker, 18.0f),
                SkillType.Staff,
                18,
                30,
                typeof(DisorientedStatusEffect),
                null,
                5,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.LineBreaker2,
                AbilityTargetingShapeType.Rect,
                8.0f,
                3.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                null);

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.LineBreaker3, PerkType.LineBreaker)
                    .Name("Line Breaker III")
                    .Level(3)
                    .HasRecastDelay(RecastGroup.LineBreaker, 18.0f),
                SkillType.Staff,
                28,
                30,
                typeof(DisorientedStatusEffect),
                null,
                8,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.LineBreaker3,
                AbilityTargetingShapeType.Rect,
                8.0f,
                3.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                null);

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.LineBreaker4, PerkType.LineBreaker)
                    .Name("Line Breaker IV")
                    .Level(4)
                    .HasRecastDelay(RecastGroup.LineBreaker, 18.0f),
                SkillType.Staff,
                38,
                30,
                typeof(DisorientedStatusEffect),
                null,
                12,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.LineBreaker4,
                AbilityTargetingShapeType.Rect,
                8.0f,
                3.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                null);

            return builder.Build();
        }
    }
}
