// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Staff
{
    public class RibBreakerAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.RibBreaker1, PerkType.RibBreaker)
                    .Name("Rib Breaker I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.RibBreaker, 24.0f),
                SkillType.Staff,
                12,
                15,
                typeof(DazedStatusEffect),
                null,
                4,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                null);

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.RibBreaker2, PerkType.RibBreaker)
                    .Name("Rib Breaker II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.RibBreaker, 24.0f),
                SkillType.Staff,
                24,
                15,
                typeof(DazedStatusEffect),
                null,
                8,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                null);

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.RibBreaker3, PerkType.RibBreaker)
                    .Name("Rib Breaker III")
                    .Level(3)
                    .HasRecastDelay(RecastGroup.RibBreaker, 24.0f),
                SkillType.Staff,
                36,
                15,
                typeof(DazedStatusEffect),
                null,
                10,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                null);

            return builder.Build();
        }
    }
}
