// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Staff
{
    public class ShelterCircleAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.ShelterCircle1, PerkType.ShelterCircle)
                    .Name("Shelter Circle")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.ShelterCircle, 60.0f),
                SkillType.Staff,
                8,
                30,
                null,
                null,
                12,
                0,
                0.0f,
                false,
                false,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    NearbyPartyStatusEffect = typeof(ShelterCircleStatusEffect),
                    NearbyPartyStatusDurationSeconds = 30,
                    NearbyPartyStatusIncludesSelf = true
                });

            return builder.Build();
        }
    }
}
