// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Staff
{
    public class SlamAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.Slam1, PerkType.Slam)
                    .Name("Slam I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.Slam, 18.0f),
                SkillType.Staff,
                8,
                0,
                null,
                null,
                3,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    ExtraDamageIfTargetControlled = 8
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.Slam2, PerkType.Slam)
                    .Name("Slam II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.Slam, 18.0f),
                SkillType.Staff,
                18,
                0,
                null,
                null,
                5,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    ExtraDamageIfTargetControlled = 14
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.Slam3, PerkType.Slam)
                    .Name("Slam III")
                    .Level(3)
                    .HasRecastDelay(RecastGroup.Slam, 18.0f),
                SkillType.Staff,
                28,
                0,
                null,
                null,
                8,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    ExtraDamageIfTargetControlled = 20
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.Slam4, PerkType.Slam)
                    .Name("Slam IV")
                    .Level(4)
                    .HasRecastDelay(RecastGroup.Slam, 18.0f),
                SkillType.Staff,
                38,
                0,
                null,
                null,
                12,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    ExtraDamageIfTargetControlled = 26
                });

            return builder.Build();
        }
    }
}
