// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Staff
{
    public class SweepingGuardAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.SweepingGuard1, PerkType.SweepingGuard)
                    .Name("Sweeping Guard")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.SweepingGuard, 30.0f),
                SkillType.Staff,
                16,
                30,
                null,
                null,
                6,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.SweepingGuard1,
                AbilityTargetingShapeType.Sphere,
                5.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    SelfDefensePercent = 20,
                    SelfStatDurationSeconds = 30
                });

            return builder.Build();
        }
    }
}
