// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Staff
{
    public class WorldbreakerAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.Worldbreaker1, PerkType.Worldbreaker)
                    .Name("Worldbreaker")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.Capstone, 90.0f),
                SkillType.Staff,
                35,
                30,
                null,
                null,
                15,
                0,
                2.0f,
                true,
                true,
                false,
                Spell.Worldbreaker1,
                AbilityTargetingShapeType.Sphere,
                5.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new GeneratedWeaponAbilityProfile
                {
                    ExtraDamageIfTargetControlled = 40,
                    RequiredTargetStatusCategoryForConditionalStatus = StatusEffectCategory.Control,
                    ConditionalTargetStatusEffect = typeof(DazedStatusEffect),
                    ConditionalTargetStatusDurationSeconds = 30
                });

            return builder.Build();
        }
    }
}
