// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Throwing
{
    public class ConcussiveTossAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.ConcussiveToss1, PerkType.ConcussiveToss)
                    .Name("Concussive Toss I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.ConcussiveToss, 30.0f),
                SkillType.Throwing,
                16,
                15,
                typeof(DazedStatusEffect),
                null,
                6,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.ConcussiveToss1,
                AbilityTargetingShapeType.Sphere,
                5.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.ThrowGrenade,
                20.0f,
                AbilityType.Perception,
                null);

            ConfigureWeaponAbility(
                builder.Create(FeatType.ConcussiveToss2, PerkType.ConcussiveToss)
                    .Name("Concussive Toss II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.ConcussiveToss, 30.0f),
                SkillType.Throwing,
                30,
                15,
                typeof(DazedStatusEffect),
                null,
                9,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.ConcussiveToss2,
                AbilityTargetingShapeType.Sphere,
                5.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.ThrowGrenade,
                20.0f,
                AbilityType.Perception,
                null);

            return builder.Build();
        }
    }
}
