// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Throwing
{
    public class ExplosiveTossAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.ExplosiveToss1, PerkType.ExplosiveToss)
                    .Name("Explosive Toss I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.ExplosiveToss, 18.0f),
                SkillType.Throwing,
                7,
                30,
                typeof(BurnStatusEffect),
                null,
                3,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.ExplosiveToss1,
                AbilityTargetingShapeType.Sphere,
                5.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.ThrowGrenade,
                20.0f,
                AbilityType.Perception,
                null);

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.ExplosiveToss2, PerkType.ExplosiveToss)
                    .Name("Explosive Toss II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.ExplosiveToss, 18.0f),
                SkillType.Throwing,
                15,
                30,
                typeof(BurnStatusEffect),
                null,
                5,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.ExplosiveToss2,
                AbilityTargetingShapeType.Sphere,
                5.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.ThrowGrenade,
                20.0f,
                AbilityType.Perception,
                null);

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.ExplosiveToss3, PerkType.ExplosiveToss)
                    .Name("Explosive Toss III")
                    .Level(3)
                    .HasRecastDelay(RecastGroup.ExplosiveToss, 18.0f),
                SkillType.Throwing,
                24,
                30,
                typeof(BurnStatusEffect),
                null,
                8,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.ExplosiveToss3,
                AbilityTargetingShapeType.Sphere,
                5.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.ThrowGrenade,
                20.0f,
                AbilityType.Perception,
                null);

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.ExplosiveToss4, PerkType.ExplosiveToss)
                    .Name("Explosive Toss IV")
                    .Level(4)
                    .HasRecastDelay(RecastGroup.ExplosiveToss, 18.0f),
                SkillType.Throwing,
                32,
                30,
                typeof(BurnStatusEffect),
                null,
                12,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.ExplosiveToss4,
                AbilityTargetingShapeType.Sphere,
                5.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.ThrowGrenade,
                20.0f,
                AbilityType.Perception,
                null);

            return builder.Build();
        }
    }
}
