// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Throwing
{
    public class OrdnanceStanceAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.OrdnanceStance1, PerkType.OrdnanceStance)
                    .Name("Ordnance Stance")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.OrdnanceStance, 30.0f),
                SkillType.Throwing,
                8,
                0,
                typeof(OrdnanceStanceStatusEffect),
                null,
                0,
                0,
                2.0f,
                true,
                false,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.ThrowGrenade,
                20.0f,
                AbilityType.Perception,
                null);

            return builder.Build();
        }
    }
}
