// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Throwing
{
    public class PerfectFlurryAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.PerfectFlurry1, PerkType.PerfectFlurry)
                    .Name("Perfect Flurry")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.Capstone, 90.0f),
                SkillType.Throwing,
                30,
                45,
                null,
                null,
                15,
                0,
                2.0f,
                true,
                true,
                false,
                Spell.PerfectFlurry1,
                AbilityTargetingShapeType.Sphere,
                5.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.ThrowGrenade,
                20.0f,
                AbilityType.Perception,
                new WeaponAbilityProfile
                {
                    ExtraDamageIfTargetBleeding = 45,
                    SpreadBleedFromTarget = true,
                    SpreadBleedDurationSeconds = 45
                });

            return builder.Build();
        }
    }
}
