// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Throwing
{
    public class PiercingTossAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.PiercingToss1, PerkType.PiercingToss)
                    .Name("Piercing Toss I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.PiercingToss, 18.0f),
                SkillType.Throwing,
                8,
                30,
                typeof(BleedStatusEffect),
                null,
                3,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.ThrowGrenade,
                20.0f,
                AbilityType.Perception,
                null);

            ConfigureWeaponAbility(
                builder.Create(FeatType.PiercingToss2, PerkType.PiercingToss)
                    .Name("Piercing Toss II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.PiercingToss, 18.0f),
                SkillType.Throwing,
                18,
                36,
                typeof(BleedStatusEffect),
                null,
                5,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.ThrowGrenade,
                20.0f,
                AbilityType.Perception,
                null);

            ConfigureWeaponAbility(
                builder.Create(FeatType.PiercingToss3, PerkType.PiercingToss)
                    .Name("Piercing Toss III")
                    .Level(3)
                    .HasRecastDelay(RecastGroup.PiercingToss, 18.0f),
                SkillType.Throwing,
                28,
                45,
                typeof(BleedStatusEffect),
                null,
                8,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.ThrowGrenade,
                20.0f,
                AbilityType.Perception,
                null);

            ConfigureWeaponAbility(
                builder.Create(FeatType.PiercingToss4, PerkType.PiercingToss)
                    .Name("Piercing Toss IV")
                    .Level(4)
                    .HasRecastDelay(RecastGroup.PiercingToss, 18.0f),
                SkillType.Throwing,
                38,
                60,
                typeof(BleedStatusEffect),
                null,
                12,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.ThrowGrenade,
                20.0f,
                AbilityType.Perception,
                null);

            return builder.Build();
        }
    }
}
