// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Throwing
{
    public class PinningTossAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.PinningToss1, PerkType.PinningToss)
                    .Name("Pinning Toss I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.PinningToss, 24.0f),
                SkillType.Throwing,
                12,
                30,
                typeof(HamstringStatusEffect),
                null,
                4,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.ThrowGrenade,
                20.0f,
                AbilityType.Perception,
                new WeaponAbilityProfile
                {
                    RequiredTargetStatusCategoryForConditionalStatus = StatusEffectCategory.Bleeding,
                    ConditionalTargetStatusEffect = typeof(DisorientedStatusEffect),
                    ConditionalTargetStatusDurationSeconds = 30
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.PinningToss2, PerkType.PinningToss)
                    .Name("Pinning Toss II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.PinningToss, 24.0f),
                SkillType.Throwing,
                24,
                30,
                typeof(HamstringStatusEffect),
                null,
                8,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.ThrowGrenade,
                20.0f,
                AbilityType.Perception,
                new WeaponAbilityProfile
                {
                    RequiredTargetStatusCategoryForConditionalStatus = StatusEffectCategory.Bleeding,
                    ConditionalTargetStatusEffect = typeof(DisorientedStatusEffect),
                    ConditionalTargetStatusDurationSeconds = 30
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.PinningToss3, PerkType.PinningToss)
                    .Name("Pinning Toss III")
                    .Level(3)
                    .HasRecastDelay(RecastGroup.PinningToss, 24.0f),
                SkillType.Throwing,
                36,
                30,
                typeof(HamstringStatusEffect),
                null,
                10,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.ThrowGrenade,
                20.0f,
                AbilityType.Perception,
                new WeaponAbilityProfile
                {
                    RequiredTargetStatusCategoryForConditionalStatus = StatusEffectCategory.Bleeding,
                    ConditionalTargetStatusEffect = typeof(DisorientedStatusEffect),
                    ConditionalTargetStatusDurationSeconds = 30
                });

            return builder.Build();
        }
    }
}
