// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Throwing
{
    public class SeveringTossAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.SeveringToss1, PerkType.SeveringToss)
                    .Name("Severing Toss I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.SeveringToss, 30.0f),
                SkillType.Throwing,
                16,
                30,
                null,
                null,
                6,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.ThrowGrenade,
                20.0f,
                AbilityType.Perception,
                new WeaponAbilityProfile
                {
                    RequiredTargetStatusCategoryForConditionalStatus = StatusEffectCategory.Bleeding,
                    ConditionalTargetStatusEffect = typeof(HemorrhageStatusEffect),
                    ConditionalTargetStatusDurationSeconds = 30
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.SeveringToss2, PerkType.SeveringToss)
                    .Name("Severing Toss II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.SeveringToss, 30.0f),
                SkillType.Throwing,
                30,
                30,
                null,
                null,
                9,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.ThrowGrenade,
                20.0f,
                AbilityType.Perception,
                new WeaponAbilityProfile
                {
                    RequiredTargetStatusCategoryForConditionalStatus = StatusEffectCategory.Bleeding,
                    ConditionalTargetStatusEffect = typeof(HemorrhageStatusEffect),
                    ConditionalTargetStatusDurationSeconds = 30
                });

            return builder.Build();
        }
    }
}
