// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Saberstaff
{
    public class DoubleStrikeAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.DoubleStrike1, PerkType.DoubleStrike)
                    .Name("Double Strike I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.DoubleStrike, 18.0f),
                SkillType.Saberstaff,
                5,
                0,
                null,
                null,
                3,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    HitCount = 2,
                    RestoreFPIfAllHitsLand = 2
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.DoubleStrike2, PerkType.DoubleStrike)
                    .Name("Double Strike II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.DoubleStrike, 18.0f),
                SkillType.Saberstaff,
                11,
                0,
                null,
                null,
                5,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    HitCount = 2,
                    RestoreFPIfAllHitsLand = 3
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.DoubleStrike3, PerkType.DoubleStrike)
                    .Name("Double Strike III")
                    .Level(3)
                    .HasRecastDelay(RecastGroup.DoubleStrike, 18.0f),
                SkillType.Saberstaff,
                17,
                0,
                null,
                null,
                8,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    HitCount = 2,
                    RestoreFPIfAllHitsLand = 4
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.DoubleStrike4, PerkType.DoubleStrike)
                    .Name("Double Strike IV")
                    .Level(4)
                    .HasRecastDelay(RecastGroup.DoubleStrike, 18.0f),
                SkillType.Saberstaff,
                23,
                0,
                null,
                null,
                12,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    HitCount = 2,
                    RestoreFPIfAllHitsLand = 5
                });

            return builder.Build();
        }
    }
}
