// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Saberstaff
{
    public class MaelstromArcAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.MaelstromArc1, PerkType.MaelstromArc)
                    .Name("Maelstrom Arc I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.MaelstromArc, 30.0f),
                SkillType.Saberstaff,
                16,
                0,
                null,
                null,
                6,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.MaelstromArc1,
                AbilityTargetingShapeType.Cone,
                5.0f,
                5.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    RestoreFPOnHit = 4
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.MaelstromArc2, PerkType.MaelstromArc)
                    .Name("Maelstrom Arc II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.MaelstromArc, 30.0f),
                SkillType.Saberstaff,
                30,
                0,
                null,
                null,
                9,
                0,
                0.0f,
                true,
                true,
                false,
                Spell.MaelstromArc2,
                AbilityTargetingShapeType.Cone,
                5.0f,
                5.0f,
                AbilityTargetingFlags.HarmsEnemies | AbilityTargetingFlags.OriginOnSelf,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    RestoreFPOnHit = 8
                });

            return builder.Build();
        }
    }
}
