// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Saberstaff
{
    public class SaberCycloneAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.SaberCyclone1, PerkType.SaberCyclone)
                    .Name("Saber Cyclone")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.Capstone, 90.0f),
                SkillType.Saberstaff,
                0,
                45,
                null,
                null,
                15,
                0,
                2.0f,
                false,
                false,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    TemporaryAreaAbilityMinTargetsResourceRestoreThreshold = 1,
                    TemporaryAreaAbilityFPRestore = 4,
                    TemporaryAreaAbilityMinTargetsBuffThreshold = 1,
                    TemporaryAreaAbilityAttackDeflection = 8,
                    TemporaryAreaAbilityBuffDurationSeconds = 30,
                    TemporaryDefeatedEnemyEffectDurationSeconds = 45
                });

            return builder.Build();
        }
    }
}
