//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Dapper.Contrib.Extensions;

namespace SWLOR.Game.Server.Data
{
    using System;
    using System.Collections.Generic;
    
    using SWLOR.Game.Server.Data.Contracts;
    
    public partial class DataPackage: IEntity
    {
        [Key]
        public int DataPackageID { get; set; }
        public System.DateTime DateFound { get; set; }
        public System.DateTime DateExported { get; set; }
        public string FileName { get; set; }
        public string PackageName { get; set; }
        public string Checksum { get; set; }
        public string Content { get; set; }
        public bool ImportedSuccessfully { get; set; }
        public string ErrorMessage { get; set; }
    }
}
