//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Dapper.Contrib.Extensions;

namespace SWLOR.Game.Server.Data
{
    using System;
    using System.Collections.Generic;
    
    using SWLOR.Game.Server.Data.Contracts;
    
    public partial class QuestPrerequisite: IEntity
    {
        [Key]
        public int QuestPrerequisiteID { get; set; }
        public int QuestID { get; set; }
        public int RequiredQuestID { get; set; }
    
        public virtual Quest Quest { get; set; }
        public virtual Quest RequiredQuest { get; set; }
    }
}
