namespace SWLOR.Game.Server.Service.GuiService
{
    public enum GuiWindowType
    {
        Invalid = 0,
        CharacterSheet = 1,
        ChangePortrait = 2,
        Quests = 3,
        Recipes = 4,
        KeyItems = 5,
        Achievements = 6,
        Skills = 7,
        Perks = 8,
        Settings = 9,
        AppearanceEditor = 10,
        Bank = 11,
        CharacterMigration = 12,
        Outfits = 13,
        MarketListing = 14,
        MarketBuying = 15,
        PriceSelection = 16,
        ExamineItem = 17,
        Notes = 18,
        DistributeRPXP = 19,
        ShipManagement = 20,
        ChangeDescription = 21,
        Craft = 22,
        ManageStaff = 23,
        ManageCitizenship = 24,
        ManageCity = 25,
        Election = 26,
        RentApartment = 27,
        ManageApartment = 28,
        RenameItem = 29,
        PermissionManagement = 30,
        ManageStructures = 31,
        PropertyItemStorage = 32,
        BugReport = 33,
        DMTools = 34,
        PlayerStatus = 35,
        TargetStatus = 36,
        ManageBans = 37,
        Refinery = 38,
        DMPlayerExamine = 39,
        AreaNotes = 40,
        CreatureManager = 41,
        AreaManager = 42,
        Emotes = 43,
        DroidAssembly = 44,
        DroidAI = 45,
        Currencies = 46,
        StatRebuild = 47,


        DebugEnmity = 900,
    }
}
