namespace SWLOR.Game.Server.Perk
{
    public enum PerkCooldownGroup
    {
        None = 0,
        Evasiveness = 1,
        ForceSpeed = 2,
        Knockdown = 3,
        AbsorbEnergy = 4,
        ForceBody = 5,
        MindShield = 6,
        Rage = 7,
        ForcePersuade = 8,
        Confusion = 9,
        ForceStun = 10,
        SithAlchemy = 11,
        ThrowSaber = 12,
        RestAndMeditate = 13,
        Provoke = 14,
        SneakAttack = 15,
        Premonition = 16,
        ComprehendSpeech = 17,
        CrossCut = 18,
        Hide = 19,
        ForceDetection = 20,
        Farseeing = 21,
        ShieldBoost = 22,
        RecoveryBlast = 23,
        LegShot = 24,
        Tranquilizer = 25,
        MassTranquilizer = 26,
        PreciseToss = 27,
        BattleAndForceInsight = 28,
        Dash = 29,
        ElectricFist = 30,
        PlasmaCell = 31,
        Chi = 32,
        Stance = 33,
        AnimalBond = 34,
        DrainLife = 35,
        ForceLightning = 36,
        ForcePush = 37,
        ForceBreach = 38,
        Skewer = 40,

    }
}
