// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Vibroknife
{
    public class BackstabAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.Backstab1, PerkType.Backstab)
                    .Name("Backstab I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.Backstab, 45.0f),
                SkillType.Vibroknife,
                20,
                6,
                null,
                null,
                8,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new GeneratedWeaponAbilityProfile
                {
                    ExtraDamageIfBehind = 10,
                    ExtraDamageIfBehindFeedbackLabel = "Backstab",
                    ConditionalTargetStatusEffect = typeof(KnockdownStatusEffect),
                    ConditionalTargetStatusDurationSeconds = 6,
                    RequireBehindForConditionalStatus = true
                });

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.Backstab2, PerkType.Backstab)
                    .Name("Backstab II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.Backstab, 45.0f),
                SkillType.Vibroknife,
                25,
                6,
                null,
                null,
                10,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new GeneratedWeaponAbilityProfile
                {
                    ExtraDamageIfBehind = 20,
                    ExtraDamageIfBehindFeedbackLabel = "Backstab",
                    ConditionalTargetStatusEffect = typeof(KnockdownStatusEffect),
                    ConditionalTargetStatusDurationSeconds = 6,
                    RequireBehindForConditionalStatus = true
                });

            return builder.Build();
        }
    }
}
