// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Vibroknife
{
    public class HemorrhageAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.Hemorrhage1, PerkType.Hemorrhage)
                    .Name("Hemorrhage I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.Hemorrhage, 60.0f),
                SkillType.Vibroknife,
                16,
                30,
                typeof(BleedStatusEffect),
                null,
                6,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                null);

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.Hemorrhage2, PerkType.Hemorrhage)
                    .Name("Hemorrhage II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.Hemorrhage, 60.0f),
                SkillType.Vibroknife,
                30,
                30,
                typeof(BleedStatusEffect),
                null,
                9,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                null);

            return builder.Build();
        }
    }
}
