// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Vibroknife
{
    public class NerveStrikeAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.NerveStrike1, PerkType.NerveStrike)
                    .Name("Nerve Strike I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.NerveStrike, 60.0f),
                SkillType.Vibroknife,
                18,
                30,
                typeof(DisorientedStatusEffect),
                null,
                6,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                () => new GeneratedWeaponAbilityProfile
                {
                    StatusEffectFactory = () => new DisorientedStatusEffect(10, 10)
                });

            ConfigureGeneratedWeaponAbility(
                builder.Create(FeatType.NerveStrike2, PerkType.NerveStrike)
                    .Name("Nerve Strike II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.NerveStrike, 60.0f),
                SkillType.Vibroknife,
                30,
                30,
                typeof(DisorientedStatusEffect),
                null,
                9,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                () => new GeneratedWeaponAbilityProfile
                {
                    StatusEffectFactory = () => new DisorientedStatusEffect(15, 15)
                });

            return builder.Build();
        }
    }
}
