// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Vibroknife
{
    public class PathogenStrikeAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.PathogenStrike1, PerkType.PathogenStrike)
                    .Name("Pathogen Strike I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.PathogenStrike, 12.0f),
                SkillType.Vibroknife,
                6,
                0,
                null,
                null,
                3,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    IsQueuedWeaponAbility = true,
                    SourceStatusEffectsToExtend = new[] { typeof(VenomStatusEffect), typeof(InfectionStatusEffect) },
                    SourceStatusExtensionSeconds = 4
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.PathogenStrike2, PerkType.PathogenStrike)
                    .Name("Pathogen Strike II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.PathogenStrike, 12.0f),
                SkillType.Vibroknife,
                12,
                0,
                null,
                null,
                4,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    IsQueuedWeaponAbility = true,
                    SourceStatusEffectsToExtend = new[] { typeof(VenomStatusEffect), typeof(InfectionStatusEffect) },
                    SourceStatusExtensionSeconds = 4
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.PathogenStrike3, PerkType.PathogenStrike)
                    .Name("Pathogen Strike III")
                    .Level(3)
                    .HasRecastDelay(RecastGroup.PathogenStrike, 12.0f),
                SkillType.Vibroknife,
                16,
                0,
                null,
                null,
                5,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    IsQueuedWeaponAbility = true,
                    SourceStatusEffectsToExtend = new[] { typeof(VenomStatusEffect), typeof(InfectionStatusEffect) },
                    SourceStatusExtensionSeconds = 6
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.PathogenStrike4, PerkType.PathogenStrike)
                    .Name("Pathogen Strike IV")
                    .Level(4)
                    .HasRecastDelay(RecastGroup.PathogenStrike, 12.0f),
                SkillType.Vibroknife,
                19,
                0,
                null,
                null,
                6,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    IsQueuedWeaponAbility = true,
                    SourceStatusEffectsToExtend = new[] { typeof(VenomStatusEffect), typeof(InfectionStatusEffect) },
                    SourceStatusExtensionSeconds = 6
                });

            return builder.Build();
        }
    }
}
