// <auto-generated by GenerateWeaponArchetypeImplementation.py>
using System;
using System.Collections.Generic;
using SWLOR.Game.Server.Feature.StatusEffectDefinition;
using SWLOR.Game.Server.Service;
using SWLOR.Game.Server.Service.AbilityService;
using SWLOR.Game.Server.Service.PerkService;
using SWLOR.Game.Server.Service.SkillService;
using SWLOR.Game.Server.Service.StatusEffectService;
using SWLOR.NWN.API.NWScript.Enum;

namespace SWLOR.Game.Server.Feature.AbilityDefinition.Vibroknife
{
    public class VirulentBladeAbilityDefinition : WeaponActiveAbilityDefinitionBase, IAbilityListDefinition
    {
        public Dictionary<FeatType, AbilityDetail> BuildAbilities()
        {
            var builder = new AbilityBuilder();

            ConfigureWeaponAbility(
                builder.Create(FeatType.VirulentBlade1, PerkType.VirulentBlade)
                    .Name("Virulent Blade I")
                    .Level(1)
                    .HasRecastDelay(RecastGroup.VirulentBlade, 30.0f),
                SkillType.Vibroknife,
                9,
                30,
                typeof(VenomStatusEffect),
                null,
                4,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    IsQueuedWeaponAbility = true
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.VirulentBlade2, PerkType.VirulentBlade)
                    .Name("Virulent Blade II")
                    .Level(2)
                    .HasRecastDelay(RecastGroup.VirulentBlade, 30.0f),
                SkillType.Vibroknife,
                12,
                30,
                typeof(VenomStatusEffect),
                null,
                6,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    IsQueuedWeaponAbility = true
                });

            ConfigureWeaponAbility(
                builder.Create(FeatType.VirulentBlade3, PerkType.VirulentBlade)
                    .Name("Virulent Blade III")
                    .Level(3)
                    .HasRecastDelay(RecastGroup.VirulentBlade, 30.0f),
                SkillType.Vibroknife,
                16,
                30,
                typeof(VenomStatusEffect),
                null,
                8,
                0,
                0.0f,
                false,
                true,
                false,
                Spell.Invalid,
                AbilityTargetingShapeType.None,
                0.0f,
                0.0f,
                AbilityTargetingFlags.HarmsEnemies,
                Animation.DoubleStrike,
                0.0f,
                AbilityType.Invalid,
                new WeaponAbilityProfile
                {
                    IsQueuedWeaponAbility = true
                });

            return builder.Build();
        }
    }
}
