using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SWLOR.Game.Server.Service;

namespace SWLOR.Web.Models
{
    public class GameTopicCollection: Dictionary<int, GameTopic>
    {
        public GameTopicCollection()
        {
            // Setting
            Add(62, new GameTopic(62, "Introduction", "This is a time of despair.\n\nAfter more than a decade of conflict, the Mandalorian Wars have finally ended. The Mandalorian clans are now scattered across the Outer Rim. They patiently wait for the right time to reunite and rise again.\n\nThis is a time of uncertainty.\n\nMillions died during the conflict and the Republic has begun to rebuild. Their stability is threatened by the numerous criminal groups and bounty hunters who aim to extend their control throughout the Outer Rim. The Republic struggles to preserve its order.\n\nThis is a time of disturbance.\n\nThe Sith Empire, secretly involved in the Mandalorian Wars, has risen again. Darth Revan and Darth Malak, former members of the Jedi Order, have turned to the Dark Side. With the help of the Star Forge, an automated factory and battle dreadnought, they have assembled a powerful army and taken control of Korriban. The Sith aim to conquer the galaxy.\n\nThis is a time of choice.\n\nWill you join the Jedi Order and attempt to preserve peace and balance in the galaxy? Or will you side with the Sith and harness the powers of the Dark Side? Perhaps you'll play both sides as a smuggler working with the Hutt Cartel? Or maybe you'll work as a freelancer, serving no one but yourself.\n\nIt's time to make a choice and navigate your own way through the galaxy...", GameTopicCategory.Setting, true, 1));
            Add(56, new GameTopic(56, "Setting & Background", "Star Wars: Legends of the Old Republic takes place in the year 3959 BBY. The Mandalorian Wars have recently ended and Revan has begun building his army. We take place several years before the events of Knight of the Old Republic 1.", GameTopicCategory.Setting, true, 2));
            Add(57, new GameTopic(57, "Locations", "The server initially takes place on CZ-220, an asteroid base owned and operated by Czerka Corporation. This serves as a tutorial to the server, setting, and gameplay. Players will travel to planet Viscara after completing the tutorial.\n\nViscara is a partially developed world with rare resources ripe for the taking. Several different factions compete over the resources and fight to claim territory over the planet. There are numerous ruins and places to discover from ages past.\n\nWe intend to offer additional planets for play after the initial launch.", GameTopicCategory.Setting, true, 3));
            Add(33, new GameTopic(33, "Human", "Bonuses: +1 SP\nPenalties: None\nStarting Languages: Galactic Basic\n\nHumans are a bipedal sentient race whose primary language is Galactic Basic Standard. They are referred to as the galaxy's most numerous species, due to the fact that they can be born and live on almost all worlds. They have had a hand in the creation of many galactic factions, and are known as one of the oldest species next to the Duros.\n\nHumans are the galaxy's most numerous and politically dominant sentient species with millions of major and minor colonies galaxy-wide. Believed to have originated on the galactic capital of Coruscant, they can be found anywhere, engaged in many different pursuits: spacers, mercenaries, smugglers, merchants, soldiers, assassins, farmers, crime lords, laborers, slaves, slavers, and many others, including Jedi and Sith.\n\nThe human race has played a key role in the Unification Wars, and it is also responsible for the forming of the Galactic Republic.\n\nSince Humans are the most common sentient species, they are often considered to be a standard or average to which the biology, psychology, and culture of other species are compared. ", GameTopicCategory.Species, true, 1));
            Add(34, new GameTopic(34, "Bothan", "Bonuses: +1 DEX, +1 INT\nPenalties: -1 STR, -1 CHA\nStarting Languages: Galactic Basic, Bothese\n\nA humanoid species identified by their short builds and fur-covered faces, Bothans are widely known as proficient and intrepid spies. However, members of the species have also become fearless leaders, relentless warriors, courageous pilots, and brilliant scientists\n\nDue largely to their reputation as spies, Bothans are often regarded as power hungry, manipulative, cunning and paranoid. But Bothans are also well-organized, keenly intelligent, and very loyal. They live orderly lives, place great emphasis on family bonds, and are extremely protective of their allies. In addition, Bothans can be passionate and surprisingly eloquent orators, poets, and politicians.\n\nBothans hail from Bothawui, a clean, cosmopolitan planet. They live in tight-knit clans and are ruled by a democratic Bothan Council. Bothans speak both Basic and their own native tongue. ", GameTopicCategory.Species, true, 2));
            Add(35, new GameTopic(35, "Chiss", "Bonuses: +1 INT, +1 WIS\nPenalties: -1 STR, -1 CON\nStarting Languages: Galactic Basic, Cheunh\n\nChiss are blue-skinned humanoids from the planet Csilla in the Unknown Regions.\n\nThe Chiss are a proud and highly intelligent species, valuing a knack for strategy and subterfuge over brute force. Although isolated in the Unknown Regions of the galaxy within their so-called “Chiss Ascendency,” the Chiss were singled out by the Empire as potential servants and allies because of their outsider status and their relative lack of moral qualms. \n\nIt is not that Chiss are by nature evil, but that they value pragmatism and efficiency and recognize both those qualities reflected in the Empire. While as a nonhuman, non-Sith species, Chiss are regarded as second-class citizens within the Empire, the Chiss Ascendancy is permitted self-vernance and supporters of a more diverse Empire often use the Chiss as an example of what the Empire can accomplish by welcoming other species. A few rare Chiss have even achieved official rank in the Imperial military and Imperial Intelligence.", GameTopicCategory.Species, true, 3));
            Add(36, new GameTopic(36, "Zabrak", "Bonuses: +1 STR, +1 CON\nPenalties: -1 INT, -1 WIS\nStarting Languages: Galactic Basic, Zabraki\n\nZabrak are near-human sentients from the planet Iridonia renowned for their independence and wandering spirit. \n\nThey have distinctive facial horns, whose number and pattern denote which subspecies an individual Zabrak belongs to. Most Zabrak wear ritual facial tattoos, which vary from simple lines to more elaborate patterns. The designs can mark significant events in their lives, or merely be a matter of personal preference. After discovering space travel early in their civilization, they quickly colonized worlds throughout the Mid Rim and gained a reputation as pioneers and explorers.\n\nZabrak are also skilled warriors, engaging in inter-clan competitions to hone their talents; their physiology, which includes a secondary heart and some resistance to pain, gives them surprising endurance in battle.", GameTopicCategory.Species, true, 4));
            Add(37, new GameTopic(37, "Twi'lek", "Bonuses: +1 CON, +1 CHA\nPenalties: -1 STR, -1 INT\nStarting Languages: Galactic Basic, Twi'leki\n\nTwi’leks are a humanoid species with long, prehensile head-tails called lekku–organs housing sections of the Twi’lek brain and specialized for communication through subtle motion. \n\nTwi’leks are native to the harsh world of Ryloth, a planet that has suffered from occupation by the Hutt Cartel in recent years; Twi’leks on Ryloth not forced to work in the mines are often taken as slaves, exported to markets throughout the Outer Rim. Millennia of dispersion into the wider galaxy, however, means that many Twi’leks have little or no sense of connection with their beleaguered homeworld; Twi’leks may be second only to humans in their ubiquity throughout known space. \n\nNonetheless, many Twi’leks can’t escape the shadows of slavery and the underworld–often, they find work with the same pirates, slavers and spice dealers who have traditionally oppressed their species. Twi’lek names vary dramatically, depending on whether the parents follow the old Twi’lek tradition of combining given and family name, or use the more common approach (separating first name and surname) used by many other species. Some Twi’leks eschew any surname altogether", GameTopicCategory.Species, true, 5));
            Add(38, new GameTopic(38, "Cathar", "Bonuses: +1 DEX, +1 CON\nPenalties: -1 INT, -1 CHA\nStarting Languages: Galactic Basic, Catharese\n\nCathar are a feline humanoid species native to the planet of the same name. They are normally covered in fur, although variations in the genetic baseline have expressed themselves as at least two distinct subspecies. \n\nCathar are noteworthy hand-to-hand combatants, possessing retractable claws, strong physiques and natural agility. It was the Cathar reputation for martial prowess that drew the Mandalorians to besiege their homeworld several centuries a. Despite their valiant resistance against the remorseless invaders, the native Cathar were virtually exterminated. \n\nOut of millions, only a few hundred escaped the Mandalorians’ attack and fled to Republic space. In the time since their near-extinction, the Cathar have rebuilt their numbers to become common faces on Republic worlds. The Jedi Order, Galactic Senate and Republic military all claim numerous proud and loyal Cathar among their ranks. It is rare to encounter a Cathar who doesn’t actively despise the Sith Empire–and especially its Mandalorian allies.", GameTopicCategory.Species, true, 6));
            Add(39, new GameTopic(39, "Cyborg", "Bonuses: None\nPenalties: None\nStarting Languages: Galactic Basic, Droidspeak\n\nCyborgs are individuals who have undergone surgery to either replace or enhance parts of their natural bodies. Augmentations can range anywhere from simple subdermal implants, to full body prosthesis.", GameTopicCategory.Species, true, 7));
            Add(59, new GameTopic(59, "Trandoshan", "Bonuses: +1 STR, +1 CON\nPenalties: -1 INT, -1 CHA\nStarting Languages: Galactic Basic, Dosh\n\nTrandoshans are a large, bipedal sentient species, with scaly skin which range in color from sandy brown to glossy green. Their skin sheds roughly once every standard year and is extremely durable.\n\nCold-blooded reptiles, Trandoshans have two super-sensitive varied color eyes with horizontal black pupils, which can see far into the infrared range.\n\nTrandoshans can regenerate lost limbs and skin until they reach their Middle Ages — around fifty-four standard years. Each of their four limbs end in three razor sharp claws. ", GameTopicCategory.Species, true, 8));
            Add(68, new GameTopic(68, "Wookiee", "Bonuses: +1 STR, +1 CON\nPenalties: -1 DEX, -1 CHA\nStarting Languages: Galactic Basic, Shyriiwook\nNOTE: Wookiees may only speak in their native language, Shyriiwook.\n\nThe Wookiees, whose name for themselves translates to the People of the Trees, are a species of hairy bipedal humanoids that were inhabitants of the planet Kashyyyk. They have the ability to easily learn most languages. However, Wookiees lack the vocal structure to speak anything other than their own languages. The Wookiees spoke an array of dialects collectively known as Wookiee language, all of which consisted in a combination of barks, roars, moans and growls.\n\nAs their name implies, Wookiees live in tree-houses in their forested planet. Their community is led by a chieftain. Wookie society is generally peaceful, and the Holder of Laws oversees Wookiee trials and judges offenses. Murder is not permitted and is punishable by death.\n\nAlthough their culture may seem primitive, they are surprisingly capable warriors. They are strong enough to rip off the limbs of their foes with their bare hands, and can pick up combat techniques pretty quickly. This legendary strength has made them prized quarry for slavers and hunters looking to use that strength for manual labor, entertainment in gladiatorial combat, or just to test their mettle against the Wookiees' combat prowess. Some Wookiees branch out and make names for themselves in the galaxy as hired muscle, pirates, smugglers, pilots, or mechanics.", GameTopicCategory.Species, true, 9));
            Add(69, new GameTopic(69, "Mirialan", "Bonuses: +1 DEX, +1 WIS\nPenalties: -1 STR, -1 CON\nStarting Languages: Galactic Basic, Mirialan\n The Mirialan people are deeply religious and practice a primitive understanding of the Force. They believe each individual's actions contribute to their destiny, building upon past successes and failures to drive them towards their fates.\n\nMirialans place a unique, often geometrically repeated tattoo on their face and hands to signify that they have completed a certain test or task, or achieved sufficient aptitude for a certain skill. The number of tattoos thus often act as a good indicator of how mature and/or skilled a Mirialan is.\n\nBecause the more markings bring about a form of status, Mirialan society is stratified and allows the heavily marked citizens to access greater opportunities. Despite its importance, most Mirialans do not know the entirety of the tattoo lexicon due to its complexity. The interaction between placement and positioning of the shapes is incredibly subtle and changes meaning greatly.\n\nWithin their belief system is the view that individual actions ripple through the Force, also affecting the destiny of the species as a whole. Because the Force is understood through the notion of the Cosmic Force on a basic level, the cultural significance of the energy is defined as fate. Those who are not sensitive to its call still have faith in fate, and feel that it guides their lives.", GameTopicCategory.Species, true, 10));
            Add(70, new GameTopic(70, "Echani", "Bonuses: +1 DEX, +1 CON\nPenalties: -1 WIS, -1 CHA\nStarting Languages: Galactic Basic\n\nThe Echani are a matriarchal caste-based society originating from the Inner Rim world of Eshan.\n\nThe Echani have similar anatomy to that of humans, but are physically distinct due to their light skin, white hair and silver eyes. They exhibit among themselves a remarkable similarity to each other in their body type and facial features, with close family members such as siblings often appearing indistinguishable to an outside observer.\n\nIt's believed that the Echani are a result of a Arkanian experimentation with the Human genome, a theory which could explain the resemblance among these members of their species.\n\nDue to the all-encompassing use of combat in all levels of their culture, Echani Generals are typically seen by others as having the ability to predict their opponent's next move. This is not a biological trait inherent to the Echani. Instead, it arose from a culture where combat is seen as the truest form of communication.", GameTopicCategory.Species, true, 11));
            Add(71, new GameTopic(71, "Mon Calamari", "Bonuses: +1 WIS, +1 CON\nPenalties: -1 INT, -1 CHA\nStarting Languages: Galactic Basic, Mon Calamarian\n\nThe Mon Calamari are a fish-like amphibious humanoid species with salmon-colored skin, webbed hands, high domed heads and huge, fish-like eyes. They are equally capable of breathing both on land and in water with them being at home in either environment. \n\nThe Mon Calamari have developed a very advanced and civilized culture. Art, music, literature and science show a creativity surpassed by by few in the galaxy. In addition to this, they have developed a reputation for being one of the most skilled starship designers in the galaxy. This partly stemmed from the fact that they see everything as a work of art rather than being a simple tool or weapon.\n\nTheir species has long been recognized for their organizational and analytical skills. It's this trait that make them brilliant strategists and tacticians.\n\nIn terms of governance, the Mon Calamari make use of a highly efficient representative form of government. They tend to be lawful and an organized people with little tolerance for those that operate outside the status quo. As such, Mon Calamari tend to dislike and mistrust smugglers.", GameTopicCategory.Species, true, 12));
            Add(58, new GameTopic(58, "Freelancer", "Temporary Bonus: None\nPermanent Bonus: +3 SP to distribute however you want.", GameTopicCategory.CharacterBackgrounds, true, 1));
            Add(9, new GameTopic(9, "Jedi Padawan (Guardian)", "Temporary Bonus: Basic Lightsaber\nPermanent Bonus: +2 Base Attack Bonus when equipped with lightsabers", GameTopicCategory.CharacterBackgrounds, false, 2));
            Add(10, new GameTopic(10, "Jedi Padawan (Sentinel)", "Temporary Bonus: Basic Saberstaff\nPermanent Bonus: +2 Base Attack Bonus when equipped with saberstaffs", GameTopicCategory.CharacterBackgrounds, false, 3));
            Add(12, new GameTopic(12, "Jedi Padawan (Consular)", "Temporary Bonus: Rank 1 of the Force Breach perk\nPermanent Bonus: +1 level to all Light Side ability checks", GameTopicCategory.CharacterBackgrounds, false, 4));
            Add(17, new GameTopic(17, "Jedi Padawan (Sage)", "Temporary Bonus: Rank 1 of the Force Heal perk\nPermanent Bonus: +1 level to all Light Side ability checks", GameTopicCategory.CharacterBackgrounds, false, 5));
            Add(13, new GameTopic(13, "Sith Apprentice (Warrior)", "Temporary Bonus: Basic Lightsaber\nPermanent Bonus: +2 Base Attack Bonus when equipped with lightsabers", GameTopicCategory.CharacterBackgrounds, false, 6));
            Add(14, new GameTopic(14, "Sith Apprentice (Assassin)", "Temporary Bonus: Basic Saberstaff\nPermanent Bonus: +2 Base Attack Bonus when equipped with saberstaffs", GameTopicCategory.CharacterBackgrounds, false, 7));
            Add(15, new GameTopic(15, "Sith Apprentice (Sorcerer)", "Temporary Bonus: Rank 1 of the Force Lightning perk\nPermanent Bonus: +1 level to all Dark Side ability checks", GameTopicCategory.CharacterBackgrounds, false, 8));
            Add(16, new GameTopic(16, "Sith Apprentice (Corrupter)", "Temporary Bonus: Rank 1 of the Dark Heal perk\nPermanent Bonus: +1 level to all Dark Side ability checks", GameTopicCategory.CharacterBackgrounds, false, 9));
            Add(18, new GameTopic(18, "Smuggler", "Temporary Bonus: Basic Blaster Pistol & Ammo\nPermanent Bonus: +2 Base Attack Bonus when equipped with blaster pistols", GameTopicCategory.CharacterBackgrounds, true, 10));
            Add(19, new GameTopic(19, "Sharpshooter", "Temporary Bonus: Basic Blaster Rifle & Ammo\nPermanent Bonus: +2 Base Attack Bonus when equipped with blaster rifles", GameTopicCategory.CharacterBackgrounds, true, 11));
            Add(20, new GameTopic(20, "Teräs Käsi", "Temporary Bonus: Basic Power Glove\nPermanent Bonus: +2 Base Attack Bonus when unarmed or equipped with a martial arts weapon", GameTopicCategory.CharacterBackgrounds, true, 12));
            Add(21, new GameTopic(21, "Security Officer", "Temporary Bonus: Basic Baton\nPermanent Bonus: +2 Base Attack Bonus when equipped with a baton.", GameTopicCategory.CharacterBackgrounds, true, 13));
            Add(22, new GameTopic(22, "Berserker", "Temporary Bonus: Basic Twin Vibroblade\nPermanent Bonus: +2 Base Attack Bonus when equipped with twin vibroblades.", GameTopicCategory.CharacterBackgrounds, true, 14));
            Add(23, new GameTopic(23, "Duelist", "Temporary Bonus: Basic Finesse Vibroblades\nPermanent Bonus: +2 Base Attack Bonus when equipped with finesse vibroblades.", GameTopicCategory.CharacterBackgrounds, true, 15));
            Add(24, new GameTopic(24, "Soldier", "Temporary Bonus: Basic Heavy Vibroblade\nPermanent Bonus: +2 Base Attack Bonus when equipped with heavy vibroblades.", GameTopicCategory.CharacterBackgrounds, true, 16));
            Add(25, new GameTopic(25, "Armorsmith", "Temporary Bonus: Rank 1 of the Armorsmith Blueprints perk\nPermanent Bonus: +1 level on all checks when crafting Armorsmith items", GameTopicCategory.CharacterBackgrounds, true, 17));
            Add(26, new GameTopic(26, "Weaponsmith", "Temporary Bonus: Rank 1 of the Weaponsmith Blueprints perk\nPermanent Bonus: +1 level on all checks when crafting Weaponsmith items", GameTopicCategory.CharacterBackgrounds, true, 18));
            Add(27, new GameTopic(27, "Chef", "Temporary Bonus: Rank 1 of the Cooking Blueprints perk\nPermanent Bonus: +1 level on all checks when crafting Cooking items", GameTopicCategory.CharacterBackgrounds, true, 19));
            Add(28, new GameTopic(28, "Engineer", "Temporary Bonus: Rank 1 of the Engineering Blueprints perk\nPermanent Bonus: +1 level on all checks when crafting Engineering items", GameTopicCategory.CharacterBackgrounds, true, 20));
            Add(29, new GameTopic(29, "Fabricator", "Temporary Bonus: Rank 1 of the Fabrication Blueprints perk\nPermanent Bonus: +1 level on all checks when crafting Fabrication items", GameTopicCategory.CharacterBackgrounds, true, 21));
            Add(30, new GameTopic(30, "Harvester", "Temporary Bonus: Basic Scanner & Basic Harvester\nPermanent Bonus: +1 level on all checks when harvesting raw materials.", GameTopicCategory.CharacterBackgrounds, true, 22));
            Add(31, new GameTopic(31, "Scavenger", "Temporary Bonus: Rank 1 of the Scavenging Expert perk\nPermanent Bonus: +1 attempt to all scavenging.", GameTopicCategory.CharacterBackgrounds, true, 23));
            Add(32, new GameTopic(32, "Medic", "Temporary Bonus: Rank 1 of the Immediate Improvement perk\nPermanent Bonus: Interval between first aid effects reduced by 50%. Also reduces chance to consume first aid items by 5%.", GameTopicCategory.CharacterBackgrounds, true, 24));
            Add(67, new GameTopic(67, "Mandalorian", "Temporary Bonus: Mandalorian Armor\nPermanent Bonus: +1 Base Attack Bonus when equipped with blaster rifles and you learn the Mandoa language.", GameTopicCategory.CharacterBackgrounds, true, 33));
            Add(1, new GameTopic(1, "Why aren't there classes?", "We made a deliberate design decision to make SWLOR a skill-based game from the beginning. This was done so that players can feel like they have complete control over their character. We didn't want to force players into a specific archetype even though many other games do. Our approach is to give players the tools they need to play how they want and then let them decide on how to beat challenges.", GameTopicCategory.FAQ, true, 1));
            Add(2, new GameTopic(2, "Why isn't \"XYZ\" race available?", "Race options are largely based on what models and content we have available. NWN is a fantasy game so the amount of Star Wars specific content can be lacking at times (though there's a lot more than one might think!). With all that said, if you come across content that would make a good fit for the server - and we don't already have it - then please be sure to let us know on Discord.", GameTopicCategory.FAQ, true, 2));
            Add(3, new GameTopic(3, "Is this server like 'ABC' game?", "We take a lot of inspiration from games like Star Wars Galaxies, Skyrim, Eve Online and Star Wars: The Old Republic. However, we have added our own spin on things to keep it interesting. You will most certainly find things we've generously \"borrowed\" from other games, but you will also find a lot of unique things as well.", GameTopicCategory.FAQ, true, 3));
            Add(4, new GameTopic(4, "Is this a Roleplay server?", "Yes. We are a roleplay server. This means you are expected to create a character and act as if you were him/her in the setting. This means leaving conversations like who won the football game, real-world politics, and other such topics out of public chat channels. If you need to speak \"out of character\" we recommend using Discord or the private \"tell\" chat in-game.", GameTopicCategory.FAQ, true, 4));
            Add(5, new GameTopic(5, "Where should I send suggestions?", "We welcome all ideas and suggestions. We'll even be happy to take **constructive** criticism too! The best place to do this is on our Discord channel. Be sure to put it in the appropriate channel. Keep in mind that just because you suggest something doesn't mean it will be implemented. The best way to get your idea implemented is to do it yourself. Our code is open source and freely available. We can help you with forking the repository and submitting a pull request. Just ask us in Discord!", GameTopicCategory.FAQ, true, 5));
            Add(6, new GameTopic(6, "Where can I donate?", "If you'd like to donate money toward server costs please visit our Patreon here: https://www.patreon.com/swlor \n\nWe are committed to a fair gameplay experience for everyone. For that reason, donations will *never* give you in-game rewards. By donating, you understand you are simply helping us foot the bill for the monthly hosting costs.", GameTopicCategory.FAQ, true, 6));
            Add(7, new GameTopic(7, "How can I contribute?", "We're really appreciative of all (non-monetary) donations. If you've built a cool area, or developed a neat feature or quest please consider donating it to the server. Our source code and module are open source and available on GitHub. If your contribution is code-related, simply create a pull request on GitHub. If your contribution is an area, item, or something else module-based please get in touch with the DM team to see how you can add it. If you need help, please get in touch with us on Discord.", GameTopicCategory.FAQ, true, 7));
            Add(8, new GameTopic(8, "What if your mod gets stolen?", "Some people question why we have chosen to make the project open source. We've chosen this approach because we feel it actually enhances the server for everyone. There have been many enhancements and features created for the server because it's freely available. Although we'd prefer everyone to play on our server and consider it the \"official\" version, we're more than happy to see our work used. If you make something cool on your version, consider contributing it to us - it will probably make its way in!", GameTopicCategory.FAQ, true, 8));
            Add(40, new GameTopic(40, "General Overview", "Crafting in SWLOR is very extensive but easy to learn. The first step is to purchase a perk for the crafting you would like to do. For example, if you want to do Engineering you would purchase the \"Engineering Blueprints\" perk. After you have that, you can use any crafting workbench to select a blueprint, add components, and begin to craft the item. What's unique about this is that every component you use for construction of the item affects the end product. For example, if you use high quality metal then any bonuses on the components get transferred to the item. In this way, items can vary greatly depending on the person making them.", GameTopicCategory.Crafting, true, 1));
            Add(41, new GameTopic(41, "What crafts are available?", "The crafting skills available are: Weaponsmith, Armorsmith, Engineering, Cooking, and Fabrication. The gathering skills available are: Harvesting and Scavenging.\n\nAs the name implies, Weaponsmith and Armorsmith create weapons and armors. Engineering focuses on creating item mods and mechanical/electronic devices like firearms.\n\nYou can use the Cooking skill to create new dishes that grant your character long-term status buffs. These last for a limited time, depending on the quality of item consumed. Their effects are modified based on the chef's crafting ability.\n\nFabrication involves creating structures like control towers, drills, silos, furniture, buildings, and player homes.\n\nHarvesting can be performed by using a \"Resource Harvester\" on any raw resource - such as ore veins and trees. You can also scan the resources use a \"Resource Scanner\" to identify the type of material, the quality, and other useful information. They also grant bonuses to your harvesting ability.\n\nFinally, Scavenging involves sifting through junk piles for scrap metal and electronics. It also is used for collecting items like Fiberplast from plants and fauna.", GameTopicCategory.Crafting, true, 2));
            Add(42, new GameTopic(42, "How many crafts can I learn?", "You can learn and use as many crafts as you want. There's no restriction on how you focus your character. The only limitation is that your character can only have a maximum of 500 skill points across all skills at one time. After you reach the cap, you will be subject to skill decay (refer to the \"Other Gameplay Information\" section for more details on that).", GameTopicCategory.Crafting, true, 3));
            Add(43, new GameTopic(43, "Can I solely be a crafter?", "Yes, absolutely! If you want to create a character entirely focused on crafting you are more than welcome to. SWLOR is about giving you options and letting you decide what you want to do with them. If you decide to  down this path, keep in mind you will need some combat friends to help you obtain materials.", GameTopicCategory.Crafting, true, 4));
            Add(44, new GameTopic(44, "How does equipment help?", "Equipment which adds bonuses to a particular craft - for example, Armorsmithing - enable you to do a couple things. First, it reduces the difficulty of a blueprint. This means you will be more successful at creating the item. Secondly, it increases the likelihood that bonuses from the components you used will transfer to the final item successfully. For this reason, it is highly recommended to work on getting a set of crafting gear so you can produce better items.", GameTopicCategory.Crafting, true, 5));
            Add(45, new GameTopic(45, "What are components?", "Components are items required by the blueprint. These are general requirements such as \"metal\" or \"organic material\". They don't call for specific items - only general item types. What components you choose to use is entirely up to you as long as it meets the item type requirement.\n\nAll blueprints have a minimum and maximum component number. The number of components you use must fall within this range.", GameTopicCategory.Crafting, true, 6));
            Add(46, new GameTopic(46, "What are enhancements?", "Enhancements are OPTIONAL items you may use for a blueprint. These are usually obtained from completing quests or looting defeated enemies. Enhancements can be added as part of the crafting process as long as two requirements are met:\n\n1.) The blueprint allows for enhancement slots.\n2.) You have the necessary skill rank and perk level to use the enhancement slot.\n\nIf both requirements are met, an option will appear on the crafting menu allowing you to do so.", GameTopicCategory.Crafting, true, 7));
            Add(47, new GameTopic(47, "What are mods?", "Mods, often called \"sockets\" in other games, are a way to customize your equipment further after it's already been created. There are four colored slots available: Red, Blue, Green, and Yellow. There is also a fifth type called Prismatic which enables any type of color mod to be inserted.\n\nIn order to attach a mod to an item you must first have an available slot on the item. These slots comes standard with higher tier items but they can also be added during the crafting process. The type of benefits are identified by the color of the mod.\n\nRed - Combat related upgrades like +HP, +STR, and +Damage.\nBlue - Force related upgrades like +FP, +CHA, and +Force.\nGreen - Crafting related upgrades like +Weaponsmith and +Harvesting.\nYellow - \"Special\" mods like +Sneak Attack, +Meditate, and +Durability.\n\nAttaching mods requires the appropriate perks in Weaponsmith and Armorsmith, depending on the item.", GameTopicCategory.Crafting, true, 8));
            Add(48, new GameTopic(48, "What is Recommended Level?", "Recommended Level (RL) is a property on items which determine the skill level required to fully utilize its features. As an example, if you use a lightsaber with RL20, but your skill rank in One-Handed is 15 you will suffer some penalties such as reduced damage and accuracy.\n\nThis comes into play with crafting because every component you add to an item increases the RL on the finished product. If you add a bunch of high-quality components to an item, it may put the item's RL beyond your skill level. You need to carefully balance for the intended outcome.\n\nThe only way to reduce the level on an item (aside from using lower-level components) is by attaching a yellow \"Level Down\" mod to the item.", GameTopicCategory.Crafting, true, 9));
            Add(49, new GameTopic(49, "How does resting work?", "Unlike vanilla NWN, there is no \"rest mechanic\". Players naturally recover HP and FP over time. These can also be recovered by using the appropriate first aid items, force abilities, and so on. This was a deliberate decision because we felt that normal NWN mechanics detract from both the role-play and game-play aspects.\n\nThe rest button has been repurposed for opening your main menu. Many options like looking at your skill levels, purchasing perks, and adjusting character settings can be found here.", GameTopicCategory.OtherGameplayInfo, true, 1));
            Add(50, new GameTopic(50, "What happens if I die?", "Players who die through normal gameplay will return to their respawn point. This respawn point can be changed by talking to the appropriate person in a medical facility. These are usually found in NPC-run cities.\n\nYou will also lose some durability points on all items you're carrying. If an item's durability reaches 0, it will be permanently destroyed.\n\nIf a player dies during a DM-run event, there may be a possibility for permanent death depending on the outcome. This is left to the individual DM to decide.", GameTopicCategory.OtherGameplayInfo, true, 2));
            Add(51, new GameTopic(51, "What are Force Points?", "Force Points, or FP, represent your ability to perform force-related abilities. This is similar to mana or MP in other games. FP naturally regenerates over time but can also be recovered by using items or using the \"Meditate\" perk ability.", GameTopicCategory.OtherGameplayInfo, true, 3));
            Add(52, new GameTopic(52, "Can I be a non-force character?", "Within the context of the server, all players have \"force potential\". This is because we use a freeform system for character building. With that said, you aren't required to use force abilities. If you want to play a non-force character then you simply need to not purchase force-related perks. It's entirely up to you to decide where to take your character.", GameTopicCategory.OtherGameplayInfo, true, 4));
            Add(53, new GameTopic(53, "Can I change the world?", "We encourage players to make their mark on the game world and we will do our best to provide everything you need to do so. However, we must still abide by established Star Wars lore as best we can. Some examples:\n\n1.) You can't play well-known and established characters like Darth Vader, Malak, and so on. The character you play must be unique but you're welcome to draw upon outside sources.\n2.)Events which would impact the overarching story for the point of time we're in (the Mandalorian Wars) cannot be accommodated. This means you can't blow up planets or kill key characters.\n3.) Any plot which would require substantial development effort or change the nature of the server can't be accommodated. For example, you can't execute Order 66 to kill off all the Jedis.\n\nOther than those guidelines, we don't have any other restrictions. We hope you'll make your own unique mark on the galaxy!", GameTopicCategory.OtherGameplayInfo, true, 5));
            Add(54, new GameTopic(54, "Where can I report issues?", "If your problem is with another player, please consider ignoring the player with the /ignore chat command. However, if it escalates please contact one of the DM staff and we will assist you.\n\nIf your problem is with a member of the staff please get in touch with an admin on Discord.", GameTopicCategory.OtherGameplayInfo, true, 6));
            Add(55, new GameTopic(55, "Where can I report bugs?", "We track all development issues on GitHub. You'll find a link up above. Simply  to the appropriate repository (game or website) and click on the issues tab. Be sure to include as much detail as you can - where you were, what you were doing, your character name, your account name, and any other pertinent information. This es a long way to resolving bugs.\n\nIf you are reporting an exploit please contact a member of staff privately on Discord. Please don't abuse or share this information with other players. We track this information and will take action - including bans - if necessary.", GameTopicCategory.OtherGameplayInfo, true, 7));
            Add(60, new GameTopic(60, "How do attributes work?", "Your Strength and Dexterity attributes work generally the same as they do in vanilla NWN. The only difference is that these may be used when calculating perk efficiency, like how much damage the ability does to a target.\n\nConstitution will increase your HP at a much higher rate than normal NWN. It also improves how much HP you naturally recover over time.\n\nWisdom and Intelligence are used for light-side and dark-side abilities, respectively. They also boost your maximum Force Points (FP).\n\nCharisma dictates your communion with the Force. It increases your maximum FP and also improves your natural FP regeneration.", GameTopicCategory.OtherGameplayInfo, true, 8));
            Add(61, new GameTopic(61, "What is skill decay?", "Skill decay occurs after you reach the maximum number of cumulative skill points. This cap is currently 500 but may change in future updates as needed.\n\nThis means the total sum of all your skill points must be under 500 or else you will encounter decay. These can be distributed anyway you want - 40 Dark-side, 20 Light-side, 100 One-Handed, etc... The sum of all these is your cumulative skill point count.\n\nOnce you reach the skill cap you are still able to increase your skills, but an existing skill will lose experience. In this way, you are able to rebuild your character over time if you decide you want to play a different way.\n\nKeep in mind that you won't lose perks you purchased, but you must be at the prerequisite skill level in order to use them. If you no longer want a perk, you may purchase a Tome of Retraining to refund the perk.\n\nIt is also possible to \"Lock\" a skill from decaying. You can do this from your skill menu.\n\nSkills that are locked won't lose EXP from decay but if all of your skills are locked you cannot gain any new experience.", GameTopicCategory.OtherGameplayInfo, true, 8));
            Add(11, new GameTopic(11, "Rule #1 - Role Play", "You are expected to role play in all interactions with players and DMs. You may not use famous characters, unearned titles or character concepts which are harmful to the world (e.g. Luke Skywalker, Revan or Darth Vader). Character concepts may be rejected at a DM’s discretion and you are expected to remake without complaint.", GameTopicCategory.Rules, true, 1));
            Add(63, new GameTopic(63, "Rule #2 - Play Respectfully", "Cybering and erotic role play (ERP) is NOT PERMITTED on this server. Our doors are open to a vast number of age ranges and, for this reason, restrict you to a “PG-13” level of interaction. Unwarranted rudeness, potentially offensive role play, inappropriate sexual references, harassment, exploiting known or unknown bugs, logging to avoid consequences, etc are prohibited.", GameTopicCategory.Rules, true, 2));
            Add(64, new GameTopic(64, "Rule #3 - Listen to the DMs", "Dungeon Masters are to be considered the final authority in any dispute, question, or issue that comes up. By playing Star Wars: Legends of the Old Republic you agree to abide by their decisions. If there is a dispute with a DM ruling or you feel you’ve been dealt with unfairly, OBEY THE RULING at the time and then contact the admin staff. You may reach us through Discord or in a private message on the forums.", GameTopicCategory.Rules, true, 3));
            Add(65, new GameTopic(65, "Rule #4 - PvP", "Combat actions against other PCs (PvP) must be interactively role played. This means: you interact, they interact, BEFORE any battle occurs. You are expected to wait one real-world day before participating in PvP or interacting in any way with that PC or other hostile PCs from the battle unless both sides explicitly agree otherwise. Having an opposing character type (i.e Jedi vs Sith) is not a sufficient reason for a PvP action.", GameTopicCategory.Rules, true, 4));


            var reservedNames = string.Empty;

            foreach (var reservedName in PlayerValidationService.ReservedWords)
            {
                reservedNames += "\"" + reservedName + "\" ";
            }
            
            Add(66, new GameTopic(66, $"Reserved Names/Words", $"The following names/words are reserved. Any characters containing them will be immediately deleted on entry to the server.\n\n{reservedNames}", GameTopicCategory.Rules, true, 5));
        }
    }
}
