using System.Text;
using SWLOR.Game.Server.Service.SlicingService;

if (args.Length != 1)
{
    Console.Error.WriteLine("Usage: SWLOR.SlicingBoardGenerator <SlicingBoardCatalog.Generated.cs>");
    return 1;
}

var outputPath = Path.GetFullPath(args[0]);
var source = new StringBuilder();
source.AppendLine("// <auto-generated />");
source.AppendLine("// Run: dotnet run --project tools/SWLOR.SlicingBoardGenerator -- SWLOR.Game.Server/Service/SlicingService/SlicingBoardCatalog.Generated.cs");
source.AppendLine("using System.Collections.Generic;");
source.AppendLine();
source.AppendLine("namespace SWLOR.Game.Server.Service.SlicingService");
source.AppendLine("{");
source.AppendLine("    public static partial class SlicingBoardCatalog");
source.AppendLine("    {");
source.AppendLine("        private static readonly IReadOnlyDictionary<int, string[]> _encodedBoards =");
source.AppendLine("            new Dictionary<int, string[]>");
source.AppendLine("            {");

for (var tier = 1; tier <= 5; tier++)
{
    source.AppendLine($"                [{tier}] = new[]");
    source.AppendLine("                {");
    for (var boardNumber = 1; boardNumber <= SlicingBoardAuthoring.BoardsPerTier; boardNumber++)
    {
        var board = SlicingBoardAuthoring.GenerateBoard(tier, boardNumber);
        source.AppendLine($"                    \"{Encode(board)}\",");
    }

    source.AppendLine("                },");
}

source.AppendLine("            };");
source.AppendLine("    }");
source.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, source.ToString());
Console.WriteLine($"Generated {5 * SlicingBoardAuthoring.BoardsPerTier} slicing boards at {outputPath}.");
return 0;

static string Encode(SlicingBoard board)
{
    var tiles = string.Join(";", board.Tiles.Select(tile =>
        $"{(int)tile.Type},{tile.Orientation},{tile.SolutionIndex},{tile.RouteOrder},{tile.SolutionOrientation}"));
    var swaps = string.Join(";", board.SolutionSwaps.Select(swap =>
        $"{swap.FirstIndex},{swap.SecondIndex}"));
    return $"{board.Width},{board.Height}|{board.BaseTrace},{board.SolutionActionCost}|{tiles}|{swaps}";
}
